---
title: "R Notebook"
output: html_notebook
---

```{r}
xdp_cah_put@meta.data

```



```{r}
table(xdp_cah_put$donor_id, xdp_cah_put$final_cell_class)
```

```{r}
caudate_cell_types = as.data.frame(table(xdp_cah_put$donor_id, xdp_cah_put$cell_class))
caudate_cell_types

caudate_cell_types = subset(caudate_cell_types, subset = Var2 == "neuron")
caudate_cell_types$CaH_neurons= caudate_cell_types$Freq
caudate_cell_types$Freq = NULL
caudate_cell_types
```


```{r}
caudate_neuron_final = subset(xdp_cah_put, subset = final_cell_class == "neuron")
unique(caudate_neuron_final$neuron_classes)
```

```{r}
caudate_neuron_final@meta.data$sub_class = caudate_neuron_final@meta.data$neuron_classes
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "SPN_exotic"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "SPN_matrix"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "SPN_patch"] = "SPN"

unique(caudate_neuron_final$sub_class)
```

```{r}
SPNs = subset(caudate_neuron_final, sub_class == "SPN" )
SPNs@meta.data
```



```{r}
xdp_cah_summary = SPNs@meta.data %>%
  group_by(donor_id) %>%
  summarise(mUMI = median(nUmi),
            pct_intronic = median(pct_intronic),
            cells = n(),
            pct_mito = median(pct_mito),
            nReads = sum(nRead),
            DV200 = unique(DV200),
            RQS = unique(RQS),
            MQS = unique(MQS),
            MQS_numerical = unique(MQS_numerical),
            Condition = unique(Condition)
            )
xdp_cah_summary
```

```{r}
xdp_cah_summary = as.data.frame(xdp_cah_summary)
xdp_cah_summary
```



```{r}
x_order =c("SCF-23-068CM", "SCF-22-054CM", "SCF-22-058CF","SCF_21-037CM2", "PCMC-16-011", "PCMC-16-012", 
  "SCF-18-003", "SCF-18-004", "SCF-18-006", "SCF-19-009", "SCF-19-014", 
  "SCF-19-018", "SCF-20-023", "SCF_20-024", "SCF-20-025", "SCF-21-030", 
   "SCF_22-043")
xdp_cah_summary$donor_id = factor(xdp_cah_summary$donor_id, levels = x_order)
```

```{r}
xdp_cah_summary
```


```{r}
a = ggplot(xdp_cah_summary, aes(x = donor_id, y = mUMI, color = donor_id, shape = Condition)) +
  geom_point(size = 3, alpha = 0.9, position = position_dodge(width = 0.5)) +
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ylab("SPN mUMIs")+
  geom_vline(xintercept = 4.5, linetype = "dashed", color = "red") + theme(
            plot.title = element_text(size = 16), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 14),  # Increase tick label font size
            axis.title = element_text(size = 15),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1)  # tilt axis labels
        )+
  theme(
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18),  # Increase legend title size
   # legend.key.size = unit(1.5, "cm")  # Increase legend key size
  )+scale_shape_manual(values = c("Control" = 15, "XDP" = 16))

ggsave(a, filename = "pic.png", width = 10, height = 6)

```


```{r}
a = ggplot(xdp_cah_summary, aes(x = DV200, y = mUMI , color = donor_id, shape = Condition)) +
  geom_point(size = 3, alpha = 0.9, position = position_dodge(width = 0.5)) +
  theme_bw() + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +scale_shape_manual(values = c("Control" = 15, "XDP" = 16))+ ylab("SPN mUMIs") 
ggsave(a, filename = "pic.png", width = 8, height = 6)
```





















```{r}
caudate_neuron_final@meta.data$sub_class = caudate_neuron_final@meta.data$cell_class
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_matrix_1"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D2_SPN_patch_2"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_patch_2"] = "SPN"
#caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "eSPN"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_patch_3"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_patch_1"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D2_SPN"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D2_SPN_patch_1"] = "SPN"

caudate_neuron_final@meta.data
```

```{r}
table(caudate_neuron_final$donor_id, caudate_neuron_final$sub_class)
```

```{r}
caudate_SPN = as.data.frame(table(caudate_neuron_final$donor_id, caudate_neuron_final$sub_class))
caudate_SPN = subset(caudate_SPN, subset = Var2 == "SPN")
caudate_SPN$CaH_SPN = caudate_SPN$Freq 
caudate_SPN$Freq = NULL
caudate_SPN
```

```{r}
# merged_SPN = merge(caudate_cell_types, caudate_SPN, by = "Var1")
# merged_SPN$Var2.y = NULL
# merged_SPN
```

```{r}
total_cells =as.data.frame(table(xdp_cah_put$donor_id))
total_cells
```

```{r}
merged_SPN_final = merge(caudate_SPN, total_cells, by = "Var1")
merged_SPN_final
```



```{r}
putamen_neuron= qread("Subclustering/putamen_neurons_integrated_subcluster.qs")
head(putamen_neuron)
```

```{r}
unique(putamen_neuron$cell_class)
```

```{r}
putamen_neuron@meta.data$sub_class = putamen_neuron@meta.data$cell_class
putamen_neuron$sub_class[putamen_neuron$sub_class == "D2_SPN_1"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D1_SPN_2"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D2_SPN_3"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D1_SPN_matrix"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D2_SPN_2"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D1_SPN_1"] = "SPN"
#putamen_neuron$sub_class[putamen_neuron$sub_class == "eSPN"] = "SPN"

putamen_neuron@meta.data
```
```{r}
putamen_SPN= as.data.frame(table(putamen_neuron$donor_id, putamen_neuron$sub_class))
putamen_SPN = subset(putamen_SPN, subset = Var2 == "SPN")
putamen_SPN$Put_SPN = putamen_SPN$Freq
putamen_SPN$Freq = NULL
putamen_SPN
```

```{r}
merged_SPN_final= merge(merged_SPN_final, putamen_SPN, by = "Var1")
merged_SPN_final
```




#could you plot each donor's SPN fraction versus their total number of SPNs?  We might want to pick donors who have a range of SPN fractions, prioritizing those with high absolute SPN numbers, to ensure they are of good quality.
```{r}
# merged_SPN$SPN_proportion_neuron = merged_SPN$Freq.y/merged_SPN$Freq.x
# merged_SPN = merge(merged_SPN, total_cells, by = "Var1")
# merged_SPN
```

```{r}
# merged_SPN$SPN_proportion_total = merged_SPN$Freq.y/merged_SPN$Freq
# 
# merged_SPN = merge(merged_SPN, putamen_SPN, by = "Var1")
# merged_SPN$CaHPutSPNs = merged_SPN$Freq.y + merged_SPN$SPNcells
# merged_SPN
```

```{r}
total_cells_put =as.data.frame(table(putamen_sobj$donor_id))
total_cells_put
```

```{r}
merged_SPN_final = merge(merged_SPN_final, total_cells_put, by = "Var1")
merged_SPN_final
```


```{r}
merged_SPN_final$total_SPNs = merged_SPN_final$CaH_SPN + merged_SPN_final$Put_SPN
merged_SPN_final$total_cells = merged_SPN_final$Freq.x + merged_SPN_final$Freq.y
merged_SPN_final$SPN_proportion = merged_SPN_final$total_SPNs/merged_SPN_final$total_cells
merged_SPN_final
```

```{r}
merged_SPN_final$Var2.x = NULL
merged_SPN_final$Var2.y = NULL
merged_SPN_final
```


```{r}
b= ggplot(data = merged_SPN_final, aes(x =SPN_proportion, y = total_cells, color = Var1)) + 
  geom_point() +
  labs(x="SPN Fraction in All Cells (CaH and Put)" , y= "Total Cells")  + ggtitle("SPN Fraction in All Cells vs Total SPNs") + scale_color_discrete(name = "Donors")+ geom_text(aes(label = Var1), vjust = -1, hjust = 0.5) 

ggsave("output/SPN_fraction.png", plot= b, width = 14, height = 7)
```




```{r}
# ggplot(data = merged_SPN, aes(x =SPN_proportion_neuron, y = CaHPutSPNs, color = Var1)) + 
#   geom_point() +
#   labs(x="SPN Fraction in Neurons (CaH and Put)" , y= "Total SPN cells (CaH and Put)")  + ggtitle("SPN Fraction in Neurons vs Total SPNs") + scale_color_discrete(name = "Donors")+ geom_text(aes(label = Var1), vjust = -1, hjust = 0.5)
# 
# ggplot(data = merged_SPN, aes(x =SPN_proportion_total, y = CaHPutSPNs, color = Var1)) + 
#   geom_point() +
#   labs(x="SPN Fraction in All Cells (CaH and Put)" , y= "Total Cells")  + ggtitle("SPN Fraction in All Cells vs Total SPNs") + scale_color_discrete(name = "Donors")+ geom_text(aes(label = Var1), vjust = -1, hjust = 0.5)
```


```

