---
title: "R Notebook"
output: html_notebook
---


```{r}
All_XDP_Cohort_new@meta.data
bican_recon@meta.data
xdp_recon@meta.data
```
```{r}
spatial_scores = function(metadata, column, title, updown = -1){
a = ggplot(metadata, aes(x= x_um, y = y_um, color = !!sym(column))) + geom_point(size =0.4) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = updown) +   labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ new_subclass_label_name)
ggsave(a, filename = "pic1.png", width = 25, height = 15)
}

spatial_scores(xdp_recon@meta.data, "Scorehla", "HLA")
spatial_scores(bican_recon@meta.data, "Scorehla", "HLA")
```


```{r}
spatial_scores = function(metadata, column, title, updown = -1){
a = ggplot(metadata, aes(x= x_um, y = y_um, color = !!sym(column))) + geom_point(size =0.4) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = updown) +   labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ cell_class_annot)

metadata_neurons = subset(metadata, subset = cell_class_annot == "neuron")
b = ggplot(metadata_neurons, aes(x= x_um, y = y_um, color = !!sym(column))) + geom_point(size = 0.4) + ggtitle(paste0(" ", title, " Scores"))+ scale_color_viridis_c(option = "magma", name = "Expression", direction = updown)+   labs(paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ reclustered_patch_matrix_exotic)

ggsave(a, filename = "pic1.png", width = 12, height = 10)
ggsave(b, filename = "pic2.png", width = 14, height = 7)
}

spatial_scores(bican_recon@meta.data, "Scorehla", "HLA")
```


```{r}
spatial_scores = function(metadata, column, title, updown = -1){
a = ggplot(metadata, aes(x= x_um, y = y_um, color = !!sym(column))) + geom_point(size =0.4) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = updown) +   labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ WM_GM)
ggsave(a, filename = "pic1.png", width = 10, height = 6)
}

xdp_recon_astro_meta = subset(xdp_recon@meta.data, subset = new_final_cell_class == "astrocyte")

spatial_scores(xdp_recon_astro_meta, "ScoreNFKB", "NFKB")
```










```{r}
All_XDP_SN = qread("All_XDP_Cohorts_SN_sct_250507.qs")
All_XDP_SN@meta.data
```

```{r}
table(All_XDP_SN$cell_class)
```



```{r}
a= DimPlot(All_XDP_SN, group.by = "cell_class", label=T, raster = F)
ggsave(a, filename = "temp.png", width = 10, height = 6)
```


```{r}
library(lme4)

ALL_XDP_meta_sn_new = All_XDP_SN@meta.data

sobj = ALL_XDP_meta_sn_new
sobj = subset(sobj, donor_id != "SCF_22_049CCF")

model_cols = c("donor_id", "cell_class", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("SN") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Class") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 

ggsave(a, filename = "temp.png", width = 7, height = 8)
```


```{r}
All_XDP_Cohort_new
xdp_recon
```
```{r}
table(xdp_recon$Class_label_name)
table(xdp_recon$Subclass_label_name)
table(xdp_recon$Group_label_name)
```

```{r}
temp = subset(xdp_recon@meta.data, subset = Class_label_name == "CN LGE GABA")

a = ggplot(temp, aes(x = x_um, y = y_um, color = Class_label_name)) + geom_point(alpha = 0.7)+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ Class_label_name)
ggsave(a, filename = "temp.png", width = 9, height = 5)
table(temp$Subclass_label_name)
```

```{r}
temp = subset(xdp_recon@meta.data, subset = Class_label_name == "CN LGE GABA")
temp = subset(temp, subset = Subclass_label_name == "STR D1 MSN GABA" |Subclass_label_name == "STR D2 MSN GABA")


a = ggplot(temp, aes(x = x_um, y = y_um, color = Group_label_name)) + geom_point(alpha = 0.7)+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ new_subclass_label_name)
ggsave(a, filename = "temp.png", width = 14, height = 10)
table(temp$Group_label_name)
```



```{r}
temp = subset(bican_recon@meta.data, subset = Class_label_name == "CN LGE GABA")

a = ggplot(temp, aes(x = x_um_rotated, y = y_um_rotated, color = Subclass_label_name)) + geom_point(alpha = 0.7)+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ Subclass_label_name)
ggsave(a, filename = "temp.png", width = 15, height = 13)
table(temp$Subclass_label_name)
```

```{r}
temp = subset(bican_recon@meta.data, subset = Class_label_name == "CN LGE GABA")
temp = subset(temp, subset = Subclass_label_name == "STR D1 MSN GABA" |Subclass_label_name == "STR D2 MSN GABA")


a = ggplot(temp, aes(x = x_um_rotated, y = y_um_rotated, color = Group_label_name)) + geom_point(alpha = 0.7)+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ Group_label_name)
ggsave(a, filename = "temp.png", width = 20, height = 18)
table(temp$Group_label_name)
```


```{r}
library(UCell)

All_XDP_Cohort_new <- AddModuleScore_UCell(All_XDP_Cohort_new, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'bican_recon_astro_markers_top50_wm')
All_XDP_Cohort_new <- AddModuleScore_UCell(All_XDP_Cohort_new, features = list(Score = bican_recon_astro_markers_top50_gm), name = 'bican_recon_astro_markers_top50_gm')

xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'bican_recon_astro_markers_top50_wm')
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_astro_markers_top50_gm), name = 'bican_recon_astro_markers_top50_gm')
```
```{r}
All_XDP_Cohort_new <- AddModuleScore_UCell(All_XDP_Cohort_new, features = list(Score = bican_recon_opc_markers_top50_wm), name = 'bican_recon_opc_markers_top50_wm')
All_XDP_Cohort_new <- AddModuleScore_UCell(All_XDP_Cohort_new, features = list(Score = bican_recon_opc_markers_top50_gm), name = 'bican_recon_opc_markers_top50_gm')
```
```{r}
bican_recon@meta.data
```


```{r}
temp = subset(bican_recon@meta.data, subset = cell_class_annot =="opc")

a = ggplot(temp, aes(x = x_um_rotated, y = y_um_rotated, color = WM_GM)) + geom_point(alpha = 0.7)+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ cell_class_annot)
ggsave(a, filename = "temp.png", width = 10, height = 8)
```



```{r}
softmax_cols = function(df, cols){
    z_cols = paste0(cols, "__z")
    softmax_cols = paste0(cols, "__softmax")
    
    # Z-score normalization of the selected columns
    df[z_cols] = scale(df[cols])
    
    # Apply softmax row-wise: exp of z-scores divided by row sum of exp(z-scores)
    df[softmax_cols] =  t(apply(df[z_cols], 1, function(x) exp(x) / sum(exp(x))))
    
    return(df)
}


columns = c("Scoretop_50_opc_recon_wm", "Scoretop_50_opc_recon_gm" )
temp = softmax_cols(bican_recon@meta.data, columns)
temp
```


```{r}
temp$OPC_WM_GM <- ifelse(
  temp$Scoretop_50_opc_recon_wm__softmax > temp$Scoretop_50_opc_recon_gm__softmax, "White Matter", 
  ifelse(temp$Scoretop_50_opc_recon_gm__softmax > temp$Scoretop_50_opc_recon_wm__softmax, "Gray Matter", "Uncertain")
)
temp
```


```{r}
p = ggplot(temp, aes(x = Scoretop_50_opc_recon_wm, y = Scoretop_50_opc_recon_gm, color = OPC_WM_GM)) +
  geom_point(alpha = 0.6, size = 0.3) +theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 20),  # Increase legend text size
    legend.title = element_text(size = 22), 
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15) 
  ) 
print(p)
p1 = ggMarginal(p, type="histogram" , xparams = list(  bins=100)) 
print(p1)

ggsave(p1, filename = "temp.png", width = 12, height =8)
```
```{r}
temp_df = subset(temp, subset = cell_class_annot =="opc")

a = ggplot(temp_df, aes(x = x_um_rotated, y = y_um_rotated, color = OPC_WM_GM)) + geom_point(alpha = 0.7)+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ cell_class_annot)
ggsave(a, filename = "temp.png", width = 8, height = 6)
```


```{r}
what = qread("/broad/macosko/kimkathl/XDP/Analysis/Gray_White_Matter_Scores/xdp_recon_meta.qs")
what
```


```{r}
columns = c("Scoretop_50_opc_recon_wm", "Scoretop_50_opc_recon_gm" )
temp = softmax_cols(what, columns)
temp
```


```{r}
temp$OPC_WM_GM <- ifelse(
  temp$Scoretop_50_opc_recon_wm__softmax > temp$Scoretop_50_opc_recon_gm__softmax, "White Matter", 
  ifelse(temp$Scoretop_50_opc_recon_gm__softmax > temp$Scoretop_50_opc_recon_wm__softmax, "Gray Matter", "Uncertain")
)
temp

p = ggplot(temp, aes(x = Scoretop_50_opc_recon_wm, y = Scoretop_50_opc_recon_gm, color = OPC_WM_GM)) +
  geom_point(alpha = 0.6, size = 0.3) +theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 20),  # Increase legend text size
    legend.title = element_text(size = 22), 
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15) 
  ) 
print(p)
p1 = ggMarginal(p, type="histogram" , xparams = list(  bins=100)) 
print(p1)

ggsave(p1, filename = "temp.png", width = 12, height =8)
```

```{r}
temp_df = subset(temp, subset = new_final_cell_class =="opc")

a = ggplot(temp_df, aes(x = x_um, y = y_um, color = OPC_WM_GM)) + geom_point()+  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + facet_wrap(~ new_final_cell_class)
ggsave(a, filename = "temp.png", width = 10, height = 8)
```



#cohorts

```{r}
All_XDP_Cohort_new <- AddModuleScore_UCell(All_XDP_Cohort_new, features = list(Score = bican_recon_opc_markers_top50_wm), name = 'top_50_opc_recon_wm')
All_XDP_Cohort_new <- AddModuleScore_UCell(All_XDP_Cohort_new, features = list(Score = bican_recon_opc_markers_top50_gm), name = 'top_50_opc_recon_gm')

All_XDP_Cohort_new@meta.data
```
```{r}
columns = c("Scoretop_50_opc_recon_wm", "Scoretop_50_opc_recon_gm" )
temp = softmax_cols(All_XDP_Cohort_new@meta.data, columns)
temp
```

```{r}
temp$OPC_WM_GM <- ifelse(
  temp$Scoretop_50_opc_recon_wm__softmax > temp$Scoretop_50_opc_recon_gm__softmax, "White Matter", 
  ifelse(temp$Scoretop_50_opc_recon_gm__softmax > temp$Scoretop_50_opc_recon_wm__softmax, "Gray Matter", "Uncertain")
)
temp
```

```{r}
p = ggplot(temp, aes(x = Scoretop_50_opc_recon_wm, y = Scoretop_50_opc_recon_gm, color = OPC_WM_GM)) +
  geom_point(alpha = 0.6, size = 0.3) +theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 20),  # Increase legend text size
    legend.title = element_text(size = 22), 
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15) 
  ) 
print(p)
p1 = ggMarginal(p, type="histogram" , xparams = list(  bins=100)) 
print(p1)
```




```{r}
table(temp$OPC_WM_GM)
```


```{r}
library(lme4)

sobj = subset(temp, subset = final_cell_class_merged_harmony == "opc") 
sobj$OPC_WM_GM[sobj$OPC_WM_GM == "Gray Matter"] = "Gray_Matter"
sobj$OPC_WM_GM[sobj$OPC_WM_GM == "White Matter"] = "White_Matter"
sobj = subset(sobj, donor_id != "SCF_22_049CCF")

model_cols = c("donor_id", "OPC_WM_GM", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$OPC_WM_GM, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("CaH/Put OPCs") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "OPC_WM_GM") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 

ggsave(a, filename = "temp.png", width = 7, height = 4)
```
```{r}
table(sobj$Group_label_names)
```

```{r}
sobj
```


```{r}

# Count total cells per donor
cells_per_donor <- as.data.frame(table(sobj$donor_id))
colnames(cells_per_donor) <- c("donor_id", "total_cells")

# Count cells by class and donor
cell_class_df <- as.data.frame(table(sobj$OPC_WM_GM, sobj$donor_id))
colnames(cell_class_df) <- c("OPC_WM_GM", "donor_id", "Freq")
cell_class_df
# Merge cell class counts with total cell counts
cell_class_df <- merge(cell_class_df, cells_per_donor, by = "donor_id")

# Calculate proportions
cell_class_df$cell_proportions <- cell_class_df$Freq / cell_class_df$total_cells

# Add donor-level metadata
cell_class_df$Cohort <- All_cells_df$Cohort[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Cohort_Condition <- All_cells_df$Cohort_Condition[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Sex <- All_cells_df$Sex[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Condition <- All_cells_df$Condition[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Age_of_Death <- All_cells_df$Age_of_Death[match(cell_class_df$donor_id, All_cells_df$donor_id)]


# Identify controls and cases by donor_id suffix
controls <- cells_per_donor[grepl("CM$|CF$|CM2$|CM6$", cells_per_donor$donor_id), ]
cases <- cells_per_donor[!grepl("CM$|CF$|CM2$|CM6$", cells_per_donor$donor_id), ]

# Sort each group by descending cell count
controls <- controls[order(-controls$total_cells), ]
cases <- cases[order(-cases$total_cells), ]

# Combine sorted donor IDs
ordered_donors <- c(controls$donor_id, cases$donor_id)

# Set donor_id as a factor with correct order
cell_class_df$donor_id <- factor(cell_class_df$donor_id, levels = ordered_donors)

# Optional: re-sort full dataframe to follow donor order
cell_class_df <- cell_class_df %>%
  arrange(factor(donor_id, levels = ordered_donors))

# cell_class_df <- cell_class_df %>%
#   group_by(donor_id) %>%
#   mutate(opc_olig = sum(cell_proportions[cell_class %in% c("oligo", "opc")])) %>%
#   ungroup()
# cell_class_df

# Now compute y_mid for neurons
astro_labels <- cell_class_df %>%
  filter(OPC_WM_GM == "White Matter") %>%
  mutate(y_mid = cell_proportions / 2)


# PLOT 3: Faceted absolute counts
a <- ggplot(cell_class_df, aes(x = donor_id, y = Freq, fill = cell_class)) +
  geom_bar(stat = "identity") +
  xlab("Donors") + ylab("Number of cells") +
  labs(fill = "OPC_WM_GM") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
 # facet_grid(~ Cohort, scales = "free_x", space = "free_x") +
  geom_text(aes(y = total_cells, label = total_cells), vjust = -0.2, size = 3, nudge_y = 0.5) + geom_vline(xintercept = 17.5, linetype = "dashed", color = "black")

# PLOT 4: Faceted proportions
b <- ggplot(cell_class_df, aes(x = donor_id, y = cell_proportions, fill = cell_class)) +
  geom_bar(stat = "identity", position = "stack") +
  xlab("Donors") + ylab("OPC_WM_GM") +
  labs(fill = "OPC_WM_GM") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
 # facet_grid(~ Cohort, scales = "free_x", space = "free_x")+ 
  geom_text( data = astro_labels,  
    aes(x = donor_id, y = y_mid, label = round(cell_proportions, 2)),  # Correctly centered text
    size = 3)+ geom_vline(xintercept = 17.5, linetype = "dashed", color = "black")


# Save plots
ggsave(a, filename = "pic.png", width = 18, height = 5)
ggsave(b, filename = "pic2.png", width = 18, height = 5)
```
```{r}
library(dplyr)
library(ggplot2)

# Count total cells per donor
cells_per_donor <- as.data.frame(table(sobj$donor_id))
colnames(cells_per_donor) <- c("donor_id", "total_cells")

# Count cells by OPC_WM_GM class and donor
cell_class_df <- as.data.frame(table(sobj$OPC_WM_GM, sobj$donor_id))
colnames(cell_class_df) <- c("cell_class", "donor_id", "Freq")

# Merge in total cell counts
cell_class_df <- merge(cell_class_df, cells_per_donor, by = "donor_id")

# Calculate proportions
cell_class_df$cell_proportions <- cell_class_df$Freq / cell_class_df$total_cells

# Add donor-level metadata
cell_class_df$Cohort <- All_cells_df$Cohort[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Cohort_Condition <- All_cells_df$Cohort_Condition[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Sex <- All_cells_df$Sex[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Condition <- All_cells_df$Condition[match(cell_class_df$donor_id, All_cells_df$donor_id)]
cell_class_df$Age_of_Death <- All_cells_df$Age_of_Death[match(cell_class_df$donor_id, All_cells_df$donor_id)]

# Identify controls and cases by donor_id suffix
controls <- cells_per_donor[grepl("CM$|CF$|CM2$|CM6$", cells_per_donor$donor_id), ]
cases <- cells_per_donor[!grepl("CM$|CF$|CM2$|CM6$", cells_per_donor$donor_id), ]

# Sort donor groups by descending cell count
controls <- controls[order(-controls$total_cells), ]
cases <- cases[order(-cases$total_cells), ]

# Combine for factor level ordering
ordered_donors <- c(controls$donor_id, cases$donor_id)
cell_class_df$donor_id <- factor(cell_class_df$donor_id, levels = ordered_donors)

# Optional: reorder full dataframe
cell_class_df <- cell_class_df %>%
  arrange(factor(donor_id, levels = ordered_donors))

# Compute y_mid for labeling: option 1 — label only one class (e.g., "White Matter")
label_df <- cell_class_df %>%
  filter(cell_class == "Gray_Matter") %>%
  mutate(y_mid = 1- (cell_proportions / 2))

# OR option 2 — compute centered labels for all classes
# Uncomment this block if you want to label all categories in the stack
# label_df <- cell_class_df %>%
#   group_by(donor_id) %>%
#   arrange(donor_id, cell_class) %>%
#   mutate(y_mid = cumsum(cell_proportions) - cell_proportions / 2)

# Create bar plot: absolute counts
a <- ggplot(cell_class_df, aes(x = donor_id, y = Freq, fill = cell_class)) +
  geom_bar(stat = "identity") +
  xlab("Donors") + ylab("Number of cells") +
  labs(fill = "OPC_WM_GM") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(aes(y = total_cells, label = total_cells),
            vjust = -0.2, size = 3, nudge_y = 0.5) +
  geom_vline(xintercept = length(controls$donor_id) + 0.5,
             linetype = "dashed", color = "black")

# Create bar plot: proportions
b <- ggplot(cell_class_df, aes(x = donor_id, y = cell_proportions, fill = cell_class)) +
  geom_bar(stat = "identity", position = "stack") +
  xlab("Donors") + ylab("Proportion of cells") +
  labs(fill = "OPC_WM_GM") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_text(data = label_df,
            aes(x = donor_id, y = y_mid, label = round(cell_proportions, 2)),
            size = 3) +
  geom_vline(xintercept = length(controls$donor_id) + 0.5,
             linetype = "dashed", color = "black")

# Save plots
ggsave(a, filename = "pic.png", width = 18, height = 5)
ggsave(b, filename = "pic2.png", width = 18, height = 5)

```

