---
title: "R Notebook"
output: html_notebook
---

```{r}
clean_recon_sobj_with_neuron_subclusters
clean_recon_sobj_with_neuron_subclusters@meta.data
```
```{r}
xdp_cah_put
xdp_cah_put@meta.data
```
```{r}
table(xdp_cah_put$donor_id,xdp_cah_put$cause_of_death )
```


```{r}
xdp_cah_put$cause_of_death = "Other"
xdp_cah_put$cause_of_death[xdp_cah_put$donor_id == "SCF-18-003" | 
                             xdp_cah_put$donor_id == "SCF-18-004" | 
                             xdp_cah_put$donor_id == "SCF-19-009"| 
                             xdp_cah_put$donor_id == "SCF-19-014" | 
                             xdp_cah_put$donor_id == "SCF-20-025" | 
                             xdp_cah_put$donor_id == "SCF-21-030"| 
                             xdp_cah_put$donor_id == "SCF_21-037CM2"] = "Infection-related Death"
                           
```

```{r}
xdp_cah_put$cause_of_death_case_control = paste(xdp_cah_put$Condition, xdp_cah_put$cause_of_death) 
```



```{r}
library(dplyr)
library(ggplot2)

data <- xdp_cah_put@meta.data
df = subset(data, subset = neuron_classes == "SPN_matrix")
df
df_avg <- df %>%
  group_by(donor_id, cause_of_death_case_control, Condition) %>%
  summarise(avg_score = mean(Scoreantigen_processing), .groups = 'drop')
df_avg

# Plot the average score per donor for each condition
ggplot(df_avg, aes(x = cause_of_death_case_control, y = avg_score, color = cause_of_death_case_control)) +
  geom_point(aes(group = donor_id), size = 3) +  # One point per donor
  labs(x = "Condition", y = "Mean Antigen Processing Score", color = "Condition + Cause of Death", title = "SPN Matrix Cells")+
  theme_minimal()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 14),  # Increase tick label font size
            axis.title = element_text(size = 15),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1)  # tilt axis labels
        )+
  theme(
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18),  # Increase legend title size
   # legend.key.size = unit(1.5, "cm")  # Increase legend key size
  ) 


```

```{r}

data <- xdp_cah_put@meta.data
df = subset(data, subset = neuron_classes == "astrocyte")
df
df_avg <- df %>%
  group_by(donor_id, cause_of_death_case_control, Condition) %>%
  summarise(avg_score = mean(Scoreantigen_processing), .groups = 'drop')
df_avg

# Plot the average score per donor for each condition
ggplot(df_avg, aes(x = cause_of_death_case_control, y = avg_score, color = cause_of_death_case_control)) +
  geom_point(aes(group = donor_id), size = 3) +  # One point per donor
  labs(x = "Condition", y = "Mean Antigen Processing Score", color = "Condition + Cause of Death", title = "Astrocyte Cells")+
  theme_minimal()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 14),  # Increase tick label font size
            axis.title = element_text(size = 15),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1)  # tilt axis labels
        )+
  theme(
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18),  # Increase legend title size
   # legend.key.size = unit(1.5, "cm")  # Increase legend key size
  ) 

```


```{r}
clean_recon_sobj_with_neuron_subclusters@meta.data
xdp_cah_put@meta.data
```

```{r}
BICAN_matrix = qread("SPN_Matrix_BICAN_findmarkers.qs")
BICAN_matrix
BICAN_matrix_genes = rownames(BICAN_matrix)
```


```{r}
length(final_c_minus_genes)
length(final_c_plus_genes)
```



```{r}
length(BICAN_matrix_genes)
BICAN_matrix_genes = intersect(rownames(clean_recon_sobj_with_neuron_subclusters),BICAN_matrix_genes)
BICAN_matrix_genes = intersect(rownames(xdp_cah_put),BICAN_matrix_genes)
length(BICAN_matrix_genes)
```


```{r}
clean_recon_sobj_with_neuron_subclusters <- AddModuleScore_UCell(clean_recon_sobj_with_neuron_subclusters,
  features = list(Matrix = BICAN_matrix_genes),
  name = '_BICAN_score'
)

clean_recon_sobj_with_neuron_subclusters <- AddModuleScore_UCell(clean_recon_sobj_with_neuron_subclusters,
  features = list(C_minus = final_c_minus_genes),
  name = '_score'
)

clean_recon_sobj_with_neuron_subclusters <- AddModuleScore_UCell(clean_recon_sobj_with_neuron_subclusters,
  features = list(C_plus = final_c_plus_genes),
  name = '_score'
)



xdp_cah_put <- AddModuleScore_UCell(xdp_cah_put,
  features = list(Matrix = BICAN_matrix_genes),
  name = '_BICAN_score'
)

xdp_cah_put <- AddModuleScore_UCell(xdp_cah_put,
  features = list(C_minus = final_c_minus_genes),
  name = '_score'
)

xdp_cah_put <- AddModuleScore_UCell(xdp_cah_put,
  features = list(C_plus = final_c_plus_genes),
  name = '_score'
)
```


```{r}
clean_recon_sobj_with_neuron_subclusters@meta.data
xdp_cah_put@meta.data
```

```{r}
data = subset(xdp_cah_put@meta.data, neuron_classes == "SPN_matrix")
data

```


```{r}
data = subset(clean_recon_sobj_with_neuron_subclusters@meta.data, reclustered_patch_matrix == "SPN_matrix")
data
data = subset(data, Scoreantigen_processing >0)
data
```


```{r}
cortest1 <- cor.test(data$ScoreNFKB, data$Matrix_BICAN_score, method = "spearman", exact = FALSE )
cortest1

cor1 <- cortest1$estimate
pvalue1 <- cortest1$p.value
subtitl1 <- paste("Spearman correlation: ", sprintf("%0.3f", cor1), " R^2: ", sprintf("%0.3f", cor1^2), " p-value: ", sprintf("%0.4f", pvalue1^2))

ggplot(data, aes(x = ScoreNFKB, y = Matrix_BICAN_score)) +
  geom_point(aes(color = Condition), size = 1, alpha = 0.4) +  # Color and shape by Condition for points only
  labs(x = "Scoreantigen_processing Score", y = "Matrix_BICAN_score", 
       title = "Scoreantigen_processing Score vs Matrix_BICAN_score", 
       subtitle = subtitl1) +
  geom_smooth(method = "lm", se = FALSE, color = "black") +  # Single trend line in black
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 18),
    legend.title = element_text(size = 18),
    legend.text = element_text(size = 16)
  )
```


#spatial_scores = function(metadata, column, title, updown = -1){

```{r}
ggplot(metadata, aes(x= x_um, y = y_um, color = Matrix_BICAN_score)) + geom_point(size =0.5) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = -1) +   
 labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) 
```

```{r}
DimPlot(xdp_cah_put, label = T)
```


```{r}
metadata = clean_recon_sobj_with_neuron_subclusters@meta.data
title = "NFKB"

a = ggplot(metadata, aes(x= x_um, y = y_um, color = ScoreNFKB)) + geom_point(size =0.5) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = -1) +   labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ reclustered_patch_matrix_exotic)

metadata_neurons = subset(metadata, subset = final_cell_class == "neuron")
b = ggplot(metadata_neurons, aes(x= x_um, y = y_um, color = Scoreinterferon_alpha)) + geom_point(size = 0.5) + ggtitle(paste0(" ", title, " Scores"))+ scale_color_viridis_c(option = "magma", name = "Expression", direction = -1)+   labs(paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ reclustered_patch_matrix_exotic)

ggsave(a, filename = "pic1.png", width = 15, height = 10)
ggsave(b, filename = "pic2.png", width = 12, height = 7)

```



histograms_by_all_celltype = function(final_df, score_col, xlab, width_size, height_size){

```{r}
final_df = xdp_cah_put@meta.data
score_col = "Scoreantigen_processing"
xlab = "Antigen Processing Score"

#celltypes = c("astrocyte", "microglia", "oligo", "opc", "endothelial","immune", "ependymal", "non_SPN", "eSPN", "SPN_matrix", "SPN_patch", "SPN_exotic")
celltypes = c("SPN_matrix")

# celltypes = unique(xdp_meta[["neuron_classes"]])  
plots <- list()

for (celltype in celltypes) {
  df_sub = final_df[final_df$neuron_classes == celltype, ]
   
  if (nrow(df_sub) == 0) {
    message(paste("No data for cell type:", celltype, "- skipping."))
    next
  }
  
#min = min(df_sub[[score_col]])
  min = 0.02
max = max(df_sub[[score_col]])
step = (max-min)/100

limits = seq(min, max, step)
  
  a = plot_overlapping_density_histogram(df = df_sub, 
                                          hist_col = df_sub[[score_col]],
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green", "pd" = "red", "ctr" = "blue", "XDP_18_006" = "orange"),
                                          breaks = limits,
                                          title = paste0(celltype),
                                          xlab = xlab,
                                          fig_filename = NULL)
  
    plots[[celltype]] = a
  
}

final_plot <- plot_grid(plotlist = plots, ncol = 4)

# Display or save the final plot
print(final_plot)  # Display
ggsave("combined_plot.png", final_plot, width = 20, height = 10)

```

```{r}
plots
```


```{r}
histograms_by_donor <- function(final_df, score_col, celltype, xlab, width_size, height_size) {
  donor_order <- c("PCMC-16-011", "PCMC-16-012", "SCF-18-003", "SCF-18-004", "SCF-18-006", 
                   "SCF-19-009", "SCF-19-014", "SCF-19-018", "SCF-20-023", "SCF_20-024", 
                   "SCF-20-025", "SCF-21-030", "SCF_22-043", "SCF-22-054CM", "SCF-22-058CF", 
                   "SCF_21-037CM2", "SCF-23-068CM")
  
  plots <- list()
  
  final_df_cellclass = subset(final_df, subset = neuron_classes == celltype)
  
     min_val <- min(final_df_cellclass[[score_col]], na.rm = TRUE)
    max_val <- max(final_df_cellclass[[score_col]], na.rm = TRUE)
    step <- (max_val - min_val) / 100
    limits <- seq(min_val, max_val, step)
    
  for (donor in donor_order) {
    df_sub <- final_df_cellclass[final_df_cellclass$donor_id == donor, ]
    
    if (nrow(df_sub) == 0) {
      message(paste("No data for donor:", donor, "- skipping."))
      next
    }
    
    
    cell_count <- nrow(df_sub)
    
    a <- plot_overlapping_density_histogram(
      df = df_sub, 
      hist_col = df_sub[[score_col]],
      fill_col = "Condition",
      colors = c("XDP" = "red", "Control" = "blue", "BICAN_V8" = "green", 
                 "pd" = "red", "ctr" = "blue", "XDP_18_006" = "orange"),
      breaks = limits,
      title = paste0(donor, ": ", celltype, " (Cells: ", cell_count, ")"),
      xlab = xlab,
      fig_filename = NULL
    )
    
    plots[[donor]] <- a
  }
  
  final_plot <- plot_grid(plotlist = plots, ncol = 5)
  
  print(final_plot)  
  ggsave("combined_plot.png", final_plot, width = width_size, height = height_size)
}

```





```{r}
xdp_meta = xdp_cah_put@meta.data
xdp_meta = subset(xdp_meta, neuron_classes == "astrocyte")
xdp_meta

xdp_meta_cases = subset(xdp_meta, Condition == "XDP")
xdp_meta_controls = subset(xdp_meta, Condition == "Control")
xdp_meta_cases
xdp_meta_controls

XDP_scores <- xdp_meta_cases$ScoreNFKB  
XDP_Control_scores <- xdp_meta_controls$ScoreNFKB 

result1 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "less")
result3 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)
```


```{r}
average_scores_df <- data.frame(donor_id = character(), SPN_score = numeric(), stringsAsFactors = FALSE)

for (donor in donor_order) {
  test <- subset(xdp_meta, donor_id == donor)
  average_SPN_matrix <- mean(test$ScoreNFKB, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, SPN_score = average_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_scores_cases
XDP_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_scores_controls

ggplot(average_scores_df, aes(x = Condition, y = SPN_score, color = Condition, shape = Condition)) +
  geom_jitter(width = 0.3, height = 0, size = 3) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average NFKB score", title = "Astrocyte") +scale_shape_manual(values = c("Control" = 15, "XDP" = 16))+ 
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18),  # Increase axis label font size
           legend.title = element_text(size = 18),  # Increase legend title size
legend.text = element_text(size = 16))  # Increase legend text size
```



```{r}
xdp_cah_put@meta.data
```


```{r}
Idents(xdp_cah_put) = "neuron_classes"
FeaturePlot(xdp_cah_put, features = c("Matrix_BICAN_score"), raster = F)
```


```{r}
spatial_scores(clean_recon_sobj_with_neuron_subclusters@meta.data, "Scoreantigen_processing", "MMR Score")

histograms_by_all_celltype(xdp_cah_put@meta.data, "Scoreantigen_processing", "Antigen Processing score", 20, 10)
```

```{r}
histograms_by_donor(xdp_cah_put@meta.data, "C_minus_score", "SPN_matrix" ,"C_minus_score", 25, 15)
```


```{r}
gene_of_interest = "MSH2" 

#replace seurat_obj here
metadata_df = clean_recon_sobj_with_neuron_subclusters@meta.data
metadata_df$cell_ids = rownames(metadata_df)

#replace seurat_obj here
gene_df = as.data.frame(FetchData(clean_recon_sobj_with_neuron_subclusters, vars = gene_of_interest))
gene_df$cell_ids = rownames(gene_df)

df_final = merge(metadata_df, gene_df, by = "cell_ids" )
df_final

#Replace GENE with gene name
ggplot(df_final, aes(x= x_um, y = y_um, color = MSH2)) + geom_point() +  scale_color_gradient(low = "lightgrey", high = "blue") +  labs(color = "Expression") +
  theme_void() +  facet_wrap(~ reclustered_patch_matrix_exotic)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)
```


```{r}
xdp_cah_put@meta.data
```

```{r}
metadata = xdp_cah_put@meta.data
metadata
table(metadata$neuron_classes)
```
```{r}
df_subset = qread("temphome/RECON/Recon_neuron.qs")
df_subset
DimPlot(df_subset, group.by = "RNA_snn_res.0.2", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.3", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.4", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.5", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.6", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.7", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.8", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.0.9", label = T)
DimPlot(df_subset, group.by = "RNA_snn_res.1", label = T)
FeaturePlot(df_subset, features = c("IFI44", "DDX60", "RIGI", "OAS1"))
```
```{r}
Idents(df_subset) = "RNA_snn_res.0.6"
a = FindAllMarkers(df_subset, min.pct = 0.1, logfc.threshold = 0.5)
a
```

```{r}
a_sig = subset(a, subset = p_val_adj < 0.05)
a_sig
```


```{r}
a_sig = subset(a_sig, subset = pct.1 > 0.8)
a_sig
```


```{r}
a_sig = subset(a, subset = p_val_adj < 0.05)
a_sig = subset(a_sig, subset = cluster == 9)
a_sig
```
```{r}
write.csv(a_sig, "interferon_marker_genes/astrocyte_interferon_genes.csv")
```


```{r}
table(df_subset$RNA_snn_res.0.3)
```


```{r}
a = read.csv("neuron_interferon_genes.csv")
a
```


```{r}
a[a$gene == "IFIT2",]

```


```{r}
a_sig = subset(a, subset = cluster == 26 & pct.1 > 0.7 & avg_log2FC > 0)
a_sig
```


```{r}
write.csv(a_sig, "interferon_marker_genes/astrocyte_interferon_genes.csv")
```

```{r}
marker_genes = a_sig$gene

a = DotPlot(object = df_subset, features = marker_genes, group.by = "RNA_snn_res.0.3")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() + theme_bw()

ggsave(a, filename = "pic.png", width = 10, height = 30)
```


```{r}
FeaturePlot(df_subset, features = c("IFI44L"))
```





```{r}
xdp_meta = xdp_cah_put@meta.data
xdp_meta = subset(xdp_meta, neuron_classes == "SPN_matrix")
xdp_meta

xdp_meta_cases = subset(xdp_meta, Condition == "XDP")
xdp_meta_controls = subset(xdp_meta, Condition == "Control")

XDP_scores <- xdp_meta_cases$Matrix_BICAN_score  
XDP_Control_scores <- xdp_meta_controls$Matrix_BICAN_score 

result1 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "less")
result3 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)
```


```{r}
average_scores_df <- data.frame(donor_id = character(), SPN_score = numeric(), stringsAsFactors = FALSE)

for (donor in donor_order) {
  test <- subset(xdp_meta, donor_id == donor)
  average_SPN_matrix <- mean(test$Matrix_BICAN_score, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, SPN_score = average_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_scores_cases
XDP_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_scores_controls

ggplot(average_scores_df, aes(x = Condition, y = SPN_score, color = Condition, shape = Condition)) +
  geom_jitter(width = 0.3, height = 0, size = 3) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average SPN Matrix score", title = "SPN Matrix") +scale_shape_manual(values = c("Control" = 15, "XDP" = 16))+ 
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18),  # Increase axis label font size
           legend.title = element_text(size = 18),  # Increase legend title size
legend.text = element_text(size = 16))  # Increase legend text size
```

```{r}
SPN = read.csv("~/temphome/SPN.csv", header = T)
SPN
average_scores_df
```
```{r}
SPN_df = merge(SPN, average_scores_df, by.x = "Var2", by.y = "donor_id")
SPN_df
```


```{r}
cortest1 <- cor.test(SPN_df$cell_proportions, SPN_df$SPN_score, method = "spearman", exact = FALSE )
cortest1

cor1 <- cortest1$estimate
pvalue1 <- cortest1$p.value
subtitl1 <- paste("Spearman correlation: ", sprintf("%0.3f", cor1), " R^2: ", sprintf("%0.3f", cor1^2), " p-value: ", sprintf("%0.3f", pvalue1^2))
```


```{r}
ggplot(SPN_df, aes(x = cell_proportions, y = SPN_score, color = Condition, shape = Condition)) +
  geom_point(size = 3) +  # Adjust width for horizontal jitter
  labs(x = "SPN fraction in all nuclei", y = "Average SPN Matrix Score", title = "Average SPN Matrix Score vs SPN fraction", subtitle = subtitl1) +scale_shape_manual(values = c("Control" = 15, "XDP" = 16))+ 
  geom_smooth(method = "lm", se = FALSE, color = "black")+
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18),  # Increase axis label font size
           legend.title = element_text(size = 18),  # Increase legend title size
legend.text = element_text(size = 16))  # Increase legend text size 
```


```{r}
ggplot(SPN_df, aes(x = cell_proportions, y = SPN_score)) +
  geom_point(aes(color = Condition, shape = Condition), size = 3) +  # Color and shape by Condition for points only
  labs(x = "SPN fraction in all nuclei", y = "Average SPN Matrix Score", 
       title = "Average SPN Matrix Score vs SPN fraction", 
       subtitle = subtitl1) +
  scale_shape_manual(values = c("Control" = 15, "XDP" = 16)) + 
  geom_smooth(method = "lm", se = FALSE, color = "black") +  # Single trend line in black
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 18),
    legend.title = element_text(size = 18),
    legend.text = element_text(size = 16)
  )

```

```{r}
diseaseduration = read.csv("dd.csv", header = T)
diseaseduration$Var2 = diseaseduration$Donor.ID
```


```{r}
SPN_df1 = left_join(SPN_df, diseaseduration, by= "Var2")
SPN_df1
SPN_df1[is.na(SPN_df1)] <- 0
SPN_df1
```

```{r}
SPN_df2 = subset(SPN_df1, Var2 != "SCF_22-043")
SPN_df2
```


```{r}
cortest1 <- cor.test(SPN_df2$CAP, SPN_df2$cell_proportions, method = "spearman", exact = FALSE )
cortest1

cor1 <- cortest1$estimate
pvalue1 <- cortest1$p.value
subtitl1 <- paste("Spearman correlation: ", sprintf("%0.3f", cor1), " R^2: ", sprintf("%0.3f", cor1^2), " p-value: ", sprintf("%0.4f", pvalue1^2))

ggplot(SPN_df2, aes(x = CAP, y = cell_proportions)) +
  geom_point(aes(color = Condition, shape = Condition), size = 3) +  # Color and shape by Condition for points only
  labs(x = "CAP Score", y = "SPN fraction in all nuclei", 
       title = "CAP Score vs SPN proportion", 
       subtitle = subtitl1) +
  scale_shape_manual(values = c("Control" = 15, "XDP" = 16)) + 
  geom_smooth(method = "lm", se = FALSE, color = "black") +  # Single trend line in black
  theme_minimal() +
  theme(
    plot.title = element_text(size = 20),
    axis.line = element_line(color = "black"),
    axis.ticks = element_line(color = "black"),
    axis.text = element_text(size = 18),
    axis.title = element_text(size = 18),
    legend.title = element_text(size = 18),
    legend.text = element_text(size = 16)
  )

```
```{r}
xdp_meta
```


```{r}
xdp_meta = xdp_cah_put@meta.data
cell_types = unique(xdp_meta$neuron_classes)

for (celltype in cell_types) {
 df = subset(xdp_meta, subset = neuron_classes == celltype)
 x_order = c("SCF_21-037CM2","SCF-23-068CM","SCF-22-054CM", "SCF-22-058CF", "SCF-20-025", "SCF-18-003",  "SCF_22-043", "SCF_20-024", "SCF-18-004", "SCF-18-006", "SCF-20-023", "SCF-21-030", "PCMC-16-012", "SCF-19-009", "SCF-19-014", "PCMC-16-011", "SCF-19-018")

df$donor_id = factor(df$donor_id, levels = x_order)
  
a = ggplot(df, aes(x=C_minus_score, y=C_plus_score, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ donor_id) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4")) 

print(a)
 ggsave(filename = paste0("pic/plot_", celltype, ".png"), plot = a, width = 12, height = 8)
}
```







```{r}
XDP_MMR_scores <- XDP_MMR_scores_cases$bottom_SPN_score  
XDP_Control_MMR_scores <- XDP_MMR_scores_controls$bottom_SPN_score 
XDP_MMR_scores
XDP_Control_MMR_scores

result1 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "less")
result3 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)

average_scores_df <- data.frame(donor_id = character(), bottom_SPN_score = numeric(), stringsAsFactors = FALSE)

for (donor in donor_order) {
  test <- subset(XDP_matrix_scores_bottom, donor_id == donor)
  average_bottom_10_SPN_matrix <- mean(test$total_expression, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, bottom_SPN_score = average_bottom_10_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_MMR_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_MMR_scores_cases
XDP_MMR_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_MMR_scores_controls

 ggplot(average_scores_df, aes(x = Condition, y = bottom_SPN_score, color = donor_id)) +
  geom_jitter(width = 0.2, height = 0, size = 3) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average Bottom 10% non-SPN score", title = "non-SPN - Bottom 10%") +
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18),  # Increase axis label font size
           legend.title = element_text(size = 18),  # Increase legend title size
legend.text = element_text(size = 16))  # Increase legend text size

```



```{r}
metadata_df
```




```{r}
df = clean_recon_sobj_with_neuron_subclusters@meta.data
df
rid = subset(df, x_um > 15700 & y_um <13000)
rid = rownames(rid)
rid

df$cell_id = rownames(df)
newdf = subset(df, !(cell_id %in% rid))
newdf
```

```{r}
newdf = clean_recon_sobj_with_neuron_subclusters@meta.data
newdf
```
```{r}
new_df1 = subset(new_df, subset = x_um >0)
new_df1
```



```{r}
ggplot(new_df, aes(x = x_um, y = y_um)) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", color = "white", n = 200) +
  scale_fill_viridis_c() + # Or use scale_fill_gradient()
  labs(title = paste("KDE for", cells)) +
  theme_void() + coord_fixed()
```


```{r}
celltype = unique(newdf$final_cell_class)
plots = list()
for (cells in celltype) {
  new = subset(newdf, final_cell_class == cells)

a = ggplot(new, aes(x = x_um, y = y_um)) +
  stat_density_2d(aes(fill = ..level..), geom = "polygon", color = "white", n = 200) +
  scale_fill_viridis_c() + # Or use scale_fill_gradient()
  labs(title = paste("KDE for", cells)) +
  theme_void() + coord_fixed()

plots[[cells]] = a

final_plot <- plot_grid(plotlist = plots, ncol = 3) + theme(panel.background = element_rect(fill = "white", color = NA))

ggsave(final_plot, filename = "pic.png", width = 10, height = 6)
#ggsave(final_plot, filename = "pic.png", width = 8, height = 4)
}

```


```{r}
a = subset(xdp_cah_put, final_cell_class =="neuron")
DimPlot(a, label = T)
FeaturePlot(a, features = c("Matrix_BICAN_score"))
FeaturePlot(a, features = c("Matrix_BICAN_score"))
a@meta.data
```


