---
title: "R Notebook"
output: html_notebook
---

```{r}
final_df = qread("XDP_BICAN_ucell_scores.qs")
final_df
```


```{r}
min(final_df$matrix_markersUCELL)
max(final_df$matrix_markersUCELL)
```

```{r}
final_df$Condition[final_df$Condition == "BICAN_V8"] = "BICAN"
table(final_df$Condition)
```


```{r}
limits = seq(0.2, 0.7, 0.005)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  a = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "SPN Matrix",
                                          xlab = "SPN Matrix Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 24),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  b = plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "Non-SPNs",
                                          xlab = "SPN Matrix Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 24),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18))+ ylab(NULL)  # Increase legend title size
  
  print(a)
  print(b)
```


```{r}
a = ggplot(cell_class_df, aes(x = Var2, y = cell_proportions, fill = Var1)) +
  geom_bar(stat = "identity", postion= "stack") + xlab("Donors from SN Village") + ylab("Cell Type Proportion") + labs(fill = "Cell Type")+ geom_vline(xintercept =  4.5, linetype = "dashed", color = "black")+ theme(axis.text.x = element_text(angle = 45, hjust = 1)) +scale_fill_manual(values = custom_colors)
ggsave(a, filename = "pic.png", width = 7.5, height = 4.5)
    
```


```{r}
min(final_df$C_minusSPN_Matrix_scores_UCELL)
max(final_df$C_minusSPN_Matrix_scores_UCELL)
```

```{r}
limits = seq(0.15, 0.75, 0.005)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  c = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$C_minusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Minus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  d = plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$C_minusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Minus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18))+ ylab(NULL)  # Increase legend title size
  
  print(c)
  print(d)
```

```{r}
min(final_df$C_plusSPN_Matrix_scores_UCELL)
max(final_df$C_plusSPN_Matrix_scores_UCELL)
```

```{r}
limits = seq(0.3, 0.6, 0.0025)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  e = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$C_plusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Plus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  f = plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$C_plusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Plus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18))+ ylab(NULL)  # Increase legend title size
  
  print(e)
  print(f)
```
```{r}
library(patchwork)
pic =  a+b+c+d+e+f + plot_layout(ncol = 2)+ plot_layout(guides = 'collect')

ggsave(pic, filename = "pic.png", width = 10.5, height = 11)
```


```{r}
calico_putamen = qread("~/pd_neurons_integrated_subclustered.qs")
calico_putamen
calico_putamen@meta.data

Idents(calico_putamen) = "patch_matrix"
DimPlot(calico_putamen, label = T)
```

#now SCT transform
```{r}
calico_putamen = qread("kkim_PD_Putamen_SOBJs_pd_neurons_sctransformed_101724.qs")
calico_putamen
```
```{r}
calico_putamen@meta.data
DefaultAssay(calico_putamen) = "SCT"

Idents(calico_putamen) = "patch_matrix"
DimPlot(calico_putamen, label = T)
```

```{r}
#getting rid of weird donor 0800 and 114 which has 2 cells
calico_putamen
calico_putamen = subset(calico_putamen, subset = participant_id != "PD0800")
calico_putamen = subset(calico_putamen, subset = participant_id != "PDC114")
calico_putamen
```



```{r}
length(BICAN_V17_matrix)
new_BICAN_V17_matrix = intersect(BICAN_V17_matrix, rownames(xdp_neurons))
length(new_BICAN_V17_matrix)
```


```{r}
new_BICAN_V17_matrix = intersect(new_BICAN_V17_matrix, rownames(calico_putamen))
length(new_BICAN_V17_matrix)
```


```{r}
new_BICAN_V17_matrix = intersect(new_BICAN_V17_matrix, rownames(BICAN_V8))
length(new_BICAN_V17_matrix)
```


```{r}
calico_putamen <- AddModuleScore_UCell(calico_putamen,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'UCELL'
)

calico_putamen <- AddModuleScore_UCell(calico_putamen,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'UCELL'
)

calico_putamen <- AddModuleScore_UCell(calico_putamen,
  features = list(D_genes = new_d_genes_BICAN),
  name = 'UCELL'
)

calico_putamen <- AddModuleScore_UCell(calico_putamen,
 features = list(matrix_markers = new_BICAN_V17_matrix),
  name = 'UCELL'
)

calico_putamen <- AddModuleScore_UCell(calico_putamen,
 features = list(spn = spn_bican),
  name = 'UCELL'
)
```

```{r}
calico_df = calico_putamen@meta.data
calico_df
```
```{r}
calico_df$Condition = calico_df$case_control
calico_df$reclustered_patch_matrix_exotic = calico_df$patch_matrix
calico_df$reclustered_patch_matrix_exotic[calico_df$reclustered_patch_matrix_exotic == "SPN_patch"] = "SPN_exotic"
```


```{r}
histograms_by_celltype(final_df= calico_df, score_col = "matrix_markersUCELL", xlab = "SPN Matrix Score")
histograms_by_celltype(final_df= calico_df, score_col = "C_minusUCELL", xlab = "C Minus Score")
histograms_by_celltype(final_df= calico_df, score_col = "C_plusUCELL", xlab = "C Plus Score")
histograms_by_celltype(final_df= calico_df, score_col = "D_genesUCELL", xlab = "D Score")
histograms_by_celltype(final_df= calico_df, score_col = "spnUCELL", xlab = "SPN Matrix Score-spn bican")
```


```{r}
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
 features = list(matrix_markers = new_BICAN_V17_matrix),
  name = 'UCELL_new'
)
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
 features = list(matrix_markers = new_BICAN_V17_matrix),
  name = 'UCELL_new'
)
```

```{r}
BICAN_V8@meta.data
```


```{r}
new_df = BICAN_V8@meta.data
xdp_df = xdp_neurons@meta.data

new_df$Condition = "BICAN"

xdp_df <- xdp_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "matrix_markersUCELL_new")]  

new_df <- new_df[, c("DONOR", "Condition", "reclustered_neuron_joint_type", "matrix_markersUCELL_new")] 

new_df$donor_id = new_df$DONOR
new_df$DONOR = NULL
```


```{r}
new_df$reclustered_patch_matrix_exotic = new_df$reclustered_neuron_joint_type
new_df$reclustered_neuron_joint_type = NULL
new_df$reclustered_patch_matrix_exotic[new_df$reclustered_patch_matrix_exotic == "SPN_patch"] = "SPN_exotic"

new_df
xdp_df
```


```{r}
final_df_spn = rbind(xdp_df, new_df)
final_df_spn
qsave(final_df_spn, "final_df_spn.qs")
```



```{r}
min(final_df_spn$matrix_markersUCELL_new)
max(final_df_spn$matrix_markersUCELL_new)

min(calico_df$matrix_markersUCELL)
max(calico_df$matrix_markersUCELL)
```
```{r}
calico_df$Condition = calico_df$case_control
calico_df$Condition[calico_df$Condition == "pd"] = "PD"
calico_df$Condition[calico_df$Condition == "ctr"] = "PD Control"
calico_df
```



#final plot
```{r}
limits = seq(0.1, 0.7, 0.005)

matrix <- final_df_spn[final_df_spn$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  a = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$matrix_markersUCELL_new,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "SPN Matrix",
                                          xlab = "SPN Matrix Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 24),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
nonSPN <- final_df_spn[final_df_spn$reclustered_patch_matrix_exotic == "non-SPN", ]
  b = plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$matrix_markersUCELL_new,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "Non-SPNs",
                                          xlab = "SPN Matrix Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 24),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18))+ ylab(NULL)  # Increase legend title size
  
  m <- calico_df[calico_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  g = plot_overlapping_density_histogram(df = m, 
                                          hist_col = m$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green", "PD" = "red", "PD Control" = "blue"),
                                          breaks = limits,
                                          title = "SPN Matrix (PD)",
                                          xlab = "SPN Matrix Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 24),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
  print(a)
  print(b)
  print(g)
```



```{r}
min(final_df$C_minusSPN_Matrix_scores_UCELL)
max(final_df$C_minusSPN_Matrix_scores_UCELL)

min(calico_df$C_minusUCELL)
max(calico_df$C_minusUCELL)

```

```{r}
limits = seq(0.1, 0.75, 0.005)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  c = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$C_minusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Minus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  d = plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$C_minusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Minus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18))+ ylab(NULL)  # Increase legend title size
  
  
  m <- calico_df[calico_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  h = plot_overlapping_density_histogram(df = m, 
                                          hist_col = m$C_minusUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green", "PD" = "red", "PD Control" = "blue"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Minus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
  print(c)
  print(d)
  print(h)
```

```{r}
min(final_df$C_plusSPN_Matrix_scores_UCELL)
max(final_df$C_plusSPN_Matrix_scores_UCELL)

min(calico_df$C_plusUCELL)
max(calico_df$C_plusUCELL)
```

```{r}
limits = seq(0.2, 0.6, 0.0025)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  e = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$C_plusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Plus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size
  
nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  f = plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$C_plusSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Plus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18))+ ylab(NULL)  # Increase legend title size
  
  
m <- calico_df[calico_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  i = plot_overlapping_density_histogram(df = m, 
                                          hist_col = m$C_plusUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN" = "green",  "PD" = "red", "PD Control" = "blue"),
                                          breaks = limits,
                                          title = "",
                                          xlab = "C Plus Score",
                                          fig_filename = NULL)+ 
  theme(
    plot.title = element_text(size = 20),  # title font size
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 13),  # Increase tick label font size
    axis.title = element_text(size = 18),  # Increase axis label font size
   legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + ylab(NULL)  # Increase legend title size

  print(e)
  print(f)
  print(i)
```

```{r}
library(patchwork)
#g, h, i will be calico
pic =  a+b+ g+c+d+h+e+f+i + plot_layout(ncol = 3)+ plot_layout(guides = 'collect')

ggsave(pic, filename = "pic.png", width = 15, height = 11)
```


```{r}
qsave(calico_df, "calico_scores_only.qs")
```


```{r}
length(new_c_plus_genes_BICAN)
length(intersect(new_c_plus_genes_BICAN, rownames(xdp_neurons)))
       
length(new_c_plus_genes_BICAN)
length(intersect(new_c_plus_genes_BICAN, rownames(BICAN_V8)))

length(new_c_plus_genes_BICAN)
length(intersect(new_c_plus_genes_BICAN, rownames(calico_putamen)))
```

```{r}
xdp_sct_c_plus = as.data.frame(rowSums(xdp_neurons@assays$SCT@counts))
xdp_sct_c_plus$genes = rownames(xdp_sct_c_plus)
xdp_sct_c_plus = subset(xdp_sct_c_plus, subset = genes %in% new_c_plus_genes_BICAN)
xdp_sct_c_plus
```


```{r}
xdp_sct_c_plus

bican_sct_c_plus = as.data.frame(rowSums(BICAN_V8@assays$SCT@counts))
bican_sct_c_plus$genes = rownames(bican_sct_c_plus)
bican_sct_c_plus = subset(bican_sct_c_plus, subset = genes %in% new_c_plus_genes_BICAN)
bican_sct_c_plus

calico_sct_c_plus = as.data.frame(rowSums(calico_putamen@assays$SCT@counts))
calico_sct_c_plus$genes = rownames(calico_sct_c_plus)
calico_sct_c_plus = subset(calico_sct_c_plus, subset = genes %in% new_c_plus_genes_BICAN)
calico_sct_c_plus
```


```{r}
merge_sct_c_plus = merge(xdp_sct_c_plus, bican_sct_c_plus, by = "genes")
merge_sct_c_plus
merge_sct_c_plus = merge(merge_sct_c_plus, calico_sct_c_plus, by = "genes")
merge_sct_c_plus
```
```{r}
merge_sct_c_plus$XDP_C_Plus_SCT_Counts = merge_sct_c_plus$`rowSums(xdp_neurons@assays$SCT@counts)`
merge_sct_c_plus$`rowSums(xdp_neurons@assays$SCT@counts)` = NULL

merge_sct_c_plus$BICAN_C_Plus_SCT_Counts = merge_sct_c_plus$`rowSums(BICAN_V8@assays$SCT@counts)`
merge_sct_c_plus$`rowSums(BICAN_V8@assays$SCT@counts)` = NULL

merge_sct_c_plus$Calico_C_Plus_SCT_Counts = merge_sct_c_plus$`rowSums(calico_putamen@assays$SCT@counts)`
merge_sct_c_plus$`rowSums(calico_putamen@assays$SCT@counts)` = NULL

merge_sct_c_plus
```

```{r}

```


```{r}
top_10 <- df %>% 
  arrange(desc(y)) %>% 
  slice(1:10)
```


```{r}
top_10 <- merge_sct_c_plus %>% 
  arrange(desc(XDP_C_Plus_SCT_Counts)) %>% 
  slice(1:5)
ggplot(data = merge_sct_c_plus, aes(x=XDP_C_Plus_SCT_Counts, y= Calico_C_Plus_SCT_Counts)) + geom_point(alpha = 0.4) + xlab("XDP SCT counts for C Plus genes") +ylab("Calico SCT counts for C Plus genes") + xlim(0,7000000) +ylim(0,7000000) +  geom_text(data = top_10, aes(label = genes), vjust = -1, hjust = 0.5, size = 4, color = "red")

top_10 <- merge_sct_c_plus %>% 
  arrange(desc(Calico_C_Plus_SCT_Counts)) %>% 
  slice(1:5)

ggplot(data = merge_sct_c_plus, aes(x=BICAN_C_Plus_SCT_Counts, y= Calico_C_Plus_SCT_Counts)) + geom_point(alpha = 0.4) + xlab("BICAN SCT counts for C Plus genes") +ylab("Calico SCT counts for C Plus genes") + xlim(0,7000000) +ylim(0,7000000)+  geom_text(data = top_10, aes(label = genes), vjust = -1, hjust = 0.5, size = 4, color = "red")

top_10 <- merge_sct_c_plus %>% 
  arrange(desc(BICAN_C_Plus_SCT_Counts)) %>% 
  slice(1:5)
ggplot(data = merge_sct_c_plus, aes(x=XDP_C_Plus_SCT_Counts, y= BICAN_C_Plus_SCT_Counts)) + geom_point(alpha = 0.4) + xlab("XDP SCT counts for C Plus genes") +ylab("BICAN SCT counts for C Plus genes") + xlim(0,7000000) +ylim(0,7000000)+  geom_text(data = top_10, aes(label = genes), vjust = -1, hjust = 0.5, size = 4, color = "red")


```

```{r}
xdp_neurons
calico_putamen
```
```{r}
test_xdp@meta.data

region = test_xdp@meta.data 
  
  test_xdp@meta.data$region rownames(test_xdp@meta.data) 
region
```



```{r}
test_xdp
```



