---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(Matrix)
library(rhdf5)
library(dplyr)
library(qs)
```


```{r}
filtered_seurat_object_list <- qread("Cellbender_seurat/filtered_seurat_object_list.qs")
filtered_seurat_object_list
```

```{r}
mergeSeuratListWithMetadata = function(seurat_obj_list, cell_ids=NULL, project=NULL){

    # Harmonize metadata columns
    all_colnames = unique(unlist(lapply(seurat_obj_list, function(x) colnames(x@meta.data))))
    seurat_obj_list = lapply(seurat_obj_list, function(x) {
        missing_cols = setdiff(all_colnames, colnames(x@meta.data))
        if(length(missing_cols) > 0){
            x@meta.data[missing_cols] = NA
        }
        return(x)
    })

    if (is.null(project)){
        project = "merged"
    }
    
    if (is.null(cell_ids)){
        seurat_merged = Reduce(function(x, y) merge(x, y, project=project), 
            seurat_obj_list)
    } else {
        seurat_merged = Reduce(function(x, y) merge(x, y, project=project, add.cell.ids=cell_ids), 
            seurat_obj_list)
    }
    
    md = lapply(seurat_obj_list, function(x){
        x@meta.data$orig.row.names = rownames(x@meta.data)
        x@meta.data
    })
    
    md = do.call(rbind, md)
    rownames(md) = md$orig.row.names
    md$orig.row.names = NULL
    seurat_merged@meta.data = md
    return(seurat_merged)
}
```


#merge caudate libraries 
```{r}
CaH_list = list(CaH_1 = filtered_seurat_object_list[["CaH_rxn1"]], CaH_2 = filtered_seurat_object_list[["CaH_rxn2"]], CaH_3 = filtered_seurat_object_list[["CaH_rxn3"]], CaH_4 = filtered_seurat_object_list[["CaH_rxn4"]])

for(name in names(CaH_list)){
     sobj =CaH_list[[name]]
     sobj$library = name
     sobj = RenameCells(sobj, new.name = paste(sobj$library, colnames(sobj), sep="__"))
     CaH_list[[name]] = sobj
     
}
merged_caudate = mergeSeuratListWithMetadata(CaH_list)

head(merged_caudate)
```


#merge putamen libraries
```{r}
Put_list = list(Put_1 = filtered_seurat_object_list[["Put_rxn1"]], Put_2 = filtered_seurat_object_list[["Put_rxn2"]], Put_3 = filtered_seurat_object_list[["Put_rxn3"]], Put_4 = filtered_seurat_object_list[["Put_rxn4"]])

for(name in names(Put_list)){
     sobj =Put_list[[name]]
     sobj$library = name
     sobj = RenameCells(sobj, new.name= paste(sobj$library, colnames(sobj), sep="__"))
     Put_list[[name]] = sobj
     
}

merged_putamen = mergeSeuratListWithMetadata(Put_list)

head(merged_putamen)
```


#save merged
```{r}
qsave(CaH_list, "Cellbender_seurat/merged_caudate.qs")
qsave(Put_list, "Cellbender_seurat/merged_putamen.qs")
```




```{r}
donor_metadata = read.csv("Cellbender_seurat/Donor_metadata.csv", header = T)
donor_metadata = donor_metadata[, c("Donor.ID","Sex", "Brain_bank", "Year_collected", "Condition", "Age.of.Onset", "Age.of.Death", "Disease_duration", "RQS", "DV200", "pH", "MQS_numerical", "MQS")]
donor_metadata
```




#merge metadata
```{r}
merged_caudate@meta.data = merge(merged_caudate@meta.data, donor_metadata, by.x = "donor_id", by.y = "Donor.ID")

merged_putamen@meta.data = merge(merged_putamen@meta.data, donor_metadata, by.x = "donor_id", by.y = "Donor.ID")

head(merged_caudate)
head(merged_caudate@meta.data)
```

```{r}
rownames(merged_caudate@meta.data) = paste(merged_caudate@meta.data$library, merged_caudate@meta.data$cell, sep = "__")
head(merged_caudate)

rownames(merged_putamen@meta.data) = paste(merged_putamen@meta.data$library, merged_putamen@meta.data$cell, sep ="__")
head(merged_putamen)

```


```{r}
merged_caudate$pct_mito = (100*colSums(merged_caudate@assays$RNA@counts[grepl("^MT-", rownames(merged_caudate)),]) /
   colSums(merged_caudate@assays$RNA@counts))
merged_caudate@meta.data
```

```{r}
merged_putamen$pct_mito = (100*colSums(merged_putamen@assays$RNA@counts[grepl("^MT-", rownames(merged_putamen)),]) /
   colSums(merged_putamen@assays$RNA@counts))
merged_putamen@meta.data
```

```{r}
qsave(merged_caudate, "Cellbender_seurat/redo2_merged_caudate.qs")
qsave(merged_putamen, "Cellbender_seurat/redo2_merged_putamen.qs")
```

```{r}
head(merged_caudate@meta.data)
```

```{r}
median_pct_intronic = median(merged_caudate$pct_intronic)
title = paste0("Caudate pct intronic, Median: ", sprintf("%0.3f", median_pct_intronic))
pct_intronic_hist = hist(merged_caudate$pct_intronic, main = title, xlab = "pct intronic", col="grey")

#pct_intronic_hist_filename = paste0("graphs_to_export/caudate_pct_intronic_hist.png")
#png(pct_intronic_hist_filename, width = 800, height = 600,  bg = "white")
#plot(pct_intronic_hist)
#dev.off()
```

```{r}
median_pct_mito = median(merged_caudate$pct_mito)
title = paste0("Caudate pct mitochondrial, Median: ", sprintf("%0.3f", median_pct_mito))
pct_mito_hist = hist(merged_caudate$pct_mito, main = title, xlab = "pct mito", col="grey")
```


```{r}
median_pct_intronic = median(merged_putamen$pct_intronic)
title = paste0("Putamen pct intronic, Median: ", sprintf("%0.3f", median_pct_intronic))
pct_intronic_hist = hist(merged_putamen$pct_intronic, main = title, xlab = "pct intronic", col="grey")


median_pct_mito = median(merged_putamen$pct_mito)
title = paste0("Putamen pct mitochondrial, Median: ", sprintf("%0.3f", median_pct_mito))
pct_mito_hist = hist(merged_putamen$pct_mito, main = title, xlab = "pct mito", col="grey")
```

```{r}
merged_caudate = qread("Cellbender_seurat/redo2_merged_caudate.qs")
merged_putamen = qread("Cellbender_seurat/redo2_merged_putamen.qs")

merged_caudate
merged_putamen
```



#filtering step: pct_mitochondrial <10, pct intronic >= 0.25 #should be & not either
```{r}
filtered_merged_caudate <- subset(merged_caudate, subset = pct_mito < 10 & pct_intronic >= 0.25)
filtered_merged_putamen <- subset(merged_putamen, subset = pct_mito < 10 & pct_intronic >= 0.25)
```

```{r}
merged_caudate
merged_putamen
```


```{r}
filtered_merged_caudate
filtered_merged_putamen
```
Number of cells by brain region
Number of number of donors’ cell numbers
Histogram of donors age
Count of donors: sex
Count of donors: case-control status


```{r}
library(ggplot2)
```


```{r}
cells_per_brain_region = data.frame(brain_regions = c("Caudate", "Putamen"),
                        cell_numbers = c(ncol(filtered_merged_caudate), ncol(filtered_merged_putamen)))
#cells_per_brain_region

ggplot(cells_per_brain_region, aes(x=cells_per_brain_region$brain_regions, y = cells_per_brain_region$cell_numbers, fill = brain_regions)) + geom_bar(stat = "identity")+ geom_text(aes(label = cells_per_brain_region$cell_numbers), vjust = -0.3, color = "black", size = 4) + xlab("Brain region") + ylab("Number of Cells")

```

```{r}
cells_per_donor_per_rxn = as.data.frame(table(filtered_merged_caudate@meta.data$donor_id, filtered_merged_caudate@meta.data$library))
cells_per_donor_per_rxn

ggplot(cells_per_donor_per_rxn, aes(x=Var1, y = Freq, fill=Var2)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ylim(0, 2500)
```

```{r}
cells_per_donor_per_rxn = as.data.frame(table(filtered_merged_putamen@meta.data$donor_id, filtered_merged_putamen@meta.data$library))
cells_per_donor_per_rxn

ggplot(cells_per_donor_per_rxn, aes(x=Var1, y = Freq, fill=Var2)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ylim(0, 2500)
```



```{r}
median_genes_per_donor <-filtered_merged_caudate@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor
```

```{r}
median_genes_per_donor <-filtered_merged_caudate@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor
```

```{r}
ggplot(median_genes_per_donor, aes(x=donor_id, y = median_genes, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median number of genes") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ylim(0,4000) 
```

```{r}
median_genes_per_donor <-filtered_merged_putamen@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor

ggplot(median_genes_per_donor, aes(x=donor_id, y = median_genes, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median number of genes") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ylim(0,4000)
```

```{r}
median_umis_per_donor <-filtered_merged_caudate@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(mUMI = median(nUmi, na.rm = TRUE))

median_umis_per_donor

ggplot(median_umis_per_donor, aes(x=donor_id, y = mUMI, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median UMIs") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
median_umis_per_donor <-filtered_merged_putamen@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(mUMI = median(nUmi, na.rm = TRUE))

median_umis_per_donor

ggplot(median_umis_per_donor, aes(x=donor_id, y = mUMI, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median UMIs") + theme(axis.text.x = element_text(angle = 45, hjust = 1))
```










```{r}
filtered_merged_caudate@meta.data
```




```{r}
donor_by_rxn = as.data.frame(table(filtered_merged_caudate@meta.data$donor_id, filtered_merged_caudate@meta.data$library))
donor_by_rxn$median_genes = median(filtered_merged_caudate$nCount_RNA["donor_id"])
donor_by_rxn
```

```{r}
donor_names = levels(donor_by_rxn$Var1)

for donors in donor_names{
  
  
}
```





```{r}
median_genes= median(filtered_merged_caudate$nFeature_RNA)

genes_per_cell_per_rxn = as.data.frame(table(filtered_merged_caudate@meta.data$donor_id, filtered_merged_caudate@meta.data$library))
cells_per_donor_per_rxn

ggplot(cells_per_donor_per_rxn, aes(x=Var1, y = Freq, fill=Var2)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ylim(0, 2500)
```












```{r}
title = "Histogram of Age at Death"
hist(donor_metadata$Age.of.Death, main=title, xlab= "Age at Death", col = "grey", breaks = 20)

title = "Histogram of Age of Onset"
hist(donor_metadata$Age.of.Onset, main=title, xlab= "Age of Onset", col = "grey", breaks = 15)

title = "Histogram of Disease Duration"
hist(donor_metadata$Disease_duration, main=title, xlab= "Disease Duration", col = "grey", breaks = 5)
```

```{r}
total_donors_cells_caudate = as.data.frame(table(filtered_merged_caudate@meta.data$donor_id))
#total_donors_cells

total_donors_cells_caudate$Var1 <- factor(total_donors_cells_caudate$Var1, levels = total_donors_cells_caudate$Var1[order(total_donors_cells_caudate$Freq, decreasing = TRUE)])


ggplot(total_donors_cells_caudate, aes(x=total_donors_cells_caudate$Var1, y = total_donors_cells_caudate$Freq)) + geom_bar(stat = "identity")+ geom_text(aes(label = total_donors_cells_caudate$Freq), vjust = -0.3, color = "black", size = 3) + xlab("Donors from Caudate Village") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

```{r}
total_donors_cells_putamen = as.data.frame(table(filtered_merged_putamen@meta.data$donor_id))
#total_donors_cells

total_donors_cells_putamen$Var1 <- factor(total_donors_cells_putamen$Var1, levels = total_donors_cells_putamen$Var1[order(total_donors_cells_putamen$Freq, decreasing = TRUE)])


ggplot(total_donors_cells_putamen, aes(x=total_donors_cells_putamen$Var1, y = total_donors_cells_putamen$Freq)) + geom_bar(stat = "identity")+ geom_text(aes(label = total_donors_cells_putamen$Freq), vjust = -0.3, color = "black", size = 3) + xlab("Donors from Putamen Village") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
```

#calculate how many cells are being filtered out from EACH donor

```{r}
#prefilter
prefilter_total_donors_cells_caudate = as.data.frame(table(merged_caudate@meta.data$donor_id, merged_caudate@meta.data$library))
prefilter_total_donors_cells_caudate
```


```{r}
total_donors_cells_caudate 

```







```{r}
barplot <- ggplot(df, aes(x = conditions, y = values)) +
  geom_bar(stat = "identity")
```


```{r}
df = table(filtered_merged_caudate@meta.data$donor_id, filtered_merged_caudate@meta.data$library)
df= as.data.frame(df)
df
```




















