---
title: "R Notebook"
output: html_notebook
---

```{r}
caudate_sobj = qread("Cellbender_seurat/Bennet_caudate_clean.qs")
putamen_sobj = qread("Cellbender_seurat/Bennet_putamen_clean.qs")

caudate_sobj
putamen_sobj
```

```{r}
table(caudate_sobj$donor_id, caudate_sobj$cell_class)
```

```{r}
caudate_cell_types = as.data.frame(table(caudate_sobj$donor_id, caudate_sobj$cell_class))
caudate_cell_types = subset(caudate_cell_types, subset = Var2 == "neuron")
caudate_cell_types$CaH_neurons= caudate_cell_types$Freq
caudate_cell_types$Freq = NULL
caudate_cell_types
```

```{r}
caudate_neuron= qread("Subclustering/caudate_neurons_integrated_subcluster.qs")
head(caudate_neuron)
```
```{r}
caudate_neuron_final = subset(caudate_neuron, subset = cell_class != "spn_delete")
caudate_neuron_final = subset(caudate_neuron_final, subset = cell_class != "interneuron_6delete")
unique(caudate_neuron_final$cell_class)
```


```{r}
caudate_neuron_final@meta.data$sub_class = caudate_neuron_final@meta.data$cell_class
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_matrix_1"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D2_SPN_patch_2"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_patch_2"] = "SPN"
#caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "eSPN"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_patch_3"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN_patch_1"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D2_SPN"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D1_SPN"] = "SPN"
caudate_neuron_final$sub_class[caudate_neuron_final$sub_class == "D2_SPN_patch_1"] = "SPN"

caudate_neuron_final@meta.data
```

```{r}
table(caudate_neuron_final$donor_id, caudate_neuron_final$sub_class)
```

```{r}
caudate_SPN = as.data.frame(table(caudate_neuron_final$donor_id, caudate_neuron_final$sub_class))
caudate_SPN = subset(caudate_SPN, subset = Var2 == "SPN")
caudate_SPN$CaH_SPN = caudate_SPN$Freq 
caudate_SPN$Freq = NULL
caudate_SPN
```

```{r}
# merged_SPN = merge(caudate_cell_types, caudate_SPN, by = "Var1")
# merged_SPN$Var2.y = NULL
# merged_SPN
```

```{r}
total_cells =as.data.frame(table(caudate_sobj$donor_id))
total_cells
```

```{r}
merged_SPN_final = merge(caudate_SPN, total_cells, by = "Var1")
merged_SPN_final
```



```{r}
putamen_neuron= qread("Subclustering/putamen_neurons_integrated_subcluster.qs")
head(putamen_neuron)
```

```{r}
unique(putamen_neuron$cell_class)
```

```{r}
putamen_neuron@meta.data$sub_class = putamen_neuron@meta.data$cell_class
putamen_neuron$sub_class[putamen_neuron$sub_class == "D2_SPN_1"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D1_SPN_2"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D2_SPN_3"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D1_SPN_matrix"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D2_SPN_2"] = "SPN"
putamen_neuron$sub_class[putamen_neuron$sub_class == "D1_SPN_1"] = "SPN"
#putamen_neuron$sub_class[putamen_neuron$sub_class == "eSPN"] = "SPN"

putamen_neuron@meta.data
```
```{r}
putamen_SPN= as.data.frame(table(putamen_neuron$donor_id, putamen_neuron$sub_class))
putamen_SPN = subset(putamen_SPN, subset = Var2 == "SPN")
putamen_SPN$Put_SPN = putamen_SPN$Freq
putamen_SPN$Freq = NULL
putamen_SPN
```

```{r}
merged_SPN_final= merge(merged_SPN_final, putamen_SPN, by = "Var1")
merged_SPN_final
```




#could you plot each donor's SPN fraction versus their total number of SPNs?  We might want to pick donors who have a range of SPN fractions, prioritizing those with high absolute SPN numbers, to ensure they are of good quality.
```{r}
# merged_SPN$SPN_proportion_neuron = merged_SPN$Freq.y/merged_SPN$Freq.x
# merged_SPN = merge(merged_SPN, total_cells, by = "Var1")
# merged_SPN
```

```{r}
# merged_SPN$SPN_proportion_total = merged_SPN$Freq.y/merged_SPN$Freq
# 
# merged_SPN = merge(merged_SPN, putamen_SPN, by = "Var1")
# merged_SPN$CaHPutSPNs = merged_SPN$Freq.y + merged_SPN$SPNcells
# merged_SPN
```

```{r}
total_cells_put =as.data.frame(table(putamen_sobj$donor_id))
total_cells_put
```

```{r}
merged_SPN_final = merge(merged_SPN_final, total_cells_put, by = "Var1")
merged_SPN_final
```


```{r}
merged_SPN_final$total_SPNs = merged_SPN_final$CaH_SPN + merged_SPN_final$Put_SPN
merged_SPN_final$total_cells = merged_SPN_final$Freq.x + merged_SPN_final$Freq.y
merged_SPN_final$SPN_proportion = merged_SPN_final$total_SPNs/merged_SPN_final$total_cells
merged_SPN_final
```

```{r}
merged_SPN_final$Var2.x = NULL
merged_SPN_final$Var2.y = NULL
merged_SPN_final
```


```{r}
b= ggplot(data = merged_SPN_final, aes(x =SPN_proportion, y = total_cells, color = Var1)) + 
  geom_point() +
  labs(x="SPN Fraction in All Cells (CaH and Put)" , y= "Total Cells")  + ggtitle("SPN Fraction in All Cells vs Total SPNs") + scale_color_discrete(name = "Donors")+ geom_text(aes(label = Var1), vjust = -1, hjust = 0.5) 

ggsave("output/SPN_fraction.png", plot= b, width = 14, height = 7)
```




```{r}
# ggplot(data = merged_SPN, aes(x =SPN_proportion_neuron, y = CaHPutSPNs, color = Var1)) + 
#   geom_point() +
#   labs(x="SPN Fraction in Neurons (CaH and Put)" , y= "Total SPN cells (CaH and Put)")  + ggtitle("SPN Fraction in Neurons vs Total SPNs") + scale_color_discrete(name = "Donors")+ geom_text(aes(label = Var1), vjust = -1, hjust = 0.5)
# 
# ggplot(data = merged_SPN, aes(x =SPN_proportion_total, y = CaHPutSPNs, color = Var1)) + 
#   geom_point() +
#   labs(x="SPN Fraction in All Cells (CaH and Put)" , y= "Total Cells")  + ggtitle("SPN Fraction in All Cells vs Total SPNs") + scale_color_discrete(name = "Donors")+ geom_text(aes(label = Var1), vjust = -1, hjust = 0.5)
```

