---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Seurat)
library(Matrix)
library(rhdf5)
library(dplyr)
library(qs)
library(ggplot2)
```

```{r}
merged_caudate = qread("Cellbender_seurat/redo2_merged_caudate.qs")
merged_putamen = qread("Cellbender_seurat/redo2_merged_putamen.qs")

merged_caudate
merged_putamen
```

```{r}
filtered_merged_caudate <- subset(merged_caudate, subset = pct_mito < 10 & pct_intronic >= 0.25)
filtered_merged_putamen <- subset(merged_putamen, subset = pct_mito < 10 & pct_intronic >= 0.25)
```

```{r}
filtered_merged_caudate
filtered_merged_putamen
```

#HVG calculation helper function
```{r}
getSeuratVarFeatureIntersectByCol = function(
   seurat_obj,
   subset_col,
   original_nfeatures,
   n_subsets_to_cover=NULL
){
  
   hvgs = list()


   unique_ids = unique(seurat_obj@meta.data[[subset_col]])


   if (is.null(n_subsets_to_cover)){
       n_subsets_to_cover = floor(length(unique_ids)/2)
   }


   i=1
   for (id in unique_ids) {
       print(paste("Subset", id, "--", i, "of", length(unique_ids)))
       i = i + 1
      
       seurat_subset = seurat_obj[, seurat_obj[[subset_col]] == id]
      
       if (ncol(seurat_subset) < 2){next}
      
       suppressWarnings({
           seurat_subset = FindVariableFeatures(
               seurat_subset, nfeatures=original_nfeatures, verbose = FALSE)
       })
      
       hvgs[[id]] = getSeuratVarFeatures(seurat_subset)
      
   }


   common_hvgs = getCommonStrings(hvgs, n_subsets_to_cover)
   print(paste("Number of HVGs in common across", n_subsets_to_cover, "--", length(common_hvgs)))


   return(common_hvgs)
}

```


```{r}
getSeuratVarFeatures = function(sobj){
    # the magical incantation that returns the slot of the attribute of the slot that actually holds the list of variable feature -_-
    return(sobj@assays$RNA@var.features)
}
```

```{r}
getCommonStrings <- function(list_of_lists, n) {
  # Create an empty list to store string occurrences
  string_occurrences <- list()

  # Iterate over each sublist
  for (sublist in list_of_lists) {
    # For each string in the sublist, increment its count in string_occurrences
    for (string in unique(sublist)) {
      if (!is.null(string_occurrences[[string]])) {
        string_occurrences[[string]] <- string_occurrences[[string]] + 1
      } else {
        string_occurrences[[string]] <- 1
      }
    }
  }

  # Filter the strings that occur at least n times
  common_strings <- names(string_occurrences)[string_occurrences >= n]

  return(common_strings)
}
```


```{r}
filtered_merged_caudate@meta.data
```


#Actual Clustering Code- caudate
```{r}
# Counts of super lowly expressed genes are essentially random
# Also, we don't really care about housekeeping genes that have almost the same expression in every cell
# Before clustering, we want to find "highly variable genes" (hvgs) that tend to be both highly expressed and vary a lot from cell to cell.
# we do this by finding hvgs in each participant individually, and collating the genes
# that are highly variable in at least half of donors.


# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(filtered_merged_caudate, subset_col="donor_id", original_nfeatures=2500)


n_dims_use=20


# now cluster
# the "%>%" lines are a little piece of syntax from the dyplr library,
# short for "apply the following transformation to the object"
# doing this line-by-line allows us to apply a sequence of transformations
filtered_merged_caudate = (filtered_merged_caudate
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)


# Now we can plot the data and just see what it looks like


setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}




DimPlot(filtered_merged_caudate, group.by = "library", label=T) # are there library batch effects?
DimPlot(filtered_merged_caudate, group.by = "donor_id", label=T) # are there donor batch effects?
DimPlot(filtered_merged_caudate, group.by = "Condition") # change col name to whatever your case control metadata column is
DimPlot(filtered_merged_caudate, group.by = "RNA_snn_res.0.5", label=T) # make a few of these for different resolutions


#qsave(filtered_merged_caudate, "somewhere/cozy")

```

```{r}
DimPlot(filtered_merged_caudate, group.by = "library") # are there library batch effects?
DimPlot(filtered_merged_caudate, group.by = "donor_id") # are there donor batch effects?
DimPlot(filtered_merged_caudate, group.by = "Condition") # change col name to whatever your case control metadata column is
DimPlot(filtered_merged_caudate, group.by = "RNA_snn_res.0.5", label=T) # make a few of these for different resolutions


qsave(filtered_merged_caudate, "Cellbender_seurat/filtered_merged_caudate_clustered.qs")
```
#clustering for putamen
```{r}
# Counts of super lowly expressed genes are essentially random
# Also, we don't really care about housekeeping genes that have almost the same expression in every cell
# Before clustering, we want to find "highly variable genes" (hvgs) that tend to be both highly expressed and vary a lot from cell to cell.
# we do this by finding hvgs in each participant individually, and collating the genes
# that are highly variable in at least half of donors.


# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(filtered_merged_putamen, subset_col="donor_id", original_nfeatures=2500)


n_dims_use=20


# now cluster
# the "%>%" lines are a little piece of syntax from the dyplr library,
# short for "apply the following transformation to the object"
# doing this line-by-line allows us to apply a sequence of transformations
filtered_merged_putamen = (filtered_merged_putamen
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_putamen$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_putamen$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)


# Now we can plot the data and just see what it looks like


setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}




DimPlot(filtered_merged_putamen, group.by = "library", label=T) # are there library batch effects?
DimPlot(filtered_merged_putamen, group.by = "donor_id", label=T) # are there donor batch effects?
DimPlot(filtered_merged_putamen, group.by = "Condition") # change col name to whatever your case control metadata column is
DimPlot(filtered_merged_putamen, group.by = "RNA_snn_res.0.3", label=T) # make a few of these for different resolutions

DimPlot(filtered_merged_putamen, group.by = "library") # are there library batch effects?
DimPlot(filtered_merged_putamen, group.by = "donor_id") # are there donor batch effects?

qsave(filtered_merged_putamen, "Cellbender_seurat/filtered_merged_putamen_clustered.qs")
```



```{r}
DimPlot(filtered_merged_caudate, group.by = "RNA_snn_res.0.2", label=T)
DimPlot(filtered_merged_putamen, group.by = "RNA_snn_res.0.2", label=T)
```

```{r}
FeaturePlot(filtered_merged_caudate, features = c("TAF1"))
FeaturePlot(filtered_merged_putamen, features = c("TAF1"))
```

```{r}
feature_caudate_plots = FeaturePlot(filtered_merged_caudate, features = c("SYT1", "AQP4", "C1QA", "FLT1", "OLIG1", "OLIG2", "CD96", "ADGB"))

ggsave(filename = "graphs_to_export/featureplot_caudate.png", plot= feature_caudate_plots)
```


```{r}
Idents(filtered_merged_caudate) = filtered_merged_caudate$RNA_snn_res.0.2
markers = FindAllMarkers(filtered_merged_caudate, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1)
```


```{r}
normalizeScalePcaClusterUmap = function(
   sobj,
   subset_col="donor_id",
   n_hvgs_orig=2500,
   n_dims_use=20,
   resolutions=c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)){
   # this function takes a Seurat object, normalizes the data, scales the data, runs PCA, finds neighbors,
   # clusters at a variety of resolutions, and runs UMAP
   # it then returns the Seurat object
  
   hvgs = getSeuratVarFeatureIntersectByCol(sobj, subset_col=subset_col, original_nfeatures=n_hvgs_orig)
   sobj = (sobj
       %>% NormalizeData()
       %>% ScaleData(features=hvgs, split.by=subset_col)
       %>% RunPCA(features=hvgs, npcs=n_dims_use)
       %>% FindNeighbors(dims = 1:n_dims_use)
   )
   for(res in resolutions){
       sobj = sobj %>% FindClusters(resolution = res)
   }
    sobj = sobj %>% RunUMAP(dims = 1:n_dims_use)
   return(sobj)
}
```


```{r}
printMarkersByCluster = function(marker_df, marker_tsv="Cellbender_seurat/all_markers.tsv", cluster=NULL){
   broad_markers = read.table(marker_tsv, header = TRUE, sep = "\t")
   broad_markers$Gene = toupper(broad_markers$Gene)


   broad_markers['broad_class'] = NA
   broad_markers$broad_class[grepl('microglia', tolower(broad_markers$pattern))] = 'microglia'
   broad_markers$broad_class[grepl('neuron', tolower(broad_markers$pattern))] = 'neuron'
   broad_markers$broad_class[grepl('astrocyte', tolower(broad_markers$pattern))] = 'astrocyte'
   broad_markers$broad_class[grepl('oligodendrocyte', tolower(broad_markers$pattern))] = 'oligo'
   broad_markers$broad_class[grepl('endothelial', tolower(broad_markers$pattern))] = 'endo'
   broad_markers$broad_class[grepl('mural', tolower(broad_markers$pattern))] = 'endo'
   broad_markers$broad_class[grepl('fibro', tolower(broad_markers$pattern))] = 'fibroblast'
   broad_markers$broad_class[grepl('ependymal', tolower(broad_markers$pattern))] = 'ependymal' 
   broad_markers$broad_class[grepl('opc', tolower(broad_markers$pattern))] = 'opc'
   broad_markers$broad_class[grepl('polydendro', tolower(broad_markers$pattern))] = 'opc'
   broad_markers$broad_class[grepl('b_cell', tolower(broad_markers$pattern))] = 'immune'
   broad_markers$broad_class[grepl('t_cell', tolower(broad_markers$pattern))] = 'immune'
   broad_markers$broad_class[grepl('neutro', tolower(broad_markers$pattern))] = 'immune'
   broad_markers$broad_class[grepl('nk_cell', tolower(broad_markers$pattern))] = 'immune'
   broad_markers = broad_markers[!is.na(broad_markers$broad_class), c('Gene', 'broad_class')]


   broad_markers_ordered = broad_markers[order(broad_markers$broad_class),]


   # Merge broad_markers_ordered with markers
   broad_markers_ordered = merge(
       broad_markers_ordered, marker_df, by.x = "Gene", by.y="gene", all.x = TRUE)


   # Order by broad_class and cluster
   broad_markers_ordered = broad_markers_ordered[
       order(broad_markers_ordered$broad_class,
       broad_markers_ordered$Gene, broad_markers_ordered$cluster),]


   if (!is.null(cluster)){
       broad_markers_ordered = broad_markers_ordered[broad_markers_ordered$cluster == cluster,]
       broad_markers_ordered = broad_markers_ordered[complete.cases(broad_markers_ordered),]
   }
   broad_markers_ordered$pct.1 = round(broad_markers_ordered$pct.1, 2)
   broad_markers_ordered$pct.2 = round(broad_markers_ordered$pct.2, 2)
   broad_markers_ordered$avg_log2FC = round(broad_markers_ordered$avg_log2FC, 2)
   print(broad_markers_ordered[,
       c("Gene", "broad_class", "cluster", "avg_log2FC", "pct.1", "pct.2")], row.names=FALSE)
}
```


```{r}
#doublecheck ******
num_clusters = length(unique(Idents(filtered_merged_caudate))) - 1

for (i in 0:num_clusters){
   printMarkersByCluster(markers, cluster=i)
}


```

```{r}
assignCellClasses = function(
   obj,
   classes,
   cluster_col="seurat_clusters",
   class_col="cell_class") {
   obj@meta.data[[class_col]] = NA  # Assign NA to the entire column in meta.data


   for (i in 1:length(classes)) {
       # Find cells that match the current cluster number
       cells = which(as.numeric(obj@meta.data[[cluster_col]]) == i)
     
       # Assign the class label to the cells in the cluster
       obj@meta.data[cells, class_col] = classes[[i]]
   }
  
   # Return the modified object
   return(obj)
}
```

```{r}
#classes = c("Neuron/oligo", "Neuron/oligo", "astrocyte", "unknown", "microglia", "oligo", "astrocyte", "neuron", "neuron", "astrocyte", "opc", "neuron", "oligo", "endo", "microglia/oligo", "ependymal", "neuron", "neuron", "neuron", "immune")

classes = c("oligo", "oligo", "astrocyte", "oligo", "microglia", "oligo", "astrocyte", "neuron", "neuron", "astrocyte", "opc", "neuron", "oligo", "endo", "oligo", "ependymal", "oligo", "neuron", "neuron", "immune")


filtered_merged_caudate = assignCellClasses(filtered_merged_caudate, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

```

```{r}
normalizeScalePcaClusterUmap(filtered_merged_caudate) # what is this
```


```{r}
Idents(filtered_merged_caudate) <- "cell_class"
DimPlot(filtered_merged_caudate, label = TRUE)
```





```{r}
Idents(filtered_merged_putamen) = filtered_merged_putamen$RNA_snn_res.0.2
markers = FindAllMarkers(filtered_merged_putamen, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1)
```

```{r}
#doublecheck ******
num_clusters = length(unique(Idents(filtered_merged_putamen))) - 1

for (i in 0:num_clusters){
   printMarkersByCluster(markers, cluster=i)
}

```

```{r}
#classes = c("oligo?", "neuron", "astrocyte", "neuron", "neuron/oligo", "microglia", "neuron", "oligo", "opc", "oligo", "neuron", "neuron", "astrocyte", "neuron", "neuron", "neuron/oligo", "endo", "neuron", "neuron", "neuron", "oligo", "neuron")

#second one is neuron but looks like it would cluster as an oligo?
classes = c("oligo", "oligo", "astrocyte", "neuron", "oligo", "microglia", "neuron", "oligo", "opc", "oligo", "neuron", "neuron", "astrocyte", "neuron", "neuron", "oligo", "endo", "neuron", "neuron", "neuron", "oligo", "neuron")

filtered_merged_putamen = assignCellClasses(filtered_merged_putamen, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

Idents(filtered_merged_putamen) <- "cell_class"
DimPlot(filtered_merged_putamen, label = TRUE)
```


```{r}
Idents(filtered_merged_caudate) = filtered_merged_caudate$RNA_snn_res.0.5
markers = FindAllMarkers(filtered_merged_caudate, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1.25)
```

```{r}
num_clusters = length(unique(Idents(filtered_merged_caudate))) - 1

for (i in 0:num_clusters){
   printMarkersByCluster(markers, cluster=i)
}
```





```{r}
filtered_merged_caudate = qread("Cellbender_seurat/filtered_merged_caudate_clustered.qs")
filtered_merged_putamen = qread("Cellbender_seurat/filtered_merged_putamen_clustered.qs")

Idents(filtered_merged_putamen) = filtered_merged_putamen$RNA_snn_res.0.5
markers = FindAllMarkers(filtered_merged_putamen, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1.25)
```
```{r}
#doublecheck ******
num_clusters = length(unique(Idents(filtered_merged_putamen))) - 1

for (i in 0:num_clusters){
   printMarkersByCluster(markers, cluster=i)
}

```
```{r}
classes = c("0", "astrocyte", "2", "3", "neuron", "neuron", "microglia", "NO", "9", "opc", "neuron", "neuron", "astrocyte", "14", "neuron", "16", "astrocyte", "neuron", "oligo", "endo", "neuron", "neuron", "23", "neuron", "neuron", "neuron", "oligo", "28", "neuron", "neuron")
  

filtered_merged_putamen = assignCellClasses(filtered_merged_putamen, classes=classes, cluster_col="RNA_snn_res.0.5", class_col = "cell_class")

Idents(filtered_merged_putamen) <- "cell_class"
DimPlot(filtered_merged_putamen, label = TRUE)
```

```{r}
Idents(filtered_merged_putamen) = filtered_merged_putamen$RNA_snn_res.0.3
markers = FindAllMarkers(filtered_merged_putamen, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1.25)
```




```{r}
feature_putamen_plots = FeaturePlot(filtered_merged_putamen, features = c("SYT1", "AQP4", "C1QA", "FLT1", "OLIG1", "OLIG2", "CD96", "ADGB"))

ggsave(filename = "graphs_to_export/featureplot_putamen.png", plot= feature_putamen_plots)
```


```{r}
#data(filtered_merged_caudate)
classes = c("oligo", "oligo", "astrocyte", "oligo", "microglia", "oligo", "astrocyte", "neuron", "neuron", "astrocyte", "opc", "neuron", "oligo", "endo", "oligo", "ependymal", "neuron", "neuron", "neuron", "immune")

filtered_merged_caudate = assignCellClasses(filtered_merged_caudate, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

Idents(filtered_merged_caudate) <- "cell_class"
cd_genes <- c("TAF1")
Dotplot_caudate = DotPlot(object = filtered_merged_caudate, features = cd_genes)
Dotplot_caudate  <- Dotplot_caudate  + theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Display the plot
print(Dotplot_caudate)

#ggsave(filename = "graphs_to_export/dotplot_caudate.png", plot= Dotplot_caudate )
```

```{r}
filtered_merged_caudate= qread("Cellbender_seurat/filtered_merged_putamen_clustered.qs")
filtered_merged_putamen =qread("Cellbender_seurat/filtered_merged_putamen_clustered.qs")
```


```{r}
classes = c("oligo", "oligo", "astrocyte", "neuron", "oligo", "microglia", "neuron", "oligo", "opc", "oligo", "neuron", "neuron", "astrocyte", "neuron", "neuron", "oligo", "endo", "neuron", "neuron", "neuron", "oligo", "neuron")

filtered_merged_putamen = assignCellClasses(filtered_merged_putamen, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

Idents(filtered_merged_putamen) <- "cell_class"
cd_genes <- c("SYT1", "AQP4", "C1QA", "FLT1", "OLIG1", "OLIG2", "CD96", "ADGB")
Dotplot_putamen = DotPlot(object = filtered_merged_putamen, features = cd_genes)
Dotplot_putamen  <- Dotplot_putamen  + theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Display the plot
print(Dotplot_putamen)
```


```{r}
classes = c("oligo", "oligo", "astrocyte", "neuron", "oligo", "microglia", "neuron", "oligo", "opc", "oligo", "neuron", "neuron", "astrocyte", "neuron", "neuron", "oligo", "endo", "neuron", "neuron", "neuron", "oligo", "neuron")

filtered_merged_putamen = assignCellClasses(filtered_merged_putamen, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

Idents(filtered_merged_putamen) <- "cell_class"
cd_genes <- c("TAF1")
Dotplot_putamen = DotPlot(object = filtered_merged_putamen, features = cd_genes)
Dotplot_putamen  <- Dotplot_putamen  + theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Display the plot
print(Dotplot_putamen)

```
```{r}
classes = c("oligo", "oligo", "astrocyte", "oligo", "microglia", "oligo", "astrocyte", "neuron", "neuron", "astrocyte", "opc", "neuron", "oligo", "endo", "oligo", "ependymal", "oligo", "neuron", "neuron", "immune")

filtered_merged_caudate = assignCellClasses(filtered_merged_caudate, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

Idents(filtered_merged_caudate) <- "cell_class"
cd_genes <- c("TAF1")
Dotplot_caudate = DotPlot(object = filtered_merged_caudate, features = cd_genes)
Dotplot_caudate  <- Dotplot_caudate  + theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Display the plot
print(Dotplot_caudate)
```

```{r}

```



```{r}
