---
title: "R Notebook"
output: html_notebook
---

```{r}
  library(ggplot2)
  library(Seurat)
  library(Matrix)
  library(rhdf5)
  library(dplyr)
  library(qs)
  # add any other libraries you need

library_list = list("ca_rxn1", "ca_rxn2", "put_rxn1", "put_rxn2")
RAW_COUNTS_BASENAME = "raw_feature_bc_matrix.h5"
FILTERED_COUNTS_BASENAME = "out_filtered.h5"
MOLECULE_INFO_BASENAME = "molecule_info.h5"
DONOR_ID_BASENAME = "vireo_final_out/donor_ids.tsv"
this_base_path = "/broad/macosko/kimkathl/Cohort3"

raw_dgc_list = list()
filtered_dgc_list = list()
mol_df_list = list()
donor_ids_list = list()
metadata_df_list = list()
seurat_object_list = list()


#helper function for cellbender loading
sum_duplicate_rownames_of_dgc_matrix=function(dgc){   
    # some umi_data has repeated rownames which causes problems down the road
    # we will sum the umi counts in these rows
    # collect rows with duplicate rownames as a dataframe
    n_occur = data.frame(table(rownames(dgc)))
    repeated_rownames = n_occur[n_occur$Freq > 1,]$Var1
    duplicated_dgc = as.data.frame(dgc[rownames(dgc) %in% repeated_rownames,])
    duplicated_dgc['symbol'] = sub("\\.\\d$", "", rownames(duplicated_dgc))

    # sum across numeric columns
    numeric_cols = setdiff(colnames(duplicated_dgc), "symbol")
    summed_duped_umi_rows = duplicated_dgc %>%
        group_by(symbol) %>%
        summarise_at(vars(numeric_cols), sum, na.rm = TRUE) %>%
        ungroup() %>%
        as.data.frame()
    # set rownames to be symbol column, then remove it
    rownames(summed_duped_umi_rows) = summed_duped_umi_rows$symbol
    summed_duped_umi_rows = summed_duped_umi_rows[, !(names(summed_duped_umi_rows) %in% c('symbol'))]

    # Hack
    # each round of the loop will remove ONE of each duplicate row 
    for(i in 1:max(n_occur$Freq)){
        dgc = dgc[!rownames(dgc) %in% repeated_rownames,]
    }

    # finally, replace the deduped rows with the summed rows via an rbind
    dgc = rbind(dgc, as(summed_duped_umi_rows, "sparseMatrix"))

    return(dgc)
}

  # Read your data
for (name in library_list) {
  
cat(name)
cat("\n")

raw_counts_path = file.path(this_base_path, name, RAW_COUNTS_BASENAME)
filtered_counts_path = file.path(this_base_path, name, paste0("pXDPsHS_v3_" , name, "_", FILTERED_COUNTS_BASENAME))
molecule_info_path = file.path(this_base_path, name, MOLECULE_INFO_BASENAME)
donor_id_path = file.path(this_base_path, name, DONOR_ID_BASENAME)

h5ls(filtered_counts_path)

file_path = filtered_counts_path # the path to the *_out_filtered.h5 file
    h5_data = h5read(file_path, "/matrix")
    counts = h5_data$data
    indices = h5_data$indices
    indptr = h5_data$indptr
    barcodes = h5_data$barcodes
    num_genes = length(h5_data$features$name)  # Number of genes
    num_cells = length(barcodes)  # Number of cells

    counts_matrix = sparseMatrix(i=indices + 1,  # +1 for 1-based indexing in R
                                    p=indptr,
                                    x=counts,
                                    dims=c(num_genes, num_cells))
    
 
    rownames(counts_matrix) = h5_data$features$name # set rownames to be genes
    colnames(counts_matrix) = barcodes # set colnames to be cell barcodes
    counts_matrix
    filtered_dgc = counts_matrix
    
       filtered_dgc_list[[name]] = filtered_dgc
       
       

print("READING RAW DGC .H5")
   raw_counts = Read10X_h5(raw_counts_path)
   raw_dgc_list[[name]] = raw_counts

   cd = data.frame(
       row.names=colnames(raw_counts),
       nUMI=colSums(raw_counts),
       log10_nUMI = log10(colSums(raw_counts) + 1),
       nGene=colSums(raw_counts > 0),
       is_in_filtered=colnames(raw_counts) %in% colnames(filtered_dgc_list[[name]])
   )

# load the molecule data such that you can map the barcodes to what came out of CellRanger
   # load umi_type to get whether or not the umi was intronic
   h5fetch = function(x){return(h5read(molecule_info_path, x))}
   mol_df = data.frame(
               barcode=h5fetch("barcodes")[h5fetch("barcode_idx")+1] %>% paste0("-1"),
               feature=h5fetch("features/name")[h5fetch("feature_idx")+1],
               umi=h5fetch("umi"),
               umi_type=h5fetch("umi_type"),
               count=h5fetch("count")
       )
      
   # only consider cells that are in the filtered umi data
   mol_df = mol_df[mol_df$barcode %in% colnames(filtered_dgc),]

mol_df_grouped = mol_df %>% group_by(barcode) %>%
       summarize(
           nUmi=n(),
           nRead=sum(count),
           pct_intronic=sum(umi_type==0)/nUmi)
   rownames(mol_df_grouped) = mol_df_grouped$barcode
   mol_df_list[[name]] = mol_df_grouped

donor_ids = read.table(donor_id_path, header=T)
  donor_ids = donor_ids[, c("cell", "donor_id", "prob_max")]
  donor_ids_list[[name]] = donor_ids

mol_df_rxn = mol_df_list[[name]] 
  metadata = merge(donor_ids, mol_df_rxn, by.x = "cell", by.y = "barcode", all = TRUE)
  rownames(metadata) <- metadata$cell
  
  metadata <- metadata[rownames(metadata) %in% colnames(filtered_dgc), ]
metadata

all(colnames(filtered_dgc) == rownames(metadata))
  metadata <- metadata[match(colnames(filtered_dgc), rownames(metadata)), ]
  all(colnames(filtered_dgc) == rownames(metadata))
  
metadata

metadata <- metadata[!is.na(metadata$donor_id), ]
metadata

file_path = file.path(this_base_path, name, paste0("pXDPsHS_v3_" , name, "_", FILTERED_COUNTS_BASENAME))
    h5_data = h5read(file_path, "/matrix")
    counts = h5_data$data
    indices = h5_data$indices
    indptr = h5_data$indptr
    barcodes = h5_data$barcodes
    num_genes = length(h5_data$features$name)  # Number of genes
    num_cells = length(barcodes)  # Number of cells

    counts_matrix = sparseMatrix(i=indices + 1,  # add 1 for 1-based indexing in R
                                    p=indptr,
                                    x=counts,
                                    dims=c(num_genes, num_cells))
    

    rownames(counts_matrix) = h5_data$features$name # set rownames to be genes
    colnames(counts_matrix) = barcodes # set colnames to be cell barcodes

# now we want to look only at cells that are in BOTh the CellRanger and CellBender objects
    # use filtered_dgc from earlier in the loop
    cellranger_filtered = filtered_dgc[, colnames(filtered_dgc) %in% all_of(colnames(counts_matrix))]
    cellranger_filtered

counts_matrix_filtered = counts_matrix[, colnames(counts_matrix) %in% all_of(colnames(cellranger_filtered))]
    counts_matrix_filtered
    print(dim(counts_matrix_filtered))
   print("1")
    # for whatever reason, there can be duplicated rownames (i.e. genes) in the cellbender output, causing errors later on. Sum these together.
    counts_matrix_filtered = sum_duplicate_rownames_of_dgc_matrix(counts_matrix_filtered) 
    print(dim(counts_matrix_filtered))
   print("2")
    counts_matrix_filtered = counts_matrix_filtered[, match(colnames(cellranger_filtered), colnames(counts_matrix_filtered))]
    print(dim(counts_matrix_filtered))
   print("3")

# create your metadata here....
metadata = metadata[rownames(metadata) %in% colnames(counts_matrix_filtered), ]
metadata

metadata_df_list[[name]] = metadata 
    # add metadata argument to CreateSeuratObject

# Compare the first few entries directly
head(colnames(counts_matrix_filtered))
head(metadata$cell)

counts_matrix_filtered
metadata

extra_barcodes <- setdiff(colnames(counts_matrix_filtered), metadata$cell)
length(extra_barcodes)  # Number of extra barcodes
extra_barcodes  # List of extra barcodes
counts_matrix_filtered <- counts_matrix_filtered[, !(colnames(counts_matrix_filtered) %in% extra_barcodes)]

# Sort both and compare
all(sort(colnames(counts_matrix_filtered)) == sort(metadata$cell))
# Check types
str(colnames(counts_matrix_filtered))
str(metadata$cell)
# Convert both to character if needed
metadata$cell <- as.character(metadata$cell)
colnames(counts_matrix_filtered) <- as.character(colnames(counts_matrix_filtered))
# Check unique values
unique(colnames(counts_matrix_filtered))[1:10]  # First 10 in counts_matrix
unique(metadata$cell)[1:10]  # First 10 in metadata
metadata_ordered <- metadata[match(colnames(counts_matrix_filtered), metadata$cell), ]

cellbender_sobj = CreateSeuratObject(counts_matrix_filtered, meta.data = metadata)

seurat_object_list[[name]] = cellbender_sobj
}
seurat_object_list

```


```{r}
qsave(seurat_object_list, "Cohort3.qs")
```

```{r}
seurat_object_list = qread("Cohort3.qs")
seurat_object_list 
```

```{r}
Cohort_3_CaH_rxn1 = seurat_object_list[["ca_rxn1"]]
Cohort_3_CaH_rxn2 = seurat_object_list[["ca_rxn2"]]
Cohort_3_Put_rxn1 = seurat_object_list[["put_rxn1"]]
Cohort_3_Put_rxn2 = seurat_object_list[["put_rxn2"]]

Cohort_3_CaH_rxn1@meta.data 
Cohort_3_CaH_rxn2@meta.data 
Cohort_3_Put_rxn1@meta.data  
Cohort_3_Put_rxn2@meta.data  
```

```{r}
table(Cohort_3_CaH_rxn1$donor_id)
```


```{r}
Cohort_3_CaH_rxn1 = subset(Cohort_3_CaH_rxn1, subset = donor_id != "doublet" & donor_id != "unassigned")
Cohort_3_CaH_rxn1

Cohort_3_CaH_rxn2 = subset(Cohort_3_CaH_rxn2, subset = donor_id != "doublet" & donor_id != "unassigned")
Cohort_3_CaH_rxn2

Cohort_3_Put_rxn1 = subset(Cohort_3_Put_rxn1, subset = donor_id != "doublet" & donor_id != "unassigned")
Cohort_3_Put_rxn1

Cohort_3_Put_rxn2 = subset(Cohort_3_Put_rxn2, subset = donor_id != "doublet" & donor_id != "unassigned")
Cohort_3_Put_rxn2
```
#calcualte pct mito
```{r}
Cohort_3_CaH_rxn1@meta.data$pct_intronic = Cohort_3_CaH_rxn1$pct_intronic *100
Cohort_3_CaH_rxn2@meta.data$pct_intronic = Cohort_3_CaH_rxn2$pct_intronic *100 
Cohort_3_Put_rxn1@meta.data$pct_intronic = Cohort_3_Put_rxn1$pct_intronic *100  
Cohort_3_Put_rxn2@meta.data$pct_intronic = Cohort_3_Put_rxn2$pct_intronic *100  
```

```{r}
mito_genes <- grep(pattern = "^MT-", x = rownames(Cohort_3_CaH_rxn1), value = TRUE)
length(mito_genes)
mito_counts <- Matrix::colSums(GetAssayData(Cohort_3_CaH_rxn1, assay = "RNA", slot = "counts")[mito_genes, ])
total_counts <- Matrix::colSums(GetAssayData(Cohort_3_CaH_rxn1, assay = "RNA", slot = "counts"))
pct_mito <- (mito_counts / total_counts) * 100
Cohort_3_CaH_rxn1$pct_mito <- pct_mito


mito_genes <- grep(pattern = "^MT-", x = rownames(Cohort_3_CaH_rxn2), value = TRUE)
length(mito_genes)
mito_counts <- Matrix::colSums(GetAssayData(Cohort_3_CaH_rxn2, assay = "RNA", slot = "counts")[mito_genes, ])
total_counts <- Matrix::colSums(GetAssayData(Cohort_3_CaH_rxn2, assay = "RNA", slot = "counts"))
pct_mito <- (mito_counts / total_counts) * 100
Cohort_3_CaH_rxn2$pct_mito <- pct_mito


mito_genes <- grep(pattern = "^MT-", x = rownames(Cohort_3_Put_rxn1), value = TRUE)
length(mito_genes)
mito_counts <- Matrix::colSums(GetAssayData(Cohort_3_Put_rxn1, assay = "RNA", slot = "counts")[mito_genes, ])
total_counts <- Matrix::colSums(GetAssayData(Cohort_3_Put_rxn1, assay = "RNA", slot = "counts"))
pct_mito <- (mito_counts / total_counts) * 100
Cohort_3_Put_rxn1$pct_mito <- pct_mito


mito_genes <- grep(pattern = "^MT-", x = rownames(Cohort_3_Put_rxn2), value = TRUE)
length(mito_genes)
mito_counts <- Matrix::colSums(GetAssayData(Cohort_3_Put_rxn2, assay = "RNA", slot = "counts")[mito_genes, ])
total_counts <- Matrix::colSums(GetAssayData(Cohort_3_Put_rxn2, assay = "RNA", slot = "counts"))
pct_mito <- (mito_counts / total_counts) * 100
Cohort_3_Put_rxn2$pct_mito <- pct_mito

```


#merge caudate libraries 
```{r}
sobj_list = list("CaH_rxn1" = Cohort_3_CaH_rxn1,
                 "CaH_rxn2" =Cohort_3_CaH_rxn2)

for(name in names(sobj_list)){
     sobj =sobj_list[[name]]
     sobj$library = name
     sobj = RenameCells(sobj, new.name = paste(sobj$library, colnames(sobj), sep="__"))
     sobj_list[[name]] = sobj
     
}

sobj_list

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))


merged_counts <- do.call(cbind, counts_list)


metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)
metadata_list

merged_metadata <- do.call(rbind, metadata_list)
merged_metadata
rownames(merged_metadata) <- unlist(lapply(metadata_list, rownames))
merged_metadata

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
CaH_Cohort3 <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
CaH_Cohort3
CaH_Cohort3@meta.data$Region = "Caudate"
CaH_Cohort3@meta.data




sobj_list = list("Put_rxn1" = Cohort_3_Put_rxn1,
                 "Put_rxn2" = Cohort_3_Put_rxn2)

for(name in names(sobj_list)){
     sobj =sobj_list[[name]]
     sobj$library = name
     sobj = RenameCells(sobj, new.name = paste(sobj$library, colnames(sobj), sep="__"))
     sobj_list[[name]] = sobj
     
}

sobj_list

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))


merged_counts <- do.call(cbind, counts_list)


metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)
metadata_list

merged_metadata <- do.call(rbind, metadata_list)
merged_metadata
rownames(merged_metadata) <- unlist(lapply(metadata_list, rownames))
merged_metadata

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
Put_Cohort3 <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
Put_Cohort3
Put_Cohort3@meta.data$Region = "Putamen"
Put_Cohort3@meta.data
```

```{r}
CaH_Cohort3@meta.data$Sex <- ifelse(grepl("CF$", CaH_Cohort3@meta.data$donor_id), "F", "M")
table(CaH_Cohort3@meta.data$Sex, CaH_Cohort3$donor_id)

CaH_Cohort3@meta.data$Condition <- ifelse(grepl("CF$|CM$|CM2$|CM6$", CaH_Cohort3@meta.data$donor_id), "Control", "XDP")

table(CaH_Cohort3@meta.data$Condition, CaH_Cohort3$donor_id)


Put_Cohort3@meta.data$Sex <- ifelse(grepl("CF$", Put_Cohort3@meta.data$donor_id), "F", "M")
table(Put_Cohort3@meta.data$Sex, Put_Cohort3$donor_id)

Put_Cohort3@meta.data$Condition <- ifelse(grepl("CF$|CM$|CM2$|CM6$", Put_Cohort3@meta.data$donor_id), "Control", "XDP")

table(Put_Cohort3@meta.data$Condition, Put_Cohort3$donor_id)
```

```{r}
CaH_Cohort3
filtered_CaH_Cohort3 <- subset(CaH_Cohort3, subset = pct_mito < 10)
filtered_CaH_Cohort3
filtered_CaH_Cohort3 = subset(filtered_CaH_Cohort3, subset = pct_intronic >= 0.25)
filtered_CaH_Cohort3
filtered_CaH_Cohort3 = subset(filtered_CaH_Cohort3, subset = nUmi > 500)
filtered_CaH_Cohort3


Put_Cohort3
filtered_Put_Cohort3 <- subset(Put_Cohort3, subset = pct_mito < 10)
filtered_Put_Cohort3
filtered_Put_Cohort3 = subset(filtered_Put_Cohort3, subset = pct_intronic >= 0.25)
filtered_Put_Cohort3
filtered_Put_Cohort3 = subset(filtered_Put_Cohort3, subset = nUmi > 500)
filtered_Put_Cohort3
```

```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(filtered_CaH_Cohort3, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
filtered_CaH_Cohort3 = (filtered_CaH_Cohort3
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_Cohort3$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_Cohort3$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(filtered_CaH_Cohort3, group.by = "donor_id") 
DimPlot(filtered_CaH_Cohort3, group.by = "Sex")
DimPlot(filtered_CaH_Cohort3, group.by = "Condition")
DimPlot(filtered_CaH_Cohort3, group.by = "library") 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(filtered_CaH_Cohort3, group.by = "RNA_snn_res.0.8", label=T)

FeaturePlot(filtered_CaH_Cohort3, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("OLIG1", "MOG", "MOBP"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(filtered_CaH_Cohort3, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
```


```{r}
Idents(filtered_CaH_Cohort3) = filtered_CaH_Cohort3$RNA_snn_res.0.3

classes = c("oligo", "oligo", "oligo", "oligo", "oligo", "astrocyte", "astrocyte", "microglia", "neuron", "neuron", "oligo", "opc", "neuron", "neuron", "astrocyte", "neuron", "neuron", "neuron", "endothelial", "ependymal", "neuron", "neuron", "oligo", "neuron", "immune")

filtered_CaH_Cohort3= assignCellClasses(filtered_CaH_Cohort3, classes=classes, cluster_col="RNA_snn_res.0.3", class_col = "cell_class")

DimPlot(filtered_CaH_Cohort3, group.by = "cell_class" ,label = T, raster = FALSE)
```

```{r}
 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN", "GAPDH","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = filtered_CaH_Cohort3, features = marker_genes, group.by = "cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```


```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(filtered_Put_Cohort3, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
filtered_Put_Cohort3 = (filtered_Put_Cohort3
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_Cohort3$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_Cohort3$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(filtered_Put_Cohort3, group.by = "donor_id") 
DimPlot(filtered_Put_Cohort3, group.by = "Sex")
DimPlot(filtered_Put_Cohort3, group.by = "Condition")
DimPlot(filtered_Put_Cohort3, group.by = "library") 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(filtered_Put_Cohort3, group.by = "RNA_snn_res.0.8", label=T)

FeaturePlot(filtered_Put_Cohort3, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("OLIG1", "MOG", "MOBP"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(filtered_Put_Cohort3, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
```



```{r}
Idents(filtered_Put_Cohort3) = filtered_Put_Cohort3$RNA_snn_res.0.2

classes = c("oligo", "oligo", "oligo", "astrocyte", "neuron", "neuron", "oligo", "microglia", "neuron", "neuron", "oligo", "neuron", "opc", "oligo", "oligo", "oligo", "astrocyte", "astrocyte", "astrocyte", "endothelial", "oligo", "neuron", "neuron", "opc", "neuron", "immune")

filtered_Put_Cohort3= assignCellClasses(filtered_Put_Cohort3, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "cell_class")

DimPlot(filtered_Put_Cohort3, group.by = "cell_class" ,label = T, raster = FALSE)

 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN", "GAPDH","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = filtered_Put_Cohort3, features = marker_genes, group.by = "cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
qsave(CaH_Cohort3, "Cohort3/sobjs/CaH_Cohort3_unfiltered.qs")
qsave(Put_Cohort3, "Cohort3/sobjs/Put_Cohort3_unfiltered.qs")

qsave(filtered_CaH_Cohort3, "Cohort3/sobjs/filtered_CaH_Cohort3.qs")
qsave(filtered_Put_Cohort3, "Cohort3/sobjs/filtered_Put_Cohort3.qs")
```


#Caudate cleaning + integration

```{r}
table(filtered_CaH_Cohort3$cell_class)
```

```{r}
temp_sobj = subset(filtered_CaH_Cohort3, subset = cell_class == "neuron")

# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(temp_sobj, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
temp_sobj = (temp_sobj
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(temp_sobj, group.by = "donor_id") 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.8", label=T) 

FeaturePlot(temp_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(temp_sobj, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(temp_sobj, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(temp_sobj, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(temp_sobj, features = c("OLIG1", "MOG", "MOBP", "MBP"), raster = F)
FeaturePlot(temp_sobj, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(temp_sobj, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(temp_sobj, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(temp_sobj, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 

```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
table(temp_sobj$RNA_snn_res.0.2)
```


```{r}
temp_sobj
temp_sobj = subset(temp_sobj, subset = RNA_snn_res.0.2 != "2" & RNA_snn_res.0.2 != "3")
temp_sobj
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.2")
```


```{r}
CaH_astro
CaH_endo
CaH_ependymal
CaH_immune
CaH_micro
CaH_oligo
CaH_opc
CaH_neuron= temp_sobj
#
```



```{r}
FeaturePlot(temp_sobj, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(temp_sobj, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(temp_sobj, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("P2RY12", "CX3CR1", "C1QB", "BCAS1"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SEMA5B", "KREMEN1", "PDE1C"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("TAC1", "NNAT", "OPRM1", "ID4"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SGK1", "EPHA4", "SV2B", "CHAT"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SST", "CALB1", "PVALB", "LAMP5"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("pct_mito"),raster=FALSE) 

```



```{r}
Idents(temp_sobj) = temp_sobj$RNA_snn_res.0.4

classes =c("D1_matrix", "D2_matrix", "D1_patch", "eSPN", "doublet", "non_SPN", "D2_patch", "non_SPN", "unsure", "non_SPN", 
  "D2_matrix", "non_SPN", "doublet", "non_SPN", "D2_eSPN", "cholinergic", "doublet", "doublet")

temp_sobj= assignCellClasses(temp_sobj, classes=classes, cluster_col="RNA_snn_res.0.4", class_col = "neuron_cell_class")

DimPlot(temp_sobj, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)

marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN", "CHAT")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.4")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
temp_sobj
temp_sobj = subset(temp_sobj, subset = neuron_cell_class != "doublet")
temp_sobj
DimPlot(temp_sobj, group.by = "neuron_cell_class")
```


```{r}
CaH_astro@meta.data$neuron_cell_class = CaH_astro$cell_class
CaH_endo@meta.data$neuron_cell_class = CaH_endo$cell_class
CaH_ependymal@meta.data$neuron_cell_class = CaH_ependymal$cell_class
CaH_immune@meta.data$neuron_cell_class = CaH_immune$cell_class
CaH_micro@meta.data$neuron_cell_class = CaH_micro$cell_class

CaH_neuron

CaH_oligo@meta.data$neuron_cell_class = CaH_oligo$cell_class
CaH_opc@meta.data$neuron_cell_class = CaH_opc$cell_class
```

```{r}
sobj_list = list(CaH_astro,
CaH_endo,
CaH_ependymal,
CaH_immune,
CaH_micro,
CaH_oligo,
CaH_opc,
CaH_neuron)

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))

merged_counts <- do.call(cbind, counts_list)

metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)

merged_metadata <- do.call(rbind, metadata_list)
merged_metadata

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
cleaned_CaH_Cohort3 <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
cleaned_CaH_Cohort3
```

```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(cleaned_CaH_Cohort3, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
cleaned_CaH_Cohort3 = (cleaned_CaH_Cohort3
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(cleaned_CaH_Cohort3, group.by = "donor_id") 
DimPlot(cleaned_CaH_Cohort3, group.by = "library") 
DimPlot(cleaned_CaH_Cohort3, group.by = "Condition") 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(cleaned_CaH_Cohort3, group.by = "RNA_snn_res.0.8", label=T)
DimPlot(cleaned_CaH_Cohort3, group.by = "cell_class", label=T)
DimPlot(cleaned_CaH_Cohort3, group.by = "neuron_cell_class", label=T)
```

```{r}
table(cleaned_CaH_Cohort3$donor_id)
unique(cohort_metadata$Donor)
```


```{r}
cleaned_CaH_Cohort3@meta.data
cohort_metadata = read.csv("/broad/macosko/kimkathl/XDP_Cohorts_1_2_3_metadata.csv", header = T)
cohort_metadata

cleaned_CaH_Cohort3@meta.data = merge(cleaned_CaH_Cohort3@meta.data, cohort_metadata, by.x = "donor_id", by.y = "Donor")
cleaned_CaH_Cohort3@meta.data

cleaned_CaH_Cohort3@meta.data$Sex = cleaned_CaH_Cohort3@meta.data$Sex.x
cleaned_CaH_Cohort3@meta.data$Sex.x = NULL
cleaned_CaH_Cohort3@meta.data$Sex.y = NULL

cleaned_CaH_Cohort3@meta.data$Condition = cleaned_CaH_Cohort3@meta.data$Condition.x
cleaned_CaH_Cohort3@meta.data$Condition.x = NULL
cleaned_CaH_Cohort3@meta.data$Condition.y = NULL
cleaned_CaH_Cohort3
```


```{r}
library(lme4)
sobj = cleaned_CaH_Cohort3
model_cols = c("donor_id", "neuron_cell_class", "Condition", "Sex", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj@meta.data[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$neuron_cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects="donor_id", # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Age_of_Death", "Sex") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("XDP vs. Control: Caudate Cohort 3") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )
```

```{r}
qsave(cleaned_CaH_Cohort3, "Cohort3/sobjs/cleaned_CaH_Cohort3.qs")
```


#Putamen cleaning + integration

```{r}
table(filtered_Put_Cohort3$cell_class)
```


```{r}
temp_sobj = subset(filtered_Put_Cohort3, subset = cell_class == "neuron")

# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(temp_sobj, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
temp_sobj = (temp_sobj
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(temp_sobj, group.by = "donor_id") 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.8", label=T) 

FeaturePlot(temp_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(temp_sobj, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(temp_sobj, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(temp_sobj, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(temp_sobj, features = c("OLIG1", "MOG", "MOBP", "MBP"), raster = F)
FeaturePlot(temp_sobj, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(temp_sobj, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(temp_sobj, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(temp_sobj, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 

```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
table(temp_sobj$RNA_snn_res.0.2)
```


```{r}
temp_sobj
temp_sobj = subset(temp_sobj, subset = RNA_snn_res.0.2 != "2" &RNA_snn_res.0.2 != "3" )
temp_sobj
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.2")
```

```{r}
Put_astro
Put_endo
Put_immune 
Put_micro
Put_opc 
Put_oligo
Put_neuron= temp_sobj
#

```



```{r}
FeaturePlot(temp_sobj, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(temp_sobj, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(temp_sobj, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("P2RY12", "CX3CR1", "C1QB", "BCAS1"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SEMA5B", "KREMEN1", "PDE1C"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("TAC1", "NNAT", "OPRM1", "ID4"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SGK1", "EPHA4", "SV2B", "CHAT"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SST", "CALB1", "PVALB", "LAMP5"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("pct_mito"),raster=FALSE) 

```

```{r}
Idents(temp_sobj) = temp_sobj$RNA_snn_res.0.4

classes = c("D2_matrix", "D1_matrix", "doublet", "eSPN", "D1_patch", "D2_patch", "non_SPN", "D2_unsure", "non_SPN", "non_SPN", 
  "doublet", "D2_eSPN", "non_SPN", "D1_D2", "cholinergic", "doublet")


temp_sobj= assignCellClasses(temp_sobj, classes=classes, cluster_col="RNA_snn_res.0.4", class_col = "neuron_cell_class")

DimPlot(temp_sobj, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "CHAT")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.4")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)

marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
temp_sobj
temp_sobj = subset(temp_sobj, subset = neuron_cell_class != "doublet")
temp_sobj
DimPlot(temp_sobj, group.by = "neuron_cell_class")
```


```{r}
Put_astro@meta.data$neuron_cell_class = Put_astro$cell_class
Put_endo@meta.data$neuron_cell_class = Put_endo$cell_class
Put_micro@meta.data$neuron_cell_class = Put_micro$cell_class
Put_immune@meta.data$neuron_cell_class = Put_immune$cell_class

Put_neuron

Put_oligo@meta.data$neuron_cell_class = Put_oligo$cell_class
Put_opc@meta.data$neuron_cell_class = Put_opc$cell_class
```

```{r}
sobj_list = list(Put_astro,
Put_endo,
Put_immune,
Put_micro,
Put_oligo,
Put_opc,
Put_neuron)

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))

merged_counts <- do.call(cbind, counts_list)

metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)

merged_metadata <- do.call(rbind, metadata_list)
merged_metadata

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
cleaned_Put_Cohort3 <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
cleaned_Put_Cohort3

# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(cleaned_Put_Cohort3, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
cleaned_Put_Cohort3 = (cleaned_Put_Cohort3
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(cleaned_Put_Cohort3, group.by = "donor_id") 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(cleaned_Put_Cohort3, group.by = "RNA_snn_res.0.8", label=T)
DimPlot(cleaned_Put_Cohort3, group.by = "cell_class", label=T)
DimPlot(cleaned_Put_Cohort3, group.by = "neuron_cell_class", label=T)
DimPlot(cleaned_Put_Cohort3, group.by = "library", label=T)
DimPlot(cleaned_Put_Cohort3, group.by = "Condition", label=T)
```


```{r}
cleaned_Put_Cohort3@meta.data = merge(cleaned_Put_Cohort3@meta.data, cohort_metadata, by.x = "donor_id", by.y = "Donor")
cleaned_Put_Cohort3@meta.data

cleaned_Put_Cohort3@meta.data$Sex = cleaned_Put_Cohort3@meta.data$Sex.x
cleaned_Put_Cohort3@meta.data$Sex.x = NULL
cleaned_Put_Cohort3@meta.data$Sex.y = NULL

cleaned_Put_Cohort3@meta.data$Condition = cleaned_Put_Cohort3@meta.data$Condition.x
cleaned_Put_Cohort3@meta.data$Condition.x = NULL
cleaned_Put_Cohort3@meta.data$Condition.y = NULL
cleaned_Put_Cohort3@meta.data
```


```{r}
library(lme4)
sobj = cleaned_Put_Cohort3
model_cols = c("donor_id", "neuron_cell_class", "Condition", "Sex", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj@meta.data[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$neuron_cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects="donor_id", # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Age_of_Death", "Sex") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("XDP vs. Control: Putamen Cohort 3") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )
```


```{r}
qsave(cleaned_Put_Cohort3, "Cohort3/sobjs/cleaned_Put_Cohort3.qs")
```


```{r}
sobj_list = list(cleaned_CaH_Cohort3,
cleaned_Put_Cohort3)

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))

merged_counts <- do.call(cbind, counts_list)

metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)

merged_metadata <- do.call(rbind, metadata_list)
rownames(merged_metadata) = paste0(merged_metadata$library, "__", merged_metadata$cell)
# Ensure that the row names of metadata match the colnames of merged counts
merged_metadata <- merged_metadata[match(colnames(merged_counts), rownames(merged_metadata)), ]
# Reorder merged_counts to match the cell names in the merged metadata
merged_counts <- merged_counts[, match(rownames(merged_metadata), colnames(merged_counts))]
# Check if the order of rownames and colnames match
all(rownames(merged_metadata) == colnames(merged_counts))  # Should return TRUE

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
cleaned_CaH_Put_Cohort3 <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
cleaned_CaH_Put_Cohort3@meta.data

# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(cleaned_CaH_Put_Cohort3, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
cleaned_CaH_Put_Cohort3 = (cleaned_CaH_Put_Cohort3
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(cleaned_CaH_Put_Cohort3, group.by = "donor_id") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "library") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "Condition") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "Region") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.8", label=T)
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "cell_class", label=T)
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "neuron_cell_class", label=T)
```


```{r}
library(harmony)
cleaned_CaH_Put_Cohort3 = (cleaned_CaH_Put_Cohort3
    %>% RunHarmony(
        group.by = "donor_id")
    %>% FindNeighbors(reduction='harmony', dims=1:20)
    %>% FindClusters(res=0.05)
    %>% FindClusters(res=0.1)
    %>% FindClusters(res=0.2)
    %>% FindClusters(res=0.3)
    %>% FindClusters(res=0.4)
    %>% FindClusters(res=0.5)
    %>% FindClusters(res=0.6)
    %>% FindClusters(res=0.7)
    %>% FindClusters(res=0.8)    
    %>% RunUMAP(reduction="harmony", dims=1:20)
)
cleaned_CaH_Put_Cohort3
cleaned_CaH_Put_Cohort3@meta.data
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "donor_id") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "library") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "Condition") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "Region") 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.05", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.1", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "RNA_snn_res.0.8", label=T)
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "cell_class", label=T)
DimPlot(cleaned_CaH_Put_Cohort3, group.by = "neuron_cell_class", label=T)

FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("OLIG1", "MOG", "MOBP", "MBP"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(cleaned_CaH_Put_Cohort3, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 

```


```{r}
Idents(cleaned_CaH_Put_Cohort3) = cleaned_CaH_Put_Cohort3$RNA_snn_res.0.1

classes = c("oligo", "astrocyte", "neuron", "neuron", "microglia", "oligo", "opc", "neuron", "neuron", "neuron", 
  "endothelial", "ependymal", "neuron", "neuron", "immune")


cleaned_CaH_Put_Cohort3= assignCellClasses(cleaned_CaH_Put_Cohort3, classes=classes, cluster_col="RNA_snn_res.0.1", class_col = "final_cell_class_merged")

DimPlot(cleaned_CaH_Put_Cohort3, group.by = "final_cell_class_merged" ,label = T, raster = FALSE)

```

```{r}
qsave(cleaned_CaH_Put_Cohort3, "Cohort3/sobjs/final_CaH_Put_Cohort3.qs")
```


#MASC Combo
```{r}
library(lme4)
sobj = cleaned_CaH_Put_Cohort3
sobj
model_cols = c("donor_id", "final_cell_class_merged", "Condition", "Sex", "Age_of_Death", "Region") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj@meta.data[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$final_cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects="donor_id", # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Age_of_Death", "Sex", "Region") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("Combined Cohort 3 CaH + Put") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )
```



```{r}
options(future.globals.maxSize = 400 * 1024^3)  
library(sctransform)
cleaned_CaH_Put_Cohort3 = SCTransform(cleaned_CaH_Put_Cohort3, vars.to.regress = "pct_mito", verbose = FALSE)
DefaultAssay(cleaned_CaH_Put_Cohort3) = "SCT"
cleaned_CaH_Put_Cohort3

library(UCell)

NFKB_genes =  c("MARCKS", "IL23A", "NINJ1", "TNFSF9", "SIK1", "ATF3", "SERPINE1", "MYC", "HES1", "CCNL1", "CCN1", "EGR1", "EGR2", "JAG1", "EGR3", "ABCA1", "GADD45B", "GADD45A", "PLK2", "KLF10", 
           "EIF1", "EHD1", "FOSL2", "FOSL1", "GPR183", "PLPP3", "IFIT2", "ICAM1", "ZC3H12A", "IER2", 
           "IL12B", "JUNB", "IER5", "IER3", "STAT5A", "DUSP5", "EDN1", "JUN", "DUSP4", "DUSP1", 
           "DUSP2", "TSC22D1", "CCL20", "SPHK1", "LIF", "IL18", "TUBB2A", "RHOB", "VEGFA", "PTPRE", 
           "IL1A", "TLR2", "IL1B", "BHLHE40", "ID2", "CLCF1", "REL", "FJX1", "SGK1", "BTG3", "BTG2", 
           "BTG1", "SDC4", "LITAF", "AREG", "SOCS3", "PANX1", "RIPK2", "NFIL3", "SERPINB2", "GCH1", 
           "IFNGR2", "G0S2", "FOS", "SERPINB8", "F3", "SPSB1", "FOSB", "PER1", "F2RL1", "HBEGF", 
           "CD44", "TRIP10", "CDKN1A", "PTGER4", "PTGS2", "IFIH1", "NAMPT", "OLR1", "ICOSLG", 
           "PHLDA1", "ZBTB10", "TAP1", "PNRC1", "CXCL10", "CXCL11", "IL6ST", "CD69", "SQSTM1", 
           "RELA", "CSF2", "CD83", "CSF1", "PPP1R15A", "CD80", "TNC", "TNF", "TANK", "RELB", "ZFP36", 
           "CCND1", "RNF19B", "CCRL2", "DENND5A", "PHLDA2", "MAP3K8", "LDLR", "SLC16A6", "SMAD3", 
           "TGIF1", "MAP2K3", "DDX58", "TRAF1", "INHBA", "NFKB1", "NFKB2", "GEM", "NR4A3", "MAFF", 
           "RCAN1", "NR4A2", "EFNA1", "MXD1", "BIRC2", "YRDC", "BIRC3", "IL7R", "PFKFB3", "IRS2", 
           "SLC2A3", "PLAU", "SLC2A6", "SAT1", "ETS2", "NR4A1", "SNN", "PMEPA1", "TNFRSF9", "MSC", 
           "TIPARP", "LAMB3", "GFPT2", "CFLAR", "TNIP1", "IRF1", "NFKBIA", "BMP2", "IL6", "TNIP2", 
           "BCL6", "BCL3", "NFKBIE", "NFE2L2", "B4GALT1", "NFAT5", "TNFAIP8", "BCL2A1", "TNFAIP6", 
           "TNFAIP3", "CXCL2", "CXCL1", "TNFAIP2", "CXCL3", "CXCL6", "FUT4", "DRAM1", "DNAJB4", 
           "PDE4B", "PDLIM5", "MCL1", "KDM6B", "IL15RA", "PLAUR", "ATP2B1", "KLF4", "KLF2", "SOD2", 
           "KLF9", "KLF6", "ACKR3", "PTX3", "B4GALT5", "TRIB1", "CEBPB", "CEBPD", "PLEK", "KYNU", 
           "CCL5", "CCL4", "CCL2")

interferon_alpha = c("IL4R", "CD74", "SP110", "MX1", "RSAD2", "TAP1", "PSMB9", "CXCL10", "CXCL11", "IFI44L", "LAP3", "LPAR6", "IFI27", "TRAFD1", "TRIM14", "LY6E", "IFITM2", "IFITM3", "SAMD9", "CSF1", 
           "IFITM1", "UBE2L6", "SAMD9L", "RNF31", "HERC6", "LAMP3", "CCRL2", "MVB12A", "B2M", "CMTR1", 
           "GBP2", "GBP4", "EPSTI1", "BATF2", "HLA-C", "TENT5A", "TDRD7", "ISG15", "IFI44", "PARP14", 
           "MOV10", "ISG20", "PARP12", "PLSCR1", "PROCR", "SELL", "PSME2", "PSME1", "CNP", "LGALS3BP", 
           "IFI35", "IFIT2", "IFI30", "DDX60", "IFIT3", "NUB1", "HELZ2", "PNPT1", "IL15", "NCOA7", 
           "EIF2AK2", "NMI", "OAS1", "BST2", "IRF1", "ELF1", "IL7", "IRF2", "IRF9", "IRF7", "UBA7", 
           "GMPR", "ADAR", "CASP8", "TRIM5", "RIPK2", "CASP1", "STAT2", "WARS1", "PARP9", "PSMA3", 
           "TXNIP", "CMPK2", "CD47", "RTP4", "C1S", "OGFR", "TMEM140", "USP18", "OASL", "SLC25A28", 
           "IFIH1", "PSMB8", "DHX58", "TRIM25", "TRIM26", "TRIM21")

antigen_processing_genes = c("CTSB", "CD74", "HSP90AA1", "KLRC3", "HSPA6", "HSPA5", "HSPA1L", "KLRC4", "HSPA8", "HSPA2", "TAP2", "HSPA4", "TAP1", "TAPBP", "CD4", "RFX5", "IFNG", "HSPA1A", "HLA-DRA", "HLA-DQB1", "KLRD1", "CALR", "HSPA1B", "TNF", "KIR2DL1", "KIR2DL2", "KIR2DL3", "KIR2DL4", "CTSS", "CTSL", "B2M", "HLA-DOB", "KIR2DL5A", "CIITA", "HLA-DQA2", "HLA-DOA", "HLA-DQA1", "PDIA3", "HLA-DRB5", 
"KIR2DS1", "NFYB", "KIR2DS2", "NFYC", "KIR2DS3", "KIR2DS4", "KIR2DS5", "HLA-C", "RFXANK", 
"KIR3DL1", "CD8B2", "KIR3DL2", "HLA-A", "HLA-B", "KIR3DL3", "HLA-G", "HLA-E", "HLA-F", "CREB1", "CD8B", "RFXAP", "CD8A", "CANX", "LGMN", "PSME2", "PSME3", "HLA-DPB1", "PSME1", "HLA-DRB4", 
"HLA-DRB3", "HLA-DRB1", "HSP90AB1", "IFI30", "HLA-DMB", "HLA-DPA1", "KLRC1", "KLRC2", "NFYA","HLA-DMA")

cleaned_CaH_Put_Cohort3 <- AddModuleScore_UCell(cleaned_CaH_Put_Cohort3,
  features = list(Score = NFKB_genes ),
  name = 'NFKB'
)

cleaned_CaH_Put_Cohort3 <- AddModuleScore_UCell(cleaned_CaH_Put_Cohort3,
  features = list(Score = interferon_alpha),
  name = 'interferon_alpha'
)

C_minus = qread("temp_disco/more_temp_1205/final_c_minus_genes.qs")
C_plus = qread("temp_disco/more_temp_1205/final_c_plus_genes.qs")

cleaned_CaH_Put_Cohort3 <- AddModuleScore_UCell(cleaned_CaH_Put_Cohort3,features = list(C_minus = C_minus), name = '_scores')
cleaned_CaH_Put_Cohort3 <- AddModuleScore_UCell(cleaned_CaH_Put_Cohort3,features = list(C_plus = C_plus), name = '_scores')

cleaned_CaH_Put_Cohort3 <- AddModuleScore_UCell(cleaned_CaH_Put_Cohort3,features = list(antigen_processing = antigen_processing_genes), name = '_scores')

qsave(cleaned_CaH_Put_Cohort3, "cleaned_CaH_Put_Cohort3_sct_ucell.qs")
```



#QC

```{r}
#histogram for pct_intronic
median_pct_intronic = median(CaH_Cohort3$pct_intronic)
title = paste0("CaH_Cohort3: pct intronic, " , "Median: ", sprintf("%0.3f", median_pct_intronic), "%")
pct_intronic_hist = hist(sobj$pct_intronic, main = title, xlab = "pct intronic", col="grey", breaks = 100)

median_pct_intronic = median(filtered_CaH_Cohort3$pct_intronic)
title = paste0("filtered_CaH_Cohort3: pct intronic, " , "Median: ", sprintf("%0.3f", median_pct_intronic), "%")
pct_intronic_hist = hist(sobj$pct_intronic, main = title, xlab = "pct intronic", col="grey", breaks = 100)

#histogram for nUMI --> take log10 of nUMI tonormalize
log_nUMI = log10(CaH_Cohort3$nUmi)
median_log_nUMI = median(log_nUMI)
title = paste0("CaH_Cohort3: log10(nUMI), ", "Median: ", sprintf("%0.3f", median_log_nUMI))
log_nUMI_hist = hist(log_nUMI, main= title, xlab = "log10(nUMI)", col="grey", breaks = 100)

saturation <- CaH_Cohort3$nRead/CaH_Cohort3$nUmi
median_umi_per_read = median(saturation)
title = paste0("CaH_Cohort3: nReads/nUMI, " , "Median: ", sprintf("%0.3f", median_umi_per_read))  
saturation_hist = hist(saturation, main= title, xlab = "nRead/nUMI", col="grey", breaks = 100)

saturation <- filtered_CaH_Cohort3$nRead/filtered_CaH_Cohort3$nUmi
median_umi_per_read = median(saturation)
title = paste0("filtered_CaH_Cohort3: nReads/nUMI, " , "Median: ", sprintf("%0.3f", median_umi_per_read))  
saturation_hist = hist(saturation, main= title, xlab = "nRead/nUMI", col="grey", breaks = 100)

median_pct_mito = median(CaH_Cohort3$pct_mito)
title = paste0("CaH_Cohort3: pct mito, " , "Median: ", sprintf("%0.3f", median_pct_mito), "%")
pct_intronic_hist = hist(sobj$pct_mito, main = title, xlab = "pct mito", col="grey", breaks = 100)

median_pct_mito = median(filtered_CaH_Cohort3$pct_mito)
title = paste0("filtered_CaH_Cohort3: pct mito, " , "Median: ", sprintf("%0.3f", median_pct_mito), "%")
pct_intronic_hist = hist(sobj$pct_mito, main = title, xlab = "pct mito", col="grey", breaks = 100)
```



#QC by library and donor
```{r}
#histogram for pct_intronic
summary_data <- filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(
    median_pct_intronic = median(pct_intronic, na.rm = TRUE), 
    log_nUMI = median(log10(nUmi), na.rm = TRUE),  # Compute log inside summarize
    saturation = median(nRead / nUmi, na.rm = TRUE),  # Ensure division inside summarize
    median_pct_mito = median(pct_mito, na.rm = TRUE)
  )

summary_data


ggplot(filtered_CaH_Cohort3@meta.data, aes(x = filtered_CaH_Cohort3$pct_intronic)) + facet_wrap(~ donor_id) + geom_histogram(bins = 100) 
```

```{r}
cah_meta = filtered_CaH_Cohort3@meta.data
put_meta = filtered_Put_Cohort3@meta.data 
```


```{r}
medians <- cah_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))

x_order = c(
  "SCF_22-046CF", "SCF_22-050CM6","SCF_22-056CF", "SCF_22-057CM", "SCF_23-081CM",
  "SCF-19-020", "SCF-22-042", "SCF-22-044",
  "SCF-22-045", "SCF_20-026", 
  "SCF_22-048",  "SCF_22-052",
  "SCF_22-060", "SCF_23-080", "SCF_23-083"
)


# Convert donor_id to a factor with a specified order in BOTH datasets
cah_meta$donor_id <- factor(cah_meta$donor_id, levels = x_order)
medians$donor_id <- factor(medians$donor_id, levels = x_order)

# Plot histogram with facet per donor and median as text
ggplot(cah_meta, aes(x = pct_intronic, fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_pct_intronic, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Caudate pct intronic by donor") +ylab("Donor")



# Compute median for each donor
medians <- put_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))

# Plot histogram with facet per donor and median as text
ggplot(put_meta, aes(x = pct_intronic, fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_pct_intronic, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Putamen pct intronic by donor") +ylab("Donor")


medians <- cah_meta %>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_log_nUMI = median(log10(nUmi), na.rm = TRUE))
# Plot histogram with facet per donor and median as text
ggplot(cah_meta, aes(x = log10(nUmi), fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_log_nUMI, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Caudate log(UMI) by donor") +ylab("Donor")



# Compute median for each donor
medians <- put_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_log_nUMI = median(log10(nUmi), na.rm = TRUE))

# Plot histogram with facet per donor and median as text
ggplot(put_meta, aes(x = log10(nUmi), fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_log_nUMI, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Putamen log(UMI) by donor") +ylab("Donor")


cah_meta$saturation <- cah_meta$nRead/cah_meta$nUmi
put_meta$saturation <- put_meta$nRead/put_meta$nUmi

medians <- cah_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_saturation = median(saturation, na.rm = TRUE))

# Plot histogram with facet per donor and median as text
ggplot(cah_meta, aes(x = saturation, fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_saturation, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Caudate saturation by donor") +ylab("Donor")



# Compute median for each donor
medians <- put_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_saturation = median(saturation, na.rm = TRUE))

# Plot histogram with facet per donor and median as text

ggplot(put_meta, aes(x = saturation, fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_saturation, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Putamen saturation by donor") +ylab("Donor")


medians <- cah_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))


# Plot histogram with facet per donor and median as text
ggplot(cah_meta, aes(x = pct_mito, fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_pct_mito, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Caudate pct mito by donor") +ylab("Donor")



# Compute median for each donor
medians <- put_meta%>%
  group_by(donor_id, Condition) %>%  # Include case/control in grouping
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))


# Plot histogram with facet per donor and median as text
ggplot(put_meta, aes(x = pct_mito, fill = Condition)) + 
  facet_wrap(~ donor_id) + 
  geom_histogram(bins = 100, alpha = 0.6) +
  scale_fill_manual(values = c("Control" = "blue", "XDP" = "red")) +  # Define colors
  geom_text(data = medians, aes(x = Inf, y = Inf, 
                                label = paste0("Median: ", round(median_pct_mito, 2))), 
            hjust = 1.1, vjust = 1.1, inherit.aes = FALSE, size = 4, color = "black") +
  theme_minimal() +
  labs(fill = "Condition") + ggtitle("Putamen pct mito by donor") +ylab("Donor")

```


```{r}
#histogram for pct_intronic
median_pct_intronic = median(Put_Cohort3$pct_intronic)
title = paste0("Put_Cohort3: pct intronic, " , "Median: ", sprintf("%0.3f", median_pct_intronic), "%")
pct_intronic_hist = hist(sobj$pct_intronic, main = title, xlab = "pct intronic", col="grey", breaks = 100)

median_pct_intronic = median(filtered_Put_Cohort3$pct_intronic)
title = paste0("filtered_Put_Cohort3: pct intronic, " , "Median: ", sprintf("%0.3f", median_pct_intronic), "%")
pct_intronic_hist = hist(sobj$pct_intronic, main = title, xlab = "pct intronic", col="grey", breaks = 100)

#histogram for nUMI --> take log10 of nUMI tonormalize
log_nUMI = log10(Put_Cohort3$nUmi)
median_log_nUMI = median(log_nUMI)
title = paste0("Put_Cohort3: log10(nUMI), ", "Median: ", sprintf("%0.3f", median_log_nUMI))
log_nUMI_hist = hist(log_nUMI, main= title, xlab = "log10(nUMI)", col="grey", breaks = 100)

saturation <- Put_Cohort3$nRead/Put_Cohort3$nUmi
median_umi_per_read = median(saturation)
title = paste0("Put_Cohort3: nReads/nUMI, " , "Median: ", sprintf("%0.3f", median_umi_per_read))  
saturation_hist = hist(saturation, main= title, xlab = "nRead/nUMI", col="grey", breaks = 100)

saturation <- filtered_Put_Cohort3$nRead/filtered_Put_Cohort3$nUmi
median_umi_per_read = median(saturation)
title = paste0("filtered_Put_Cohort3: nReads/nUMI, " , "Median: ", sprintf("%0.3f", median_umi_per_read))  
saturation_hist = hist(saturation, main= title, xlab = "nRead/nUMI", col="grey", breaks = 100)

median_pct_mito = median(Put_Cohort3$pct_mito)
title = paste0("Put_Cohort3: pct mito, " , "Median: ", sprintf("%0.3f", median_pct_mito), "%")
pct_intronic_hist = hist(sobj$pct_mito, main = title, xlab = "pct mito", col="grey", breaks = 100)

median_pct_mito = median(filtered_Put_Cohort3$pct_mito)
title = paste0("filtered_Put_Cohort3: pct mito, " , "Median: ", sprintf("%0.3f", median_pct_mito), "%")
pct_intronic_hist = hist(sobj$pct_mito, main = title, xlab = "pct mito", col="grey", breaks = 100)
```


```{r}
total_donors_cells_caudate <- as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id))
colnames(total_donors_cells_caudate) <- c("donor_id", "cell_count")

# Add condition information
total_donors_cells_caudate$Condition <- filtered_CaH_Cohort3@meta.data$Condition[match(total_donors_cells_caudate$donor_id, filtered_CaH_Cohort3@meta.data$donor_id)]

total_donors_cells_caudate$donor_id <- factor(total_donors_cells_caudate$donor_id, levels = total_donors_cells_caudate$donor_id[order(total_donors_cells_caudate$cell_count, decreasing = TRUE)])


ggplot(total_donors_cells_caudate, aes(x = donor_id, y = cell_count, fill = Condition)) + 
  geom_bar(stat = "identity") + 
  geom_text(aes(label = cell_count), vjust = -0.3, color = "black", size = 3) + 
  xlab("Donors from Caudate Village") + 
  ylab("Number of Cells") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
scale_fill_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4"))

```

```{r}
total_donors_cells_caudate <- as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id,filtered_CaH_Cohort3@meta.data$library ))
colnames(total_donors_cells_caudate) <- c("donor_id", "library", "cell_count")
total_donors_cells_caudate

# Add condition information
total_donors_cells_caudate$Condition <- filtered_CaH_Cohort3@meta.data$Condition[match(total_donors_cells_caudate$donor_id, filtered_CaH_Cohort3@meta.data$donor_id)]
total_donors_cells_caudate

caudate_cell = as.data.frame(table(filtered_CaH_Cohort3@meta.data$Condition))
caudate_cell$Condition = caudate_cell$Var1
caudate_cell$Var1 = NULL
caudate_cell$Village = "Caudate"
putamen_cell = as.data.frame(table(filtered_Put_Cohort3@meta.data$Condition))
putamen_cell$Condition = putamen_cell$Var1
putamen_cell$Var1 = NULL
putamen_cell$Village = "Putamen"
cells_villages = rbind(caudate_cell, putamen_cell)

total_freq_per_village <- aggregate(Freq ~ Village, data = cells_villages, FUN = sum)
total_freq_per_village

ggplot(cells_villages, aes(x = Village, y = Freq, fill = Condition)) +
  geom_bar(stat = "identity") +  
  geom_text(aes(label = Freq), position = position_stack(vjust = 0.5), size = 3, color = "white") +  
  geom_text(data = total_freq_per_village, aes(x = Village, y = Freq, label = Freq), vjust = -0.5, size = 4, inherit.aes = FALSE) +  
  labs(title = "Cell Counts by Region and Condition", x = "Region", y = "Cell Counts", fill = "Condition") +
  theme_minimal()


```

```{r}
caudate_cell = as.data.frame(table(filtered_CaH_Cohort3@meta.data$library))
caudate_cell$library = caudate_cell$Var1
caudate_cell$Var1 = NULL
caudate_cell$Village = "Caudate"
putamen_cell = as.data.frame(table(filtered_Put_Cohort3@meta.data$library))
putamen_cell$library = putamen_cell$Var1
putamen_cell$Var1 = NULL
putamen_cell$Village = "Putamen"
cells_villages = rbind(caudate_cell, putamen_cell)

total_freq_per_village <- aggregate(Freq ~ Village, data = cells_villages, FUN = sum)
total_freq_per_village

ggplot(cells_villages, aes(x = Village, y = Freq, fill = library)) +
  geom_bar(stat = "identity") +  
  geom_text(aes(label = Freq), position = position_stack(vjust = 0.5), size = 3, color = "white") +  
  geom_text(data = total_freq_per_village, aes(x = Village, y = Freq, label = Freq), vjust = -0.5, size = 4, inherit.aes = FALSE) +  
  labs(title = "Cell Counts by Region and Library", x = "Region", y = "Cell Counts", fill = "Condition") +
  theme_minimal()
```

```{r}
per_donor = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id))
per_donor

cells_per_donor_per_rxn = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id, filtered_CaH_Cohort3@meta.data$library))
cells_per_donor_per_rxn = merge(cells_per_donor_per_rxn, per_donor, by = "Var1" )
cells_per_donor_per_rxn

cells_per_donor_per_rxn$Var1 = factor(cells_per_donor_per_rxn$Var1, levels = x_order)

ggplot(cells_per_donor_per_rxn, aes(x = Var1, y = Freq.x, fill = Var2)) +
  geom_bar(stat = "identity") + xlab("Donors from Caudate Village") +  geom_text(data = cells_per_donor_per_rxn, aes(x = Var1, y = Freq.y, label = Freq.y), vjust = -0.2, size = 3, nudge_y = 0.5) + ylab("Number of Cells") +
 labs(fill = "Library")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
per_donor = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id))
per_donor

cells_per_donor_per_rxn = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id, filtered_Put_Cohort3@meta.data$library))
cells_per_donor_per_rxn = merge(cells_per_donor_per_rxn, per_donor, by = "Var1" )
cells_per_donor_per_rxn

cells_per_donor_per_rxn$Var1 = factor(cells_per_donor_per_rxn$Var1, levels = x_order)

ggplot(cells_per_donor_per_rxn, aes(x = Var1, y = Freq.x, fill = Var2)) +
  geom_bar(stat = "identity") + xlab("Donors from Putamen Village") +  geom_text(data = cells_per_donor_per_rxn, aes(x = Var1, y = Freq.y, label = Freq.y), vjust = -0.2, size = 3, nudge_y = 0.5) + ylab("Number of Cells") +
 labs(fill = "Library")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
DimPlot(filtered_CaH_Cohort3, group.by = "Condition")
DimPlot(filtered_CaH_Cohort3, group.by = "library")
DimPlot(filtered_CaH_Cohort3, group.by = "donor_id")

DimPlot(filtered_Put_Cohort3, group.by = "Condition")
DimPlot(filtered_Put_Cohort3, group.by = "library")
DimPlot(filtered_Put_Cohort3, group.by = "donor_id")

FeaturePlot(filtered_CaH_Cohort3, features = c("nUmi", "pct_mito"))
```


```{r}
cells_per_donor_per_rxn = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id, filtered_CaH_Cohort3@meta.data$library))
cells_per_donor_per_rxn
cells_per_donor_per_rxn$Var1 = factor(cells_per_donor_per_rxn$Var1, levels = x_order)

ggplot(cells_per_donor_per_rxn, aes(x=Var1, y = Freq, fill=Var2)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(fill = "Library")

cells_per_donor_per_rxn = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id, filtered_Put_Cohort3@meta.data$library))
cells_per_donor_per_rxn

cells_per_donor_per_rxn$Var1 = factor(cells_per_donor_per_rxn$Var1, levels = x_order)
ggplot(cells_per_donor_per_rxn, aes(x=Var1, y = Freq, fill=Var2)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Number of Cells") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + labs(fill = "Library")
```
```{r}
median_genes_per_donor <-filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor

median_genes_per_donor <-filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor
median_genes_per_donor$donor_id = factor(median_genes_per_donor$donor_id, levels = x_order)
ggplot(median_genes_per_donor, aes(x=donor_id, y = median_genes, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median number of genes") + theme(axis.text.x = element_text(angle = 45, hjust = 1))  +ggtitle("Caudate: Median genes per library")
```


```{r}
median_genes_per_donor <-filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor

median_genes_per_donor <-filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(median_genes = median(nFeature_RNA, na.rm = TRUE))

median_genes_per_donor
median_genes_per_donor$donor_id = factor(median_genes_per_donor$donor_id, levels = x_order)
ggplot(median_genes_per_donor, aes(x=donor_id, y = median_genes, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median number of genes") + theme(axis.text.x = element_text(angle = 45, hjust = 1))  +ggtitle("Putamen: Median genes per library")
```

```{r}
median_umis_per_donor <-filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(mUMI = median(nUmi, na.rm = TRUE))

median_umis_per_donor
median_umis_per_donor$donor_id = factor(median_umis_per_donor$donor_id, levels = x_order)
ggplot(median_umis_per_donor, aes(x=donor_id, y = mUMI, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median UMIs") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +ggtitle("Caudate: Median UMIs")


median_umis_per_donor <-filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id, library) %>%
  summarize(mUMI = median(nUmi, na.rm = TRUE))

median_umis_per_donor
median_umis_per_donor$donor_id = factor(median_umis_per_donor$donor_id, levels = x_order)
ggplot(median_umis_per_donor, aes(x=donor_id, y = mUMI, fill=library)) + geom_point(shape = 21, size = 3)+ xlab("Donors") + ylab("Median UMIs") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) +ggtitle("Putamen: Median UMIs")
```

```{r}
total_donors_cells_caudate_per_rxn = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id, filtered_CaH_Cohort3$library))

#install.packages("forcats")
library(forcats)

# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_caudate_per_rxn %>%
  group_by(Var1) %>%
  summarize(total_Freq = sum(Freq))

# Reorder Var1 based on total_Freq
total_donors_cells_caudate_per_rxn <- total_donors_cells_caudate_per_rxn %>%
  mutate(Var1 = fct_reorder(Var1, -summary_data$total_Freq[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>%
  mutate(Var1 = fct_reorder(Var1, -total_Freq))

# Create the stacked bar plot
ggplot(total_donors_cells_caudate_per_rxn, aes(x = Var1, y = Freq, fill = Var2)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_Freq, label = total_Freq), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Caudate Village") +
  ylab("Number of Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
total_donors_cells_putamen_per_rxn = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id, filtered_Put_Cohort3$library))
total_donors_cells_putamen_per_rxn

#install.packages("forcats")
#library(forcats)

# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_putamen_per_rxn %>%
  group_by(Var1) %>%
  summarize(total_Freq = sum(Freq))

# Reorder Var1 based on total_Freq
total_donors_cells_putamen_per_rxn <- total_donors_cells_putamen_per_rxn %>%
  mutate(Var1 = fct_reorder(Var1, -summary_data$total_Freq[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>%
  mutate(Var1 = fct_reorder(Var1, -total_Freq))

# Create the stacked bar plot
ggplot(total_donors_cells_putamen_per_rxn, aes(x = Var1, y = Freq, fill = Var2)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_Freq, label = total_Freq), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Putamen Village") +
  ylab("Number of Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```



#calculate how many cells are being filtered out from EACH donor
```{r}
total_donors_cells_caudate_by_rxn = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id, filtered_CaH_Cohort3@meta.data$library))
total_donors_cells_caudate_by_rxn

total_donors_cells_putamen_by_rxn = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id, filtered_Put_Cohort3@meta.data$library))
total_donors_cells_putamen_by_rxn

#prefilter
prefilter_caudate_by_rxn = as.data.frame(table(CaH_Cohort3@meta.data$donor_id, CaH_Cohort3@meta.data$library))
prefilter_caudate_by_rxn = subset(prefilter_caudate_by_rxn, subset = Var1 != "SCF_21_036B")
prefilter_caudate_by_rxn

prefilter_putamen_by_rxn = as.data.frame(table(Put_Cohort3@meta.data$donor_id, Put_Cohort3@meta.data$library))
prefilter_putamen_by_rxn
```

```{r}
total_donors_cells_caudate_by_rxn$filtered_cells = prefilter_caudate_by_rxn$Freq - total_donors_cells_caudate_by_rxn$Freq
total_donors_cells_caudate_by_rxn

total_donors_cells_putamen_by_rxn$filtered_cells =  prefilter_putamen_by_rxn$Freq - total_donors_cells_putamen_by_rxn$Freq
total_donors_cells_putamen_by_rxn

```
```{r}
total_donors_cells_caudate_by_rxn$proportion = total_donors_cells_caudate_by_rxn$filtered_cells/total_donors_cells_caudate_by_rxn$Freq
total_donors_cells_caudate_by_rxn$proportion <- round(total_donors_cells_caudate_by_rxn$proportion, 2)
total_donors_cells_caudate_by_rxn
```

```{r}
total_donors_cells_caudate_by_rxn
summary_data
```


```{r}
# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_caudate_by_rxn %>%
  group_by(Var1) %>%
  summarize(total_filtered_cells = sum(filtered_cells), total_cells = sum(Freq))

summary_data$total_proportion = summary_data$total_filtered_cells/summary_data$total_cells
summary_data$total_proportion <- round(summary_data$total_proportion, 2)

summary_data

# Reorder Var1 based on total_filtered_cells
total_donors_cells_caudate_by_rxn <- total_donors_cells_caudate_by_rxn %>%
  mutate(Var1 = fct_reorder(Var1, -summary_data$total_proportion[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>% mutate(Var1 = fct_reorder(Var1, -total_proportion))
summary_data

# Create the stacked bar plot
ggplot(summary_data, aes(x = Var1, y = total_proportion)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_proportion, label = total_proportion), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Caudate Village") +
  ylab("Proportion of Filtered Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_caudate_by_rxn %>%
  group_by(Var1) %>%
  summarize(total_filtered_cells = sum(filtered_cells))

summary_data

# Reorder Var1 based on total_filtered_cells
total_donors_cells_caudate_by_rxn <- total_donors_cells_caudate_by_rxn %>%
  mutate(Var1 = fct_reorder(Var1, -summary_data$total_filtered_cells[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>% mutate(Var1 = fct_reorder(Var1, -total_filtered_cells))
summary_data

# Create the stacked bar plot
ggplot(total_donors_cells_caudate_by_rxn, aes(x = Var1, y = filtered_cells, fill = Var2)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_filtered_cells, label = total_filtered_cells), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Caudate Village") +
  ylab("Number of Filtered Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_putamen_by_rxn %>%
  group_by(Var1) %>%
  summarize(total_filtered_cells = sum(filtered_cells))


# Reorder Var1 based on total_filtered_cells
total_donors_cells_putamen_by_rxn <- total_donors_cells_putamen_by_rxn %>%
mutate(Var1 = fct_reorder(Var1, -summary_data$total_filtered_cells[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>% mutate(Var1 = fct_reorder(Var1, -total_filtered_cells))
summary_data

# Create the stacked bar plot
ggplot(total_donors_cells_putamen_by_rxn, aes(x = Var1, y = filtered_cells, fill = Var2)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_filtered_cells, label = total_filtered_cells), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Putamen Village") +
  ylab("Number of Filtered Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
total_donors_cells_putamen_by_rxn$proportion = total_donors_cells_putamen_by_rxn$filtered_cells/total_donors_cells_putamen_by_rxn$Freq
total_donors_cells_putamen_by_rxn$proportion <- round(total_donors_cells_putamen_by_rxn$proportion, 2)
total_donors_cells_putamen_by_rxn

# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_putamen_by_rxn %>%
  group_by(Var1) %>%
  summarize(total_filtered_cells = sum(filtered_cells), total_cells = sum(Freq), total_proportion = sum(proportion))

summary_data


# Reorder Var1 based on total_filtered_cells
total_donors_cells_putamen_by_rxn <- total_donors_cells_putamen_by_rxn %>%
  mutate(Var1 = fct_reorder(Var1, -summary_data$total_proportion[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>% mutate(Var1 = fct_reorder(Var1, -total_proportion))
summary_data

# Create the stacked bar plot
ggplot(total_donors_cells_putamen_by_rxn, aes(x = Var1, y = proportion, fill = Var2)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_proportion, label = total_proportion), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Putamen Village") +
  ylab("Proportion of Filtered Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
# Summarize the data to get the sum of frequencies for each Var1
summary_data <- total_donors_cells_putamen_by_rxn %>%
  group_by(Var1) %>%
  summarize(total_filtered_cells = sum(filtered_cells), total_cells = sum(Freq))

summary_data$total_proportion = summary_data$total_filtered_cells/summary_data$total_cells
summary_data$total_proportion <- round(summary_data$total_proportion, 2)

summary_data

# Reorder Var1 based on total_filtered_cells
total_donors_cells_putamen_by_rxn <- total_donors_cells_putamen_by_rxn %>%
  mutate(Var1 = fct_reorder(Var1, -summary_data$total_proportion[match(Var1, summary_data$Var1)]))

# Update summary_data to use the same reordered Var1
summary_data <- summary_data %>% mutate(Var1 = fct_reorder(Var1, -total_proportion))
summary_data

# Create the stacked bar plot
ggplot(summary_data, aes(x = Var1, y = total_proportion)) +
  geom_bar(stat = "identity") +
  geom_text(data = summary_data, aes(x = Var1, y = total_proportion, label = total_proportion), 
            vjust = -0.3, color = "black", size = 3, inherit.aes = FALSE) +
  xlab("Donors from Putamen Village") +
  ylab("Proportion of Filtered Cells") + labs(fill = "Rxn")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
cells_per_donor = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id))
cells_per_donor

cell_class_df = as.data.frame(table(filtered_CaH_Cohort3@meta.data$cell_class, filtered_CaH_Cohort3@meta.data$donor_id))


cell_class_df = merge(cell_class_df, cells_per_donor, by.x="Var2", by.y = "Var1")
cell_class_df

cell_class_df$cell_proportions = cell_class_df$Freq.x/cell_class_df$Freq.y
cell_class_df


cell_class_df

cell_class_df$Var2 = factor(cell_class_df$Var2, levels = x_order)

ggplot(cell_class_df, aes(x = Var2, y = Freq.x, fill = Var1)) +
  geom_bar(stat = "identity") + xlab("Donors from Caudate Village") + ylab("Number of cells by cell type") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black") +theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(cell_class_df, aes(x = Var2, y = cell_proportions, fill = Var1)) +
  geom_bar(stat = "identity", postion= "stack") + xlab("Donors from Caudate Village") + ylab("Cell Type Proportion") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  
#+ facet_wrap(~ Var1)
```
```{r}
cells_per_donor = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id))
cells_per_donor

cell_class_df = as.data.frame(table(filtered_Put_Cohort3@meta.data$cell_class, filtered_Put_Cohort3@meta.data$donor_id))


cell_class_df = merge(cell_class_df, cells_per_donor, by.x="Var2", by.y = "Var1")
cell_class_df

cell_class_df$cell_proportions = cell_class_df$Freq.x/cell_class_df$Freq.y
cell_class_df


cell_class_df

cell_class_df$Var2 = factor(cell_class_df$Var2, levels = x_order)

ggplot(cell_class_df, aes(x = Var2, y = Freq.x, fill = Var1)) +
  geom_bar(stat = "identity") + xlab("Donors from Putamen Village") + ylab("Number of cells by cell type") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black") +theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(cell_class_df, aes(x = Var2, y = cell_proportions, fill = Var1)) +
  geom_bar(stat = "identity", postion= "stack") + xlab("Donors from Putamen Village") + ylab("Cell Type Proportion") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  
#+ facet_wrap(~ Var1)
```


```{r}
#totalcells
cells_per_library = as.data.frame(table(filtered_CaH_Cohort3@meta.data$donor_id))
names(cells_per_library)[names(cells_per_library) == "Var1"] ="library"
names(cells_per_library)[names(cells_per_library) == "Freq"] ="total_cells"
cells_per_library  

#median/mean nUMI
median_nUmi = filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_UMI = median(nUmi, na.rm = TRUE))
median_nUmi

# mean_nUmi = filtered_CaH_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_UMI = mean(nUmi, na.rm = TRUE))
# mean_nUmi

#median/mean nGenes
median_nGenes = filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_nGenes = median(nFeature_RNA, na.rm = TRUE))
median_nGenes

# mean_nGenes = filtered_CaH_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_nGenes = mean(nFeature_RNA, na.rm = TRUE))
# mean_nGenes

#median/mean reads/numi
median_reads_per_umi = filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_reads_per_umi = median((nRead/nUmi), na.rm = TRUE))
median_reads_per_umi

# mean_reads_per_umi = filtered_CaH_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_reads_per_umi = mean((nRead/nUmi), na.rm = TRUE))
# mean_reads_per_umi

#median/mean pctintronic
median_pct_intronic = filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))
median_pct_intronic

# mean_pct_intronic = filtered_CaH_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_pct_intronic = mean(pct_intronic, na.rm = TRUE))
# mean_pct_intronic

#median/mean pctmito
median_pct_mito = filtered_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))
median_pct_mito

# mean_pct_mito = filtered_CaH_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_pct_mito = mean(pct_mito, na.rm = TRUE))
# mean_pct_mito
```
```{r}
library(gridExtra)
caudate_library_qc_df_list = list(median_nUmi, median_nGenes, median_reads_per_umi, median_pct_intronic,  median_pct_mito)
caudate_library_qc_df = reduce(caudate_library_qc_df_list, left_join, by = "donor_id")
caudate_library_qc_df

caudate_library_qc_df[, -1] <- round(caudate_library_qc_df[, -1], digits = 2)
caudate_library_qc_df
table_grob = tableGrob(caudate_library_qc_df)
ggsave("caudate_donor_qc_df.png", table_grob, width = 15, height = 6, dpi = 300)
```


```{r}
library(purrr)
# List of data frames to merge
df_list <- list(median_nUmi, median_nGenes,median_reads_per_umi, median_pct_intronic, median_pct_mito )

# Merge all data frames on the common column Donor.ID
merged_df <- reduce(df_list, function(x, y) merge(x, y, by = "donor_id"))

# Print the merged data frame
print(merged_df)

qc_graphs = function(data, y, xlab, ylab, title){


data$donor_id = factor(data$donor_id, levels = x_order)
median = median(y)

ggplot(data, aes(x = donor_id, y = y, fill = donor_id)) +
  geom_bar(stat = "identity") + xlab(xlab) + ylab(ylab)+ labs(fill = "donor_id")+ ggtitle(label = title, subtitle = paste("Median: ", sprintf("%0.2f", median)))+geom_hline(yintercept = median, linetype = "dashed", color = "black") +
  geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+  theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```

```{r}
qc_graphs(merged_df, merged_df$median_UMI, "Donors", "median UMI", "CaH Village: median UMI")
qc_graphs(merged_df, merged_df$median_nGenes, "Donors", "median nGenes", "CaH Village: median nGenes")
qc_graphs(merged_df, merged_df$median_reads_per_umi, "Donors", "median reads/UMI", "CaH Village: median reads/UMI")
qc_graphs(merged_df, merged_df$median_pct_intronic, "Donors", "median pct intronic", "CaH Village: median pct intronic")
qc_graphs(merged_df, merged_df$median_pct_mito, "Donors", "median pct mito", "CaH Village: median pct mito")
```


#putamen
```{r}
#totalcells
cells_per_library = as.data.frame(table(filtered_Put_Cohort3@meta.data$donor_id))
names(cells_per_library)[names(cells_per_library) == "Var1"] ="library"
names(cells_per_library)[names(cells_per_library) == "Freq"] ="total_cells"
cells_per_library  

#median/mean nUMI
median_nUmi = filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_UMI = median(nUmi, na.rm = TRUE))
median_nUmi

# mean_nUmi = filtered_Put_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_UMI = mean(nUmi, na.rm = TRUE))
# mean_nUmi

#median/mean nGenes
median_nGenes = filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_nGenes = median(nFeature_RNA, na.rm = TRUE))
median_nGenes

# mean_nGenes = filtered_Put_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_nGenes = mean(nFeature_RNA, na.rm = TRUE))
# mean_nGenes

#median/mean reads/numi
median_reads_per_umi = filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_reads_per_umi = median((nRead/nUmi), na.rm = TRUE))
median_reads_per_umi

# mean_reads_per_umi = filtered_Put_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_reads_per_umi = mean((nRead/nUmi), na.rm = TRUE))
# mean_reads_per_umi

#median/mean pctintronic
median_pct_intronic = filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))
median_pct_intronic

# mean_pct_intronic = filtered_Put_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_pct_intronic = mean(pct_intronic, na.rm = TRUE))
# mean_pct_intronic

#median/mean pctmito
median_pct_mito = filtered_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))
median_pct_mito

# mean_pct_mito = filtered_Put_Cohort3@meta.data %>%
#   group_by(donor_id) %>%
#   summarize(mean_pct_mito = mean(pct_mito, na.rm = TRUE))
# mean_pct_mito

# List of data frames to merge
df_list <- list(median_nUmi, median_nGenes,median_reads_per_umi, median_pct_intronic, median_pct_mito )

# Merge all data frames on the common column Donor.ID
merged_df <- reduce(df_list, function(x, y) merge(x, y, by = "donor_id"))

# Print the merged data frame
print(merged_df)
```

```{r}
putamen_library_qc_df_list = list(median_nUmi, median_nGenes, median_reads_per_umi, median_pct_intronic,  median_pct_mito)
putamen_library_qc_df = reduce(putamen_library_qc_df_list, left_join, by = "donor_id")
putamen_library_qc_df

putamen_library_qc_df[, -1] <- round(putamen_library_qc_df[, -1], digits = 2)
putamen_library_qc_df
table_grob = tableGrob(putamen_library_qc_df)
ggsave("putamen_donor_qc_df.png", table_grob, width = 15, height = 6, dpi = 300)
```

```{r}
qc_graphs(merged_df, merged_df$median_UMI, "Donors", "median UMI", "Put Village: median UMI")
qc_graphs(merged_df, merged_df$median_nGenes, "Donors", "median nGenes", "Put Village: median nGenes")
qc_graphs(merged_df, merged_df$median_reads_per_umi, "Donors", "median reads/UMI", "Put Village: median reads/UMI")
qc_graphs(merged_df, merged_df$median_pct_intronic, "Donors", "median pct intronic", "Put Village: median pct intronic")
qc_graphs(merged_df, merged_df$median_pct_mito, "Donors", "median pct mito", "Put Village: median pct mito")
```



```{r}
#totalcells
cells_per_library = as.data.frame(table(filtered_CaH_Cohort3@meta.data$library))
names(cells_per_library)[names(cells_per_library) == "Var1"] ="library"
names(cells_per_library)[names(cells_per_library) == "Freq"] ="total_cells"
cells_per_library  

#median/mean nUMI
median_nUmi = filtered_CaH_Cohort3@meta.data %>%
  group_by(library) %>%
  summarize(median_UMI = median(nUmi, na.rm = TRUE))
median_nUmi

#median/mean nGenes
median_nGenes = filtered_CaH_Cohort3@meta.data %>%
  group_by(library) %>%
  summarize(median_nGenes = median(nFeature_RNA, na.rm = TRUE))
median_nGenes

#median/mean reads/numi
median_reads_per_umi = filtered_CaH_Cohort3@meta.data %>%
  group_by(library) %>%
  summarize(median_reads_per_umi = median((nRead/nUmi), na.rm = TRUE))
median_reads_per_umi

#median/mean pctintronic
median_pct_intronic = filtered_CaH_Cohort3@meta.data %>%
  group_by(library) %>%
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))
median_pct_intronic


#median/mean pctmito
median_pct_mito = filtered_CaH_Cohort3@meta.data %>%
  group_by(library) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))
median_pct_mito

```
```{r}
library(gridExtra)
caudate_library_qc_df_list = list(median_nUmi, median_nGenes, median_reads_per_umi, median_pct_intronic,  median_pct_mito)
caudate_library_qc_df = reduce(caudate_library_qc_df_list, left_join, by = "library")
caudate_library_qc_df

caudate_library_qc_df[, -1] <- round(caudate_library_qc_df[, -1], digits = 2)
caudate_library_qc_df
table_grob = tableGrob(caudate_library_qc_df)
ggsave("caudate_library_qc_df.png", table_grob, width = 15, height = 6, dpi = 300)
```


```{r}
library(purrr)
# List of data frames to merge
df_list <- list(median_nUmi, median_nGenes,median_reads_per_umi, median_pct_intronic, median_pct_mito )

# Merge all data frames on the common column Donor.ID
merged_df <- reduce(df_list, function(x, y) merge(x, y, by = "library"))

# Print the merged data frame
print(merged_df)


merged_df_final_combined = rbind(merged_df,merged_df_final)
merged_df_final_combined

qc_graphs_lib = function(data, y, xlab, ylab, title){

x_order = c("CaH_rxn1", "CaH_rxn2", "Put_rxn1", "Put_rxn2")  

data$library = factor(data$library, levels = x_order)
median = median(y)

ggplot(data, aes(x = library, y = y, fill = library)) +
  geom_bar(stat = "identity") + xlab(xlab) + ylab(ylab)+ labs(fill = "library")+ ggtitle(label = title, subtitle = paste("Median: ", sprintf("%0.2f", median)))+geom_hline(yintercept = median, linetype = "dashed", color = "black") +
  geom_vline(xintercept =  8.5, linetype = "dashed", color = "black")+  theme(axis.text.x = element_text(angle = 45, hjust = 1))
}
```

```{r}
qc_graphs_lib(merged_df_final_combined, merged_df_final_combined$median_UMI, "Library", "median UMI", "CaH + Put: median UMI")
qc_graphs_lib(merged_df_final_combined, merged_df_final_combined$median_nGenes, "Library", "median nGenes", "CaH + Put: median nGenes")
qc_graphs_lib(merged_df_final_combined, merged_df_final_combined$median_reads_per_umi, "Library", "median reads/UMI", "CaH + Put: median reads/UMI")
qc_graphs_lib(merged_df_final_combined, merged_df_final_combined$median_pct_intronic, "Library", "median pct intronic", "CaH + Put: median pct intronic")
qc_graphs_lib(merged_df_final_combined, merged_df_final_combined$median_pct_mito, "Library", "median pct mito", "CaH + Put: median pct mito")
```


```{r}
cells_per_donor = as.data.frame(table(cleaned_CaH_Cohort3@meta.data$donor_id))
cells_per_donor

cell_class_df = as.data.frame(table(cleaned_CaH_Cohort3@meta.data$cell_class, cleaned_CaH_Cohort3@meta.data$donor_id))


cell_class_df = merge(cell_class_df, cells_per_donor, by.x="Var2", by.y = "Var1")
cell_class_df

cell_class_df$cell_proportions = cell_class_df$Freq.x/cell_class_df$Freq.y
cell_class_df


cell_class_df

cell_class_df$Var2 = factor(cell_class_df$Var2, levels = x_order)

ggplot(cell_class_df, aes(x = Var2, y = Freq.x, fill = Var1)) +
  geom_bar(stat = "identity") + xlab("Donors from Caudate Village") + ylab("Number of cells by cell type") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black") +theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(cell_class_df, aes(x = Var2, y = cell_proportions, fill = Var1)) +
  geom_bar(stat = "identity", postion= "stack") + xlab("Donors from Caudate Village") + ylab("Cell Type Proportion") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  
#+ facet_wrap(~ Var1)
```

```{r}
#totalcells
cells_per_library = as.data.frame(table(cleaned_CaH_Cohort3@meta.data$donor_id))
names(cells_per_library)[names(cells_per_library) == "Var1"] ="library"
names(cells_per_library)[names(cells_per_library) == "Freq"] ="total_cells"
cells_per_library  

#median/mean nUMI
median_nUmi = cleaned_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_UMI = median(nUmi, na.rm = TRUE))
median_nUmi


#median/mean nGenes
median_nGenes = cleaned_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_nGenes = median(nFeature_RNA, na.rm = TRUE))
median_nGenes


#median/mean reads/numi
median_reads_per_umi = cleaned_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_reads_per_umi = median((nRead/nUmi), na.rm = TRUE))
median_reads_per_umi


#median/mean pctintronic
median_pct_intronic = cleaned_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))
median_pct_intronic

#median/mean pctmito
median_pct_mito = cleaned_CaH_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))
median_pct_mito


```

```{r}
library(purrr)
# List of data frames to merge
df_list <- list(median_nUmi, median_nGenes,median_reads_per_umi, median_pct_intronic, median_pct_mito )

# Merge all data frames on the common column Donor.ID
merged_df <- reduce(df_list, function(x, y) merge(x, y, by = "donor_id"))

# Print the merged data frame
print(merged_df)


qc_graphs(merged_df, merged_df$median_UMI, "Donors", "median UMI", "CaH Village: median UMI")
qc_graphs(merged_df, merged_df$median_nGenes, "Donors", "median nGenes", "CaH Village: median nGenes")
qc_graphs(merged_df, merged_df$median_reads_per_umi, "Donors", "median reads/UMI", "CaH Village: median reads/UMI")
qc_graphs(merged_df, merged_df$median_pct_intronic, "Donors", "median pct intronic", "CaH Village: median pct intronic")
qc_graphs(merged_df, merged_df$median_pct_mito, "Donors", "median pct mito", "CaH Village: median pct mito")
```



```{r}
cells_per_donor = as.data.frame(table(cleaned_Put_Cohort3@meta.data$donor_id))
cells_per_donor

cell_class_df = as.data.frame(table(cleaned_Put_Cohort3@meta.data$cell_class, cleaned_Put_Cohort3@meta.data$donor_id))


cell_class_df = merge(cell_class_df, cells_per_donor, by.x="Var2", by.y = "Var1")
cell_class_df

cell_class_df$cell_proportions = cell_class_df$Freq.x/cell_class_df$Freq.y
cell_class_df


cell_class_df


cell_class_df$Var2 = factor(cell_class_df$Var2, levels = x_order)

ggplot(cell_class_df, aes(x = Var2, y = Freq.x, fill = Var1)) +
  geom_bar(stat = "identity") + xlab("Donors from Putamen Village") + ylab("Number of cells by cell type") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black") +theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(cell_class_df, aes(x = Var2, y = cell_proportions, fill = Var1)) +
  geom_bar(stat = "identity", postion= "stack") + xlab("Donors from Putamen Village") + ylab("Cell Type Proportion") + labs(fill = "Cell Type")+ geom_vline(xintercept =  5.5, linetype = "dashed", color = "black")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  
#+ facet_wrap(~ Var1)
```



```{r}
#totalcells
cells_per_library = as.data.frame(table(cleaned_Put_Cohort3@meta.data$donor_id))
names(cells_per_library)[names(cells_per_library) == "Var1"] ="library"
names(cells_per_library)[names(cells_per_library) == "Freq"] ="total_cells"
cells_per_library  

#median/mean nUMI
median_nUmi = cleaned_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_UMI = median(nUmi, na.rm = TRUE))
median_nUmi


#median/mean nGenes
median_nGenes = cleaned_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_nGenes = median(nFeature_RNA, na.rm = TRUE))
median_nGenes


#median/mean reads/numi
median_reads_per_umi = cleaned_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_reads_per_umi = median((nRead/nUmi), na.rm = TRUE))
median_reads_per_umi


#median/mean pctintronic
median_pct_intronic = cleaned_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))
median_pct_intronic

#median/mean pctmito
median_pct_mito = cleaned_Put_Cohort3@meta.data %>%
  group_by(donor_id) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))
median_pct_mito


library(purrr)
# List of data frames to merge
df_list <- list(median_nUmi, median_nGenes,median_reads_per_umi, median_pct_intronic, median_pct_mito )

# Merge all data frames on the common column Donor.ID
merged_df <- reduce(df_list, function(x, y) merge(x, y, by = "donor_id"))

# Print the merged data frame
print(merged_df)


table(cleaned_Put_Cohort3$donor_id)

qc_graphs(merged_df, merged_df$median_UMI, "Donors", "median UMI", "Put Village: median UMI")
qc_graphs(merged_df, merged_df$median_nGenes, "Donors", "median nGenes", "Put Village: median nGenes")
qc_graphs(merged_df, merged_df$median_reads_per_umi, "Donors", "median reads/UMI", "Put Village: median reads/UMI")
qc_graphs(merged_df, merged_df$median_pct_intronic, "Donors", "median pct intronic", "Put Village: median pct intronic")
qc_graphs(merged_df, merged_df$median_pct_mito, "Donors", "median pct mito", "Put Village: median pct mito")
```







