---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(qs)
library(tidyverse)
library(ggplot2)
```

```{r}
All_DFC = qread("All_XDP_Cohorts_DFC_sct.qs")
All_DFC
All_DFC@meta.data
DimPlot(All_DFC, group.by = "final_cell_class_merged_harmony")
```
```{r}
DefaultAssay(All_DFC) = "RNA"
All_DFC_neurons = subset(All_DFC, subset = final_cell_class_merged_harmony == "neuron")
All_DFC_neurons
```

```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(All_DFC_neurons, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
All_DFC_neurons = (All_DFC_neurons
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_DFC$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_DFC$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}
```

```{r}
DimPlot(All_DFC_neurons, group.by = "donor_id") 
```


```{r}
DimPlot(All_DFC_neurons, group.by = "donor_id") 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(All_DFC_neurons, group.by = "RNA_snn_res.0.8", label=T)

FeaturePlot(All_DFC_neurons, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("FAM163A", "CCDC88C", "CNGB1"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("TWIST2", "MET", "ALDH1A1", "ANXA1"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("PKD2L1", "ABCC12", "ABCB11", "PQLC2L"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("CORIN", "NPNT", "OPN4", "VWA5A"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("LGR5", "C14orf64", "COL9A3", "FAM89A"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("FSHR", "ADAMTS12", "NPSR1", "IL26"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("MYOCD", "SMOC1", "CDC14A", "SYT10"), raster = F)
FeaturePlot(All_DFC_neurons, features = c("ELK3", "GALR1", "CHAT"),raster=FALSE) 
FeaturePlot(All_DFC_neurons, features = c("SST", "CALB1", "SLC17A6", "SLC17A7"),raster=FALSE) 
FeaturePlot(All_DFC_neurons, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 

```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN")

Dotplot = DotPlot(object = All_DFC_neurons, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


marker_genes <- c("CHAT", "SLC17A7", "CALB1", "SST", "GALR1", "ELK3", "SYT10", "CDC14A", "SMOC1", "MYOCD", "IL26", "NPSR1", "ADAMTS12", "FSHR", "FAM89A", "COL9A3", "C14orf64", "LGR5", "VWA5A", "OPN4", "NPNT", "CORIN", "PQLC2L", "ABCB11", "ABCC12", "PKD2L1", "ANXA1", "ALDH1A1", "MET", "TWIST2", "CNGB1", "CCDC88C", "FAM163A", "SLC17A6", "GAD2", "RBFOX3", "SYT1")



Dotplot = DotPlot(object = All_DFC_neurons, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
FeaturePlot(All_DFC_neurons, features = c("OLIG1", "MOG", "GFAP", "OLIG2"), raster = F)
```

```{r}
Idents(All_DFC_neurons) = All_DFC_neurons$RNA_snn_res.0.5

classes = c("L2-3 IT", "L3-5 IT-1", "L3-5 IT-3", "3", "4", "5", "L3-5 IT-2", "7", "L3-5 IT-1", "9", "10", "L6B", "12", "L3-5 IT-1", "14", "L3-5 IT-2", "L5-6 NP", "L6 IT-2", "18", "19", "doublet", "L5 ET", "doublet", "doublet")


All_DFC_neurons= assignCellClasses(All_DFC_neurons, classes=classes, cluster_col="RNA_snn_res.0.5", class_col = "neuron_cell_class")

DimPlot(All_DFC_neurons, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```


```{r}
marker_genes <- c("CHAT", "SLC17A7", "CALB1", "SST", "GALR1", "ELK3", "SYT10", "CDC14A", "SMOC1", "MYOCD", "IL26", "NPSR1", "ADAMTS12", "FSHR", "FAM89A", "COL9A3", "C14orf64", "LGR5", "VWA5A", "OPN4", "NPNT", "CORIN", "PQLC2L", "ABCB11", "ABCC12", "PKD2L1", "ANXA1", "ALDH1A1", "MET", "TWIST2", "CNGB1", "CCDC88C", "FAM163A", "SLC17A6", "GAD2", "RBFOX3", "SYT1")

Dotplot = DotPlot(object = All_DFC_neurons, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


marker_genes <- c("LAMP5", "LHX6", "RELN", "VIP", "ADARB2", "KCNG1", "SST", "HGF", "PVALB", "NPY", "TH", "CALB1")

Dotplot = DotPlot(object = All_DFC_neurons, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```



```{r}
All_SN = qread("All_XDP_Cohorts_SN_sct.qs")
All_SN
All_SN@meta.data
```
```{r}
DefaultAssay(All_SN) = "RNA"
All_SN_neurons = subset(All_SN, subset = final_cell_class_merged_harmony == "neuron")
All_SN_neurons
```

```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(All_SN_neurons, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
All_SN_neurons = (All_SN_neurons
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_DFC$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_DFC$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}


DimPlot(All_SN_neurons, group.by = "donor_id") 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(All_SN_neurons, group.by = "RNA_snn_res.0.8", label=T)
```


```{r}
FeaturePlot(All_SN_neurons, features = c("SYT1", "RBFOX3", "GAD2", "CHAT"), raster = F)
FeaturePlot(All_SN_neurons, features = c("SOX6", "CALB1", "SLC1A3", "KIT"), raster = F)
FeaturePlot(All_SN_neurons, features = c("PLP1", "RELN", "GULP1", "CDH6"), raster = F)
FeaturePlot(All_SN_neurons, features = c("NXPH1", "EYA4", "SLC18A2", "TH"), raster = F)
FeaturePlot(All_SN_neurons, features = c("SLC6A3", "TRHR", "GEM", "RBP4"), raster = F)
FeaturePlot(All_SN_neurons, features = c("PPP1R17", "CCDC68", "CRYM", "CALCR"), raster = F)
FeaturePlot(All_SN_neurons, features = c("GFRA2", "DDT", "SYNPR", "AGTR1"), raster = F)
FeaturePlot(All_SN_neurons, features = c("TMEM200A", "SST", "SLC17A6", "SLC17A7"), raster=FALSE)
FeaturePlot(All_SN_neurons, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 

```

```{r}
marker_genes <- c("SYT1", "RBFOX3", "GAD2", "CHAT", "SOX6", "CALB1", "SLC1A3", "KIT","PLP1", "RELN", "GULP1", "CDH6", "NXPH1", "EYA4", "SLC18A2", "TH", "SLC6A3", "TRHR", "GEM", "RBP4", "PPP1R17", "CCDC68", "CRYM", "CALCR", "GFRA2", "DDT", "SYNPR", "AGTR1", "TMEM200A", "SST", "SLC17A6", "SLC17A7")

Dotplot = DotPlot(object = All_SN_neurons, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)

marker_genes <- c("TRHR", "GEM", "RBP4", "PPP1R17", "CCDC68", "CRYM", "CALCR", "GFRA2", "DDT", "PART1", "FAM19A4","SYNPR", "AGTR1", "TMEM200A", "CALB1", "SOX6")

Dotplot = DotPlot(object = All_SN_neurons, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

