---
title: "R Notebook"
output: html_notebook
---

#accidentally deleted orig file ughhhhhh this is from memory

#functions
```{r}
spatial_gene_expression <- function(seurat_obj, gene_of_interest) {

  metadata_df = seurat_obj@meta.data
  metadata_df$cell_ids = rownames(metadata_df)

  gene_df = as.data.frame(FetchData(seurat_obj, vars = gene_of_interest))
  gene_df$cell_ids = rownames(gene_df)
  
  df_final = merge(metadata_df, gene_df, by = "cell_ids")
  
  ggplot(df_final, aes(x = x_um, y = y_um, color = .data[[gene_of_interest]])) + 
    geom_point() + 
    scale_color_gradient(low = "lightgrey", high = "blue") + 
    labs(color = "Expression") +
    theme_void() + 
    facet_wrap(~ cell_class_annot) + 
    ylab(NULL)
}

```

```{r}
bican_recon = qread("/broad/macosko/kimkathl/bican_recon_apr2025_sct_mask.qs")
bican_recon

qsave(bican_recon, "/broad/macosko/kimkathl/bican_recon_apr2025_sct_mask.qs")
```

```{r}
bican_cell_class = unique(bican_recon@meta.data$cell_class_annot)
bican_recon = subset(bican_recon, subset = WM_GM != "Unplaced") #remove unplaced cells before running findallmarkers

bican_marker_list = list()
bican_subset_sobj_list = list()

for (celltype in bican_cell_class) {
  temp = subset(bican_recon, subset = cell_class_annot == celltype)
  Idents(temp) = "WM_GM"
  markers = FindAllMarkers(temp, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1.25)

  bican_marker_list = bican_marker_list[[celltype]]
  bican_subset_sobj_list = bican_subset_sobj_list[[celltype]]
  
}

```

```{r}
bican_marker_list = qread("/broad/macosko/kimkathl/XDP/Analysis/Gray_White_Matter_Scores/bican_marker_list.qs")
bican_marker_list
#bican_subset_sobj_list
```

```{r}
bican_recon_astro_markers = bican_marker_list[["astro"]]
bican_recon_opc_markers = bican_marker_list[["opc"]]
bican_recon_oligo_markers = bican_marker_list[["oligo"]]
bican_recon_endo_markers = bican_marker_list[["endo"]]
bican_recon_neuron_markers = bican_marker_list[["neuron"]]
bican_recon_mg_markers = bican_marker_list[["mg"]]
```

```{r}
bican_recon_astro_markers_wm = subset(bican_recon_astro_markers, subset = cluster == "White_Matter")
bican_recon_astro_markers_gm = subset(bican_recon_astro_markers, subset = cluster == "Gray_Matter")
bican_recon_opc_markers_wm  = subset(bican_recon_opc_markers, subset = cluster == "White_Matter")
bican_recon_opc_markers_gm = subset(bican_recon_opc_markers, subset = cluster == "Gray_Matter")
bican_recon_oligo_markers_wm = subset(bican_recon_oligo_markers, subset = cluster == "White_Matter")
bican_recon_oligo_markers_gm = subset(bican_recon_oligo_markers, subset = cluster == "Gray_Matter")
bican_recon_mg_markers_wm = subset(bican_recon_mg_markers, subset = cluster == "White_Matter")
bican_recon_mg_markers_gm = subset(bican_recon_mg_markers, subset = cluster == "Gray_Matter")

bican_recon_astro_markers_wm 
bican_recon_astro_markers_gm 
bican_recon_opc_markers_wm  
bican_recon_opc_markers_gm 
bican_recon_oligo_markers_wm 
bican_recon_oligo_markers_gm 
bican_recon_mg_markers_wm 
bican_recon_mg_markers_gm 
```


```{r}
bican_recon_astro_markers_filtered = subset(bican_recon_astro_markers, subset = pct.1 > 0.7 & pct.2 < 0.3)
bican_recon_opc_markers_filtered = subset(bican_recon_opc_markers, subset = pct.1 > 0.7 & pct.2 < 0.3)
bican_recon_oligo_markers_filtered = subset(bican_recon_oligo_markers, subset = pct.1 > 0.6 & pct.2 < 0.3)
bican_recon_mg_markers_filtered = subset(bican_recon_mg_markers, subset = pct.1 > 0.6 & pct.2 < 0.3)

bican_recon_astro_markers_filtered_wm= subset(bican_recon_astro_markers_filtered, subset = cluster == "White_Matter")
bican_recon_astro_markers_filtered_gm= subset(bican_recon_astro_markers_filtered, subset = cluster == "Gray_Matter")
bican_recon_opc_markers_filtered_wm= subset(bican_recon_opc_markers_filtered, subset = cluster == "White_Matter")
bican_recon_opc_markers_filtered_gm= subset(bican_recon_opc_markers_filtered, subset = cluster == "Gray_Matter")
bican_recon_oligo_markers_filtered_wm= subset(bican_recon_oligo_markers_filtered, subset = cluster == "White_Matter")
bican_recon_oligo_markers_filtered_gm= subset(bican_recon_oligo_markers_filtered, subset = cluster == "Gray_Matter")
bican_recon_mg_markers_filtered_wm= subset(bican_recon_mg_markers_filtered, subset = cluster == "White_Matter")
bican_recon_mg_markers_filtered_gm= subset(bican_recon_mg_markers_filtered, subset = cluster == "Gray_Matter")

bican_recon_astro_markers_filtered_wm
bican_recon_astro_markers_filtered_gm
bican_recon_opc_markers_filtered_wm
bican_recon_opc_markers_filtered_gm
bican_recon_oligo_markers_filtered_wm
bican_recon_oligo_markers_filtered_gm #none
bican_recon_mg_markers_filtered_wm
bican_recon_mg_markers_filtered_gm #none
```

```{r}
bican_recon_astro_markers_filtered_wm = rownames(bican_recon_astro_markers_filtered_wm)
bican_recon_astro_markers_filtered_gm= rownames(bican_recon_astro_markers_filtered_gm)
bican_recon_opc_markers_filtered_wm= rownames(bican_recon_opc_markers_filtered_wm)
bican_recon_opc_markers_filtered_gm= rownames(bican_recon_opc_markers_filtered_gm)
bican_recon_oligo_markers_filtered_wm= rownames(bican_recon_oligo_markers_filtered_wm)
bican_recon_oligo_markers_filtered_gm= rownames(bican_recon_oligo_markers_filtered_gm)
bican_recon_mg_markers_filtered_wm= rownames(bican_recon_mg_markers_filtered_wm)
bican_recon_mg_markers_filtered_gm= rownames(bican_recon_mg_markers_filtered_gm)

bican_recon_astro_markers_filtered_wm
bican_recon_astro_markers_filtered_gm
bican_recon_opc_markers_filtered_wm
bican_recon_opc_markers_filtered_gm
bican_recon_oligo_markers_filtered_wm
bican_recon_oligo_markers_filtered_gm #none
bican_recon_mg_markers_filtered_wm
bican_recon_mg_markers_filtered_gm #none
```

```{r}
bican_recon_astro_markers_top50_wm <- bican_recon_astro_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_astro_markers_top50_gm <- bican_recon_astro_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_opc_markers_top50_wm <- bican_recon_opc_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)
bican_recon_opc_markers_top50_gm <- bican_recon_opc_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_oligo_markers_top50_wm <- bican_recon_oligo_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_oligo_markers_top50_gm <- bican_recon_oligo_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_mg_markers_top50_wm <- bican_recon_mg_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_mg_markers_top50_gm <- bican_recon_mg_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)


bican_recon_astro_markers_top50_wm
bican_recon_astro_markers_top50_gm
bican_recon_opc_markers_top50_wm
bican_recon_opc_markers_top50_gm
bican_recon_oligo_markers_top50_wm
bican_recon_oligo_markers_top50_gm
bican_recon_mg_markers_top50_wm
bican_recon_mg_markers_top50_gm


bican_recon_astro_markers_top50_wm = rownames(bican_recon_astro_markers_top50_wm)
bican_recon_astro_markers_top50_gm= rownames(bican_recon_astro_markers_top50_gm)
bican_recon_opc_markers_top50_wm= rownames(bican_recon_opc_markers_top50_wm)
bican_recon_opc_markers_top50_gm= rownames(bican_recon_opc_markers_top50_gm)
bican_recon_oligo_markers_top50_wm= rownames(bican_recon_oligo_markers_top50_wm)
bican_recon_oligo_markers_top50_gm= rownames(bican_recon_oligo_markers_top50_gm)
bican_recon_mg_markers_top50_wm= rownames(bican_recon_mg_markers_top50_wm)
bican_recon_mg_markers_top50_gm= rownames(bican_recon_mg_markers_top50_gm)
```


```{r}
bican_recon@meta.data
```

```{r}
library(UCell)

bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_astro_markers_filtered_wm), name = 'filtered_astro_recon_wm')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_astro_markers_filtered_gm), name = 'filtered_astro_recon_gm')

bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_opc_markers_filtered_wm), name = 'filtered_opc_recon_wm')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_opc_markers_filtered_gm), name = 'filtered_opc_recon_gm')

bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_oligo_markers_filtered_wm), name = 'filtered_oligo_recon_wm')


bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_mg_markers_filtered_wm), name = 'filtered_mg_recon_wm')



bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'top_50_astro_recon_wm')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_astro_markers_top50_gm), name = 'top_50_astro_recon_gm')

bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_opc_markers_top50_wm), name = 'top_50_opc_recon_wm')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_opc_markers_top50_gm), name = 'top_50_opc_recon_gm')

bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_oligo_markers_top50_wm), name = 'top_50_oligo_recon_wm')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_oligo_markers_top50_gm), name = 'top_50_oligo_recon_gm')

bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_mg_markers_top50_wm), name = 'top_50_mg_recon_wm')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = bican_recon_mg_markers_top50_gm), name = 'top_50_mg_recon_gm')

bican_recon_meta = bican_recon@meta.data
qsave(bican_recon_meta, "bican_recon_meta.qs")
```


```{r}
bican_recon_meta = qread("bican_recon_meta.qs")

bican_recon_meta
```

```{r}
spatial_scores_bican = function(metadata, column, title, updown = -1){
a = ggplot(metadata, aes(x= x_um_rotated, y = y_um_rotated, color = !!sym(column))) + geom_point(size =0.6) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = updown) +   labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ cell_class_annot)

metadata_neurons = subset(metadata, subset = cell_class_annot == "neuron" )
b = ggplot(metadata_neurons, aes(x= x_um_rotated, y = y_um_rotated, color = !!sym(column))) + geom_point(size = 0.6) + ggtitle(paste0(" ", title, " Scores"))+ scale_color_viridis_c(option = "magma", name = "Expression", direction = updown)+ labs(paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ reclustered_patch_matrix_exotic)

ggsave(a, filename = "pic1.png", width = 16, height = 12)
ggsave(b, filename = "pic2.png", width = 16, height = 8)
}

spatial_scores_xdp = function(metadata, column, title, updown = -1){
a = ggplot(metadata, aes(x= x_um, y = y_um, color = !!sym(column))) + geom_point(size =0.6) + ggtitle(paste0(" ", title, " Scores")) + scale_color_viridis_c(option = "magma", name = "Expression", direction = updown) +   labs(color = paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ new_final_cell_class)

metadata_neurons = subset(metadata, subset = new_final_cell_class == "neuron")
b = ggplot(metadata_neurons, aes(x= x_um, y = y_um, color = !!sym(column))) + geom_point(size = 0.6) + ggtitle(paste0(" ", title, " Scores"))+ scale_color_viridis_c(option = "magma", name = "Expression", direction = updown)+ labs(paste0(title," Scores")) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL) + facet_wrap(~ new_reclustered_patch_matrix_exotic)

ggsave(a, filename = "pic3.png", width = 14, height = 12)
ggsave(b, filename = "pic4.png", width = 12, height = 10)
}

histograms_by_all_celltype = function(final_df, score_col, colorby, xlab, width_size, height_size){

celltypes = unique(everything_metadata_new[["ALL_neuron_grouped_classes"]])  
plots <- list()

min = min(final_df[[score_col]])
max = max(final_df[[score_col]])
step = (max-min)/100

limits = seq(min, max, step)

for (celltype in celltypes) {
  df_sub = final_df[final_df$ALL_neuron_grouped_classes == celltype, ]
   
  if (nrow(df_sub) == 0) {
    message(paste("No data for cell type:", celltype, "- skipping."))
    next
  }
  

  a = plot_overlapping_density_histogram(df = df_sub, 
                                          hist_col = df_sub[[score_col]],
                                          fill_col = colorby,
                                          colors = Condition_colors,
                                          breaks = limits,
                                          title = paste0("XDP vs Control: ", celltype),
                                          xlab = xlab,
                                          fig_filename = NULL) 
  
    plots[[celltype]] = a
  
}

final_plot <- plot_grid(plotlist = plots, ncol = 4)

# Display or save the final plot
print(final_plot)  # Display
ggsave("combined_plot.png", final_plot, width = width_size, height = height_size)
}

histograms_by_donor <- function(final_df, score_col, celltype, colorby, xlab, width_size, height_size) {
  donor_order <- c("PCMC-16-011", "PCMC-16-012", "SCF-18-003", "SCF-18-004", "SCF-18-006", "SCF-19-009", "SCF-19-014", "SCF-19-018", "SCF-20-023", "SCF-20-025", "SCF_20-024", "SCF-21-030", "SCF_22-043", "SCF_21_027", "SCF_21_029", "SCF_21_032", "SCF_21_034", "SCF_21_038", "SCF_21_041", "SCF_23_070_MMC","SCF_21-037CM2",  "SCF-22-054CM", "SCF-23-068CM", "SCF-22-058CF","SCF_22_049CCF",  "SCF_22_063CM","SCF_22_065CM", "SCF_22_067CM", "SCF_23_072CF",  "SCF_23_074CF", "SCF_23_075CM", "SCF_23_079CF", "BICAN_donor")

  plots <- list()
  
  final_df_cellclass <- subset(final_df, ALL_neuron_grouped_classes == celltype)

  # Remove rows with NA values in the score column
  final_df_cellclass <- final_df_cellclass[!is.na(final_df_cellclass[[score_col]]), ]

  # Set common x-axis limits
  min_val <- min(final_df_cellclass[[score_col]], na.rm = TRUE)
  max_val <- max(final_df_cellclass[[score_col]], na.rm = TRUE)
  step <- (max_val - min_val) / 100
  limits <- seq(min_val, max_val, step)

  first_plot <- NULL
  for (donor in donor_order) {
    df_sub <- final_df_cellclass[final_df_cellclass$donor_id == donor, ]
    if (nrow(df_sub) == 0) {
      message(paste("No data for donor:", donor, "- skipping."))
      next
    }
    
    cell_count <- nrow(df_sub)

    # Create the plot, keep legend only for the first plot
    plot <- plot_overlapping_density_histogram(
      df = df_sub, 
      hist_col = df_sub[[score_col]],
      fill_col = colorby,
      colors = Condition_colors,
      breaks = limits,
      title = paste0(donor, ": (Cells: ", cell_count, ")"),
      xlab = xlab,
      fig_filename = NULL
    ) + theme(legend.position = "none")  # Removed ylim() to prevent warnings

    if (is.null(first_plot)) {
      first_plot <- plot  # Store first plot (which has a legend)
    }
    
    plots[[donor]] <- plot
  }

  if (length(plots) == 0) {
    stop("No valid plots were generated. Check if data exists for the specified cell type.")
  }

  # Extract legend from the first plot
  legend <- get_legend(first_plot)

  # Combine all plots without individual legends
  final_plot <- plot_grid(plotlist = plots, ncol = 6)

  # Add a big title at the top
  title_plot <- ggdraw() + draw_label(celltype, fontface = "bold", size = 16)

  # Arrange the final grid with the legend below and title on top
  final_plot_with_legend <- plot_grid(title_plot, final_plot, legend, ncol = 1, rel_heights = c(0.2, 4, 0.3))

  print(final_plot_with_legend)  
  ggsave("combined_plot.png", final_plot_with_legend, width = width_size, height = height_size)
}

wilcox_dot_plot = function(data, cell_class, score_col, colorby = "Cohort", ylab, titl){
  
df = subset(data, subset = ALL_neuron_grouped_classes == cell_class)
df
print(df)
df_avg <- df %>%
  group_by(donor_id, Condition, Cohort) %>%
  summarise(avg_score = mean(.data[[score_col]]), .groups = 'drop')
df_avg
print(df_avg)

cases = subset(df, Condition == "XDP")
controls = subset(df, Condition == "Control")

print(XDP_scores)
print(XDP_Control_scores)

XDP_scores <- cases[[score_col]]
XDP_Control_scores <-controls[[score_col]]


result1 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "less")
result3 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "greater")

print(result1)
print(result2)
print(result3)

if (result2$p.value  < 0.05) {
  finalresult <- result2$p.value
finalresult <- ifelse(finalresult < 2.2e-16, "< 2.2e-16", formatC(pval, format = "e", digits = 3))
finalresultlab = (paste("p-value:", finalresult))

} else if (result3$p.value  < 0.05) {
    finalresult <- result3$p.value
finalresult <- ifelse(finalresult < 2.2e-16, "< 2.2e-16", formatC(pval, format = "e", digits = 3))
finalresultlab= (paste("p-value:", finalresult))
  
} else{
  finalresultlab = "p-value: NS"
}

# Plot the average score per donor for each condition
a = ggplot(df_avg, aes(x = Condition, y = avg_score, color = df_avg[[colorby]], shape = Cohort)) +
  geom_point(aes(group = donor_id), size = 3, alpha = 0.8) + scale_color_manual(values = rev(scales::hue_pal()(3)))+ # One point per donor
  labs(x = "Condition", y = paste0("Mean ", ylab), color = colorby, shape = "Cohort", title =paste0(titl, ", wilcox ", finalresultlab))+ scale_shape_manual(values = rev(c(16, 17, 18))) +
  theme_minimal()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 14),  # Increase tick label font size
            axis.title = element_text(size = 15),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1)  # tilt axis labels
        )+
  theme(
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18),  # Increase legend title size
   # legend.key.size = unit(1.5, "cm")  # Increase legend key size
  ) 

print(a)

ggsave(a, filename = "dotplot.png", width = 7, height = 6)

}
```

```{r}
spatial_scores_bican(bican_recon_meta, "Scoretop_50_mg_recon_gm", "Scoretop_50_mg_recon_gm")
```

```{r}
bican_recon_meta
```

```{r}
bican_recon= AddMetaData(bican_recon, metadata = bican_recon_meta)
bican_recon@meta.data
```
```{r}
a= FeaturePlot(bican_recon, features = c("Scorefiltered_mg_recon_wm", "Scoretop_50_mg_recon_wm", "Scoretop_50_mg_recon_gm"), raster = F, label = T)
ggsave(a, filename= "pic.png", width = 15, height =10)
```


```{r}
FeaturePlot(bican_recon, features = c("Scorefiltered_astro_recon_wm", "Scorefiltered_astro_recon_gm", "Scoretop_50_astro_recon_wm", "Scoretop_50_astro_recon_gm"), raster = F, label = T)

FeaturePlot(bican_recon, features = c("Scorefiltered_opc_recon_wm", "Scorefiltered_opc_recon_gm", "Scoretop_50_opc_recon_wm", "Scoretop_50_opc_recon_gm"), raster = F, label = T)

FeaturePlot(bican_recon, features = c("Scorefiltered_oligo_recon_wm", "Scoretop_50_oligo_recon_wm", "Scoretop_50_oligo_recon_gm"), raster = F, label = T)

FeaturePlot(bican_recon, features = c("Scorefiltered_mg_recon_wm", "Scoretop_50_mg_recon_wm", "Scoretop_50_mg_recon_gm"), raster = F, label = T)
```



```{r}
xdp_co12 = qread("/broad/macosko/kimkathl/XDP_Cohorts_1_2_full_032825.qs")
```


```{r}
xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'top_50_astro_recon_wm')
xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_astro_markers_top50_gm), name = 'top_50_astro_recon_gm')

xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_opc_markers_top50_wm), name = 'top_50_opc_recon_wm')
xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_opc_markers_top50_gm), name = 'top_50_opc_recon_gm')

xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_oligo_markers_top50_wm), name = 'top_50_oligo_recon_wm')
xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_oligo_markers_top50_gm), name = 'top_50_oligo_recon_gm')

xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_mg_markers_top50_wm), name = 'top_50_mg_recon_wm')
xdp_co12 <- AddModuleScore_UCell(xdp_co12, features = list(Score = bican_recon_mg_markers_top50_gm), name = 'top_50_mg_recon_gm')

xdp_co12_meta = xdp_co12@meta.data
qsave(xdp_co12_meta, "xdp_co12_meta.qs")

rm(xdp_co12)
gc()


xdp_recon = qread("/broad/macosko/kimkathl/xdp_recon_apr2025_sct_mask.qs")

xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'top_50_astro_recon_wm')
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_astro_markers_top50_gm), name = 'top_50_astro_recon_gm')

xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_opc_markers_top50_wm), name = 'top_50_opc_recon_wm')
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_opc_markers_top50_gm), name = 'top_50_opc_recon_gm')

xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_oligo_markers_top50_wm), name = 'top_50_oligo_recon_wm')
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_oligo_markers_top50_gm), name = 'top_50_oligo_recon_gm')

xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_mg_markers_top50_wm), name = 'top_50_mg_recon_wm')
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = bican_recon_mg_markers_top50_gm), name = 'top_50_mg_recon_gm')

xdp_recon_meta = xdp_recon@meta.data
qsave(xdp_recon_meta, "xdp_recon_meta.qs")

```




```{r}
bican_recon_meta
xdp_recon_meta
xdp_co12_meta
```

```{r}
spatial_scores_xdp(xdp_recon_meta, "Scoretop_50_mg_recon_gm", "Scoretop_50_mg_recon_gm")
```

```{r}
xdp_recon= AddMetaData(xdp_recon, metadata = xdp_recon_meta)
xdp_recon@meta.data
```

```{r}
a= FeaturePlot(xdp_recon, features = c("Scoretop_50_oligo_recon_wm", "Scoretop_50_oligo_recon_gm","Scoretop_50_mg_recon_wm", "Scoretop_50_mg_recon_gm"), raster = F, label = T)
ggsave(a, filename= "pic.png", width = 15, height =10)
```


```{r}
FeaturePlot(xdp_recon, features = c("Scoretop_50_astro_recon_wm", "Scoretop_50_astro_recon_gm","Scoretop_50_opc_recon_wm", "Scoretop_50_opc_recon_gm"), raster = F, label = T)
FeaturePlot(xdp_recon, features = c("Scoretop_50_oligo_recon_wm", "Scoretop_50_oligo_recon_gm","Scoretop_50_mg_recon_wm", "Scoretop_50_mg_recon_gm"), raster = F, label = T)
```
















```{r}
histograms_by_all_celltype(everything_metadata_new, "antigen_processing_scores", "Cohort_Condition","Antigen Processing Score", 20, 12)
```


```{r}
histograms_by_all_celltype(Control_scores, "antigen_processing_scores", "Cohort_Condition","Antigen Processing Score", 20, 12)
```

```{r}
histograms_by_donor(everything_metadata_new_fixed, "antigen_processing_scores", "astrocyte" ,"Cohort_Condition", "Antigen Processing Score", 28,20)

wilcox_dot_plot(everything_metadata_new_fixed, "astrocyte","antigen_processing_scores", colorby = "Cohort", ylab = "Antigen Processing Score", titl= "Astrocyte")
```

























```{r}
DimPlot(bican_recon, group.by = "WM_GM", raster = F)
FeaturePlot(bican_recon, features = c("WIF1", "TNC"), raster = F) #best astro
FeaturePlot(bican_recon, features = c("CDH19", "MIR3681HG", "ENSG00000286778", "LNX1"), raster = F) #opc (1WM and 3 GM)
FeaturePlot(bican_recon, features = c("ACTN2", "HSPA1A"), raster = F) #oligo, both WM
FeaturePlot(bican_recon, features = c("MIR9-1HG", "EGR1"), raster = F) #endo, both GM
FeaturePlot(bican_recon, features = c("DNAJB1"), raster = F) #mg, WM
```

```{r}
Idents(bican_recon) = "WM_GM"
markers = FindAllMarkers(bican_recon, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1.25)
markers_filtered = subset(markers, subset = pct.1 > 0.7)
markers_filtered
markers_filtered_2 = subset(markers_filtered, subset = pct.2 < 0.3)
markers_filtered_2


markers
markers_filtered
markers_filtered_2
```

```{r}
FeaturePlot(bican_recon, features = c("PIEZO2", "LRP2", "ESRRG", "ARPP21"), raster = F) #all WM vs GM, both WM markers
#mostly just looks like for oligos tbh

features = c("PIEZO2", "LRP2", "ESRRG", "ARPP21")
for (gene in features) {
  print(spatial_gene_expression(bican_recon, gene))
}

```

```{r}
ggplot(bican_recon@meta.data, aes(x = x_um, y = y_um, color = WM_GM )) + geom_point(size =0.1, alpha = 0.5) +facet_wrap(~ cell_class_annot)
```

#tried doing top 50 genes for white and gray matter from findallmarkers output for all white matter vs all gray matter but it's not very effective. It seems that the WM score is just oligos and GM score is just neurons. Other cell classes don't do very well.  
```{r}
markers

white_matter_genes = markers %>% filter(cluster == "White_Matter")
length(white_matter_genes)
gray_matter_genes = markers %>% filter(cluster == "Gray_Matter")
length(gray_matter_genes)

white_top <- white_matter_genes %>% top_n(50, wt = avg_log2FC)
gray_top <- gray_matter_genes %>% top_n(50, wt = avg_log2FC)

white_top_genes = rownames(white_top)
gray_top_genes = rownames(gray_top)

library(UCell)
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = gray_top_genes), name = 'All_GM')
bican_recon <- AddModuleScore_UCell(bican_recon, features = list(Score = white_top_genes), name = 'All_WM')
bican_recon@meta.data

ggplot(bican_recon@meta.data, aes(x= x_um, y = y_um, color = ScoreAll_WM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "WM Score") +  theme_void() + ylab(NULL)+ facet_wrap(~ cell_class_annot)

ggplot(bican_recon@meta.data, aes(x= x_um, y = y_um, color = ScoreAll_GM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "GM Score") +  theme_void() + ylab(NULL) + facet_wrap(~ cell_class_annot)

```






#no shared genes tbh
```{r}
bican_recon_astro_markers$cell_class = "astrocyte"
bican_recon_opc_markers$cell_class = "opc"
bican_recon_oligo_markers$cell_class = "oligo"
bican_recon_mg_markers$cell_class = "microglia"

shared_WM_GM_markers = intersect(rownames(bican_recon_astro_markers), rownames(bican_recon_opc_markers))
shared_WM_GM_markers
bican_recon_astro_markers[rownames(bican_recon_astro_markers) %in% shared_WM_GM_markers, ]
bican_recon_opc_markers[rownames(bican_recon_opc_markers) %in% shared_WM_GM_markers, ]

for (gene in shared_WM_GM_markers) {
  print(spatial_gene_expression(bican_recon, gene))
}

```


```{r}
shared_WM_GM_markers = intersect(rownames(bican_recon_astro_markers), rownames(bican_recon_mg_markers))
shared_WM_GM_markers
bican_recon_astro_markers[rownames(bican_recon_astro_markers) %in% shared_WM_GM_markers, ]
bican_recon_mg_markers[rownames(bican_recon_mg_markers) %in% shared_WM_GM_markers, ]

shared_WM_GM_markers = intersect(rownames(bican_recon_astro_markers), rownames(bican_recon_oligo_markers))
shared_WM_GM_markers
bican_recon_astro_markers[rownames(bican_recon_astro_markers) %in% shared_WM_GM_markers, ]
bican_recon_oligo_markers[rownames(bican_recon_oligo_markers) %in% shared_WM_GM_markers, ]

shared_WM_GM_markers = intersect(rownames(bican_recon_opc_markers), rownames(bican_recon_oligo_markers))
shared_WM_GM_markers
bican_recon_opc_markers[rownames(bican_recon_opc_markers) %in% shared_WM_GM_markers, ]
bican_recon_oligo_markers[rownames(bican_recon_oligo_markers) %in% shared_WM_GM_markers, ]
```

