---
title: "R Notebook"
output: html_notebook
---

```{r}
markers_filtered_2
```

```{r}
WM_astro_markers = c("TNC", "DCLK1", "ADAMTSL3", "SLC24A4", "GRIK4", "DLGAP1") #"ENSG00000287704", 
GM_astro_markers = c("WIF1", "SLIT1",  "TMEM132C", "PTCH1") #"MIAT", "ENSG00000287544",LINC00499
```


```{r}
#XDP_Cohorts_1_2_full= qread("XDP_Cohorts_1_2_full_032825.qs")
XDP_Cohorts_1_2_full@meta.data
XDP_astro_Cohorts_1_2 = subset(XDP_Cohorts_1_2_full, subset = final_cell_class_merged_harmony == "astrocyte")
XDP_astro_Cohorts_1_2
```

```{r}
XDP_astro_Cohorts_1_2 <- AddModuleScore_UCell(XDP_astro_Cohorts_1_2, features = list(Score = WM_astro_markers), name = 'WM')
XDP_astro_Cohorts_1_2 <- AddModuleScore_UCell(XDP_astro_Cohorts_1_2, features = list(Score = GM_astro_markers), name = 'GM')
XDP_astro_Cohorts_1_2 <- AddModuleScore_UCell(XDP_astro_Cohorts_1_2, features = list(Score = c("WIF1")), name = 'WIF1')
XDP_astro_Cohorts_1_2 <- AddModuleScore_UCell(XDP_astro_Cohorts_1_2, features = list(Score = c("TNC")), name = 'TNC')
XDP_astro_Cohorts_1_2@meta.data

XDP_astro_Cohorts_1_2_WMGM = select(XDP_astro_Cohorts_1_2@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC"))

FeaturePlot(XDP_Cohorts_1_2_full, features = c("WIF1", "TNC", "ScoreNFKB"), raster = F)
FeaturePlot(XDP_astro_Cohorts_1_2, features = c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC"), raster = F)
```

```{r}
XDP_astro_Cohorts_1_2_WMGM
```
```{r}
rm(XDP_Cohorts_1_2_full)
gc()
```


```{r}
xdp_recon = qread("xdp_recon_full_mar2025.qs")
xdp_recon@meta.data

xdp_recon_meta = xdp_recon@meta.data
```


```{r}
xdp_recon_astrocyte = subset(xdp_recon, subset =new_cell_class == "astrocyte")
xdp_recon_astrocyte
```
```{r}
xdp_recon_astrocyte <- AddModuleScore_UCell(xdp_recon_astrocyte, features = list(Score = WM_astro_markers), name = 'WM')
xdp_recon_astrocyte <- AddModuleScore_UCell(xdp_recon_astrocyte, features = list(Score = GM_astro_markers), name = 'GM')
xdp_recon_astrocyte <- AddModuleScore_UCell(xdp_recon_astrocyte, features = list(Score = c("WIF1")), name = 'WIF1')
xdp_recon_astrocyte <- AddModuleScore_UCell(xdp_recon_astrocyte, features = list(Score = c("TNC")), name = 'TNC')
xdp_recon_astrocyte@meta.data
```

```{r}
ggplot(xdp_recon_astrocyte@meta.data, aes(x= x_um, y = y_um, color = ScoreGM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "GM Score") +  theme_void() + ylab(NULL) 

```

```{r}
xdp_recon_astrocyte_WMGM = select(xdp_recon_astrocyte@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC"))
xdp_recon_astrocyte_WMGM
```

```{r}
FeaturePlot(xdp_recon, features = c("WIF1", "TNC"), raster = F)
```

```{r}
rm(xdp_recon)
gc()
```


```{r}
bican_recon = qread("bican_recon_mar2025_sct.qs")
bican_recon_astrocyte = subset(bican_recon, subset =cell_class_annot == "astro")
bican_recon_astrocyte
```
```{r}
1+1
```


```{r}
bican_recon_astrocyte <- AddModuleScore_UCell(bican_recon_astrocyte, features = list(Score = WM_astro_markers), name = 'WM')
bican_recon_astrocyte <- AddModuleScore_UCell(bican_recon_astrocyte, features = list(Score = GM_astro_markers), name = 'GM')
bican_recon_astrocyte <- AddModuleScore_UCell(bican_recon_astrocyte, features = list(Score = c("WIF1")), name = 'WIF1')
bican_recon_astrocyte <- AddModuleScore_UCell(bican_recon_astrocyte, features = list(Score = c("TNC")), name = 'TNC')
bican_recon_astrocyte@meta.data

bican_recon_astrocyte_WMGM = select(bican_recon_astrocyte@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC"))
bican_recon_astrocyte_WMGM
```

```{r}
ggplot(bican_recon_astrocyte@meta.data, aes(x= x_um, y = y_um, color = ScoreWM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "WM Score") +  theme_void() + ylab(NULL) 

```


```{r}
FeaturePlot(bican_recon, features = c("WIF1", "TNC"))
```

```{r}
xdp_recon_meta
everything_metadata_new
```


```{r}
xdp_recon_meta$wonk_ass_id = paste0(xdp_recon_meta$nCount_RNA, "_", xdp_recon_meta$nFeature_RNA, "_", xdp_recon_meta$donor_id, "_", xdp_recon_meta$C_minus_scores, "_", xdp_recon_meta$C_plus_scores, "_", xdp_recon_meta$antigen_processing_scores, "_", xdp_recon_meta$percent.mt)
head(xdp_recon_meta$wonk_ass_id)

everything_metadata_new$wonk_ass_id = paste0(everything_metadata_new$nCount_RNA, "_", everything_metadata_new$nFeature_RNA, "_", everything_metadata_new$donor_id, "_", everything_metadata_new$C_minus_scores, "_", everything_metadata_new$C_plus_scores, "_", everything_metadata_new$antigen_processing_scores, "_", everything_metadata_new$percent.mt)
head(everything_metadata_new$wonk_ass_id)
head(xdp_recon_meta$wonk_ass_id)
```

```{r}
xdp_recon_meta$cell_id = rownames(xdp_recon_meta)
everything_metadata_new_xdp_recon_fix = subset(everything_metadata_new, subset = Cohort_Condition == "Recon_XDP")
everything_metadata_new_xdp_recon_fix
```

```{r}
everything_metadata_new_xdp_recon_fix = left_join(xdp_recon_meta, everything_metadata_new_xdp_recon_fix, by = "wonk_ass_id")
everything_metadata_new_xdp_recon_fix
```
```{r}
everything_metadata_new_xdp_recon_fix_names = select(everything_metadata_new_xdp_recon_fix, c("wonk_ass_id", "cell_id.x"))
everything_metadata_new_xdp_recon_fix_names$cell_id = everything_metadata_new_xdp_recon_fix_names$cell_id.x
everything_metadata_new_xdp_recon_fix_names$cell_id.x = NULL
everything_metadata_new_xdp_recon_fix_names
```

```{r}
everything_metadata_new = read.csv("everything_metadata_new.csv", header = T)
everything_metadata_new
everything_metadata_new$cell_id = everything_metadata_new$X
rownames(everything_metadata_new) = everything_metadata_new$cell_id 
everything_metadata_new
everything_metadata_new_xdp_recon_fix_names
```


```{r}
everything_metadata_new_fixed = merge(everything_metadata_new, everything_metadata_new_xdp_recon_fix_names, by = "wonk_ass_id", all = T)
everything_metadata_new_fixed
```
```{r}
everything_metadata_new_fixed$cell_id_new = coalesce(everything_metadata_new_fixed$cell_id.y, everything_metadata_new_fixed$cell_id.x)
everything_metadata_new_fixed$cell_id.x = NULL
everything_metadata_new_fixed$cell_id.y = NULL
rownames(everything_metadata_new_fixed) = everything_metadata_new_fixed$cell_id_new
everything_metadata_new_fixed
```





```{r}
bican_recon_astrocyte@meta.data$library = "BICAN_Recon"
bican_recon_astrocyte@meta.data$cell = bican_recon_astrocyte$cb
xdp_recon_astrocyte@meta.data$library = "XDP_Recon"
xdp_recon_astrocyte@meta.data$cell = xdp_recon_astrocyte$cb

bican_recon_astrocyte@meta.data
xdp_recon_astrocyte@meta.data
XDP_astro_Cohorts_1_2@meta.data
```

```{r}
bican_recon_astrocyte_WMGM = select(bican_recon_astrocyte@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC", "library", "cell"))
xdp_recon_astrocyte_WMGM = select(xdp_recon_astrocyte@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC","library", "cell"))
XDP_astro_Cohorts_1_2_WMGM = select(XDP_astro_Cohorts_1_2@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC","library", "cell"))

bican_recon_astrocyte_WMGM
xdp_recon_astrocyte_WMGM
XDP_astro_Cohorts_1_2_WMGM
```


```{r}
WMGM_all = rbind(XDP_astro_Cohorts_1_2_WMGM, bican_recon_astrocyte_WMGM, xdp_recon_astrocyte_WMGM)
WMGM_all
```


```{r}
WMGM_all$cell_id = paste0(WMGM_all$library, "___",  WMGM_all$cell)
WMGM_all
#qsave(WMGM_all, "WMGM_all.qs")
```

```{r}
WMGM_all[is.na(WMGM_all$ScoreWM),]
```




```{r}
everything_metadata$cell_id = rownames(everything_metadata)
everything_metadata_new = left_join(everything_metadata, WMGM_all, 
                      by = "cell_id")
everything_metadata_new

rownames(everything_metadata_new) = everything_metadata_new$cell_id
everything_metadata_new
```

```{r}
everything_metadata_new$Condition[everything_metadata_new$Condition == "Control_BICAN"] = "Control"
everything_metadata_new$Condition[everything_metadata_new$Condition == "XDP_18_006"] = "XDP"

everything_metadata_new$Cohort[everything_metadata_new$Cohort == "Control_BICAN"] = "Recon"
everything_metadata_new$Cohort[everything_metadata_new$Cohort == "XDP_18_006"] = "Recon"


everything_metadata_new$Cohort_Condition = paste0(everything_metadata_new$Cohort, "_", everything_metadata_new$Condition)
table(everything_metadata_new$Cohort_Condition)

```

```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 
newdf = subset(df, subset = Condition == "Control")
newdf
```






```{r}
table(newdf$Cohort_Condition)
```







```{r}
table(newdf$Cohort_Condition)
```

```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 

min = min(newdf$ScoreNFKB)
max = max(newdf$ScoreNFKB)
step = (max-min)/100

limits = seq(min, max, step)

 a= plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreNFKB,
                                          fill_col = "Cohort_Condition",
                                  colors = c("Cohort_1_XDP" = "red", "Cohort_2_XDP" = "orange", "Recon_XDP" = "pink", "Cohort_1_Control" = "blue","Cohort_2_Control" = "cyan", "Recon_Control" = "green"),
                                          breaks = limits,
                                          title = "Control Astrocytes",
                                          xlab = "NFKB Score",
                                          fig_filename = NULL) + facet_wrap(~ Cohort_Condition)
 print(a)
 ggsave(a, filename = "a.png", width = 8, height = 5)
```



```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 

regions = unique(newdf$CAP_Region)

for (region in regions) {
  
new_df =subset(newdf, subset = CAP_Region == region) 

min = min(new_df$ScoreNFKB)
max = max(new_df$ScoreNFKB)
step = (max-min)/100

limits = seq(min, max, step)

 a= plot_overlapping_density_histogram(df = new_df, 
                                          hist_col = new_df$ScoreNFKB,
                                          fill_col = "Cohort_Condition",
                                  colors = c("Cohort_1_XDP" = "red", "Cohort_2_XDP" = "orange", "Recon_XDP" = "pink", "Cohort_1_Control" = "blue","Cohort_2_Control" = "cyan", "Recon_Control" = "green"),
                                          breaks = limits,
                                          title = paste0("Astrocytes, ", region),
                                          xlab = "NFKB Score",
                                          fig_filename = NULL) + facet_wrap(~ Cohort_Condition)
 print(a)
 ggsave(a, filename = paste0(region, ".png"), width = 8, height = 5)
}

```







```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf
newdf = subset(everything_metadata_new, subset = Condition == "Control")
newdf

min = 0
max = 1
step = (max-min)/100

limits = seq(min, max, step)

 a= plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreGM,
                                          fill_col = "Cohort_Condition",
                                  colors = c("Cohort_1_XDP" = "red", "Cohort_2_XDP" = "orange", "Recon_XDP" = "pink", "Cohort_1_Control" = "blue","Cohort_2_Control" = "cyan", "Recon_Control" = "green"),
                                          breaks = limits,
                                          title = "Control Astrocytes",
                                          xlab = "GM Score",
                                          fig_filename = NULL) + facet_wrap(~ Cohort_Condition) + ylim(0,10)
 print(a)
 ggsave(a, filename = "a.png", width = 12, height = 4)
```



```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 
newdf = subset(everything_metadata_new, subset = Condition == "Control")
newdf

regions = unique(newdf$CAP_Region)

for (region in regions) {
  
new_df =subset(newdf, subset = CAP_Region == region) 

min = 0
max = 1
step = (max-min)/100

limits = seq(min, max, step)

 a= plot_overlapping_density_histogram(df = new_df, 
                                          hist_col = new_df$ScoreGM,
                                          fill_col = "Cohort_Condition",
                                  colors = c("Cohort_1_XDP" = "red", "Cohort_2_XDP" = "orange", "Recon_XDP" = "pink", "Cohort_1_Control" = "blue","Cohort_2_Control" = "cyan", "Recon_Control" = "green"),
                                          breaks = limits,
                                          title = paste0("Astrocytes, ", region),
                                          xlab = "GM Score",
                                          fig_filename = NULL) + facet_wrap(~ Cohort_Condition) + ylim(0,10)
 print(a)
 ggsave(a, filename = paste0(region, ".png"), width = 8, height = 5)
}
```














```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 
newdf = subset(df, subset = Condition == "Control")
newdf

min = 0
max = 1
step = (max-min)/100

limits = seq(min, max, step)

 a = plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreGM,
                                          fill_col = "CAP_Region",
                                    colors = c("Caudate" = "red", "Putamen" = "green", "Nucleus_Accumbens" = "orange", "Internal_Capsule" = "blue"),
                                          breaks = limits,
                                          title = "Control Astrocytes",
                                          xlab = "GM Score",
                                          fig_filename = NULL) + facet_wrap(~ Cohort)
 
  ggsave(a, filename = "a.png", width = 12, height = 4)
```


```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 
newdf = subset(df, subset = Condition == "Control")
newdf

min = min(new_df$ScoreNFKB)
max = max(new_df$ScoreNFKB)
step = (max-min)/100

limits = seq(min, max, step)

 a = plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreNFKB,
                                          fill_col = "GM_WM_IC",
                                    colors = c("Gray_Matter" = "red", "s" = "orange", "RECON_XDP_18_006" = "pink", "White_Matter" = "blue","Cohort_2_Control" = "cyan", "Internal_Capsule" = "green"),
                                          breaks = limits,
                                          title = "Control Astrocytes",
                                          xlab = "NFKB Score",
                                          fig_filename = NULL) + facet_wrap(~ GM_WM_IC)
   ggsave(a, filename = "a.png", width = 12, height = 6)
```


```{r}
newdf = subset(everything_metadata_new, subset = ALL_final_cell_class == "astrocyte")
newdf 
newdf = subset(df, subset = Condition == "Control")
newdf

min = 0
max = 1
step = (max-min)/100

limits = seq(min, max, step)

 a = plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreWM,
                                          fill_col = "Cohort",
                                    colors = c("Cohort_1" = "red", "s" = "orange", "RECON_XDP_18_006" = "pink", "Cohort_2" = "blue","Cohort_2_Control" = "cyan", "Recon" = "green"),
                                          breaks = limits,
                                          title = "Control Astrocytes",
                                          xlab = "WM Score",
                                          fig_filename = NULL) +facet_wrap(~ CAP_Region)+ ylim(0, 10)
    ggsave(a, filename = "a.png", width = 12, height = 6)
```


```{r}


 a = plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreGM,
                                          fill_col = "Cohort",
                                    colors = c("Cohort_1" = "red", "s" = "orange", "RECON_XDP_18_006" = "pink", "Cohort_2" = "blue","Cohort_2_Control" = "cyan", "Recon" = "green"),
                                          breaks = limits,
                                          title = "Control Astrocytes",
                                          xlab = "GM Score",
                                          fig_filename = NULL) +facet_wrap(~ CAP_Region) + ylim(0, 10)
    ggsave(a, filename = "a.png", width = 12, height = 6)
```
 


```{r}
regions = unique(df$CAP_Region)

for (region in regions) {
  
new_df =subset(df, subset = CAP_Region == region) 
new_df
xlab = "ScoreNFKB"
min = min(new_df$ScoreNFKB)
max = max(new_df$ScoreNFKB)
step = (max-min)/100

limits = seq(min, max, step)
  
a = plot_overlapping_density_histogram(df = new_df, 
                                          hist_col = new_df$ScoreNFKB,
                                          fill_col = "Cohort_Condition",
                                    colors = c("Cohort_1_XDP" = "red", "Cohort_2_XDP" = "orange", "RECON_XDP_18_006" = "pink", "Cohort_1_Control" = "blue","Cohort_2_Control" = "cyan", "RECON_Control_BICAN" = "green"),
                                          breaks = limits,
                                          title = paste0(region),
                                          xlab = xlab,
                                          fig_filename = NULL) +facet_wrap(~ Cohort_Condition)
  
  

# Display or save the final plot
print(a)
#ggsave("combined_plot.png", a, width = 7, height =5 )
}
```

```{r}
XDP_Cohorts_1_2_full = qread("XDP_Cohorts_1_2_full_032825.qs")

FeaturePlot(XDP_Cohorts_1_2_full, features = c("WIF1", "TNC"))
```


```{r}
ggplot(bican_recon_astrocyte@meta.data, aes(x= x_um, y = y_um, color = ScoreWM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "WM Score") +  theme_void() + ylab(NULL) 

```

