---
title: "R Notebook"
output: html_notebook
---

```{r}
Recon_opc = qread("temphome/RECON/Recon_opc.qs")
Recon_oligo = qread("temphome/RECON/Recon_oligo.qs")
Recon_micro = qread("temphome/RECON/Recon_microglia.qs")
Recon_ependymal = qread("temphome/RECON/Recon_ependymal.qs")
Recon_endo = qread("temphome/RECON/Recon_endo.qs")
Recon_astrocyte = qread("temphome/RECON/Recon_astrocyte.qs")
Recon_neuron_subclustered = qread("RECON_neuron_subclustered_102824.qs")
```

```{r}
Recon_endo@meta.data
DimPlot(Recon_endo, label = T)
DimPlot(Recon_endo, label = T, group.by = "RNA_snn_res.0.3")
```

```{r}
Recon_endo = subset(Recon_endo, subset = RNA_snn_res.0.3 !="3")
DimPlot(Recon_endo, label = T)
DimPlot(Recon_endo, label = T, group.by = "RNA_snn_res.0.3")
```
```{r}
Recon_neuron_subclustered@meta.data
```


```{r}
Recon_neuron_subclustered$C_minusUCELL = NULL
Recon_neuron_subclustered$C_plusUCELL= NULL
Recon_neuron_subclustered$matrix_markersUCELL= NULL
Recon_neuron_subclustered$D_genesUCELL= NULL
Recon_neuron_subclustered$MMRUCELL= NULL
Recon_neuron_subclustered$BERUCELL= NULL
Recon_neuron_subclustered$signature_1UCELL= NULL
Recon_neuron_subclustered$MSH2UCELL= NULL
Recon_neuron_subclustered$MSH3UCELL= NULL
Recon_neuron_subclustered$nCount_SCT = NULL
Recon_neuron_subclustered$nFeature_SCT = NULL
```


```{r}
Idents(Recon_neuron_subclustered) = "final_cell_class"
Recon_neuron_subclustered
DimPlot(Recon_neuron_subclustered)
```

```{r}
DefaultAssay(Recon_neuron_subclustered) = "RNA"
Recon_neuron_subclustered[["SCT"]] = NULL
Recon_neuron_subclustered
```
```{r}
Recon_opc@meta.data$final_cell_class = Recon_opc$subclass
Recon_oligo@meta.data$final_cell_class = Recon_oligo$subclass
Recon_micro@meta.data$final_cell_class = Recon_micro$subclass
Recon_ependymal@meta.data$final_cell_class = Recon_ependymal$subclass
Recon_astrocyte@meta.data$final_cell_class = Recon_astrocyte$subclass
Recon_endo@meta.data$final_cell_class = Recon_endo$subclass

table(Recon_micro$final_cell_class)
Recon_micro$final_cell_class[Recon_micro$final_cell_class == "immune"] = "microglia"
table(Recon_micro$final_cell_class)
```
```{r}
Recon_opc@meta.data$reclustered_patch_matrix_exotic = Recon_opc$final_cell_class
Recon_oligo@meta.data$reclustered_patch_matrix_exotic = Recon_oligo$final_cell_class
Recon_micro@meta.data$reclustered_patch_matrix_exotic = Recon_micro$final_cell_class
Recon_ependymal@meta.data$reclustered_patch_matrix_exotic = Recon_ependymal$final_cell_class
Recon_astrocyte@meta.data$reclustered_patch_matrix_exotic = Recon_astrocyte$final_cell_class
Recon_endo@meta.data$reclustered_patch_matrix_exotic = Recon_endo$final_cell_class
```


```{r}
sobj_list = list(Recon_neuron_subclustered, Recon_opc, Recon_oligo, Recon_micro, Recon_ependymal, Recon_astrocyte, Recon_endo)
sobj_list
```

#create sobj
```{r}
counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))
counts_list
```

```{r}
merged_counts <- do.call(cbind, counts_list)
merged_counts
```

```{r}
metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)
metadata_list
```

```{r}
merged_metadata <- do.call(rbind, metadata_list)
merged_metadata
```

```{r}
stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))
```

```{r}
# Create Seurat object
clean_recon_sobj_with_neuron_subclusters <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
clean_recon_sobj_with_neuron_subclusters
```

```{r}
n_dims_use=20

clean_recon_sobj_with_neuron_subclusters = (clean_recon_sobj_with_neuron_subclusters
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.1) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
clean_recon_sobj_with_neuron_subclusters

clean_recon_sobj_with_neuron_subclusters@meta.data
```

```{r}
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "subclass", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "reclustered_patch_matrix_exotic", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "final_cell_class", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.2", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.3", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.4", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.5", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.6", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.7", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.8", raster = F, label = T)
```

```{r}
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("OLIG1", "MOG", "MOBP"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(clean_recon_sobj_with_neuron_subclusters, features = c("logumi", "percent.mt"),raster=FALSE)
```

```{r}
table(clean_recon_sobj_with_neuron_subclusters$final_cell_class)
table(clean_recon_sobj_with_neuron_subclusters$RNA_snn_res.0.2)
```
```{r}
ggplot(clean_recon_sobj_with_neuron_subclusters@meta.data, aes(x= x_um, y = y_um, color = final_cell_class)) + geom_point(alpha = 0.2, size = 0.2) + facet_wrap(~ final_cell_class) +theme_void()

ggplot(clean_recon_sobj_with_neuron_subclusters@meta.data, aes(x= x_um, y = y_um, color = RNA_snn_res.0.2)) + geom_point(alpha = 0.2, size = 0.2) + facet_wrap(~ RNA_snn_res.0.2) +theme_void()
```
```{r}
clean_recon_sobj_with_neuron_subclusters@meta.data
```

```{r}
Idents(clean_recon_sobj_with_neuron_subclusters) = "final_cell_class"
DimPlot(clean_recon_sobj_with_neuron_subclusters, raster = F)
```


```{r}
qsave(clean_recon_sobj_with_neuron_subclusters, "temphome/RECON/clean_recon_sobj_with_neuron_subclusters_103124.qs")
```


#change one ependymal to astrocyte
```{r}
clean_recon_sobj
clean_recon_sobj_with_neuron_subclusters = qread("temphome/RECON/clean_recon_sobj_with_neuron_subclusters_103124.qs")
clean_recon_sobj_with_neuron_subclusters
```
```{r}
table(clean_recon_sobj_with_neuron_subclusters$final_cell_class)
```


```{r}
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "final_cell_class", raster = F, label = T)
DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "RNA_snn_res.0.2", raster = F, label = T)
```



```{r}
Idents(clean_recon_sobj_with_neuron_subclusters) = clean_recon_sobj_with_neuron_subclusters$RNA_snn_res.0.2

classes = c("oligo", "astrocyte", "neuron", "microglia", "neuron", "opc", "oligo", "endothelial", "neuron", "astrocyte", "neuron", "neuron", "ependymal", "neuron", "neuron", "neuron", "neuron")


clean_recon_sobj_with_neuron_subclusters= assignCellClasses(clean_recon_sobj_with_neuron_subclusters, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "new_cell_class")

DimPlot(clean_recon_sobj_with_neuron_subclusters, group.by = "new_cell_class" ,label = T, raster = FALSE)
```
```{r}
marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6", "AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12", "FLT1", "DCN", "RGS5","OLIG1", "MOG", "MOBP","OLIG2", "VCAN", "ZBBX", "CFAP157", "CFAP299", "BSG", "CD96")


Dotplot = DotPlot(object = clean_recon_sobj_with_neuron_subclusters, features = marker_genes, group.by = "new_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
table(clean_recon_sobj_with_neuron_subclusters$new_cell_class)
```

```{r}
ggplot(clean_recon_sobj_with_neuron_subclusters@meta.data, aes(x= x_um, y = y_um, color = new_cell_class)) + geom_point(alpha = 0.2, size = 0.4) + facet_wrap(~ new_cell_class) +theme_void() + theme(
    plot.title = element_text(size = 20),
    plot.subtitle = element_text(size = 20),
    strip.text = element_text(size = 20),
    plot.background = element_rect(fill = "white", color = NA))
```
```{r}
clean_recon_sobj_with_neuron_subclusters
```
```{r}
qsave(clean_recon_sobj_with_neuron_subclusters, "temphome/RECON/clean_recon_sobj_with_neuron_subclusters_103124.qs")
```

