---
title: "R Notebook"
output: html_notebook
---

```{r}
# if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
# BiocManager::install("UCell")
library(Seurat)
library(UCell)
library(ggplot2)
library(qs)
```

```{r}
plot_overlapping_density_histogram = function(
  
    df, 
    hist_col,
    fill_col,
    colors = c("blue", "red"),
    alpha=0.5,
    breaks=seq(0, 16, 1),
    title= NULL,
    xlab = NULL,
    fig_filename = NULL

){
    # hist_col is the column you're making a histogram of (e.g. nUMI)
    # fill_col is the column you're coloring by (e.g. cell_class)
    # if fig_filename is not null, the plot will be saved to that file
     
    if (is.null(xlab)){
        xlab = hist_col
    }

    if (is.null(title)){
        title = paste0("Density Histogram of ", xlab, " by ", fill_col)
    }


    p = (
        ggplot(df, aes_string(x=hist_col, fill=fill_col)) 
        + geom_histogram(aes(y=..density..), alpha=alpha, position="identity", breaks=breaks)
        + labs(title=title, x=xlab, y="Density")    
        + theme(
                plot.title = element_text(size=16),
                axis.line = element_line(color = "black"),  # Add axis lines
                axis.ticks = element_line(color = "black"),  # Add axis ticks
                axis.text = element_text(size = 14),  # Increase tick label font size
                axis.title = element_text(size = 15)  # Increase axis label font size
            ) 
        + scale_fill_manual(values=colors)   
    )

    if (!is.null(fig_filename)){
        ggsave(fig_filename, p, width=8, height=6)
    }

    return(p)
}
```

```{r}
c_minus_genes = readRDS("~/Downloads/ferris_handsaker_genes_phase_c_minus.rds")
c_plus_genes = readRDS("~/Downloads/ferris_handsaker_genes_phase_c_plus.rds")
d_genes = readRDS("~/Downloads/ferris_handsaker_genes_phase_d.rds")
c_minus_genes
c_plus_genes
d_genes
```

```{r}
xdp_neurons = qread("~/Downloads/kkim_SOBJ_USE_THESE_final_merged_xdp_neurons.qs")
xdp_neurons
```
#186/203 c minus genes, 340/369 c plus genes, 32/107 d genes
```{r}
length(c_minus_genes)
new_c_minus_genes = intersect(rownames(xdp_neurons), c_minus_genes) 
length(new_c_minus_genes)

length(c_plus_genes)
new_c_plus_genes = intersect(rownames(xdp_neurons), c_plus_genes) 
length(new_c_plus_genes)

length(d_genes)
new_d_genes = intersect(rownames(xdp_neurons), d_genes) 
length(new_d_genes)
```


```{r}
DimPlot(xdp_neurons, label = T)
```

```{r}
spn_bican = qread("~/Downloads/SPN_Matrix_BICAN_findmarkers.qs")
spn_bican = rownames(spn_bican)
```

```{r}
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(SPN = spn_bican),
  name = 'SPN_Matrix_scores_UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(D_genes = new_d_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)
```

```{r}
qsave(xdp_neurons, "xdp_neurons_ucell.qs") 
xdp_df = xdp_neurons@meta.data 
xdp_df
```

```{r}
min(new_df$D_genesSPN_Matrix_scores_UCELL)
max(new_df$D_genesSPN_Matrix_scores_UCELL)
```


```{r}
limits = seq(0.001, 0.10, 0.001)

matrix <- new_df[new_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  
  patch <- new_df[new_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  nonSPN <- new_df[new_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  

    eSPN <- new_df[new_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  
      exotic <- new_df[new_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
```
```{r}
qsave(xdp_df, "XDP_ucell_scores.qs")
```



```{r}
cell_types = unique(xdp_df$reclustered_patch_matrix_exotic)

for (celltype in cell_types) {
 df = subset(xdp_df, subset = reclustered_patch_matrix_exotic == celltype)
 x_order = c("SCF_21-037CM2","SCF-23-068CM","SCF-22-054CM", "SCF-22-058CF", "SCF-20-025", "SCF-18-003",  "SCF_22-043", "SCF_20-024", "SCF-18-004", "SCF-18-006", "SCF-20-023", "SCF-21-030", "PCMC-16-012", "SCF-19-009", "SCF-19-014", "PCMC-16-011", "SCF-19-018")

df$donor_id = factor(df$donor_id, levels = x_order)
  
a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ donor_id) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4")) 

print(a)
 ggsave(filename = paste0("plot_", celltype, ".png"), plot = a, width = 12, height = 8)
}

```


#now BICAN
```{r}
BICAN_V8 = qread("~/Downloads/kkim_SOBJ_USE_THESE_090424_sobjs_final_V8_BICAN_neurons.qs")
BICAN_V8
DimPlot(BICAN_V8, label = T)
BICAN_V8@meta.data$reclustered_patch_matrix_exotic = BICAN_V8$reclustered_neuron_joint_type
BICAN_V8$reclustered_patch_matrix_exotic[BICAN_V8$reclustered_patch_matrix_exotic == "SPN_patch"] = "SPN_exotic"
Idents(BICAN_V8) = "reclustered_patch_matrix_exotic"
DimPlot(BICAN_V8, label = T)
```

#186/203 c minus genes, 339/369 c plus genes, 30/107 d genes 

```{r}
length(new_c_minus_genes)
new_c_minus_genes_BICAN = intersect(rownames(BICAN_V8), new_c_minus_genes) 
length(new_c_minus_genes_BICAN)

length(new_c_plus_genes)
new_c_plus_genes_BICAN = intersect(rownames(BICAN_V8), new_c_plus_genes) 
length(new_c_plus_genes_BICAN)

length(new_d_genes)
new_d_genes_BICAN = intersect(rownames(BICAN_V8), new_d_genes) 
length(new_d_genes_BICAN)
```

```{r}
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(SPN = spn_bican),
  name = 'SPN_Matrix_scores_UCELL'
)
```

```{r}
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(D_genes = new_d_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)
```

```{r}
qsave(BICAN_V8, "BICAN_neurons_ucell.qs") 
new_df = BICAN_V8@meta.data 
new_df
```

```{r}
xdp_df = qread("XDP_ucell_scores.qs")
xdp_df
new_df
```
```{r}
colnames(new_df)
```


```{r}
new_df$Condition = "BICAN_V8"
# Select specific columns from each data frame
xdp_df <- xdp_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "SPNSPN_Matrix_scores_UCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL")]  
new_df <- new_df[, c("DONOR", "Condition", "reclustered_patch_matrix_exotic", "SPNSPN_Matrix_scores_UCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL")]

new_df$donor_id = new_df$DONOR
new_df$DONOR = NULL

new_df
xdp_df
```

```{r}
final_df = rbind(xdp_df, new_df)
final_df
```
```{r}
min(final_df$C_plusSPN_Matrix_scores_UCELL)
max(final_df$C_plusSPN_Matrix_scores_UCELL)
```

```{r}
limits = seq(0.001, 0.1, 0.001)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  
  patch <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  
    eSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
  
      exotic <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$D_genesSPN_Matrix_scores_UCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = "D score UCell",
                                          fig_filename = NULL)
```

```{r}
qsave(final_df, "XDP_BICAN_ucell_scores.qs")
```



```{r}
cell_types = unique(new_df$reclustered_patch_matrix_exotic)

for (celltype in cell_types) {
 df = subset(new_df, subset = reclustered_patch_matrix_exotic == celltype)
  
a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ donor_id) + scale_color_manual(values = c("BICAN_V8" = "#00BA38")) 

print(a)
 ggsave(filename = paste0("plot_", celltype, ".png"), plot = a, width = 12, height = 8)
}

```


```{r}
for (celltype in cell_types) {
  
df = subset(final_df, subset = reclustered_patch_matrix_exotic == celltype)

a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ Condition) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4", "BICAN_V8" = "#00BA38")) 
print(a)
}

df = subset(final_df, subset = reclustered_patch_matrix_exotic == "SPN_patch")

a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle("SPN_patch: C minus vs C plus UCell Scores") + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ Condition) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4")) 
print(a)
```


