---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(qs)
library(tidyverse)
library(ggplot2)
```

```{r}
All_XDP_DFC= qread("All_XDP_Cohorts_DFC_sct.qs")
All_XDP_DFC
DimPlot(All_XDP_DFC, raster = F, group.by = "final_cell_class_merged_harmony")
```
```{r}
All_XDP_DFC = subset(All_XDP_DFC, subset = pct_intronic >= 25)
All_XDP_DFC@meta.data
DimPlot(All_XDP_DFC, raster = F, group.by = "final_cell_class_merged_harmony")
DefaultAssay(All_XDP_DFC) = "RNA"
```


```{r}
table(All_XDP_DFC$final_cell_class_merged_harmony)
```

```{r}
temp_sobj = subset(All_XDP_DFC, subset = final_cell_class_merged_harmony == "neuron")

# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(temp_sobj, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
temp_sobj = (temp_sobj
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_DFC$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_DFC$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(temp_sobj, group.by = "donor_id") 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.8", label=T) 

FeaturePlot(temp_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(temp_sobj, features = c("AQP4", "GINS3", "GFAP", "TH"), raster = F)
FeaturePlot(temp_sobj, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(temp_sobj, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(temp_sobj, features = c("OLIG1", "MOG", "MOBP", "MBP"), raster = F)
FeaturePlot(temp_sobj, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(temp_sobj, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(temp_sobj, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(temp_sobj, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("pct_mito", "pct_intronic", "nUmi","TH"),raster=FALSE) 


```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.4")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "RNA_snn_res.0.4")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
FeaturePlot(temp_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(temp_sobj, features = c("FAM163A", "CCDC88C", "CNGB1"), raster = F)
FeaturePlot(temp_sobj, features = c("TWIST2", "MET", "ALDH1A1", "ANXA1"), raster = F)
FeaturePlot(temp_sobj, features = c("PKD2L1", "ABCC12", "ABCB11", "PQLC2L"), raster = F)
FeaturePlot(temp_sobj, features = c("CORIN", "NPNT", "OPN4", "VWA5A"), raster = F)
FeaturePlot(temp_sobj, features = c("LGR5", "C14orf64", "COL9A3", "FAM89A"), raster = F)
FeaturePlot(temp_sobj, features = c("FSHR", "ADAMTS12", "NPSR1", "IL26"), raster = F)
FeaturePlot(temp_sobj, features = c("MYOCD", "SMOC1", "CDC14A", "SYT10"), raster = F)
FeaturePlot(temp_sobj, features = c("ELK3", "GALR1", "CHAT"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("SST", "CALB1", "SLC17A6", "SLC17A7"),raster=FALSE) 
FeaturePlot(temp_sobj, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 
```


```{r}
marker_genes <- c("CHAT", "SLC17A7", "CALB1", "SST", "GALR1", "ELK3", "SYT10", "CDC14A", "SMOC1", "MYOCD", "IL26", "NPSR1", "ADAMTS12", "FSHR", "FAM89A", "COL9A3", "C14orf64", "LGR5", "VWA5A", "OPN4", "NPNT", "CORIN", "PQLC2L", "ABCB11", "ABCC12", "PKD2L1", "ANXA1", "ALDH1A1", "MET", "TWIST2", "CNGB1", "CCDC88C", "FAM163A", "SLC17A6", "GAD2", "RBFOX3", "SYT1", "SLC1A3")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


marker_genes <- c("LAMP5", "LHX6", "RELN", "VIP", "ADARB2", "KCNG1", "SST", "HGF", "PVALB", "NPY", "TH", "CALB1")

Dotplot = DotPlot(object = temp_sobj, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
Idents(temp_sobj) = temp_sobj$RNA_snn_res.0.4

classes = c("L2_3_IT", "L2_3_IT", "L3_5_IT_3", "GABA_SST", "GABA_LHX6", "GABA_VIP", "L3_5_IT_2", "L3_5_IT_1", "L6_IT_1", "GABA_RELN", "glutamatergic_unsure", "L6B", "GABA_LAMP5_RELN", "L3_5_IT_1", "L6_CT", "L3_5_IT_2", "L5_6_NP", "L6_IT_2", "GABA_RELN", "GABA_LAMP5_LHX6", "NPNT_unsure", "doublet", "L5_ET", "doublet", "doublet")


temp_sobj= assignCellClasses(temp_sobj, classes=classes, cluster_col="RNA_snn_res.0.4", class_col = "neuron_cell_class")

DimPlot(temp_sobj, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
table(temp_sobj$RNA_snn_res.0.6)
```

```{r}
temp_sobj$final_cell_class_merged_harmony[temp_sobj$RNA_snn_res.0.2 == "4"] = "immune"
```


```{r}
temp_sobj
temp_sobj = subset(temp_sobj, subset = RNA_snn_res.0.4 != "4")
temp_sobj
DimPlot(temp_sobj, group.by = "RNA_snn_res.0.2")
```


```{r}
temp_sobj
temp_sobj = subset(temp_sobj, subset = neuron_cell_class != "doublet")
temp_sobj
```
```{r}
table(temp_sobj$neuron_cell_class)
```

```{r}
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "glutamatergic_unsure"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L2_3_IT"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L3_5_IT_1"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L3_5_IT_2"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L3_5_IT_3"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L5_6_NP"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L5_ET"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L6_CT"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L6_IT_1"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L6_IT_2"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "L6B"] = "glutamatergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "NPNT_unsure"] = "glutamatergic"


temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "GABA_LAMP5_LHX6"] = "gabaergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "GABA_LAMP5_RELN"] = "gabaergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "GABA_LHX6"] = "gabaergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "GABA_RELN"] = "gabaergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "GABA_SST"] = "gabaergic"
temp_sobj$final_cell_class_merged_harmony[temp_sobj$neuron_cell_class == "GABA_VIP"] = "gabaergic"
table(temp_sobj$final_cell_class_merged_harmony)
```

```{r}
DFC_oligo
DFC_opc 
DFC_neuron= temp_sobj
```

```{r}
DFC_astro@meta.data$neuron_cell_class = DFC_astro$final_cell_class_merged_harmony
DFC_endo@meta.data$neuron_cell_class = DFC_endo$final_cell_class_merged_harmony
DFC_micro@meta.data$neuron_cell_class = DFC_micro$final_cell_class_merged_harmony
DFC_oligo@meta.data$neuron_cell_class = DFC_oligo$final_cell_class_merged_harmony
DFC_opc@meta.data$neuron_cell_class = DFC_opc$final_cell_class_merged_harmony
#
```

```{r}
sobj_list = list(DFC_astro,
DFC_endo,
DFC_micro,
DFC_oligo,
DFC_opc,
DFC_neuron)

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))

merged_counts <- do.call(cbind, counts_list)

metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)

merged_metadata <- do.call(rbind, metadata_list)
merged_metadata

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
cleaned_DFC_Cohort1 <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
cleaned_DFC_Cohort1
```
```{r}
qsave(cleaned_DFC_Cohort1, "cleaned_DFC_wip.qs")
```

```{r}
cleaned_DFC_Cohort1 = qread("cleaned_DFC_wip.qs")
cleaned_DFC_Cohort1
```


```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(cleaned_DFC_Cohort1, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
cleaned_DFC_Cohort1 = (cleaned_DFC_Cohort1
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_DFC$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_DFC$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}
```


```{r}
DimPlot(cleaned_DFC_Cohort1, group.by = "donor_id") 
DimPlot(cleaned_DFC_Cohort1, group.by = "library") 
DimPlot(cleaned_DFC_Cohort1, group.by = "Condition") 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(cleaned_DFC_Cohort1, group.by = "RNA_snn_res.0.8", label=T)
DimPlot(cleaned_DFC_Cohort1, group.by = "cell_class", label=T)

DimPlot(cleaned_DFC_Cohort1, group.by = "final_cell_class_merged_harmony", label=T)
```

```{r}
cleaned_DFC_Cohort1 = qread("cleaned_DFC_wip2.qs")
cleaned_DFC_Cohort1@meta.data
```
```{r}
DimPlot(cleaned_DFC_Cohort1, group.by = "cell_class", label = T, raster = F)
DimPlot(cleaned_DFC_Cohort1, group.by = "donor_id", label = T, raster = F)
DimPlot(cleaned_DFC_Cohort1, group.by = "final_cell_class_merged_harmony", label = T, raster = F)
DimPlot(cleaned_DFC_Cohort1, group.by = "Class_label_name", label = T, raster = F)
DimPlot(cleaned_DFC_Cohort1, group.by = "neuron_cell_class", label = T, raster = F)

```






```{r}
Idents(cleaned_DFC_Cohort1) = "neuron_cell_class"

All_XDP_Cohorts_DFC_h5 = cleaned_DFC_Cohort1

DefaultAssay(All_XDP_Cohorts_DFC_h5) <- "RNA"

# Keep only the RNA assay
# if seurat object version is 5 or later, counts is accessed with $, 4 or earlier with @

if (All_XDP_Cohorts_DFC_h5@version >= 5) {
    All_XDP_Cohorts_DFC_h5[["RNA"]] <- CreateAssayObject(counts = All_XDP_Cohorts_DFC_h5@assays$RNA$counts)
} else {
    All_XDP_Cohorts_DFC_h5[["RNA"]] <- CreateAssayObject(counts = All_XDP_Cohorts_DFC_h5@assays$RNA@counts)
}


# Remove all other assays
All_XDP_Cohorts_DFC_h5@assays <- list(RNA = All_XDP_Cohorts_DFC_h5[["RNA"]])

# Ensure metadata is properly aligned
if (!all(rownames(All_XDP_Cohorts_DFC_h5@meta.data) == colnames(All_XDP_Cohorts_DFC_h5))) {
    stop("Cell names in meta.data do not match counts matrix! Check alignment.")
}

library(SeuratDisk)
# Save the cleaned Seurat object
SaveH5Seurat(All_XDP_Cohorts_DFC_h5, filename = "All_XDP_Cohorts_DFC_final.h5Seurat", overwrite = TRUE)

# Convert to H5AD
Convert("All_XDP_Cohorts_DFC_final.h5Seurat", dest = "h5ad", overwrite = TRUE)
```

```{r}
assayNames(basal)
expr_mat2 <- assay(basal, "X")

sum(is.na(expr_mat2))       # Count of NA / NaN values
sum(is.nan(expr_mat2))      # Specifically NaN count
sum(expr_mat2 < 0)   
```
```{r}
class(expr_mat2)
summary(expr_mat2[1:10, 1:10])
```

```{r}
vals <- assay(atlas, "X")[sample(1:nrow(atlas), 10), sample(1:ncol(atlas), 10)]
summary(as.numeric(vals))

```

```{r}
assayNames(atlas)
expr_mat <- assay(atlas, "X")
```

```{r}
sum(is.na(expr_mat))       # Count of NA / NaN values
sum(is.nan(expr_mat))      # Specifically NaN count
sum(expr_mat < 0)          # Count of negative values
```

```{r}
class(expr_mat)
summary(expr_mat[1:10, 1:10])
```

```{r}
str(metadata(atlas))

```


```{r}
assayNames(atlas)

```



```{r}
nano xdpall_dfc_submit_mapmycells_REDO.slurm
sbatch xdpall_dfc_submit_mapmycells_REDO.slurm

#!/bin/bash
#SBATCH --job-name=mapmycells
#SBATCH --output=mapmycells_%j.out
#SBATCH --error=mapmycells_%j.err
#SBATCH --time=04:00:00              # adjust as needed
#SBATCH --mem=300G                    # adjust memory based on your data
#SBATCH --cpus-per-task=12
#SBATCH --partition=disco   # replace with your cluster's partition

# Load conda or module environment if needed
source ~/.bashrc
conda activate your_env_name

# Run your script
bash  /broad/macosko/kimkathl/XDP/QC_and_Clustering/DFC_TRY/run_mapmycells_cortical.sh \
  -r /broad/macosko/kimkathl/XDP/QC_and_Clustering/DFC_TRY/Atlas_Cortex_trim.h5ad \
  -q /broad/macosko/kimkathl/XDP/QC_and_Clustering/DFC_TRY/All_XDP_Cohorts_DFC_final.h5ad \
  -o /broad/macosko/kimkathl/XDP/QC_and_Clustering/DFC_TRY \
  -c
```




```{r}
library(zellkonverter)
atlas = readH5AD("XDP/QC_and_Clustering/Atlas_Cortex_trim.h5ad")
atlas
```
```{r}
colnames(colData(atlas))
```
```{r}
colnames(colData(basal))
```


```{r}
basal = readH5AD("XDP/QC_and_Clustering/files_needed/hmba_neuron.h5ad")
basal
```













```{r}
cleaned_DFC_Cohort1 = qread("cleaned_DFC_wip2.qs")
```



```{r}
library(sctransform)
options(future.globals.maxSize = 400 * 1024^3)  
All_XDP_Cohorts_DFC= cleaned_DFC_Cohort1
rm(cleaned_DFC_Cohort1)
All_XDP_Cohorts_DFC = SCTransform(All_XDP_Cohorts_DFC, vars.to.regress = "pct_mito", verbose = FALSE)
DefaultAssay(All_XDP_Cohorts_DFC) = "SCT"
All_XDP_Cohorts_DFC

# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(All_XDP_Cohorts_DFC, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
All_XDP_Cohorts_DFC = (All_XDP_Cohorts_DFC
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}
```


```{r}
DimPlot(All_XDP_Cohorts_DFC, group.by = "donor_id", raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Condition", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Cohort", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "cell_class", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_merged_harmony", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.2", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.3", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.4", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.5", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.6", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.7", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.8", label=T, raster = F)
```

```{r}
qsave(All_XDP_Cohorts_DFC, "cleaned_DFC_wip3.qs")
```

```{r}
library(harmony)
All_XDP_Cohorts_DFC = (All_XDP_Cohorts_DFC
    %>% RunHarmony(
        group.by = "donor_id")
    %>% FindNeighbors(reduction='harmony', dims=1:20)
    %>% FindClusters(res=0.05)
    %>% FindClusters(res=0.1)
    %>% FindClusters(res=0.2)
    %>% FindClusters(res=0.3)
    %>% FindClusters(res=0.4)
    %>% FindClusters(res=0.5)
    %>% FindClusters(res=0.6)
    %>% FindClusters(res=0.7)
    %>% FindClusters(res=0.8)    
    %>% RunUMAP(reduction="harmony", dims=1:20)
)
All_XDP_Cohorts_DFC
All_XDP_Cohorts_DFC@meta.data
DimPlot(All_XDP_Cohorts_DFC, group.by = "donor_id", raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.05", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.1", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.2", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.3", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.4", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.5", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.6", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.7", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.8", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "library", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Cohort", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "library_cohort", raster = F)

DimPlot(All_XDP_Cohorts_DFC, group.by = "Condition", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "cell_class", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_merged_harmony", label=T, raster = F)
```
```{r}
qsave(All_XDP_Cohorts_DFC, "cleaned_DFC_wip3.qs")
```


```{r}
FeaturePlot(All_XDP_Cohorts_DFC, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("MBP", "MOBP", "WIF1", "TNC"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("pct_mito", "pct_intronic", "nUmi", "TH"),raster=FALSE) 

FeaturePlot(All_XDP_Cohorts_DFC, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("FLT1", "DCN", "RGS5"), raster = F)

FeaturePlot(All_XDP_Cohorts_DFC, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("CD96", "NKG7", "SKAP1"), raster = F)

```

```{r}
FeaturePlot(All_XDP_Cohorts_DFC, features = c("TH", "SLC6A3"), raster = F)
```


```{r}
Idents(All_XDP_Cohorts_DFC) = All_XDP_Cohorts_DFC$SCT_snn_res.0.8

classes = c("oligo","neuron", "oligo", "neuron", "astrocyte", "neuron", "microglia", "opc", "neuron", "neuron", "neuron", 
  "neuron", "oligo", "neuron", "oligo", "doublet", "neuron", "neuron", "astrocyte", "neuron", "doublet", 
  "astrocyte", "neuron", "neuron", "neuron", "doublet", "neuron", "astrocyte", "endothelial", "neuron", "endothelial",
  "neuron", "neuron", "neuron", "doublet", "neuron", "neuron", "oligo")



All_XDP_Cohorts_DFC= assignCellClasses(All_XDP_Cohorts_DFC, classes=classes, cluster_col="SCT_snn_res.0.8", class_col = "final_cell_class_new")

DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_new" ,label = T, raster = FALSE)
Idents(All_XDP_Cohorts_DFC) = "final_cell_class_new"
```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN", "TH", "SLC6A3")

Dotplot = DotPlot(object = All_XDP_Cohorts_DFC, features = marker_genes, group.by = "final_cell_class_new")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = All_XDP_Cohorts_DFC, features = marker_genes, group.by = "final_cell_class_new")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)

```

```{r}
table(All_XDP_Cohorts_DFC$final_cell_class_new)
```

```{r}
All_XDP_Cohorts_DFC = subset(All_XDP_Cohorts_DFC, subset = final_cell_class_new != "doublet")
```

```{r}
All_XDP_Cohorts_DFC
```


```{r}
hvgs = getSeuratVarFeatureIntersectByCol(All_XDP_Cohorts_DFC, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
All_XDP_Cohorts_DFC = (All_XDP_Cohorts_DFC
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(All_XDP_Cohorts_DFC, group.by = "donor_id", raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Condition", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Cohort", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "cell_class", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_merged_harmony", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_new", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.2", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.3", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.4", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.5", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.6", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.7", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.8", label=T, raster = F)
```


```{r}
FeaturePlot(All_XDP_Cohorts_DFC, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("MBP", "MOBP", "WIF1", "TNC"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("pct_mito", "pct_intronic", "nUmi", "TH"),raster=FALSE) 

FeaturePlot(All_XDP_Cohorts_DFC, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("FLT1", "DCN", "RGS5"), raster = F)

FeaturePlot(All_XDP_Cohorts_DFC, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("CD96", "NKG7", "SKAP1"), raster = F)

```

```{r}
All_XDP_Cohorts_DFC
```

```{r}
qsave(All_XDP_Cohorts_DFC, "cleaned_DFC_wip4.qs")
```


```{r}
library(harmony)
All_XDP_Cohorts_DFC = (All_XDP_Cohorts_DFC
    %>% RunHarmony(
        group.by = "donor_id")
    %>% FindNeighbors(reduction='harmony', dims=1:20)
    %>% FindClusters(res=0.05)
    %>% FindClusters(res=0.1)
    %>% FindClusters(res=0.2)
    %>% FindClusters(res=0.3)
    %>% FindClusters(res=0.4)
    %>% FindClusters(res=0.5)
    %>% FindClusters(res=0.6)
    %>% FindClusters(res=0.7)
    %>% FindClusters(res=0.8)    
    %>% RunUMAP(reduction="harmony", dims=1:20)
)

DimPlot(All_XDP_Cohorts_DFC, group.by = "donor_id", raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Condition", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Cohort", raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "Region", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "cell_class", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_merged_harmony", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_new", label=T, raster = F)
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.2", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.3", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.4", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.5", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.6", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.7", label=T, raster = F) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "SCT_snn_res.0.8", label=T, raster = F)
```

```{r}
FeaturePlot(All_XDP_Cohorts_DFC, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("MBP", "MOBP", "WIF1", "TNC"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_DFC, features = c("pct_mito", "pct_intronic", "nUmi", "TH"),raster=FALSE) 

FeaturePlot(All_XDP_Cohorts_DFC, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("FLT1", "DCN", "RGS5"), raster = F)

FeaturePlot(All_XDP_Cohorts_DFC, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(All_XDP_Cohorts_DFC, features = c("CD96", "NKG7", "SKAP1"), raster = F)
```

```{r}
All_XDP_Cohorts_DFC@meta.data
```

```{r}
DimPlot(All_XDP_Cohorts_DFC, group.by = "cell_class", raster = F, label = T) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_merged_harmony", raster = F, label = T) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "Class_label_name", raster = F, label = T) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "Subclass_label_name", raster = F, label = T) 
DimPlot(All_XDP_Cohorts_DFC, group.by = "neuron_cell_class", raster = F, label = T)
DimPlot(All_XDP_Cohorts_DFC, group.by = "final_cell_class_new", raster = F, label = T)
```


```{r}
Idents(All_XDP_Cohorts_DFC) = All_XDP_Cohorts_DFC$SCT_snn_res.0.3

classes = c("oligo", "glutamatergic", "glutamatergic", "astrocyte", "oligo", "glutamatergic", "glutamatergic", "microglia", "opc", "gabaergic", "gabaergic", "gabaergic", "gabaergic", "glutamatergic", "astrocyte", "glutamatergic", "endothelial", "glutamatergic", "glutamatergic", "glutamatergic", "gabaergic", "gabaergic", "glutamatergic")



All_XDP_Cohorts_DFC= assignCellClasses(All_XDP_Cohorts_DFC, classes=classes, cluster_col="SCT_snn_res.0.3", class_col = "cell_class")

DimPlot(All_XDP_Cohorts_DFC, group.by = "cell_class" ,label = T, raster = FALSE)
```


```{r}
colnames(All_XDP_Cohorts_DFC@meta.data) <- tolower(colnames(All_XDP_Cohorts_DFC@meta.data))
All_XDP_Cohorts_DFC@meta.data
```

```{r}
All_XDP_Cohorts_DFC@meta.data
```

```{r}
qsave(All_XDP_Cohorts_DFC, "All_XDP_Cohorts_DFC_sct_final_051525.qs")
```


```{r}
All_XDP_Cohorts_DFC_meta = All_XDP_Cohorts_DFC@meta.data
qsave(All_XDP_Cohorts_DFC_meta, "All_XDP_Cohorts_DFC_meta.qs")
```

```{r}
All_XDP_Cohorts_DFC_meta = qread("All_XDP_Cohorts_DFC_meta.qs")
```


```{r}
library(lme4)
sobj = All_XDP_Cohorts_DFC_meta
sobj = subset(sobj, donor_id != "SCF_22_049CCF")
model_cols = c("donor_id", "cell_class", "condition", "sex", "age_of_death", "cohort") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = All_XDP_Cohorts_DFC_meta[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("age_of_death", "sex", "cohort") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("DFC All Cohorts (no CCF)") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )

ggsave(a, filename = "pic.png", width = 7, height = 8)
```
```{r}
table(All_XDP_Cohorts_DFC_meta$neuron_cell_class)
```

```{r}
library(lme4)
sobj = All_XDP_Cohorts_DFC_meta
sobj = subset(sobj, donor_id != "SCF_22_049CCF")
sobj = subset(sobj, cell_class == "gabaergic" | cell_class == "glutamatergic")
model_cols = c("donor_id", "neuron_cell_class", "condition", "sex", "age_of_death", "cohort") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$neuron_cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("age_of_death", "sex", "cohort") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("DFC All Cohorts (no CCF)") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Neuron Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )

ggsave(a, filename = "pic.png", width = 7, height = 8)
```

```{r}
cohort = read.csv("cohortsnew.csv")
cohort
```

```{r}

```

```{r}
ggplot(cohort, aes(x = SPN_proportion, y = total_cells, color = Condition)) + geom_point()
```


