---
title: "R Notebook"
output: html_notebook
---

```{r}
All_XDP_Cohorts_CaHPut_meta
All_XDP_Cohorts_DFC_meta
All_XDP_Cohorts_SN_meta
```

```{r}
table(All_XDP_Cohorts_CaHPut_meta$cell_class)
table(All_XDP_Cohorts_CaHPut_meta$neuron_cell_class)
table(All_XDP_Cohorts_CaHPut_meta$class_label_name)
table(All_XDP_Cohorts_CaHPut_meta$subclass_label_name)
table(All_XDP_Cohorts_CaHPut_meta$group_label_name)
```

```{r}
conf_mat <- table(All_XDP_Cohorts_CaHPut_meta$cell_class,All_XDP_Cohorts_CaHPut_meta$class_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Class Labels -  XDP Striatum")
```
```{r}
All_XDP_Cohorts_CaHPut_neuron_meta = subset(All_XDP_Cohorts_CaHPut_meta, subset = cell_class == "SPN" | cell_class == "non_SPN")
All_XDP_Cohorts_CaHPut_neuron_meta
```


```{r}
conf_mat <- table(All_XDP_Cohorts_CaHPut_neuron_meta$neuron_cell_class,All_XDP_Cohorts_CaHPut_neuron_meta$subclass_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Subclass Labels -  XDP Striatum Neurons")
```
```{r}
temp = All_XDP_Cohorts_CaHPut_neuron_meta[All_XDP_Cohorts_CaHPut_neuron_meta$subclass_label_bootstrapping_probability < 0.90, ]

table(temp$neuron_cell_class)
table(temp$subclass_label_name)
```

```{r}
conf_mat <- table(All_XDP_Cohorts_CaHPut_neuron_meta$neuron_cell_class,All_XDP_Cohorts_CaHPut_neuron_meta$group_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Group Labels -  XDP Striatum Neurons")
```

```{r}
bican_recon_meta = qread("bican_recon_newest_meta.qs")
bican_recon_meta
```
```{r}
bican_recon_meta$cell_type_annot[is.na(bican_recon_meta$cell_type_annot)] <- 
  bican_recon_meta$cell_class_annot[is.na(bican_recon_meta$cell_type_annot)]
bican_recon_meta
```


#bican
```{r}
conf_mat <- table(bican_recon_meta$cell_class_annot,bican_recon_meta$Class_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Class Labels -  BICAN Recon")

bican_recon_meta_neuron_meta = subset(bican_recon_meta, subset = cell_class_annot == "neuron")
bican_recon_meta_neuron_meta

conf_mat <- table(bican_recon_meta_neuron_meta$cell_type_annot,bican_recon_meta_neuron_meta$Subclass_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Subclass Labels -  BICAN Recon Neurons")

conf_mat <- table(bican_recon_meta_neuron_meta$cell_type_annot,bican_recon_meta_neuron_meta$Group_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Group Labels -  BICAN Recon Neurons")
```



```{r}
xdp_recon_meta = qread("XDP/Analysis/Gray_White_Matter_Scores/xdp_recon_meta.qs")
xdp_recon_meta
```

#xdp_recon
```{r}
conf_mat <- table(xdp_recon_meta$new_final_cell_class,xdp_recon_meta$Class_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Class Labels -  XDP Recon")

xdp_recon_meta_neuron_meta = subset(xdp_recon_meta, subset = new_final_cell_class == "neuron")
xdp_recon_meta_neuron_meta

conf_mat <- table(xdp_recon_meta_neuron_meta$subclass,xdp_recon_meta_neuron_meta$Subclass_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Subclass Labels -  XDP Recon Neurons")

conf_mat <- table(xdp_recon_meta_neuron_meta$subclass,xdp_recon_meta_neuron_meta$Group_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Group Labels -  XDP Recon Neurons")
```

```{r}
XDP_SN_meta = qread("All_XDP_Cohorts_SN_meta.qs")
XDP_SN_meta
```


#xdp sn
```{r}
conf_mat <- table(XDP_SN_meta$cell_class,XDP_SN_meta$class_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Class Labels -  XDP SN")

xdp_sn_meta_neuron_meta = subset(XDP_SN_meta, subset = cell_class == "DaN" | cell_class == "non_da" )
xdp_sn_meta_neuron_meta

conf_mat <- table(xdp_sn_meta_neuron_meta$cell_class,xdp_sn_meta_neuron_meta$subclass_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Subclass Labels -  XDP SN Neurons")

conf_mat <- table(xdp_sn_meta_neuron_meta$cell_class,xdp_sn_meta_neuron_meta$group_label_name)
conf_mat

blues <- colorRampPalette(c("white", "blue"))(100)

# Set breakpoints from 0 to max count
max_count <- max(conf_mat)

pheatmap(conf_mat,
         cluster_rows = FALSE,
         cluster_cols = FALSE,
         display_numbers = TRUE,
         number_format = "%.0f",
         color = blues,
         breaks = seq(0, max_count, length.out = 101),
         main = "Manual vs Group Labels -  XDP SN Neurons")
```


```{r}
temp
```


```{r}
temp = subset(All_XDP_Cohorts_CaHPut_meta, subclass_label_name == "Astrocyte")

min =  min(temp$scorenfkb)
max = max(temp$scorenfkb)
step = (max-min)/100

limits = seq(min, max, step)


a = plot_overlapping_density_histogram(df = temp, 
                                          hist_col = temp$scorenfkb,
                                          fill_col = "condition",
                                  colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = paste0("Astrocyte"),
                                          xlab = "NFKB Score",
                                          fig_filename = NULL) + facet_wrap(~ cohort)
 print(a)
 #ggsave(a, filename = "pic.png", width = 10, height = 4)
```

```{r}

softmax_cols = function(df, cols){
  z_cols = paste0(cols, "__z")
  softmax_cols = paste0(cols, "__softmax")
  
  # Z-score normalization of the selected columns
  df[z_cols] = scale(df[cols])
  
  # Apply softmax row-wise: exp of z-scores divided by row sum of exp(z-scores)
  df[softmax_cols] =  t(apply(df[z_cols], 1, function(x) exp(x) / sum(exp(x))))
  
  return(df)
}


columns = c("scorenfkb", "c_minus_scores")
All_XDP_Cohorts_CaHPut_meta = softmax_cols(All_XDP_Cohorts_CaHPut_meta, columns)
```

```{r}
All_XDP_Cohorts_CaHPut_meta
```


```{r}
temp = subset(All_XDP_Cohorts_CaHPut_meta, subclass_label_name == "Astrocyte")

min =  min(temp$scorenfkb__softmax)
max = max(temp$scorenfkb__softmax)
step = (max-min)/100

limits = seq(min, max, step)


a = plot_overlapping_density_histogram(df = temp, 
                                          hist_col = temp$scorenfkb__softmax,
                                          fill_col = "condition",
                                  colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = paste0("Astrocyte"),
                                          xlab = "NFKB Score",
                                          fig_filename = NULL) + facet_wrap(~ cohort)
 print(a)
```





```{r}
library(jsonlite)
json_data <- fromJSON("XDP/QC_and_Clustering/files_needed/query_markers.json")
head(json_data)
names(json_data)


D1_genes <- json_data[["Subclass_label/STR D1 MSN GABA"]]
length(D1_genes)
D2_genes <- json_data[["Subclass_label/STR D2 MSN GABA"]]
length(D2_genes)

combined_SPN = unique(c(D1_genes, D2_genes))
length(combined_SPN)
```

```{r}
C_minus = qread("temp_disco/more_temp_1205/final_c_minus_genes.qs")
C_plus = qread("temp_disco/more_temp_1205/final_c_plus_genes.qs")

length(C_minus)
length(C_plus)
```

```{r}
C_minus_intersect = intersect(C_minus, combined_SPN)
length(C_minus_intersect)
C_plus_intersect = intersect(C_plus, combined_SPN)
length(C_plus_intersect)
```
```{r}
C_minus_intersect
C_plus_intersect
#39 shared genes, C minus
#13 shared genes, C plus
```
```{r}
C_minus_new = setdiff(C_minus, combined_SPN)
C_plus_new = setdiff(C_plus, combined_SPN)

length(C_minus_new)
length(C_plus_new)
```

```{r}
All_XDP_Cohorts_CaHPut@meta.data
```


```{r}
library(UCell)
All_XDP_Cohorts_CaHPut <- AddModuleScore_UCell(All_XDP_Cohorts_CaHPut, features = list(Score = C_minus_new), name = 'C_minus_new')
All_XDP_Cohorts_CaHPut <- AddModuleScore_UCell(All_XDP_Cohorts_CaHPut, features = list(Score = C_plus_new), name = 'C_plus_new')
```

```{r}
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = C_minus_new), name = 'C_minus_new')
xdp_recon <- AddModuleScore_UCell(xdp_recon, features = list(Score = C_plus_new), name = 'C_plus_new')
```

```{r}
All_XDP_Cohorts_DFC
```


```{r}
1+1
```


