---
title: "R Notebook"
output: html_notebook
---

```{r}
All_XDP_Cohorts@meta.data
```
```{r}
table(All_XDP_Cohorts@meta.data$Class_label_name)
table(All_XDP_Cohorts@meta.data$Subclass_label_name) 
table(All_XDP_Cohorts@meta.data$Group_label_name)
```

```{r}
DimPlot(All_XDP_Cohorts, group.by = "Class_label_name", label = T, raster = F)

```


```{r}
library(lme4)
sobj = All_XDP_Cohorts@meta.data
sobj = subset(sobj, donor_id != "SCF_22_049CCF")
sobj = subset(sobj, Class_label_name != "BG GABA Glut")

sobj$Class_label_name <- gsub("[- ]", "_", sobj$Class_label_name)
sobj$Subclass_label_name <- gsub("[- ]", "_", sobj$Subclass_label_name)
sobj$Group_label_name <- gsub("[- ]", "_", sobj$Group_label_name)

model_cols = c("donor_id", "Class_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Class_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("CaH/Put all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Class Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 

ggsave(a, filename = "pic.png", width = 7, height = 8)
```

```{r}
All_XDP_Cohorts_neurons = subset(All_XDP_Cohorts@meta.data, subset = Class_label_name == "CN CGE GABA" | Class_label_name == "CN LGE GABA" | Class_label_name == "CN MGE GABA" | Class_label_name == "F M Glut")
All_XDP_Cohorts_neurons

table(All_XDP_Cohorts_neurons$Subclass_label_name)
table(All_XDP_Cohorts_neurons$Group_label_name)

table_counts <- table(All_XDP_Cohorts_neurons$Group_label_name)
low_count_groups <- table_counts[table_counts < 100]
low_count_groups

keep_groups <- names(table_counts[table_counts >= 100])
filtered_neurons <- subset(All_XDP_Cohorts_neurons, 
                       subset = Group_label_name %in% keep_groups)

table(filtered_neurons$Group_label_name)

sobj = filtered_neurons
sobj = subset(sobj, donor_id != "SCF_22_049CCF")

sobj$Class_label_name <- gsub("[- ]", "_", sobj$Class_label_name)
sobj$Subclass_label_name <- gsub("[- ]", "_", sobj$Subclass_label_name)
sobj$Group_label_name <- gsub("[- ]", "_", sobj$Group_label_name)

model_cols = c("donor_id", "Subclass_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Subclass_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("CaH/Put Neurons all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Subclass Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df1 = masc_df
ggsave(a, filename = "pic1.png", width = 7, height = 8)

#cah/put neuron group
model_cols = c("donor_id", "Group_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Group_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("CaH/Put Neurons all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Group Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df2 = masc_df
ggsave(a, filename = "pic2.png", width = 7, height = 8)
```


```{r}
#DFC

All_XDP_Cohorts_DFC@meta.data

table(All_XDP_Cohorts_DFC@meta.data$Class_label_name)
table(All_XDP_Cohorts_DFC@meta.data$Subclass_label_name) 
table(All_XDP_Cohorts_DFC@meta.data$Group_label_name)

DimPlot(All_XDP_Cohorts_DFC, group.by = "Class_label_name", label = T, raster = F)


library(lme4)
sobj = All_XDP_Cohorts_DFC@meta.data
sobj = subset(sobj, donor_id != "SCF_22_049CCF")

sobj$Class_label_name <- gsub("[- ]", "_", sobj$Class_label_name)
sobj$Subclass_label_name <- gsub("[- ]", "_", sobj$Subclass_label_name)
sobj$Group_label_name <- gsub("[- ]", "_", sobj$Group_label_name)

model_cols = c("donor_id", "Class_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Class_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("DFC all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Class Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df3 = masc_df
ggsave(a, filename = "pic3.png", width = 7, height = 8)
```


```{r}
All_XDP_Cohorts_neurons_DFC = subset(All_XDP_Cohorts_DFC@meta.data, subset = Class_label_name == "CN CGE GABA" | Class_label_name == "CN LGE GABA" | Class_label_name == "CN MGE GABA" | Class_label_name == "F M Glut")
All_XDP_Cohorts_neurons_DFC

table(All_XDP_Cohorts_neurons_DFC$Subclass_label_name)
table(All_XDP_Cohorts_neurons_DFC$Group_label_name)

table_counts <- table(All_XDP_Cohorts_neurons_DFC$Group_label_name)
low_count_groups <- table_counts[table_counts < 100]
low_count_groups

keep_groups <- names(table_counts[table_counts >= 100])
filtered_neurons_dfc <- subset(All_XDP_Cohorts_neurons_DFC, 
                       subset = Group_label_name %in% keep_groups)

table(filtered_neurons_dfc$Group_label_name)

sobj = filtered_neurons_dfc
sobj = subset(sobj, donor_id != "SCF_22_049CCF")

sobj$Class_label_name <- gsub("[- ]", "_", sobj$Class_label_name)
sobj$Subclass_label_name <- gsub("[- ]", "_", sobj$Subclass_label_name)
sobj$Group_label_name <- gsub("[- ]", "_", sobj$Group_label_name)

model_cols = c("donor_id", "Subclass_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Subclass_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("DFC Neurons all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Subclass Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df4 = masc_df
ggsave(a, filename = "pic4.png", width = 7, height = 8)

#cah/put neuron group
model_cols = c("donor_id", "Group_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Group_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("DFC Neurons all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Group Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df5 = masc_df
ggsave(a, filename = "pic5.png", width = 7, height = 8)

```


#SN

```{r}
All_XDP_Cohorts_SN@meta.data

table(All_XDP_Cohorts_SN@meta.data$Class_label_name)
table(All_XDP_Cohorts_SN@meta.data$Subclass_label_name) 
table(All_XDP_Cohorts_SN@meta.data$Group_label_name)

DimPlot(All_XDP_Cohorts_SN, group.by = "Class_label_name", label = T, raster = F)


library(lme4)
sobj = All_XDP_Cohorts_SN@meta.data
sobj = subset(sobj, donor_id != "SCF_22_049CCF")
sobj = subset(sobj, Class_label_name != "BG GABA Glut")

sobj$Class_label_name <- gsub("[- ]", "_", sobj$Class_label_name)
sobj$Subclass_label_name <- gsub("[- ]", "_", sobj$Subclass_label_name)
sobj$Group_label_name <- gsub("[- ]", "_", sobj$Group_label_name)

model_cols = c("donor_id", "Class_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Class_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("SN all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Class Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df6 = masc_df
ggsave(a, filename = "pic6.png", width = 7, height = 8)
```


```{r}
All_XDP_Cohorts_neurons_SN = subset(All_XDP_Cohorts_SN@meta.data, subset = Class_label_name == "CN CGE GABA" | Class_label_name == "CN LGE GABA" | Class_label_name == "CN MGE GABA" | Class_label_name == "F M Glut" | Class_label_name == "MB Dopaminergic")
All_XDP_Cohorts_neurons_SN

table(All_XDP_Cohorts_neurons_SN$Subclass_label_name)
table(All_XDP_Cohorts_neurons_SN$Group_label_name)

table_counts <- table(All_XDP_Cohorts_neurons_SN$Group_label_name)
low_count_groups <- table_counts[table_counts < 100]
low_count_groups

keep_groups <- names(table_counts[table_counts >= 100])
filtered_neurons_SN <- subset(All_XDP_Cohorts_neurons_SN, 
                       subset = Group_label_name %in% keep_groups)

table(filtered_neurons_SN$Group_label_name)

sobj = filtered_neurons_SN
sobj = subset(sobj, donor_id != "SCF_22_049CCF")

sobj$Class_label_name <- gsub("[- ]", "_", sobj$Class_label_name)
sobj$Subclass_label_name <- gsub("[- ]", "_", sobj$Subclass_label_name)
sobj$Group_label_name <- gsub("[- ]", "_", sobj$Group_label_name)

model_cols = c("donor_id", "Subclass_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Subclass_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("SN Neurons all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Subclass Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df7 = masc_df
ggsave(a, filename = "pic7.png", width = 7, height = 8)
masc_df7
```


```{r}
#cah/put neuron group
model_cols = c("donor_id", "Group_label_name", "Condition", "Sex", "Cohort", "Age_of_Death") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$Condition)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$Group_label_name, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects=c("donor_id"), # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("Cohort", "Sex", "Age_of_Death") # your covariates
)

masc_df

my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorXDP.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorXDP.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorXDP.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df


library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
a = ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  ggtitle("SN Neurons all Cohorts") +
  geom_vline(xintercept = 0, linetype = "dotted", color = "gray") +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Group Label") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  ) 
masc_df8 = masc_df
ggsave(a, filename = "pic8.png", width = 7, height = 8)

```



```{r}
bican_marker_list = qread("/broad/macosko/kimkathl/XDP/Analysis/Gray_White_Matter_Scores/bican_marker_list.qs")
bican_marker_list
#bican_subset_sobj_list

bican_recon_astro_markers = bican_marker_list[["astro"]]
bican_recon_opc_markers = bican_marker_list[["opc"]]
bican_recon_oligo_markers = bican_marker_list[["oligo"]]
bican_recon_endo_markers = bican_marker_list[["endo"]]
bican_recon_neuron_markers = bican_marker_list[["neuron"]]
bican_recon_mg_markers = bican_marker_list[["mg"]]

bican_recon_astro_markers_wm = subset(bican_recon_astro_markers, subset = cluster == "White_Matter")
bican_recon_astro_markers_gm = subset(bican_recon_astro_markers, subset = cluster == "Gray_Matter")
bican_recon_opc_markers_wm  = subset(bican_recon_opc_markers, subset = cluster == "White_Matter")
bican_recon_opc_markers_gm = subset(bican_recon_opc_markers, subset = cluster == "Gray_Matter")
bican_recon_oligo_markers_wm = subset(bican_recon_oligo_markers, subset = cluster == "White_Matter")
bican_recon_oligo_markers_gm = subset(bican_recon_oligo_markers, subset = cluster == "Gray_Matter")
bican_recon_mg_markers_wm = subset(bican_recon_mg_markers, subset = cluster == "White_Matter")
bican_recon_mg_markers_gm = subset(bican_recon_mg_markers, subset = cluster == "Gray_Matter")

bican_recon_astro_markers_wm 
bican_recon_astro_markers_gm 
bican_recon_opc_markers_wm  
bican_recon_opc_markers_gm 
bican_recon_oligo_markers_wm 
bican_recon_oligo_markers_gm 
bican_recon_mg_markers_wm 
bican_recon_mg_markers_gm 

bican_recon_astro_markers_filtered = subset(bican_recon_astro_markers, subset = pct.1 > 0.7 & pct.2 < 0.3)
bican_recon_opc_markers_filtered = subset(bican_recon_opc_markers, subset = pct.1 > 0.7 & pct.2 < 0.3)
bican_recon_oligo_markers_filtered = subset(bican_recon_oligo_markers, subset = pct.1 > 0.6 & pct.2 < 0.3)
bican_recon_mg_markers_filtered = subset(bican_recon_mg_markers, subset = pct.1 > 0.6 & pct.2 < 0.3)

bican_recon_astro_markers_filtered_wm= subset(bican_recon_astro_markers_filtered, subset = cluster == "White_Matter")
bican_recon_astro_markers_filtered_gm= subset(bican_recon_astro_markers_filtered, subset = cluster == "Gray_Matter")
bican_recon_opc_markers_filtered_wm= subset(bican_recon_opc_markers_filtered, subset = cluster == "White_Matter")
bican_recon_opc_markers_filtered_gm= subset(bican_recon_opc_markers_filtered, subset = cluster == "Gray_Matter")
bican_recon_oligo_markers_filtered_wm= subset(bican_recon_oligo_markers_filtered, subset = cluster == "White_Matter")
bican_recon_oligo_markers_filtered_gm= subset(bican_recon_oligo_markers_filtered, subset = cluster == "Gray_Matter")
bican_recon_mg_markers_filtered_wm= subset(bican_recon_mg_markers_filtered, subset = cluster == "White_Matter")
bican_recon_mg_markers_filtered_gm= subset(bican_recon_mg_markers_filtered, subset = cluster == "Gray_Matter")

bican_recon_astro_markers_filtered_wm
bican_recon_astro_markers_filtered_gm
bican_recon_opc_markers_filtered_wm
bican_recon_opc_markers_filtered_gm
bican_recon_oligo_markers_filtered_wm
bican_recon_oligo_markers_filtered_gm #none
bican_recon_mg_markers_filtered_wm
bican_recon_mg_markers_filtered_gm #none

bican_recon_astro_markers_filtered_wm = rownames(bican_recon_astro_markers_filtered_wm)
bican_recon_astro_markers_filtered_gm= rownames(bican_recon_astro_markers_filtered_gm)
bican_recon_opc_markers_filtered_wm= rownames(bican_recon_opc_markers_filtered_wm)
bican_recon_opc_markers_filtered_gm= rownames(bican_recon_opc_markers_filtered_gm)
bican_recon_oligo_markers_filtered_wm= rownames(bican_recon_oligo_markers_filtered_wm)
bican_recon_oligo_markers_filtered_gm= rownames(bican_recon_oligo_markers_filtered_gm)
bican_recon_mg_markers_filtered_wm= rownames(bican_recon_mg_markers_filtered_wm)
bican_recon_mg_markers_filtered_gm= rownames(bican_recon_mg_markers_filtered_gm)

bican_recon_astro_markers_filtered_wm
bican_recon_astro_markers_filtered_gm
bican_recon_opc_markers_filtered_wm
bican_recon_opc_markers_filtered_gm
bican_recon_oligo_markers_filtered_wm
bican_recon_oligo_markers_filtered_gm #none
bican_recon_mg_markers_filtered_wm
bican_recon_mg_markers_filtered_gm #none

bican_recon_astro_markers_top50_wm <- bican_recon_astro_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_astro_markers_top50_gm <- bican_recon_astro_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_opc_markers_top50_wm <- bican_recon_opc_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)
bican_recon_opc_markers_top50_gm <- bican_recon_opc_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_oligo_markers_top50_wm <- bican_recon_oligo_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_oligo_markers_top50_gm <- bican_recon_oligo_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_mg_markers_top50_wm <- bican_recon_mg_markers_wm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)

bican_recon_mg_markers_top50_gm <- bican_recon_mg_markers_gm %>%
  mutate(pct_diff = pct.1 - pct.2) %>%
  arrange(desc(pct_diff)) %>%
  slice_head(n = 50)


bican_recon_astro_markers_top50_wm
bican_recon_astro_markers_top50_gm
bican_recon_opc_markers_top50_wm
bican_recon_opc_markers_top50_gm
bican_recon_oligo_markers_top50_wm
bican_recon_oligo_markers_top50_gm
bican_recon_mg_markers_top50_wm
bican_recon_mg_markers_top50_gm


bican_recon_astro_markers_top50_wm = rownames(bican_recon_astro_markers_top50_wm)
bican_recon_astro_markers_top50_gm= rownames(bican_recon_astro_markers_top50_gm)
bican_recon_opc_markers_top50_wm= rownames(bican_recon_opc_markers_top50_wm)
bican_recon_opc_markers_top50_gm= rownames(bican_recon_opc_markers_top50_gm)
bican_recon_oligo_markers_top50_wm= rownames(bican_recon_oligo_markers_top50_wm)
bican_recon_oligo_markers_top50_gm= rownames(bican_recon_oligo_markers_top50_gm)
bican_recon_mg_markers_top50_wm= rownames(bican_recon_mg_markers_top50_wm)
bican_recon_mg_markers_top50_gm= rownames(bican_recon_mg_markers_top50_gm)

library(UCell)

All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_astro_markers_filtered_wm), name = 'filtered_astro_recon_wm')
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_astro_markers_filtered_gm), name = 'filtered_astro_recon_gm')
```

```{r}
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'bican_recon_astro_markers_top50_wm')
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_astro_markers_filtered_gm), name = 'bican_recon_astro_markers_filtered_gm')
```




```{r}
All_XDP_Cohorts_DFC <- AddModuleScore_UCell(All_XDP_Cohorts_DFC, features = list(Score = bican_recon_astro_markers_filtered_wm), name = 'filtered_astro_recon_wm')
All_XDP_Cohorts_DFC <- AddModuleScore_UCell(All_XDP_Cohorts_DFC, features = list(Score = bican_recon_astro_markers_filtered_gm), name = 'filtered_astro_recon_gm')

All_XDP_Cohorts_SN <- AddModuleScore_UCell(All_XDP_Cohorts_SN, features = list(Score = bican_recon_astro_markers_filtered_wm), name = 'filtered_astro_recon_wm')
All_XDP_Cohorts_SN <- AddModuleScore_UCell(All_XDP_Cohorts_SN, features = list(Score = bican_recon_astro_markers_filtered_gm), name = 'filtered_astro_recon_gm')

```

```{r}
All_XDP_Cohorts@meta.data

```


```{r}


All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_astro_markers_top50_wm), name = 'top_50_astro_recon_wm')
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_astro_markers_top50_gm), name = 'top_50_astro_recon_gm')

All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_opc_markers_top50_wm), name = 'top_50_opc_recon_wm')
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_opc_markers_top50_gm), name = 'top_50_opc_recon_gm')

All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_oligo_markers_top50_wm), name = 'top_50_oligo_recon_wm')
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_oligo_markers_top50_gm), name = 'top_50_oligo_recon_gm')

All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_mg_markers_top50_wm), name = 'top_50_mg_recon_wm')
All_XDP_Cohorts <- AddModuleScore_UCell(All_XDP_Cohorts, features = list(Score = bican_recon_mg_markers_top50_gm), name = 'top_50_mg_recon_gm')

```


```{r}
All_XDP_Cohorts@meta.data
```

```{r}
All_XDP_Cohorts_neurons = subset(All_XDP_Cohorts, final_cell_class_merged_harmony == "neuron")

DefaultAssay(All_XDP_Cohorts_neurons) = "RNA"
All_XDP_Cohorts_neurons
```
```{r}
hvgs = getSeuratVarFeatureIntersectByCol(All_XDP_Cohorts_neurons, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
All_XDP_Cohorts_neurons = (All_XDP_Cohorts_neurons
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(All_XDP_Cohorts_neurons, group.by = "donor_id") 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(All_XDP_Cohorts_neurons, group.by = "RNA_snn_res.0.8", label=T) 

FeaturePlot(All_XDP_Cohorts_neurons, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("OLIG1", "MOG", "MOBP", "MBP"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("pct_mito", "pct_intronic", "nUmi"),raster=FALSE) 

```

```{r}
FeaturePlot(All_XDP_Cohorts_neurons, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE)
FeaturePlot(All_XDP_Cohorts_neurons, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("P2RY12", "CX3CR1", "C1QB", "BCAS1"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("SEMA5B", "KREMEN1", "PDE1C"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("TAC1", "NNAT", "OPRM1", "ID4"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("SGK1", "EPHA4", "SV2B", "CHAT"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("SST", "CALB1", "PVALB", "LAMP5"),raster=FALSE) 
FeaturePlot(All_XDP_Cohorts_neurons, features = c("pct_mito"),raster=FALSE) 

```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "VCAN")

Dotplot = DotPlot(object = All_XDP_Cohorts_neurons, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)


 marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6","AQP4", "GINS3", "GFAP","C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5", "OLIG1", "MOG", "MOBP", "OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG","CD96", "NKG7", "SKAP1")
 Dotplot = DotPlot(object = All_XDP_Cohorts_neurons, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
Idents(All_XDP_Cohorts_neurons) = All_XDP_Cohorts_neurons$RNA_snn_res.0.3

classes = c("D2_matrix", "D1_matrix", "eSPN", "SPN_junk", "D2_patch", "D2_matrix", "non_SPN", "non_SPN", "non_SPN", "D2_eSPN", "non_SPN", "glutamatergic", "D1_D2", "cholinergic", "doublet", "doublet", "doublet", "doublet", "D2_patch")

All_XDP_Cohorts_neurons= assignCellClasses(All_XDP_Cohorts_neurons, classes=classes, cluster_col="RNA_snn_res.0.3", class_col = "neuron_cell_class")

DimPlot(All_XDP_Cohorts_neurons, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "CHAT")

Dotplot = DotPlot(object = All_XDP_Cohorts_neurons, features = marker_genes, group.by = "neuron_cell_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
All_XDP_Cohorts_neurons = subset(All_XDP_Cohorts_neurons, subset = neuron_cell_class != "doublet")
All_XDP_Cohorts_neurons
DimPlot(All_XDP_Cohorts_neurons, group.by = "neuron_cell_class")
```
```{r}
All_XDP_Cohorts_allelse = subset(All_XDP_Cohorts, final_cell_class_merged_harmony != "neuron")

DefaultAssay(All_XDP_Cohorts_allelse) = "RNA"
All_XDP_Cohorts_allelse
```


```{r}
sobj_list = list(All_XDP_Cohorts_neurons,
All_XDP_Cohorts_allelse)

counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))

merged_counts <- do.call(cbind, counts_list)

metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)

merged_metadata <- do.call(rbind, metadata_list)
merged_metadata

stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))

# Create Seurat object
All_XDP_Cohorts_bennett <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
All_XDP_Cohorts_bennett
```

```{r}
# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(All_XDP_Cohorts_bennett, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
All_XDP_Cohorts_bennett = (All_XDP_Cohorts_bennett
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(All_XDP_Cohorts_bennett, group.by = "donor_id") 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.2", label=T) 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.3", label=T) 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.4", label=T) 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.5", label=T) 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.6", label=T) 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.7", label=T) 
DimPlot(All_XDP_Cohorts_bennett, group.by = "RNA_snn_res.0.8", label=T)
DimPlot(All_XDP_Cohorts_bennett, group.by = "final_cell_class_merged_harmony", label=T)
DimPlot(All_XDP_Cohorts_bennett, group.by = "cell_class", label=T)
DimPlot(All_XDP_Cohorts_bennett, group.by = "neuron_cell_class", label=T)
DimPlot(All_XDP_Cohorts_bennett, group.by = "class_label_name", label=T)
DimPlot(All_XDP_Cohorts_bennett, group.by = "subclass_label_name", label=T)
DimPlot(All_XDP_Cohorts_bennett, group.by = "group_label_name", label=T)
```
```{r}
All_XDP_Cohorts_bennett@meta.data
```

```{r}
colnames(All_XDP_Cohorts_bennett@meta.data) <- tolower(colnames(All_XDP_Cohorts_bennett@meta.data))
All_XDP_Cohorts_bennett@meta.data
```

```{r}
All_XDP_Cohorts_bennett@meta.data$final_cell_class_merged= NULL
All_XDP_Cohorts_bennett@meta.data$final_cell_class_merged_harmony= NULL
All_XDP_Cohorts_bennett@meta.data
```

```{r}
qsave(All_XDP_Cohorts_bennett, "All_XDP_Cohorts_CaH_Put_final.qs")
```

```{r}
All_XDP_Cohorts_bennett
```

