---
title: "R Notebook"
output: html_notebook
---

```{r}
bican_recon = qread("Current_sobj/bican_recon_250331_sct_mask.qs")
bican_recon
bican_recon@meta.data
```


```{r}
bican_recon@meta.data$GM_WM = bican_recon@meta.data$gray_matter_roi
bican_recon@meta.data$GM_WM[bican_recon@meta.data$GM_WM == TRUE] = "Gray_Matter"
bican_recon@meta.data$GM_WM[bican_recon@meta.data$GM_WM == FALSE] = "White_Matter"
bican_recon@meta.data
```

```{r}
ggplot(bican_recon@meta.data, aes(x = x_um, y = y_um, color =GM_WM)) +geom_point(alpha = 0.5, size = 0.3) + facet_wrap(~ cell_class_annot)
```

```{r}
bican_recon_opc = subset(bican_recon, subset = cell_class_annot == "opc")
bican_recon_opc
```

```{r}
ggplot(bican_recon_opc@meta.data, aes(x = x_um, y = y_um, color =cell_class_annot)) +geom_point(alpha = 0.5, size = 0.3) + facet_wrap(~ GM_WM)
```

```{r}
Idents(bican_recon_opc) = "GM_WM"
markers = FindAllMarkers(bican_recon_opc, only.pos = TRUE, min.pct = 0.2, logfc.threshold = 1.25)
markers
```
```{r}
markers_filtered = subset(markers, subset = pct.1 > 0.6)
markers_filtered
markers_filtered_2 = subset(markers_filtered, subset = pct.2 < 0.3)
markers_filtered_2
```

```{r}
DimPlot(bican_recon, group.by = "cell_class_annot", raster = F)
DimPlot(bican_recon, group.by = "GM_WM", raster = F)
FeaturePlot(bican_recon, features = c("CDH19", "IGF2BP2"), raster = F)
FeaturePlot(bican_recon, features = c("MIR3681HG", "ENSG00000286778", "SGCZ", "PBX3"), raster = F)
FeaturePlot(bican_recon, features = c("LNX1", "CACNB2", "EYA2"), raster = F)
```

```{r}
rm(bican_recon)
gc()
```


```{r}
WM_opc_markers = c("CDH19", "IGF2BP2")
GM_opc_markers = c("MIR3681HG", "ENSG00000286778", "SGCZ", "PBX3", "LNX1", "CACNB2", "EYA2")
```

```{r}
XDP_Cohorts_1_2_full= qread("XDP_Cohorts_1_2_full_032825.qs")
XDP_Cohorts_1_2_full@meta.data
XDP_opc_Cohorts_1_2 = subset(XDP_Cohorts_1_2_full, subset = final_cell_class_merged_harmony == "opc")
XDP_opc_Cohorts_1_2
```
```{r}
FeaturePlot(XDP_Cohorts_1_2_full, features = c("CDH19", "IGF2BP2"), raster = F)
FeaturePlot(XDP_Cohorts_1_2_full, features = c("MIR3681HG", "ENSG00000286778", "SGCZ", "PBX3"), raster = F)
FeaturePlot(XDP_Cohorts_1_2_full, features = c("LNX1", "CACNB2", "EYA2"), raster = F)
```


```{r}
XDP_opc_Cohorts_1_2 <- AddModuleScore_UCell(XDP_opc_Cohorts_1_2, features = list(Score = WM_opc_markers), name = 'WM')
XDP_opc_Cohorts_1_2 <- AddModuleScore_UCell(XDP_opc_Cohorts_1_2, features = list(Score = GM_opc_markers), name = 'GM')

XDP_opc_Cohorts_1_2@meta.data

FeaturePlot(XDP_opc_Cohorts_1_2, features = c("ScoreWM", "ScoreGM"), raster = F)
```
```{r}
XDP_opc_meta = XDP_opc_Cohorts_1_2@meta.data
```

```{r}
hvgs = getSeuratVarFeatureIntersectByCol(XDP_opc_Cohorts_1_2, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
XDP_opc_Cohorts_1_2 = (XDP_opc_Cohorts_1_2
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_CaH_Cohort2$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_CaH_Cohort2$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(XDP_opc_Cohorts_1_2, group.by = "donor_id") 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.2", label=T) 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.3", label=T) 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.4", label=T) 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.5", label=T) 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.6", label=T) 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.7", label=T) 
DimPlot(XDP_opc_Cohorts_1_2, group.by = "SCT_snn_res.0.8", label=T)
FeaturePlot(XDP_opc_Cohorts_1_2, features = c("ScoreWM", "ScoreGM"), raster = F)
```


```{r}
rm(XDP_Cohorts_1_2_full)
gc()
```


```{r}
xdp_recon = qread("xdp_recon_full_mar2025.qs")
xdp_recon@meta.data

xdp_recon_meta = xdp_recon@meta.data
```


```{r}
xdp_recon_opc = subset(xdp_recon, subset =new_cell_class == "opc")
xdp_recon_opc
```

```{r}
xdp_recon_opc <- AddModuleScore_UCell(xdp_recon_opc, features = list(Score = WM_opc_markers), name = 'WM')
xdp_recon_opc <- AddModuleScore_UCell(xdp_recon_opc, features = list(Score = GM_opc_markers), name = 'GM')
xdp_recon_opc@meta.data

ggplot(xdp_recon_opc@meta.data, aes(x= x_um, y = y_um, color = ScoreWM)) + geom_point(size = 0.5) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "WM Score") +  theme_void() + ylab(NULL) 


ggplot(xdp_recon_opc@meta.data, aes(x= x_um, y = y_um, color = ScoreGM)) + geom_point(size = 0.5) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "GM Score") +  theme_void() + ylab(NULL) 

```

```{r}
hvgs = getSeuratVarFeatureIntersectByCol(xdp_recon_opc, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
xdp_recon_opc = (xdp_recon_opc
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_CaH_Cohort2$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_CaH_Cohort2$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.2", label=T) 
DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.3", label=T) 
DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.4", label=T) 
DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.5", label=T) 
DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.6", label=T) 
DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.7", label=T) 
DimPlot(xdp_recon_opc, group.by = "SCT_snn_res.0.8", label=T)
FeaturePlot(xdp_recon_opc, features = c("ScoreWM", "ScoreGM"), raster = F)
```



```{r}
xdp_recon_opc_WMGM = select(xdp_recon_opc@meta.data, c("ScoreWM", "ScoreGM", "ScoreWIF1", "ScoreTNC"))
xdp_recon_opc_WMGM
```

```{r}
FeaturePlot(xdp_recon, features = c("WIF1", "TNC"), raster = F)
```

```{r}
rm(xdp_recon)
gc()
```


```{r}
bican_recon = qread("bican_recon_mar2025_sct.qs")
bican_recon_opc = subset(bican_recon, subset =cell_class_annot == "opc")
bican_recon_opc

bican_recon_opc <- AddModuleScore_UCell(bican_recon_opc, features = list(Score = WM_opc_markers), name = 'WM')
bican_recon_opc <- AddModuleScore_UCell(bican_recon_opc, features = list(Score = GM_opc_markers), name = 'GM')

bican_recon_opc@meta.data

ggplot(bican_recon_opc@meta.data, aes(x= x_um, y = y_um, color = ScoreWM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "WM Score") +  theme_void() + ylab(NULL) 


ggplot(bican_recon_opc@meta.data, aes(x= x_um, y = y_um, color = ScoreGM)) + geom_point(size = 0.2) + scale_color_gradientn(colors = c("gray","#FFD700", "#87CEEB", "#4682B4", "#0000FF")) +   labs(color = "GM Score") +  theme_void() + ylab(NULL) 
```


```{r}
bican_recon_opc@meta.data$donor_id = "BICAN_donor"
hvgs = getSeuratVarFeatureIntersectByCol(bican_recon_opc, subset_col="donor_id", original_nfeatures=2500)
n_dims_use=20
bican_recon_opc = (bican_recon_opc
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.2) # finds clusters at a variety of resolutions
   %>% FindClusters(resolution = 0.3) # after clustering, the cluster labels are accessible via filtered_CaH_Cohort2$RNA_snn_res.{resolution}
   %>% FindClusters(resolution = 0.4) # e.g.: filtered_CaH_Cohort2$RNA_snn_res.0.4 here
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)

setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.2", label=T) 
DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.3", label=T) 
DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.4", label=T) 
DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.5", label=T) 
DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.6", label=T) 
DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.7", label=T) 
DimPlot(bican_recon_opc, group.by = "SCT_snn_res.0.8", label=T)
FeaturePlot(bican_recon_opc, features = c("ScoreWM", "ScoreGM"), raster = F)
```



```{r}
XDP_opc_Cohorts_1_2@meta.data
bican_recon_opc@meta.data
xdp_recon_opc@meta.data
```


```{r}
bican_recon_opc_WMGM = select(bican_recon_opc@meta.data, c("ScoreWM", "ScoreGM", "donor_id", "x_um", "y_um"))
bican_recon_opc_WMGM$Condition = "Control"
bican_recon_opc_WMGM$Cohort = "BICAN_Recon"
bican_recon_opc_WMGM$Cohort_Condition = "BICAN_Recon"

xdp_recon_opc_WMGM = select(xdp_recon_opc@meta.data, c("ScoreWM", "ScoreGM", "donor_id",  "x_um", "y_um"))
xdp_recon_opc_WMGM$Condition = "XDP"
xdp_recon_opc_WMGM$Cohort = "XDP_Recon"
xdp_recon_opc_WMGM$Cohort_Condition = "XDP_Recon"

XDP_opc_Cohorts_1_2_WMGM = select(XDP_opc_Cohorts_1_2@meta.data, c("ScoreWM", "ScoreGM", "donor_id", "Condition", "Cohort"))
XDP_opc_Cohorts_1_2_WMGM$Cohort_Condition = paste0(XDP_opc_Cohorts_1_2_WMGM$Cohort, "_", XDP_opc_Cohorts_1_2_WMGM$Condition)
XDP_opc_Cohorts_1_2_WMGM$x_um = NA
XDP_opc_Cohorts_1_2_WMGM$y_um = NA 

bican_recon_opc_WMGM
xdp_recon_opc_WMGM
XDP_opc_Cohorts_1_2_WMGM
```


```{r}
WMGM_opc_all = rbind(XDP_opc_Cohorts_1_2_WMGM, bican_recon_opc_WMGM, xdp_recon_opc_WMGM)
WMGM_opc_all
```


```{r}
newdf = subset(WMGM_opc_all, subset = Condition == "Control")
newdf
```

```{r}
table(newdf$Cohort_Condition)
```

```{r}
min = 0.001
max = max(newdf$ScoreWM)
step = (max-min)/100

limits = seq(min, max, step)

 a= plot_overlapping_density_histogram(df = newdf, 
                                          hist_col = newdf$ScoreWM,
                                          fill_col = "Cohort_Condition",
                                  colors = c("Cohort_1_XDP" = "red", "Cohort_2_XDP" = "orange", "XDP_Recon" = "pink", "Cohort_1_Control" = "blue","Cohort_2_Control" = "cyan", "BICAN_Recon" = "green"),
                                          breaks = limits,
                                          title = "Control OPC",
                                          xlab = "WM Score",
                                          fig_filename = NULL) + facet_wrap(~ Cohort_Condition)
 print(a)
 ggsave(a, filename = "a.png", width = 8, height = 5)
```

```{r}
WMGM_opc_all$WM_GM_test <- ifelse(
  WMGM_opc_all$ScoreWM > WMGM_opc_all$ScoreGM, "White Matter", 
  ifelse(WMGM_opc_all$ScoreGM > WMGM_opc_all$ScoreWM, "Gray Matter", "Uncertain")
)
WMGM_opc_all

 p = ggplot(WMGM_opc_all, aes(x = ScoreWM, y = ScoreGM, color = WM_GM_test)) +
  geom_point(alpha = 0.5) 
p1 = ggMarginal(p, type="histogram" , xparams = list(  bins=100))
print(p1)
```

```{r}
WMGM_opc_all$Cohort[WMGM_opc_all$Cohort == "BICAN_Recon"] = "Recon"
WMGM_opc_all$Cohort[WMGM_opc_all$Cohort == "XDP_Recon"] = "Recon"

```

```{r}
table(WMGM_opc_all$Cohort_Condition)

WMGM_opc_all$donor_id[WMGM_opc_all$Cohort_Condition == "XDP_Recon"] = "XDP_Recon"
```


```{r}
WMGM_opc_recon = subset(WMGM_opc_all, Cohort == "Recon")
a = ggplot(WMGM_opc_recon, aes(x = x_um, y = y_um, color = WM_GM_test)) + geom_point(size = 0.3, alpha = 0.5)+ facet_wrap(~ Cohort_Condition)

ggsave(a, filename = "pic.png", width = 10, height = 4.5)
```

```{r}
table(WMGM_opc_all$donor_id, WMGM_opc_all$WM_GM_test)
```



```{r}
cells_per_donor = as.data.frame(table(WMGM_opc_all$donor_id))
cells_per_donor

cell_class_df = as.data.frame(table(WMGM_opc_all$WM_GM, WMGM_opc_all$donor_id))


cell_class_df = merge(cell_class_df, cells_per_donor, by.x="Var2", by.y = "Var1")
cell_class_df

cell_class_df$cell_proportions = cell_class_df$Freq.x/cell_class_df$Freq.y
cell_class_df

cell_class_df$Cohort <- WMGM_opc_all$Cohort[match(cell_class_df$Var2, WMGM_opc_all$donor_id)]

cell_class_df$Cohort_Condition <- WMGM_opc_all$Cohort_Condition[match(cell_class_df$Var2, WMGM_opc_all$donor_id)]

cell_class_df$Sex <- WMGM_opc_all$Sex[match(cell_class_df$Var2, WMGM_opc_all$donor_id)]

cell_class_df$Condition <- WMGM_opc_all$Condition[match(cell_class_df$Var2, WMGM_opc_all$donor_id)]

cell_class_df
cell_class_df$Var2[is.na(cell_class_df$Var2)] = "XDP_Recon"
cell_class_df

# Count the number of cells per donor
donor_counts <- table(WMGM_opc_all$donor_id)

# Convert to dataframe for sorting
donor_df <- as.data.frame(donor_counts)
colnames(donor_df) <- c("donor_id", "cell_count")

# Identify controls (CM, CF) - ensuring it only checks ENDING
controls <- donor_df[grepl("CM$|CF$|CM2$", donor_df$donor_id), ]
cases <- donor_df[!grepl("CM$|CF$|CM2$", donor_df$donor_id), ]


# Sort both groups by cell count in descending order
controls <- controls[order(-controls$cell_count), ]
cases <- cases[order(-cases$cell_count), ]


# Combine ordered donor IDs
ordered_donors <- c(controls$donor_id, cases$donor_id)

# Print or use the ordered donor IDs
print(ordered_donors)
            
cell_class_df$Var2 = factor(cell_class_df$Var2, levels = ordered_donors)
# Extract Cohort information
cell_class_df <- cell_class_df %>%
  arrange(Cohort, match(Var2, ordered_donors)) %>%
  mutate(Var2 = factor(Var2, levels = unique(Var2))) 

astro_labels <- cell_class_df %>%
  filter(Var1 == "White Matter") %>%
  mutate(y_mid = cell_proportions / 2) 

cell_class_df



```




```{r}
a = ggplot(cell_class_df, aes(x = Var2, y = Freq.x, fill = Var1)) +
  geom_bar(stat = "identity") + xlab("Donors") + ylab("Number of cells by OPC WM GM") + labs(fill = "OPC WM GM") +theme(axis.text.x = element_text(angle = 45, hjust = 1))  +facet_grid(~ Cohort, scales = "free_x", space = "free_x")+ geom_text(data = cell_class_df, aes(x = Var2, y = Freq.y, label = Freq.y), vjust = -0.2, size = 3, nudge_y = 0.5) + ylim(0,1000)

b= ggplot(cell_class_df, aes(x = Var2, y = cell_proportions, fill = Var1)) +
  geom_bar(stat = "identity", postion= "stack") + xlab("Donors") + ylab("OPC WM GM Proportion") + labs(fill = "OPC WM GM")+ theme(axis.text.x = element_text(angle = 45, hjust = 1))   + facet_grid(~ Cohort, scales = "free_x", space = "free_x")+ geom_text(
    data = astro_labels,  
    aes(x = Var2, y = y_mid, label = round(cell_proportions, 2)),  # Correctly centered text
    size = 3
  )

ggsave(a, filename = "pic.png", width = 14, height = 5)
ggsave(b, filename = "pic2.png", width = 14, height = 5)
```


```{r}
WMGM_opc_all$cell_id = rownames(WMGM_opc_all)
WMGM_opc_all
all_regions = select(everything_metadata_new_astrocytes, c("CAP_Region"))
all_regions$cell_id = rownames(all_regions)
all_regions

WMGM_opc_all_regions = left_join(WMGM_opc_all, all_regions, by = "cell_id")
WMGM_opc_all_regions

rownames(WMGM_opc_all_regions) = WMGM_opc_all_regions$cell_id
WMGM_opc_all_regions
```


#um no
```{r}
data = WMGM_opc_all_regions
region = "Gray Matter"
score_col = "ScoreWM"
ylab = "ScoreWM"
titl = "ScoreWM in Astrocytes"
  
df = subset(data, subset = WM_GM_test == region)
df_avg <- df %>%
  group_by(donor_id, Condition, Cohort, Cohort_Condition, WM_GM_test) %>%
  summarise(avg_score = mean(.data[[score_col]]), .groups = 'drop')
df_avg


# Plot the average score per donor for each condition
a = ggplot(df_avg, aes(x = Cohort_Condition, y = avg_score, color = Condition, shape = Cohort)) +
  geom_point(aes(group = donor_id), size = 3, alpha = 0.8) + scale_color_manual(values = rev(scales::hue_pal()(2)))+ # One point per donor
  labs(x = "Cohort_Condition", y = paste0("Mean ", ylab), color = "Condition", shape = "Cohort", title =titl)+ scale_shape_manual(values = rev(c(16, 17, 18))) +
  theme_minimal()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))  + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 14),  # Increase tick label font size
            axis.title = element_text(size = 15),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1)  # tilt axis labels
        )+
  theme(
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18),  # Increase legend title size
   # legend.key.size = unit(1.5, "cm")  # Increase legend key size
  ) + facet_wrap(~ WM_GM_test)

print(a)

ggsave(a, filename = "dotplot.png", width = 7, height = 6)
```

```{r}
xdp_meta = subset(df_avg, Cohort == "Cohort_2")
xdp_meta

xdp_meta_cases = subset(xdp_meta, Condition == "XDP")
xdp_meta_controls = subset(xdp_meta, Condition == "Control")
xdp_meta_cases
xdp_meta_controls

XDP_scores <- xdp_meta_cases$avg_score  
XDP_Control_scores <- xdp_meta_controls$avg_score 

result1 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "less")
result3 <- wilcox.test(XDP_scores, XDP_Control_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)

```









#mapmycells

```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("zellkonverter")
```


```{r}
library(zellkonverter)

# function convert seurat object to h5ad
# input: obj, output_dir
# output: NA (saves .h5ad to output_dir)
seurat_to_h5ad = function(obj, output_dir) {
  sce <- as.SingleCellExperiment(obj)
  writeH5AD(sce, output_dir)
}
```

```{r}
xdp_neurons = qread("XDP_neurons_Cohorts_1_2_sct_ucell_032125.qs")
xdp_neurons
DefaultAssay(xdp_neurons) = "RNA"
xdp_neurons
```


```{r}
seurat_to_h5ad(xdp_neurons, "xdp_neurons.h5ad")
```


```{r}

```


```{r}
./mapmycells.sh --ref /broad/macosko/kimkathl/hmba_ref.h5ad --query /broad/macosko/kimkathl/xdp_neurons.h5ad -o /broad/macosko/kimkathl/output_directory
```


```{r}
# Load Seurat object
seurat_obj <- qread("cell_type_mapper/hmba_neuron.qs")
DefaultAssay(seurat_obj) <- "RNA"

# Keep only the RNA assay
# if seurat object version is 5 or later, counts is accessed with $, 4 or earlier with @

if (seurat_obj@version >= 5) {
    seurat_obj[["RNA"]] <- CreateAssayObject(counts = seurat_obj@assays$RNA$counts)
} else {
    seurat_obj[["RNA"]] <- CreateAssayObject(counts = seurat_obj@assays$RNA@counts)
}


# Remove all other assays
seurat_obj@assays <- list(RNA = seurat_obj[["RNA"]])

# Ensure metadata is properly aligned
if (!all(rownames(seurat_obj@meta.data) == colnames(seurat_obj))) {
    stop("Cell names in meta.data do not match counts matrix! Check alignment.")
}

# Save the cleaned Seurat object
SaveH5Seurat(seurat_obj, filename = "hmba_neuron.h5Seurat", overwrite = TRUE)
#SaveH5Seurat(seurat_obj, filename = h5seurat_fname, overwrite = TRUE)

# Convert to H5AD
#Convert(h5seurat_fname, dest = "h5ad", overwrite = TRUE)
Convert("hmba_neuron.h5Seurat", dest = "h5ad", overwrite = TRUE)
```

```{r}
chmod +x run_mapmycells.sh
path/to/run_mapmycells.sh --ref path/to/hmba_ref.h5ad --query path/to/merged_caudate_putamen_v1_v2_neurons.h5ad -o output/directory



  25424     disco map_cell kimkathl  R       1:58      1 slurm-bits-rh7-d002


#!/bin/bash
#SBATCH --job-name=map_cells         # Job name
#SBATCH --output=map_cells_%j.out    # Output log file (%j inserts job ID)
#SBATCH --error=map_cells_%j.err     # Error log file
#SBATCH --time=4:00:00               # Max runtime (HH:MM:SS)
#SBATCH --mem=128G                   # Memory (adjust as needed)
#SBATCH --cpus-per-task=16           # Number of CPU cores
#SBATCH --partition=compute          # Adjust to your cluster's partition

# Activate Conda environment (if needed)
source ~/.bashrc
conda activate cell_mapping_env  # Replace with your actual Conda env

# Run the mapping script
bash run_map_my_cells.sh -r reference.h5ad -q query.h5ad -o output_dir




bash /broad/macosko/kimkathl/cell_type_mapper/run_mapmycells.sh --ref /broad/macosko/kimkathl/hmba_neuron.h5ad --query /broad/macosko/kimkathl/xdp_neurons_mmc.h5ad -o /broad/macosko/kimkathl/new_output

```









```{r}
#mapping_output doesn't have labels, just id numbers
mapping_output_cohort1_2_neurons = read.csv(file = "mapping_output.csv", skip = 3)
mapping_output_cohort1_2_neurons

mapping_output_cohort1_2_neurons$Group_id = mapping_output_cohort1_2_neurons$Group_label_label
mapping_output_cohort1_2_neurons$Group_label_label = NULL
mapping_output_cohort1_2_neurons$Subclass_id = mapping_output_cohort1_2_neurons$Subclass_label_label
mapping_output_cohort1_2_neurons$Subclass_label_label = NULL
mapping_output_cohort1_2_neurons$Class_id = mapping_output_cohort1_2_neurons$Class_label_label
mapping_output_cohort1_2_neurons$Class_label_label = NULL
mapping_output_cohort1_2_neurons
```


```{r}
table(seurat_obj@meta.data$Class_id)
```


```{r}
hmba_reference_ids = seurat_obj@meta.data %>%
  distinct(Class_id, Class_label, Subclass_id, Subclass_label, Group_id, Group_label) 

hmba_reference_ids = as.data.frame(hmba_reference_ids)
hmba_reference_ids

```

```{r}
library(dplyr)

merged_df <- mapping_output_cohort1_2_neurons %>%
  left_join(hmba_reference_ids %>% distinct(Group_id, Group_label), by = "Group_id") %>%
  left_join(hmba_reference_ids %>% distinct(Subclass_id, Subclass_label), by = "Subclass_id") %>%
  left_join(hmba_reference_ids %>% distinct(Class_id, Class_label), by = "Class_id") %>%
  mutate(
    Group_label_label = Group_label,
    Subclass_label_label = Subclass_label,
    Class_label_label = Class_label
  ) %>%
  select(-Group_label, -Subclass_label, -Class_label)  # Remove redundant columns
merged_df
```

```{r}
setdiff(mapping_output_cohort1_2_neurons$Group_id, hmba_reference_ids$Group_id)
setdiff(mapping_output_cohort1_2_neurons$Subclass_id, hmba_reference_ids$Subclass_id)
setdiff(mapping_output_cohort1_2_neurons$Class_id, hmba_reference_ids$Class_id)
```


```{r}
table(merged_df$Class_id)
table(merged_df$Class_label_label)
table(merged_df$Subclass_id)
table(merged_df$Subclass_label_label)
table(merged_df$Group_id)
table(merged_df$Group_label_label)
```
```{r}
table(seurat_obj$Donor_id)
```



```{r}
mmc_co1_2_neurons_result = select(merged_df, c("cell_id","Class_label_label", "Subclass_label_label","Group_label_label", "Class_label_bootstrapping_probability", "Subclass_label_bootstrapping_probability", "Group_label_bootstrapping_probability"))
rownames(mmc_co1_2_neurons_result) = mmc_co1_2_neurons_result$cell_id
mmc_co1_2_neurons_result
```

```{r}
mmc_co1_2_neurons_result[is.na(mmc_co1_2_neurons_result$Group_label_label),]
```


```{r}
xdp_neurons <- AddMetaData(xdp_neurons, metadata = mmc_co1_2_neurons_result)
xdp_neurons@meta.data
```
```{r}
DimPlot(xdp_neurons, group.by = "final_neuron_cell_class_merged_harmony", label = T)
DimPlot(xdp_neurons, group.by = "final_neuron_subclass_merged", label = T)
DimPlot(xdp_neurons, group.by = "neuron_subclass_merged", label = T)
 DimPlot(xdp_neurons, group.by = "Class_label_label", label = T)
 DimPlot(xdp_neurons, group.by = "Subclass_label_label", label = T)
 DimPlot(xdp_neurons, group.by = "Group_label_label", label = T)

a = DimPlot(xdp_neurons, group.by = "Class_label_label", label = T)
ggsave(a, filename= "pic.png", width = 15, height = 10)

a = DimPlot(xdp_neurons, group.by = "Subclass_label_label", label = T)
ggsave(a, filename= "pic.png", width = 15, height = 10)

a = DimPlot(xdp_neurons, group.by = "Group_label_label", label = T)
ggsave(a, filename= "pic.png", width = 15, height = 10)
```







```{r}
Class_id -- > Class_label
Subclass_id --> Subclass_label
Group_id --> Group_label
```


```{r}
seurat_obj@meta.data
```




```{r}
xdp_co2_neurons_temp = xdp_co2_neurons
DefaultAssay(xdp_co2_neurons_temp) <- "RNA"  # Optional: set RNA as the default assay
xdp_co2_neurons_temp[["SCT"]] <- NULL
```
```{r}
xdp_co2_neurons_temp

```
```{r}
# Remove scale.data
Seurat::SetAssayData(xdp_co2_neurons_temp, assay = "RNA", slot = "scale.data", new.data = NULL)
Seurat::SetAssayData(xdp_co2_neurons_temp, assay = "RNA", slot = "data", new.data = NULL)
```
```{r}
# Remove dimensional reductions if not needed
xdp_co2_neurons_temp@reductions[["pca"]] <- NULL
xdp_co2_neurons_temp@reductions[["umap"]] <- NULL
xdp_co2_neurons_temp@reductions[["harmony"]] <- NULL

```


```{r}
xdp_co2_neurons_temp

```
```{r}
colnames(xdp_co2_neurons_temp@meta.data)
```

```{r}
xdp_co2_neurons_temp@meta.data$seurat_clusters = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.2 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.3 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.4 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.5 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.6 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.7 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.8 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.2 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.3 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.4 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.5 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.6 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.7 = NULL
xdp_co2_neurons_temp@meta.data$RNA_snn_res.0.8 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.05 = NULL
xdp_co2_neurons_temp@meta.data$SCT_snn_res.0.1 = NULL
xdp_co2_neurons_temp@meta.data$Pedigree...if.enrolled = NULL
xdp_co2_neurons_temp@meta.data$Brain.Code = NULL
xdp_co2_neurons_temp@meta.data$ScoreNFKB = NULL
xdp_co2_neurons_temp@meta.data$antigen_processing_scores = NULL
xdp_co2_neurons_temp@meta.data$Scoreinterferon_alpha = NULL
```

```{r}
xdp_co2_neurons_temp
```
```{r}
# Keep only 'counts' layer
DefaultAssay(xdp_co2_neurons_temp) <- "RNA"

Layers(xdp_co2_neurons_temp[["RNA"]])

xdp_co2_neurons_temp[["RNA"]]@layers$data <- NULL
xdp_co2_neurons_temp[["RNA"]]@layers$scale.data <- NULL
xdp_co2_neurons_temp
```



```{r}
seurat_to_h5ad(xdp_co2_neurons_temp, "xdp_co2_neurons.h5ad")
```


```{r}
temp = xdp_co1_neurons
temp
```
```{r}
DefaultAssay(temp) <- "RNA"  # Optional: set RNA as the default assay
temp[["SCT"]] <- NULL
```

```{r}
# Keep only 'counts' layer
Layers(temp[["RNA"]])

```

```{r}
temp@reductions[["pca"]] <- NULL
temp@reductions[["umap"]] <- NULL
temp@reductions[["harmony"]] <- NULL

```


```{r}
temp@meta.data$seurat_clusters = NULL
temp@meta.data$SCT_snn_res.0.2 = NULL
temp@meta.data$SCT_snn_res.0.3 = NULL
temp@meta.data$SCT_snn_res.0.4 = NULL
temp@meta.data$SCT_snn_res.0.5 = NULL
temp@meta.data$SCT_snn_res.0.6 = NULL
temp@meta.data$SCT_snn_res.0.7 = NULL
temp@meta.data$SCT_snn_res.0.8 = NULL
temp@meta.data$RNA_snn_res.01.2 = NULL
temp@meta.data$RNA_snn_res.0.3 = NULL
temp@meta.data$RNA_snn_res.0.4 = NULL
temp@meta.data$RNA_snn_res.0.5 = NULL
temp@meta.data$RNA_snn_res.0.6 = NULL
temp@meta.data$RNA_snn_res.0.7 = NULL
temp@meta.data$RNA_snn_res.0.8 = NULL
temp@meta.data$SCT_snn_res.0.05 = NULL
temp@meta.data$SCT_snn_res.0.1 = NULL
temp@meta.data$Pedigree...if.enrolled = NULL
temp@meta.data$Brain.Code = NULL
temp@meta.data$ScoreNFKB = NULL
temp@meta.data$antigen_processing_scores = NULL
temp@meta.data$Scoreinterferon_alpha = NULL
```

```{r}
temp
library(Seurat)

# Subset the Seurat object to keep only the counts layer
temp <- DietSeurat(temp, counts = TRUE, data = FALSE, scale.data = FALSE)
temp
```
```{r}
temp@assays$RNA@data <- matrix(numeric(0), nrow = 0, ncol = 0)
temp
```


```{r}
seurat_to_h5ad(temp, "xdp_co1_neurons.h5ad")
```
```{r}
xdp_co1_mmc = read.csv("xdp_co1_neurons_10xWholeHumanBrain(CCN202210140)_HierarchicalMapping_UTC_1742929716462.csv")
xdp_co1_mmc
xdp_co2_mmc = read.csv("xdp_co2_neurons_10xWholeHumanBrain(CCN202210140)_HierarchicalMapping_UTC_1742928963154.csv")
xdp_co2_mmc
```
```{r}
table(xdp_co1_mmc$supercluster_name)
table(xdp_co2_mmc$supercluster_name)
```

```{r}
mapmycells_neurons_combined = rbind(xdp_co1_mmc,xdp_co2_mmc)
mapmycells_neurons_combined
```
```{r}
# Ensure rownames of df match cell barcodes in Seurat object
rownames(mapmycells_neurons_combined) <- mapmycells_neurons_combined$cell_id  # Set cell_id as rownames
mapmycells_neurons_combined$cell_id <- NULL          # Remove redundant column

# Add new metadata column(s)
XDP_neurons_Cohorts_1_2 <- AddMetaData(XDP_neurons_Cohorts_1_2, metadata = mapmycells_neurons_combined)

```


```{r}
table(XDP_neurons_Cohorts_1_2@meta.data$supercluster_name)
```

```{r}
DimPlot(XDP_neurons_Cohorts_1_2, group.by = "final_neuron_subclass_merged", label = T)
DimPlot(XDP_neurons_Cohorts_1_2, group.by = "supercluster_name", label = T)


```










