---
title: "R Notebook"
output: html_notebook
---
```{r}
pd_putamen_sobj = qread("~/pd_putamen_sobj_notscaled.qs")
pd_putamen_sobj
```

```{r}

hvgs = getSeuratVarFeatureIntersectByCol(pd_putamen_sobj, subset_col="donor_id", original_nfeatures=2500)


n_dims_use=20

pd_putamen_sobj = (pd_putamen_sobj
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.01) # finds clusters at a variety of resolutions
   #%>% FindClusters(resolution = 0.05) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
  # %>% FindClusters(resolution = 0.1) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
  #%>% FindClusters(resolution = 0.15)
  # %>% FindClusters(resolution = 0.2)
  # %>% FindClusters(resolution = 0.3)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)


# Now we can plot the data and just see what it looks like


setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

 head(pd_putamen_sobj)
```



```{r}
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.2", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.3", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.4", raster = F)
DimPlot(calico_putamen_integrated, group.by = "participant_id", raster = F)
DimPlot(calico_putamen_integrated, group.by = "sub_class", raster = F)
DimPlot(calico_putamen_integrated, group.by = "case_control", raster = F)
FeaturePlot(calico_putamen_integrated, features = c("SYT1","SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE)
FeaturePlot(calico_putamen_integrated, features = c("DRD1", "DRD2", "EPHA4", "SEMA3E"),raster=FALSE)
FeaturePlot(calico_putamen_integrated, features = c("QC_MT.pct", "nUMI"),raster=FALSE)

FeaturePlot(calico_putamen_integrated, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE,)
FeaturePlot(calico_putamen_integrated, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE,) 
FeaturePlot(calico_putamen_integrated, features = c("CACNG4", "SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE,)
FeaturePlot(calico_putamen_integrated, features = c("QC_MT.pct", "nUMI"),raster=FALSE,)
FeaturePlot(calico_putamen_integrated, features = c("LAMP5","VIP", "SST", "PVALB"),raster=FALSE)
```
```{r}
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.2", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.3", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.4", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.5", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.6", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.7", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.8", raster = F)
```


```{r}
Idents(calico_putamen_integrated) = calico_putamen_integrated$RNA_snn_res.0.4

classes = c("D1_matrix", "D2_matrix", "D2_matrix", "D1_matrix", "D2_patch", "D1_patch", "eSPN_1", "SPN_junk", "interneuron_1", "eSPN_2", "interneuron_2", "interneuron_3", "interneuron_4")
  

calico_putamen_integrated= assignCellClasses(calico_putamen_integrated, classes=classes, cluster_col="RNA_snn_res.0.4", class_col = "neuron_cell_class")

DimPlot(calico_putamen_integrated, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
FeaturePlot(calico_putamen_integrated, features = c("LAMP5", "PVALB", "VIP"), raster = FALSE)
FeaturePlot(calico_putamen_integrated, features = c("GAD1", "GAD2","SST", "CALB2"), raster = FALSE)
FeaturePlot(calico_putamen_integrated, features = c("CUX2", "SATB2","SLC17A7", "SLC17A6"), raster = FALSE)
```


```{r}
calico_putamen_integrated
calico_putamen_integrated = subset(calico_putamen_integrated, subset = neuron_cell_class != "SPN_junk")
calico_putamen_integrated
DimPlot(calico_putamen_integrated, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
table(calico_putamen_integrated$neuron_cell_class)
```

```{r}
calico_putamen_integrated@meta.data$patch_matrix = calico_putamen_integrated$neuron_cell_class
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "eSPN_1"] = "eSPN"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "eSPN_2"] = "eSPN"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "interneuron_1"] = "non-SPN"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "interneuron_2"] = "non-SPN"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "interneuron_3"] = "non-SPN"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "interneuron_4"] = "non-SPN"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "D1_matrix"] = "SPN_matrix"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "D2_matrix"] = "SPN_matrix"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "D1_patch"] = "SPN_patch"
calico_putamen_integrated$patch_matrix[calico_putamen_integrated$patch_matrix == "D2_patch"] = "SPN_patch"

table(calico_putamen_integrated$patch_matrix)
```

```{r}
DimPlot(calico_putamen_integrated, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
DimPlot(calico_putamen_integrated, group.by = "patch_matrix" ,label = T, raster = FALSE)
```


```{r}
qsave(calico_putamen_integrated, "~/pd_neurons_integrated_subclustered.qs")
```



```{r}
Intersected_BICAN_matrix_markers_final_filtered = qread("~/rstudio/workdir/Old Work/SPN_Matrix_BICAN_findmarkers.qs")
Intersected_BICAN_matrix_markers_final_filtered
spn_bican = rownames(Intersected_BICAN_matrix_markers_final_filtered)
```

```{r}
calico_putamen_integrated
calico_putamen_integrated = subset(calico_putamen_integrated, subset = participant_id != "PD0800")
calico_putamen_integrated
```


```{r}
Idents(calico_putamen_integrated) = "patch_matrix"
calico_putamen_integrated <- AddModuleScore(
  object = calico_putamen_integrated,
  features = list(SPN = spn_bican),
  name = 'SPN_Matrix_scores'
)

new_df = calico_putamen_integrated@meta.data 
new_df
```

```{r}
table(new_df$patch_matrix)
```


```{r}
min(new_df$SPN_Matrix_scores1)
max(new_df$SPN_Matrix_scores1)
```


```{r}
limits = seq(-0.15, 0.9, 0.01)

matrix <- new_df[new_df$patch_matrix == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  patch <- new_df[new_df$patch_matrix == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: SPN patch",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- new_df[new_df$patch_matrix == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  

    eSPN <- new_df[new_df$patch_matrix == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: eSPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
```



```{r}
DimPlot(calico_putamen_integrated, raster = FALSE)
```


```{r}
FeaturePlot(calico_putamen_integrated, features = c("SPN_Matrix_scores1", "QC_MT.pct","nUMI"), raster = FALSE)
```

```{r}
FeaturePlot(calico_putamen_integrated, features = c("SPN_Matrix_scores1"), raster = FALSE, split.by = "patch_matrix")
```

```{r}
  # Subset the data
  SPN_score_output_identity_loss_SPN <- subset(new_df, subset = SPN_Matrix_scores1 < 0.45 & patch_matrix == "SPN_matrix")
  
  print(SPN_score_output_identity_loss_SPN)
  print(table(SPN_score_output_identity_loss_SPN$participant_id))
  print(table(SPN_score_output_identity_loss_SPN$case_control))
```


```{r}
identity_loss_cells <- unique(rownames(SPN_score_output_identity_loss_SPN))
  
  calico_putamen_integrated@meta.data$SPN_identity <- "Other"
  calico_putamen_integrated$SPN_identity[identity_loss_cells] <- "Losing_Identity"
  calico_putamen_integrated@meta.data
```


```{r}
# Visualize on UMAP
  pic <- DimPlot(calico_putamen_integrated, reduction = "umap", group.by = "SPN_identity", split.by = "case_control", cols = c("red", "grey"))
  print(pic)
  ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
```

```{r}
pic = FeaturePlot(calico_putamen_integrated, features = c("QC_MT.pct","nUMI"), raster = FALSE)
print(pic)
 ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
```


```{r}
# Visualize on UMAP
  
what = subset(calico_putamen_integrated, subset = participant_id == "PD0800" & patch_matrix == "SPN_matrix")
DimPlot(what, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) + ggtitle("PD0800 SPN Matrix")

```






















```{r}
head(calico_putamen)
```

```{r}
table(calico_putamen$donor_id)
table(calico_putamen$participant_id)
```


```{r}
calico_putamen = normalizeScalePcaClusterUmap(calico_putamen, subset_col = "donor_id", resolutions = c(0.01, 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1))
DimPlot(calico_putamen)
DimPlot(calico_putamen, group.by = "participant_id", raster = F)
DimPlot(calico_putamen, group.by = "cell_class", raster = F)
DimPlot(calico_putamen, group.by = "library", raster = F)
c
```








