---
title: "R Notebook"
output: html_notebook
---

```{r}
calico_putamen
calico_putamen@meta.data
```


```{r}
Idents(calico_putamen) = "crude_cell_class"
DimPlot(calico_putamen, raster = F)
```



```{r}
.sconline.MASCfn = function(
    dataset, 
    cluster, 
    contrast, 
    random_effects = NULL, 
    fixed_effects = NULL,
    verbose = TRUE, 
    jackknife=F,
    statistical.test="Wald") {
  
  
  #Adapted from Fonseka et al. PMID: 30333237
  
  # Check inputs
  require(lme4)
  if (is.factor(dataset[[contrast]]) == FALSE & is.numeric(dataset[[contrast]]) == FALSE) {
    stop("Specified contrast term should be coded as a factor or numeric in the dataset")
  }
  
  match.arg(statistical.test,c("LRT","Wald"))
  
  
  # Convert cluster assignments to string
  cluster = as.character(cluster)
  # Prepend design matrix generated from cluster assignments
  designmat = model.matrix(~ cluster + 0, data.frame(cluster = cluster))
  dataset = cbind(designmat, dataset)
  # Create output list to hold results
  res = vector(mode = "list", length = length(unique(cluster)))
  names(res) = attributes(designmat)$dimnames[[2]]
  
  # Create model formulas
  if (!is.null(fixed_effects) && !is.null(random_effects)) {
    model_rhs = paste0(c(paste0(fixed_effects, collapse = " + "),
                          paste0("(1|", random_effects, ")", collapse = " + ")),
                        collapse = " + ")
    if (verbose == TRUE & statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
    }
  } else if (!is.null(fixed_effects) && is.null(random_effects)) {
    model_rhs = paste0(fixed_effects, collapse = " + ")
    if (verbose == TRUE&statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
      # For now, do not allow models without mixed effects terms
      
    }
    stop("No random effects specified")
  } else if (is.null(fixed_effects) && !is.null(random_effects)) {
    model_rhs = paste0("(1|", random_effects, ")", collapse = " + ")
    if (verbose == TRUE&statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
    }
  } else {
    model_rhs = "1" # only includes intercept
    if (verbose == TRUE&statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
      
    }
    stop("No random or fixed effects specified")
  }
  
  # Initialize list to store model objects for each cluster
  cluster_models = vector(mode = "list",
                           length = length(attributes(designmat)$dimnames[[2]]))
  names(cluster_models) = attributes(designmat)$dimnames[[2]]
  
  # Run nested mixed-effects models for each cluster
  for (i in seq_along(attributes(designmat)$dimnames[[2]])) {
    test_cluster = attributes(designmat)$dimnames[[2]][i]
    if (verbose == TRUE) {
      message(paste("Creating logistic mixed models for", test_cluster))
    }
    null_fm = as.formula(paste0(c(paste0(test_cluster, " ~ 1 + "),
                                   model_rhs), collapse = ""))
    full_fm = as.formula(paste0(c(paste0(test_cluster, " ~ ", contrast, " + "),
                                   model_rhs), collapse = ""))

    if (verbose == TRUE) {
      message(paste("Null model:", null_fm))
      message(paste("Full model:", full_fm))
    }
    
    # Run null and full mixed-effects models
    full_model = lme4::glmer(formula = full_fm, data = dataset,
                              family = binomial, nAGQ = 1, verbose = 0,
                              control = glmerControl(optimizer = "bobyqa"))
    
    
    # calculate confidence intervals for contrast term beta
    if(is.factor(dataset[[contrast]])){
      contrast_lvl2 = paste0(contrast, levels(dataset[[contrast]])[2])
      
    } else {
      contrast_lvl2 = contrast
    }
    
    contrast_ci = confint.merMod(full_model, method = "Wald",
                                  parm = contrast_lvl2)
    
    
    if(statistical.test=="Wald"){
      pval=summary(full_model)
      
      pval=pval$coefficients[contrast_lvl2,4]
    } else {
      null_model = lme4::glmer(formula = null_fm, data = dataset,
                                family = binomial, nAGQ = 1, verbose = 0,
                                control = glmerControl(optimizer = "bobyqa"))
      model_lrt = anova(null_model, full_model)
      pval=model_lrt[["Pr(>Chisq)"]][2]
    }
    
    # Save model objects to list
    cluster_models[[i]]$confint = contrast_ci
    cluster_models[[i]]$pval = pval
    cluster_models[[i]]$full_model = full_model
    
    #jackknifing
    jk_pvalvec=c()
    jk_coefvec=c()
    jk_stable=1
    if(jackknife){
      for(ibatch in unique(dataset[,random_effects])){
        tmp_dataset=dataset[which(dataset[,random_effects]!=ibatch),]
        
        jk_full_model = tryCatch({lme4::glmer(formula = full_fm, data = tmp_dataset,
                                               family = binomial, nAGQ = 1, verbose = 0,
                                               control = glmerControl(optimizer = "bobyqa"))},error=function(e){return(F)})
        
        if(class(jk_full_model)!=class(T)){
          jk_coefvec=c(jk_coefvec,fixef(jk_full_model)[[contrast_lvl2]])
          if(statistical.test=="Wald"){
            tmp_pval=summary(jk_full_model)
            tmp_pval=tmp_pval$coefficients[contrast_lvl2,4]
            jk_pvalvec=c(jk_pvalvec,tmp_pval)
          } else {
            jk_null_model = tryCatch({lme4::glmer(formula = null_fm, data = tmp_dataset,
                                                   family = binomial, nAGQ = 1, verbose = 0,
                                                   control = glmerControl(optimizer = "bobyqa"))},error=function(e) {return(F)})
            
            if(class(jk_null_model)!=class(T)){
              jk_model_lrt = anova(jk_null_model, jk_full_model)
              # calculate confidence intervals for contrast term beta
              jk_pvalvec=c(jk_pvalvec,jk_model_lrt[["Pr(>Chisq)"]][2])
            } else {
              jk_stable=0
            }
          }
          
        } else {
          jk_stable=0
        }
        
      }
    } else {
      jk_pvalvec=(-1)
      jk_coefvec=(-1)
    }
    
    cluster_models[[i]]$jk_pval_median = median(jk_pvalvec)
    cluster_models[[i]]$jk_pval_mean = mean(jk_pvalvec)
    cluster_models[[i]]$jk_pval_max = max(jk_pvalvec)
    
    cluster_models[[i]]$jk_coef_median = median(jk_coefvec)
    cluster_models[[i]]$jk_coef_mean = mean(jk_coefvec)
    cluster_models[[i]]$jk_stable = jk_stable
    cluster_models[[i]]$jk_coef_min = jk_coefvec[which(abs(jk_coefvec)==min(abs(jk_coefvec)))[1]]
  }
  
  # Organize results into output dataframe
  output = data.frame(cluster = attributes(designmat)$dimnames[[2]],
                       size = colSums(designmat))
  output$model.pvalue = sapply(cluster_models, function(x) x$pval)
  output[[paste(contrast_lvl2, "OR", sep = ".")]] = sapply(cluster_models, function(x) exp(fixef(x$full)[[contrast_lvl2]]))
  output[[paste(contrast_lvl2, "OR", "95pct.ci.lower", sep = ".")]] = sapply(cluster_models, function(x) exp(x$confint[contrast_lvl2, "2.5 %"]))
  output[[paste(contrast_lvl2, "OR", "95pct.ci.upper", sep = ".")]] = sapply(cluster_models, function(x) exp(x$confint[contrast_lvl2, "97.5 %"]))
  output[[paste(contrast_lvl2,"JK","Min", "OR", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_coef_min==(-1)){-1} else{exp(x$jk_coef_min)}})
  output[[paste(contrast_lvl2,"JK","Mean", "OR", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_coef_mean==(-1)){-1} else {exp(x$jk_coef_mean)}})
  output[[paste(contrast_lvl2,"JK","Median", "OR", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_coef_median==(-1)){-1} else {exp(x$jk_coef_median)}})
  output[[paste(contrast_lvl2,"JK","Max", "pvalue", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_pval_max==(-1)){-1} else {x$jk_pval_max}})
  output[[paste(contrast_lvl2,"JK","Mean", "pvalue", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_pval_mean==(-1)){-1} else {x$jk_pval_mean}})
  output[[paste(contrast_lvl2,"JK","Median", "pvalue", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_pval_median==(-1)){-1} else {x$jk_pval_median}})
  output[[paste(contrast_lvl2,"JK","Stable", sep = ".")]] = sapply(cluster_models, function(x) x$jk_stable)
  
  return(output)
}
```

```{r}
head(calico_putamen)
```
```{r}
table(calico_putamen$case_control)
```


```{r}
library(dplyr)
library(ggplot2)
library(lme4)
library(qs)
library(Seurat)

sobj = calico_putamen
model_cols = c("donor_id", "crude_cell_class", "case_control", "sex", "age") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj@meta.data[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$case_control)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$crude_cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects="donor_id", # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("sex", "age") # your covariates
)

masc_df
#write.csv(masc_df, "MASC/caudate_neurons_masc_df.csv")
```

```{r}
masc_df
```


```{r}
my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorpd.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorpd.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorpd.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df

library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black", size = 1) +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )
```

```{r}
write.csv(masc_df, "pd_masc.csv")
```

#neurons

```{r}
calico_putamen
calico_putamen@meta.data
```


```{r}
Idents(calico_putamen) = "crude_cell_class"
DimPlot(calico_putamen, raster = F)
```



```{r}
.sconline.MASCfn = function(
    dataset, 
    cluster, 
    contrast, 
    random_effects = NULL, 
    fixed_effects = NULL,
    verbose = TRUE, 
    jackknife=F,
    statistical.test="Wald") {
  
  
  #Adapted from Fonseka et al. PMID: 30333237
  
  # Check inputs
  require(lme4)
  if (is.factor(dataset[[contrast]]) == FALSE & is.numeric(dataset[[contrast]]) == FALSE) {
    stop("Specified contrast term should be coded as a factor or numeric in the dataset")
  }
  
  match.arg(statistical.test,c("LRT","Wald"))
  
  
  # Convert cluster assignments to string
  cluster = as.character(cluster)
  # Prepend design matrix generated from cluster assignments
  designmat = model.matrix(~ cluster + 0, data.frame(cluster = cluster))
  dataset = cbind(designmat, dataset)
  # Create output list to hold results
  res = vector(mode = "list", length = length(unique(cluster)))
  names(res) = attributes(designmat)$dimnames[[2]]
  
  # Create model formulas
  if (!is.null(fixed_effects) && !is.null(random_effects)) {
    model_rhs = paste0(c(paste0(fixed_effects, collapse = " + "),
                          paste0("(1|", random_effects, ")", collapse = " + ")),
                        collapse = " + ")
    if (verbose == TRUE & statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
    }
  } else if (!is.null(fixed_effects) && is.null(random_effects)) {
    model_rhs = paste0(fixed_effects, collapse = " + ")
    if (verbose == TRUE&statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
      # For now, do not allow models without mixed effects terms
      
    }
    stop("No random effects specified")
  } else if (is.null(fixed_effects) && !is.null(random_effects)) {
    model_rhs = paste0("(1|", random_effects, ")", collapse = " + ")
    if (verbose == TRUE&statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
    }
  } else {
    model_rhs = "1" # only includes intercept
    if (verbose == TRUE&statistical.test=="LRT") {
      message(paste("Using null model:", "cluster ~", model_rhs))
      
    }
    stop("No random or fixed effects specified")
  }
  
  # Initialize list to store model objects for each cluster
  cluster_models = vector(mode = "list",
                           length = length(attributes(designmat)$dimnames[[2]]))
  names(cluster_models) = attributes(designmat)$dimnames[[2]]
  
  # Run nested mixed-effects models for each cluster
  for (i in seq_along(attributes(designmat)$dimnames[[2]])) {
    test_cluster = attributes(designmat)$dimnames[[2]][i]
    if (verbose == TRUE) {
      message(paste("Creating logistic mixed models for", test_cluster))
    }
    null_fm = as.formula(paste0(c(paste0(test_cluster, " ~ 1 + "),
                                   model_rhs), collapse = ""))
    full_fm = as.formula(paste0(c(paste0(test_cluster, " ~ ", contrast, " + "),
                                   model_rhs), collapse = ""))

    if (verbose == TRUE) {
      message(paste("Null model:", null_fm))
      message(paste("Full model:", full_fm))
    }
    
    # Run null and full mixed-effects models
    full_model = lme4::glmer(formula = full_fm, data = dataset,
                              family = binomial, nAGQ = 1, verbose = 0,
                              control = glmerControl(optimizer = "bobyqa"))
    
    
    # calculate confidence intervals for contrast term beta
    if(is.factor(dataset[[contrast]])){
      contrast_lvl2 = paste0(contrast, levels(dataset[[contrast]])[2])
      
    } else {
      contrast_lvl2 = contrast
    }
    
    contrast_ci = confint.merMod(full_model, method = "Wald",
                                  parm = contrast_lvl2)
    
    
    if(statistical.test=="Wald"){
      pval=summary(full_model)
      
      pval=pval$coefficients[contrast_lvl2,4]
    } else {
      null_model = lme4::glmer(formula = null_fm, data = dataset,
                                family = binomial, nAGQ = 1, verbose = 0,
                                control = glmerControl(optimizer = "bobyqa"))
      model_lrt = anova(null_model, full_model)
      pval=model_lrt[["Pr(>Chisq)"]][2]
    }
    
    # Save model objects to list
    cluster_models[[i]]$confint = contrast_ci
    cluster_models[[i]]$pval = pval
    cluster_models[[i]]$full_model = full_model
    
    #jackknifing
    jk_pvalvec=c()
    jk_coefvec=c()
    jk_stable=1
    if(jackknife){
      for(ibatch in unique(dataset[,random_effects])){
        tmp_dataset=dataset[which(dataset[,random_effects]!=ibatch),]
        
        jk_full_model = tryCatch({lme4::glmer(formula = full_fm, data = tmp_dataset,
                                               family = binomial, nAGQ = 1, verbose = 0,
                                               control = glmerControl(optimizer = "bobyqa"))},error=function(e){return(F)})
        
        if(class(jk_full_model)!=class(T)){
          jk_coefvec=c(jk_coefvec,fixef(jk_full_model)[[contrast_lvl2]])
          if(statistical.test=="Wald"){
            tmp_pval=summary(jk_full_model)
            tmp_pval=tmp_pval$coefficients[contrast_lvl2,4]
            jk_pvalvec=c(jk_pvalvec,tmp_pval)
          } else {
            jk_null_model = tryCatch({lme4::glmer(formula = null_fm, data = tmp_dataset,
                                                   family = binomial, nAGQ = 1, verbose = 0,
                                                   control = glmerControl(optimizer = "bobyqa"))},error=function(e) {return(F)})
            
            if(class(jk_null_model)!=class(T)){
              jk_model_lrt = anova(jk_null_model, jk_full_model)
              # calculate confidence intervals for contrast term beta
              jk_pvalvec=c(jk_pvalvec,jk_model_lrt[["Pr(>Chisq)"]][2])
            } else {
              jk_stable=0
            }
          }
          
        } else {
          jk_stable=0
        }
        
      }
    } else {
      jk_pvalvec=(-1)
      jk_coefvec=(-1)
    }
    
    cluster_models[[i]]$jk_pval_median = median(jk_pvalvec)
    cluster_models[[i]]$jk_pval_mean = mean(jk_pvalvec)
    cluster_models[[i]]$jk_pval_max = max(jk_pvalvec)
    
    cluster_models[[i]]$jk_coef_median = median(jk_coefvec)
    cluster_models[[i]]$jk_coef_mean = mean(jk_coefvec)
    cluster_models[[i]]$jk_stable = jk_stable
    cluster_models[[i]]$jk_coef_min = jk_coefvec[which(abs(jk_coefvec)==min(abs(jk_coefvec)))[1]]
  }
  
  # Organize results into output dataframe
  output = data.frame(cluster = attributes(designmat)$dimnames[[2]],
                       size = colSums(designmat))
  output$model.pvalue = sapply(cluster_models, function(x) x$pval)
  output[[paste(contrast_lvl2, "OR", sep = ".")]] = sapply(cluster_models, function(x) exp(fixef(x$full)[[contrast_lvl2]]))
  output[[paste(contrast_lvl2, "OR", "95pct.ci.lower", sep = ".")]] = sapply(cluster_models, function(x) exp(x$confint[contrast_lvl2, "2.5 %"]))
  output[[paste(contrast_lvl2, "OR", "95pct.ci.upper", sep = ".")]] = sapply(cluster_models, function(x) exp(x$confint[contrast_lvl2, "97.5 %"]))
  output[[paste(contrast_lvl2,"JK","Min", "OR", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_coef_min==(-1)){-1} else{exp(x$jk_coef_min)}})
  output[[paste(contrast_lvl2,"JK","Mean", "OR", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_coef_mean==(-1)){-1} else {exp(x$jk_coef_mean)}})
  output[[paste(contrast_lvl2,"JK","Median", "OR", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_coef_median==(-1)){-1} else {exp(x$jk_coef_median)}})
  output[[paste(contrast_lvl2,"JK","Max", "pvalue", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_pval_max==(-1)){-1} else {x$jk_pval_max}})
  output[[paste(contrast_lvl2,"JK","Mean", "pvalue", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_pval_mean==(-1)){-1} else {x$jk_pval_mean}})
  output[[paste(contrast_lvl2,"JK","Median", "pvalue", sep = ".")]] = sapply(cluster_models, function(x) {if(x$jk_pval_median==(-1)){-1} else {x$jk_pval_median}})
  output[[paste(contrast_lvl2,"JK","Stable", sep = ".")]] = sapply(cluster_models, function(x) x$jk_stable)
  
  return(output)
}
```

```{r}
head(calico_putamen)
```
```{r}
table(calico_putamen$case_control)
```


```{r}
library(dplyr)
library(ggplot2)
library(lme4)
library(qs)
library(Seurat)

sobj = calico_putamen
model_cols = c("donor_id", "crude_cell_class", "case_control", "sex", "age") #include any other covariates of interest, replace cell_class with whatever column defines the cluster annotations
pd = sobj@meta.data[,model_cols]
pd = pd[complete.cases(pd),] # don't want any NAs
pd$case_control_factor = as.factor(pd$case_control)

masc_df = .sconline.MASCfn(
    dataset=pd,
    cluster=pd$crude_cell_class, # cluster annotations
    contrast="case_control_factor", # name of contrast annotations (what you want to run the test for)
    random_effects="donor_id", # name of random effects annotations (not interested in these coefficients, but account for variability in probable sources ob batch effects, in this case donor
    fixed_effects = c("sex", "age") # your covariates
)

masc_df
#write.csv(masc_df, "MASC/caudate_neurons_masc_df.csv")
```

```{r}
masc_df
```


```{r}
my_order <- unique(masc_df$cluster)
masc_df$cluster_name <- sub("cluster", "", masc_df$cluster) # for legibility
masc_df$log2_or = log2(masc_df$case_control_factorpd.OR) # the names of the case_control_factor<whatever> columns will change from project to project depending on the unique values of your Condition column
masc_df$log2_or_ci_low = log2(masc_df$case_control_factorpd.OR.95pct.ci.lower)
masc_df$log2_or_ci_high = log2(masc_df$case_control_factorpd.OR.95pct.ci.upper)

# order the graph to put disease-enriched populations on top
masc_df = masc_df[order(-masc_df$log2_or), ] 
masc_df$cluster_name = factor(masc_df$cluster_name, levels = masc_df$cluster_name[order(masc_df$log2_or)])
masc_df

library(RColorBrewer)
library(ggplot2)

# Create the forest plot with ticks on error bars, axis lines with ticks, RdBu color map, and opaque white circles on top
ggplot(masc_df, aes(y = cluster_name, x = log2_or)) +
  geom_vline(xintercept = 0, linetype = "dotted", color = "black", size = 1) +  # Add dotted vertical line at x=0
  geom_segment(aes(x = log2_or_ci_low, xend = log2_or_ci_high, y = cluster_name, yend = cluster_name, color = log2_or), size = 1) +  # Add horizontal error bars
  geom_point(size = 3, aes(color = log2_or), shape = 1) +  # Add points for effect sizes
  geom_point(size = 3, shape = 21, fill = "white") +  # Add opaque white circle on top of the error bar line
  scale_color_gradientn(colors = RColorBrewer::brewer.pal(10, "RdBu")) +  # Use RdBu color map
  theme_minimal() +  # Minimal theme
  labs(x = "log2(OR)", y = "Cell Classes") +  # Axis labels
  theme(
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(), 
    legend.position = "none",
    plot.title = element_text(size=16),
    axis.line = element_line(color = "black"),  # Add axis lines
    axis.ticks = element_line(color = "black"),  # Add axis ticks
    axis.text = element_text(size = 14),  # Increase tick label font size
    axis.title = element_text(size = 15)  # Increase axis label font size
  )
```

```{r}
write.csv(masc_df, "pd_masc.csv")
```