---
title: "R Notebook"
output: html_notebook
---

```{r}
SPN_score_output = XDP_matrix_scores 
                             
                             total_expression = "total_expression" 
                             fillcol = "reclustered_patch_matrix_exotic" 
                             color = color6 
                             donor_graph_title = "XDP SPN scores" 
                             SCtransformcounts =final_merged_xdp_transformed  
                             SPN_score_col_name ="SPN_Matrix_Score"
                             xlab_name = "SPN Matrix Score" 
                             limits = seq(0, 120, 1)
  
  # Ensure total_expression is a string
  total_expression <- as.character(total_expression)
  
  # Calculate min, max, and median
  min_SPN_score <- min(SPN_score_output[[total_expression]], na.rm = TRUE)
  max_SPN_score <- max(SPN_score_output[[total_expression]], na.rm = TRUE)
  median_SPN_score <- median(SPN_score_output[[total_expression]], na.rm = TRUE)
  
  print("min, max, median scores")
  print(min_SPN_score)
  print(max_SPN_score)
  print(median_SPN_score)
  
  options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  
  for (donor in donor_order) {
    test <- SPN_score_output[SPN_score_output$donor_id == donor, ]
    plots[[donor]] <- plot_overlapping_density_histogram(df = test,
                                                         hist_col = total_expression,
                                                         fill_col = fillcol,
                                                         colors = color,
                                                         breaks = limits,
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "SPN Matrix Score",
                                                         fig_filename = NULL)
  }
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  print("donor plot done")
  
  XDP <- SPN_score_output[SPN_score_output$Condition == "XDP", ]
  a <- plot_overlapping_density_histogram(df = XDP, 
                                          hist_col = total_expression,
                                          fill_col = fillcol,
                                          colors = color,
                                          breaks = limits,
                                          title = paste(donor_graph_title, ": ", "XDP"),
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  Control <- SPN_score_output[SPN_score_output$Condition == "Control", ]
  b <- plot_overlapping_density_histogram(df = Control, 
                                          hist_col = total_expression,
                                          fill_col = fillcol,
                                          colors = color,
                                          breaks = limits,
                                          title = paste(donor_graph_title, ": ", "Control"),
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  print("Condition plot done")
  
    
  SPN <- SPN_score_output[SPN_score_output$reclustered_subcluster == "SPN", ]
  c <- plot_overlapping_density_histogram(df = SPN, 
                                          hist_col = total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  notSPN <- SPN_score_output[SPN_score_output$reclustered_subcluster == "non-SPN", ]
  d <- plot_overlapping_density_histogram(df = notSPN, 
                                          hist_col = total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  print(a)
  print(b)
  print(c)
  print(d)
  
  print("graphs done")
  
  # Calculate the threshold
  threshold <- quantile(SPN_score_output[[total_expression]][SPN_score_output[["reclustered_subcluster"]] == "SPN" & SPN_score_output[["Condition"]] == "XDP"], 0.1, na.rm = TRUE)
  print(threshold)
  
  # Subset the data
  SPN_score_output_identity_loss_SPN <- SPN_score_output[SPN_score_output[[total_expression]] < threshold & SPN_score_output[["reclustered_subcluster"]] == "SPN", ]
  
  print(SPN_score_output_identity_loss_SPN)
  print(table(SPN_score_output_identity_loss_SPN$donor_id))
  
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Losing_Identity"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  pic <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity",  cols = c("red", "grey"))
  #split.by = "Condition",
  print(pic)
  ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
  
  spn_scores <- setNames(SPN_score_output[[total_expression]], SPN_score_output$cell_id)
  
  SCtransformcounts <- AddMetaData(SCtransformcounts, metadata = spn_scores, col.name = SPN_score_col_name)
  
  pic2 <- FeaturePlot(SCtransformcounts, features = SPN_score_col_name)
  print(pic2)
  ggsave("~/SPN_SCORE_Output/SPN_UMAP_TEST.png", plot = pic2, width = 20, height = 8, units = "in", dpi = 300)
  
```


```{r}
matrix_markers
patch_markers
eSPN_markers
non_SPN_markers
```


```{r}
XDP_matrix_scores = Cell_Scorer(non_SPN_markers, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply", type = "XDP", donor_order1 = donor_order, score_region = "non-SPN")
XDP_matrix_scores
```


```{r}
bottom_10 <- data.frame()


for (donor in donor_order) {
   test <- XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, ]
   threshold <- quantile(test[["total_expression"]][test[["reclustered_patch_matrix_exotic"]] == "non-SPN"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- test[test[["total_expression"]] < threshold & test[["reclustered_patch_matrix_exotic"]] == "non-SPN", ]
   
  print(SPN_score_output_identity_loss_SPN)
  
  
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = subset(final_merged_xdp_transformed, subset = donor_id == donor)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of non-SPN"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  plots[[donor]] <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) +ggtitle(paste(donor, ", 10% threshold:", sprintf("%.2f", threshold)))
  
    bottom = subset(SCtransformcounts, subset = SPN_identity == "Bottom 10% of non-SPN")
    bottom_10 <- rbind(bottom_10, bottom@meta.data)
}

layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/tenten.png", plot = grid_plots, width = 36, height = 16)
```
```{r}
bottom_10
```

#wilcox

```{r}
XDP_matrix_scores_bottom = subset(XDP_matrix_scores, subset = cell_id %in% rownames(bottom_10))
XDP_matrix_scores_bottom
```


```{r}
#write.csv(XDP_matrix_scores_bottom, "~/bottom_10_non_SPN_final.csv")
```

```{r}
XDP_matrix_scores_bottom = read.csv("~/bottom_10_non_SPN_final.csv")
XDP_matrix_scores_bottom
```


```{r}
average_scores_df <- data.frame(donor_id = character(), bottom_SPN_score = numeric(), stringsAsFactors = FALSE)

for (donor in donor_order) {
  test <- subset(XDP_matrix_scores_bottom, donor_id == donor)
  average_bottom_10_SPN_matrix <- mean(test$total_expression, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, bottom_SPN_score = average_bottom_10_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_MMR_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_MMR_scores_cases
XDP_MMR_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_MMR_scores_controls

 # ggplot(average_scores_df, aes(x = Condition, y = bottom_SPN_score, color = donor_id)) +
 #  geom_jitter(width = 0.2, height = 0) +  # Adjust width for horizontal jitter
 #  labs(x = "Condition", y = "Average Bottom 10% non-SPN score", title = "non-SPN - Bottom 10%") +
 #  theme_minimal()
 
 ggplot(average_scores_df, aes(x = Condition, y = bottom_SPN_score, color = donor_id)) +
  geom_jitter(width = 0.2, height = 0, size = 3) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average Bottom 10% non-SPN score", title = "non-SPN - Bottom 10%") +
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18),  # Increase axis label font size
           legend.title = element_text(size = 18),  # Increase legend title size
legend.text = element_text(size = 16))  # Increase legend text size

```


```{r}
XDP_MMR_scores <- XDP_MMR_scores_cases$bottom_SPN_score  
XDP_Control_MMR_scores <- XDP_MMR_scores_controls$bottom_SPN_score 
XDP_MMR_scores
XDP_Control_MMR_scores

result1 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "less")
result3 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)

```

```{r}
limits = seq(0, 100, 2)
xlab_name = "Bottom 10% SPN Matrix Score"
  plot_overlapping_density_histogram(df = average_scores_df, 
                                          hist_col = average_scores_df$bottom_SPN_score,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = xlab_name,
                                          fig_filename = NULL)
```






#averages
```{r}
matrix_markers
patch_markers
eSPN_markers
non_SPN_markers
```

```{r}
XDP_matrix_scores = Cell_Scorer(matrix_markers, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply", type = "XDP", donor_order1 = donor_order, score_region = "SPN_matrix")
XDP_matrix_scores
```


```{r}
average_scores_df <- data.frame(donor_id = character(), SPN_score = numeric(), stringsAsFactors = FALSE)

XDP_matrix_scores1 = subset(XDP_matrix_scores, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
XDP_matrix_scores1
for (donor in donor_order) {
  test <- subset(XDP_matrix_scores1, donor_id == donor)
  average_SPN_matrix <- mean(test$total_expression, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, SPN_score = average_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_MMR_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_MMR_scores_cases
XDP_MMR_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_MMR_scores_controls

 ggplot(average_scores_df, aes(x = Condition, y = SPN_score, color = donor_id)) +
  geom_jitter(width = 0.2, height = 0, size = 3) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average non-SPN scores", title = "non-SPN") +
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18))  # Increase legend text size
```


```{r}
XDP_MMR_scores <- XDP_MMR_scores_cases$SPN_score  
XDP_Control_MMR_scores <- XDP_MMR_scores_controls$SPN_score 
XDP_MMR_scores
XDP_Control_MMR_scores

result1 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "less")
result3 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)

```



```{r}
average_scores_df$Condition = NULL
```

```{r}
meta
```

```{r}
XDP_matrix_scores
```
```{r}
SPN_score = XDP_matrix_scores %>% select(cell_id, total_expression)
```


```{r}
meta$cell_id = rownames(meta)
new_meta = merge(meta, SPN_score, by = "cell_id")
new_meta
```


```{r}
new_meta1 = subset(new_meta, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
```


```{r}
  options(repr.plot.width = 24, repr.plot.height = 16)
plots = list()
for (donor in donor_order) {
   test = subset(new_meta1, subset = donor_id == donor)
   
cortest1 <- cor.test(test$total_expression, test$MMR_Score1, method = "spearman", exact = FALSE )
cortest1

cor1 <- cortest1$estimate
pvalue1 <- cortest1$p.value
subtitl1 <- paste("Spearman correlation: ", sprintf("%0.3f", cor1), " R^2: ", sprintf("%0.3f", cor1^2), " pval: ", sprintf("%0.3f", pvalue1))   
   
  plots[[donor]] = ggplot(data = test, aes(x = MMR_Score1, y = total_expression , color = region)) + geom_point(alpha = 0.4) + ggtitle(paste(donor, "- SPN Matrix"), subtitle = subtitl1)+ geom_smooth(method = "lm", se = FALSE, color = "black") + scale_color_discrete(name = "Sample ID") + xlab("MMR scores")+ ylab("SPN Scores")  

}
 layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  print("donor plot done")
```















#wilcox MMR BER

```{r}
meta = seurat_obj@meta.data
meta
```


```{r}
top_10 <- data.frame()


for (donor in donor_order) {
   test <- meta[meta$donor_id == donor, ]
   threshold <- quantile(test[["MMR_Score1"]][test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.9, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- test[test[["MMR_Score1"]] > threshold & test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  
    top_10 <- rbind(top_10, SPN_score_output_identity_loss_SPN)
}
top_10


average_scores_df <- data.frame(donor_id = character(), average_score_MMR = numeric(), average_score_BER= numeric(),  stringsAsFactors = FALSE)

for (donor in donor_order) {
  test <- subset(top_10, donor_id == donor)
  average_MMR <- mean(test$MMR_Score1, na.rm = TRUE)
  average_BER <- mean(test$BER_Score1, na.rm = TRUE)
  condition = test$Condition
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, average_score_MMR = average_MMR, average_score_BER = average_BER))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_MMR_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_MMR_scores_cases
XDP_MMR_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_MMR_scores_controls
```

```{r}
# ggplot(average_scores_df, aes(x = Condition, y = average_score_MMR, color = donor_id)) +
#   geom_jitter(width = 0.2, height = 0, size =3) +  # Adjust width for horizontal jitter
#   labs(x = "Condition", y = "Average Top 10% MMR score", title = "non-SPN - MMR") +
#   theme_minimal()+ theme(
#             plot.title = element_text(size = 20), # title font size
#             axis.line = element_line(color = "black"),  # Add axis lines
#             axis.ticks = element_line(color = "black"),  # Add axis ticks
#             axis.text = element_text(size = 18),  # Increase tick label font size
#             axis.title = element_text(size = 18),  # Increase axis label font size
#                legend.title = element_text(size = 18),  # Increase legend title size
#     legend.text = element_text(size = 16))  # Increase legend text size

ggplot(average_scores_df, aes(x = Condition, y = average_score_BER, color = donor_id)) +
  geom_jitter(width = 0.2, height = 0, size = 3) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average BER score", title = "non-SPN - BER") +
  theme_minimal()+ theme(
        plot.title = element_text(size = 20), # title font size
        axis.line = element_line(color = "black"),  # Add axis lines
        axis.ticks = element_line(color = "black"),  # Add axis ticks
        axis.text = element_text(size = 18),  # Increase tick label font size
        axis.title = element_text(size = 18),  # Increase axis label font size
           legend.title = element_text(size = 18),  # Increase legend title size
legend.text = element_text(size = 16))  # Increase legend text size

```


```{r}
XDP_MMR_scores <- XDP_MMR_scores_cases$average_score_MMR
XDP_Control_MMR_scores <- XDP_MMR_scores_controls$average_score_MMR
XDP_MMR_scores
XDP_Control_MMR_scores

result1 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "less")
result3 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)

# XDP_BER_scores <- XDP_MMR_scores_cases$average_score_BER
# XDP_Control_BER_scores <- XDP_MMR_scores_controls$average_score_BER
# 
# result1 <- wilcox.test(XDP_BER_scores, XDP_Control_BER_scores, alternative = "two.sided")
# result2 <- wilcox.test(XDP_BER_scores, XDP_Control_BER_scores, alternative = "less")
# result3 <- wilcox.test(XDP_BER_scores, XDP_Control_BER_scores, alternative = "greater")
# print(result1)
# print(result2)
# print(result3)

```


```{r}
matrix_markers
patch_markers
eSPN_markers
non_SPN_markers
```


```{r}
XDP_matrix_scores = Cell_Scorer(non_SPN_markers, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply", type = "XDP", donor_order1 = donor_order, score_region = "non-SPN")
XDP_matrix_scores
```



#wilcox

```{r}
XDP_matrix_scores_bottom = subset(XDP_matrix_scores, subset = cell_id %in% rownames(bottom_10))
XDP_matrix_scores_bottom
```


```{r}
write.csv(XDP_matrix_scores_bottom, "~/bottom_10_non_SPN_final.csv")
```


```{r}
average_scores_df <- data.frame(donor_id = character(), bottom_SPN_score = numeric(), stringsAsFactors = FALSE)

for (donor in donor_order) {
  test <- subset(XDP_matrix_scores_bottom, donor_id == donor)
  average_bottom_10_SPN_matrix <- mean(test$total_expression, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, bottom_SPN_score = average_bottom_10_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

XDP_MMR_scores_cases = subset(average_scores_df, subset = Condition == "XDP")
XDP_MMR_scores_cases
XDP_MMR_scores_controls = subset(average_scores_df, subset = Condition == "Control") 
XDP_MMR_scores_controls

 ggplot(average_scores_df, aes(x = Condition, y = bottom_SPN_score, color = donor_id)) +
  geom_jitter(width = 0.2, height = 0) +  # Adjust width for horizontal jitter
  labs(x = "Condition", y = "Average Bottom 10% non-SPN score", title = "non-SPN - Bottom 10%") +
  theme_minimal()
```


```{r}
XDP_MMR_scores <- XDP_MMR_scores_cases$bottom_SPN_score  
XDP_Control_MMR_scores <- XDP_MMR_scores_controls$bottom_SPN_score 
XDP_MMR_scores
XDP_Control_MMR_scores

result1 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "two.sided")
result2 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "less")
result3 <- wilcox.test(XDP_MMR_scores, XDP_Control_MMR_scores, alternative = "greater")
print(result1)
print(result2)
print(result3)

```




```{r}
XDP_matrix_scores = Cell_Scorer(non_SPN_markers, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply", type = "XDP", donor_order1 = donor_order, score_region = "non-SPN")
XDP_matrix_scores

matrix <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix_exotic == "non-SPN", ]
min(matrix$total_expression)
max(matrix$total_expression)

```


```{r}
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(0, 350, 5),
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "non-SPN Score", 
                                          fig_filename = NULL) + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 18),  # Increase tick label font size
            axis.title = element_text(size = 18),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1),  # tilt axis labels 
               legend.title = element_text(size = 18),  # Increase legend title size
    legend.text = element_text(size = 16))  # Increase legend text size
          
      
```


```{r}
XDP_matrix_scores = Cell_Scorer(matrix_markers, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply", type = "XDP", donor_order1 = donor_order, score_region = "SPN_matrix")
XDP_matrix_scores
```

```{r}

```


```{r}
XDP_matrix_scores_meta = XDP_matrix_scores %>% select(cell_id, total_expression, scaled_score)
XDP_matrix_scores_meta

meta$cell_id = rownames(meta)
merged = merge(meta,XDP_matrix_scores_meta, by = "cell_id" )
merged

merged$Repeat_Length[is.na(merged$Repeat_Length)] <- 0
merged$Age.of.Onset[is.na(merged$Age.of.Onset)] <- 0
merged$Disease_duration[is.na(merged$Disease_duration)] <- 0
```

```{r}
merged_matrix = subset(merged, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
```

```{r}
bottom_10 = read.csv("~/bottom_10_SPN_matrix_final.csv")
bottom_10

merged_bottom_10 = subset(merged, subset = cell_id %in% bottom_10$cell_id)
merged_bottom_10
```

```{r}
ggplot(merged_matrix, aes(x = Disease_duration, y = total_expression, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id") +
  stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 1, color = "black") + xlab("Disease Duration") + ylab("SPN Score") + ggtitle(label = "Disease Duration vs SPN Matrix Scores") + labs(color = "Donor")
```

```{r}
seurat_obj@meta.data
```

#average SPN matrix score vs SPN or matrix %
```{r}
a = as.data.frame(table(seurat_obj$reclustered_patch_matrix_exotic, seurat_obj$donor_id))
a
```

```{r}
write.csv(a, "~/matrix_percent.csv")
```



```{r}
fractions = read.csv("~/fractions.csv")
fractions
```

```{r}
XDP_matrix_scores = Cell_Scorer(matrix_markers, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply", type = "XDP", donor_order1 = donor_order, score_region = "SPN_matrix")
XDP_matrix_scores
```

```{r}
average_scores_df <- data.frame(donor_id = character(), SPN_score = numeric(), stringsAsFactors = FALSE)

XDP_matrix_scores1 = subset(XDP_matrix_scores, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
XDP_matrix_scores1
for (donor in donor_order) {
  test <- subset(XDP_matrix_scores1, donor_id == donor)
  average_SPN_matrix <- mean(test$total_expression, na.rm = TRUE)
  average_scores_df <- rbind(average_scores_df, data.frame(donor_id = donor, SPN_score = average_SPN_matrix))
}

average_scores_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", average_scores_df$donor_id), "Control", "XDP")

print(average_scores_df)

```




```{r}
new = merge(average_scores_df, fractions, by = "donor_id")
new
```

```{r}
library(ggplot2)
ggplot(new, aes(x = neuron_percentage, y = SPN_score, color = donor_id)) +geom_point()+ labs(fill = "donor_id") + xlab("SPN Matrix percentage (all neurons)") + ylab("SPN Matrix Score") + ggtitle(label = "SPN Matrix Score vs Percentage in Neurons") + labs(color = "Donor") + geom_text(aes(label = donor_id), vjust = -0.5, size = 3.5)  + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 18),  # Increase tick label font size
            axis.title = element_text(size = 18),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(new, aes(x = total_cell_proportion, y = SPN_score, color = donor_id)) +geom_point()+  geom_text(aes(label = donor_id), vjust = -0.5, size = 3.5)+ labs(fill = "donor_id") + xlab("SPN Matrix percentage (all cells)") + ylab("Average SPN Matrix Score") + ggtitle(label = "Average SPN Matrix Score vs Percentage in all cells") + labs(color = "Donor") + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 18),  # Increase tick label font size
            axis.title = element_text(size = 18),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(new, aes(x = total_cell_proportion, y = SPN_score, color = donor_id)) +geom_point()+  labs(fill = "donor_id") + xlab("SPN Matrix percentage (all cells)") + ylab("Average SPN Matrix Score") + ggtitle(label = "SPN Matrix Score vs Percentage in all cells") + labs(color = "Donor") + theme(
            plot.title = element_text(size = 20), # title font size
            axis.line = element_line(color = "black"),  # Add axis lines
            axis.ticks = element_line(color = "black"),  # Add axis ticks
            axis.text = element_text(size = 18),  # Increase tick label font size
            axis.title = element_text(size = 18),  # Increase axis label font size
            axis.text.x = element_text(angle = 45, hjust = 1))
```



```{r}
fractions
```

```{r}
a = read.csv("~/props.csv")
a
```


```{r}
x_order =  c("SCF_21-037CM2","SCF-22-054CM","SCF-22-058CF","SCF-23-068CM", "PCMC-16-011", "PCMC-16-012", "SCF-18-003", "SCF-18-004","SCF-18-006","SCF-19-009", "SCF-19-014", "SCF-19-018","SCF-20-023","SCF_20-024", "SCF-20-025", "SCF-21-030",  "SCF_22-043")
  

a$Var2 = factor(a$Var2, levels = x_order)
a

ggplot(a, aes(x = Var2, y = X.1, fill = p)) +
  geom_bar(stat = "identity") + xlab("Donors") + ylab("Neuron Proportions") + labs(fill = "Cell Type")+ geom_vline(xintercept =  4.5, linetype = "dashed", color = "black") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + ggtitle("Neuronal proportions in Caudate & Putamen")

# #+ theme(
#             plot.title = element_text(size = 20), # title font size
#             axis.line = element_line(color = "black"),  # Add axis lines
#             axis.ticks = element_line(color = "black"),  # Add axis ticks
#             axis.text = element_text(size = 18),  # Increase tick label font size
#             axis.title = element_text(size = 18))
```

