---
title: "R Notebook"
output: html_notebook
---

```{r}
bican_recon_newest_meta = bican_recon@meta.data
qsave(bican_recon_newest_meta, "bican_recon_newest_meta.qs(")
```

```{r}
cohorts = qread("/broad/macosko/kimkathl/All_XDP_Cohorts_CaH_Put_final.qs")
cohorts@meta.data
```
```{r}
table(cohorts@meta.data$neuron_cell_class)
```


```{r}
cohorts@meta.data$SPN = cohorts@meta.data$neuron_cell_class
cohorts$SPN[cohorts$SPN == "D1_D2"] = "SPN"
cohorts$SPN[cohorts$SPN == "D1_matrix"] = "SPN"
cohorts$SPN[cohorts$SPN == "D2_matrix"] = "SPN"
cohorts$SPN[cohorts$SPN == "D2_patch"] = "SPN"
cohorts$SPN[cohorts$SPN == "SPN_junk"] = "SPN"

table(cohorts@meta.data$SPN)
```

```{r}
cohorts@meta.data

caudate= subset(cohorts@meta.data, subset = region == "Caudate")
caudate
```
```{r}
caudate_filtered <- caudate %>%
  filter(numi > 500, nfeature_rna > 200, pct_mito < 10)
library(dplyr)

# Total cells per donor
cells_per_donor <- caudate_filtered %>%
  group_by(Chemistry, donor_id) %>%
  summarize(total_cells = n(), .groups = "drop")

# Median UMIs per donor
median_UMI <- caudate_filtered %>%
  group_by(Chemistry, donor_id) %>%
  summarize(median_UMI = median(numi, na.rm = TRUE), .groups = "drop")

# Median nGenes per donor
median_nGenes <- caudate_filtered %>%
  group_by(Chemistry, donor_id) %>%
  summarize(median_nGenes = median(nfeature_rna, na.rm = TRUE), .groups = "drop")

# Median mito%
median_pct_mito <- caudate_filtered %>%
  group_by(Chemistry, donor_id) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE), .groups = "drop")

# SPN-specific metrics (if labeled)
SPN_cells_per_donor <- caudate_filtered %>%
  filter(SPN == "SPN") %>%
  group_by(Chemistry, donor_id) %>%
  summarize(total_SPNs = n(), .groups = "drop")

SPN_median_UMI <- caudate_filtered %>%
  filter(SPN == "SPN") %>%
  group_by(Chemistry, donor_id) %>%
  summarize(median_SPN_UMI = median(numi, na.rm = TRUE), .groups = "drop")
df_list <- list(cells_per_donor, median_UMI, median_nGenes, median_pct_mito,
                SPN_cells_per_donor, SPN_median_UMI)

merged_df <- Reduce(function(x, y) merge(x, y, by = c("Chemistry", "donor_id"), all = TRUE), df_list)

qc_metrics <- caudate %>%
  group_by(donor_id) %>%
  summarize(
    RQS = rqs[1],
    MQS = mqs_numerical[1],
    DV200 = dv200[1],
    .groups = "drop"
  )


# Add RQS/morphology/DV200 if in separate table
merged_df <- merge(merged_df, qc_metrics, by = "donor_id", all.x = TRUE)
library(ggplot2)
```


```{r}
merged_df
ggplot(merged_df, aes(x = RQS, y = median_UMI, color = Chemistry)) +
  geom_point(size = 3) +
  geom_smooth(method = "lm", se = FALSE) +
  theme_minimal() +
  labs(title = "RQS vs. Median UMI per Donor (Stratified by Chemistry)",
       x = "RQS",
       y = "Median UMIs")

```








```{r}
cells_per_donor = as.data.frame(table(caudate$donor_id))
names(cells_per_donor)[names(cells_per_donor) == "Var1"] ="donor_id"
names(cells_per_donor)[names(cells_per_donor) == "Freq"] ="total_cells"
cells_per_donor 

#median/mean nUMI
median_nUmi = caudate %>%
  group_by(donor_id) %>%
  summarize(median_UMI = median(numi, na.rm = TRUE))
median_nUmi


#median/mean nGenes
median_nGenes = caudate%>%
  group_by(donor_id) %>%
  summarize(median_nGenes = median(nfeature_rna, na.rm = TRUE))
median_nGenes


#median/mean reads/numi
median_reads_per_umi = caudate%>%
  group_by(donor_id) %>%
  summarize(median_reads_per_umi = median((nread/numi), na.rm = TRUE))
median_reads_per_umi


#median/mean pctintronic
median_pct_intronic = caudate %>%
  group_by(donor_id) %>%
  summarize(median_pct_intronic = median(pct_intronic, na.rm = TRUE))
median_pct_intronic

#median/mean pctmito
median_pct_mito = caudate %>%
  group_by(donor_id) %>%
  summarize(median_pct_mito = median(pct_mito, na.rm = TRUE))
median_pct_mito



SPN_cells_per_donor <- caudate%>% 
  filter(SPN == "SPN") %>%
  group_by(donor_id) %>%
  summarize(SPN_n = n())
SPN_cells_per_donor

SPN_median_nUmi = caudate %>%
  filter(SPN == "SPN") %>% 
  group_by(donor_id) %>%
  summarize(median_SPN_UMI = median(numi, na.rm = TRUE))
SPN_median_nUmi



library(purrr)
# List of data frames to merge
df_list <- list(cells_per_donor, median_nUmi, median_nGenes,median_reads_per_umi, median_pct_intronic, median_pct_mito,SPN_cells_per_donor , SPN_median_nUmi)

# Merge all data frames on the common column Donor.ID
merged_df <- Reduce(function(x, y) merge(x, y, by = "donor_id"), df_list)


# Print the merged data frame
print(merged_df)
write.csv(merged_df, "cah.csv")

```

```{r}
write.csv(merged_df, "cohort.csv")
```

```{r}
caudate$Chemistry = caudate$cohort
caudate$Chemistry[caudate$Chemistry  == "Cohort_1"] = "Next-GEM"
caudate$Chemistry[caudate$Chemistry  == "Cohort_2"] = "GEM-X"
caudate$Chemistry[caudate$Chemistry  == "Cohort_3"] = "GEM-X"

caudate %>%
  group_by(Chemistry, donor_id) %>%
  summarize(median_UMI = median(numi, na.rm = TRUE))

```

