---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(tidyr)
library(qs)
library(tibble)
library(gridExtra)
```

#functions
```{r}
assignCellClasses = function(
   obj,
   classes,
   cluster_col="seurat_clusters",
   class_col="cell_class") {
   obj@meta.data[[class_col]] = NA  # Assign NA to the entire column in meta.data


   for (i in 1:length(classes)) {
       # Find cells that match the current cluster number
       cells = which(as.numeric(obj@meta.data[[cluster_col]]) == i)
     
       # Assign the class label to the cells in the cluster
       obj@meta.data[cells, class_col] = classes[[i]]
   }
  
   # Return the modified object
   return(obj)
}

```

```{r}
getSeuratVarFeatureIntersectByCol = function(
   seurat_obj,
   subset_col,
   original_nfeatures,
   n_subsets_to_cover=NULL
){
  
   hvgs = list()


   unique_ids = unique(seurat_obj@meta.data[[subset_col]])


   if (is.null(n_subsets_to_cover)){
       n_subsets_to_cover = floor(length(unique_ids)/2)
   }


   i=1
   for (id in unique_ids) {
       print(paste("Subset", id, "--", i, "of", length(unique_ids)))
       i = i + 1
      
       seurat_subset = seurat_obj[, seurat_obj[[subset_col]] == id]
      
       if (ncol(seurat_subset) < 2){next}
      
       suppressWarnings({
           seurat_subset = FindVariableFeatures(
               seurat_subset, nfeatures=original_nfeatures, verbose = FALSE)
       })
      
       hvgs[[id]] = getSeuratVarFeatures(seurat_subset)
      
   }


   common_hvgs = getCommonStrings(hvgs, n_subsets_to_cover)
   print(paste("Number of HVGs in common across", n_subsets_to_cover, "--", length(common_hvgs)))


   return(common_hvgs)
}


getSeuratVarFeatures = function(sobj){
    # the magical incantation that returns the slot of the attribute of the slot that actually holds the list of variable feature -_-
    return(sobj@assays$RNA@var.features)
}

getCommonStrings <- function(list_of_lists, n) {
  # Create an empty list to store string occurrences
  string_occurrences <- list()

  # Iterate over each sublist
  for (sublist in list_of_lists) {
    # For each string in the sublist, increment its count in string_occurrences
    for (string in unique(sublist)) {
      if (!is.null(string_occurrences[[string]])) {
        string_occurrences[[string]] <- string_occurrences[[string]] + 1
      } else {
        string_occurrences[[string]] <- 1
      }
    }
  }

  # Filter the strings that occur at least n times
  common_strings <- names(string_occurrences)[string_occurrences >= n]

  return(common_strings)
}
```


```{r}
mergeSeuratListWithMetadata = function(seurat_obj_list, cell_ids=NULL, project=NULL){

    # Harmonize metadata columns
    all_colnames = unique(unlist(lapply(seurat_obj_list, function(x) colnames(x@meta.data))))
    seurat_obj_list = lapply(seurat_obj_list, function(x) {
        missing_cols = setdiff(all_colnames, colnames(x@meta.data))
        if(length(missing_cols) > 0){
            x@meta.data[missing_cols] = NA
        }
        return(x)
    })

    if (is.null(project)){
        project = "merged"
    }
    
    if (is.null(cell_ids)){
        seurat_merged = Reduce(function(x, y) merge(x, y, project=project), 
            seurat_obj_list)
    } else {
        seurat_merged = Reduce(function(x, y) merge(x, y, project=project, add.cell.ids=cell_ids), 
            seurat_obj_list)
    }
    
    md = lapply(seurat_obj_list, function(x){
        x@meta.data$orig.row.names = rownames(x@meta.data)
        x@meta.data
    })
    
    md = do.call(rbind, md)
    rownames(md) = md$orig.row.names
    md$orig.row.names = NULL
    seurat_merged@meta.data = md
    return(seurat_merged)
}
```

```{r}
Recon_E1 = qread("~/RECON/SI-TT-E1/seurat.qs")
Recon_E1
Recon_E2 = qread("~/RECON/SI-TT-E2/seurat.qs")
Recon_E2
Recon_E3 = qread("~/RECON/SI-TT-E3/seurat.qs")
Recon_E3
Recon_E4 = qread("~/RECON/SI-TT-E4/seurat.qs")
Recon_E4
Recon_E5 = qread("~/RECON/SI-TT-E5/seurat.qs")
Recon_E5
Recon_E6 = qread("~/RECON/SI-TT-E6/seurat.qs")
Recon_E6
Recon_E7 = qread("~/RECON/SI-TT-E7/seurat.qs")
Recon_E7
Recon_E8 = qread("~/RECON/SI-TT-E8/seurat.qs")
Recon_E8
```
```{r}
Recon_E1@meta.data$library = "Rxn_1"
Recon_E1@meta.data
Recon_E2@meta.data$library = "Rxn_2"
Recon_E2@meta.data
Recon_E3@meta.data$library = "Rxn_3"
Recon_E3@meta.data
Recon_E4@meta.data$library = "Rxn_4"
Recon_E4@meta.data
Recon_E5@meta.data$library = "Rxn_5"
Recon_E5@meta.data
Recon_E6@meta.data$library = "Rxn_6"
Recon_E6@meta.data
Recon_E7@meta.data$library = "Rxn_7"
Recon_E7@meta.data
Recon_E8@meta.data$library = "Rxn_8"
Recon_E8@meta.data
```

```{r}
Recon_list = list("RECON_rxn1" = Recon_E1, 
                  "RECON_rxn2"= Recon_E2, 
                  "RECON_rxn3"= Recon_E3, 
                  "RECON_rxn4"= Recon_E4, 
                  "RECON_rxn5"= Recon_E5, 
                  "RECON_rxn6"= Recon_E6, 
                  "RECON_rxn7"= Recon_E7, 
                  "RECON_rxn8"= Recon_E8)
Recon_list
```

```{r}
for(name in names(Recon_list)){
     sobj =Recon_list[[name]]
     sobj$library = name
     sobj = RenameCells(sobj, new.name = paste(sobj$library, colnames(sobj), sep="__"))
     Recon_list[[name]] = sobj
}

Recon_list
```
```{r}
#qsave(Recon_list, "Recon_list.qs")
```

```{r}
Recon_list = qread("Recon_list.qs")
Recon_list
```


#create sobj
```{r}
counts_list <- lapply(Recon_list, function(sobj) GetAssayData(sobj, slot = "counts"))
counts_list
```

```{r}
merged_counts <- do.call(cbind, counts_list)
merged_counts
```

```{r}
metadata_list <- lapply(Recon_list, function(sobj) sobj@meta.data)
metadata_list
```

```{r}
merged_metadata <- do.call(rbind, metadata_list)
merged_metadata
```

```{r}
stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))
```

```{r}
# Create Seurat object
Recon_sobj <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
Recon_sobj
```
```{r}
#this is if i wanted to also keep data and scale.data
# data_list <- lapply(Recon_list, function(sobj) GetAssayData(sobj, slot = "data"))
# scaled_data_list <- lapply(Recon_list, function(sobj) GetAssayData(sobj, slot = "scale.data"))
# 
# merged_data <- do.call(cbind, data_list)
# merged_scaled_data <- do.call(cbind, scaled_data_list)
# 
# 
# merged_sobj <- SetAssayData(merged_sobj, slot = "data", new.data = merged_data)
# merged_sobj <- SetAssayData(merged_sobj, slot = "scale.data", new.data = merged_scaled_data)
# 
# merged_sobj
# 
# Recon_sobj = merged_sobj
```

#at first metadata had extra stuff in name but it is fixed
```{r}
unmatched <- setdiff(rownames(merged_metadata), colnames(merged_counts))
length(unmatched)  # Check how many are unmatched
head(unmatched)  # Look at the first few unmatched entries

```
```{r}
unmatched_counts <- setdiff(colnames(merged_counts), rownames(merged_metadata))
length(unmatched_counts)
head(unmatched_counts)
```
```{r}
# Remove the prefix before the first "."
rownames(merged_metadata) <- gsub("^[^.]+\\.", "", rownames(merged_metadata))

```


```{r}
# Check cell names in one of the Seurat objects
head(Cells(Recon_list[[1]]))

# Check colnames of merged counts
head(colnames(merged_counts))

# Check rownames of merged metadata
head(rownames(merged_metadata))

```


```{r}
stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))
```



```{r}
meta = Recon_sobj@meta.data
meta

ggplot(meta, aes(x= x_um, y = y_um, color = logumi)) + geom_point() + facet_wrap(~ library)
```

```{r}
Recon_sobj@meta.data$donor_id = "SCF-18-006"
Recon_sobj@meta.data
```

```{r}
hist(Recon_sobj$nCount_RNA)
hist(Recon_sobj$nFeature_RNA)
hist(Recon_sobj$logumi)
hist(Recon_sobj$percent.mt)
```


```{r}
Recon_sobj
Recon_sobj = subset(Recon_sobj, subset = percent.mt < 10)
Recon_sobj
```


```{r}
n_dims_use=20

Recon_sobj = (Recon_sobj
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
Recon_sobj
```

```{r}
DimPlot(Recon_sobj)
DimPlot(Recon_sobj, group.by = "library", raster = F)
DimPlot(Recon_sobj, group.by = "donor_id",raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.2", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.3", label=T,raster = F)
```


```{r}
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.2", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.3", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.4", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.5", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.6", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.7", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.8", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.9", label=T,raster = F)
DimPlot(Recon_sobj, group.by = "RNA_snn_res.1", label=T,raster = F)
```


```{r}
Recon_sobj@meta.data
```

```{r}
hist(Recon_sobj$percent.mt, breaks = 100)
```



#9725 cells filtered out from high mito 

```{r}
DimPlot(Recon_sobj, group.by = "RNA_snn_res.0.2", label=T,raster = F)
FeaturePlot(Recon_sobj, features = c("DRD1", "DRD2", "PPP1R1B", "CASZ1"), raster = F)
FeaturePlot(Recon_sobj, features = c("EPHA4", "SEMA3E", "CACNG4", "SLC6A3"), raster = F)
FeaturePlot(Recon_sobj, features = c("CACNG4", "DRD2","percent.mt", "logumi"), raster = F)
FeaturePlot(Recon_sobj, features = c("SYT1", "AQP4", "C1QA","FLT1"), raster = F)
FeaturePlot(Recon_sobj, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"), raster = F)
FeaturePlot(Recon_sobj, features = c("C1QB", "ACTA2", "CACNG4", "GFAP"), raster = F)
FeaturePlot(Recon_sobj, features = c("GAD1", "GAD2", "GRIA2", "SST"), raster = F)
```

```{r}
Idents(Recon_sobj) = Recon_sobj$RNA_snn_res.0.3

classes = c("oligo", "1", "neuron", "neuron", "neuron", "ependymal", "neuron", "neuron", "neuron", "neuron", "astrocyte", "endothelial", "astrocyte", "opc", "neuron", "microglia", "neuron", "neuron", "opc", "endothelial", "neuron", "astrocyte")

Recon_sobj= assignCellClasses(Recon_sobj, classes=classes, cluster_col="RNA_snn_res.0.3", class_col = "crude_cell_class")

DimPlot(Recon_sobj, group.by = "crude_cell_class" ,label = T, raster = FALSE)
```

```{r}
FeaturePlot(Recon_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(Recon_sobj, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(Recon_sobj, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(Recon_sobj, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(Recon_sobj, features = c("OLIG1", "MOG", "MOBP"), raster = F)
FeaturePlot(Recon_sobj, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(Recon_sobj, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(Recon_sobj, features = c("CD96", "NKG7", "SKAP1"), raster = F)

```

```{r}
marker_genes <- c("SYT1", "RBFOX3", "GAD2", "SLC17A6", "AQP4", "GINS3", "GFAP", "C1QA", "C1QB", "CX3CR1", "P2RY12","FLT1", "DCN", "RGS5","OLIG1", "MOG", "MOBP","OLIG2", "VCAN","ZBBX", "CFAP157", "CFAP299", "BSG", "CD96", "NKG7", "SKAP1")

Dotplot = DotPlot(object = Recon_sobj, features = marker_genes, group.by = "crude_cell_class")
Dotplot <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```


```{r}
FeaturePlot(Recon_sobj, features = c("UBB", "TUBB2A", "GAPDH"), raster = F)
```

```{r}
table(Recon_sobj$crude_cell_class)
```


```{r}
Idents(Recon_sobj) = "crude_cell_class"
markers = FindAllMarkers(Recon_sobj, logfc.threshold=2, min.pct = 0.5, only.pos = T) 
markers 
```

```{r}
markers_sig = subset(markers, subset = p_val_adj < 0.05)
markers_sig
```

```{r}
markers_sigg = subset(markers_sig, subset = cluster == "1")
markers_sigg
```

```{r}
markers_1 = subset(markers, subset = cluster ==1)
markers_1
```


```{r}
Recon_sobj@meta.data
```

```{r}
table(Recon_sobj$crude_cell_class)
```

```{r}
Recon_sobj
Recon_sobj = subset(Recon_sobj, subset = crude_cell_class != "1")
Recon_sobj
meta = Recon_sobj@meta.data
```

```{r}
ggplot(meta, aes(x= x_um, y = y_um, color = crude_cell_class)) + geom_point(alpha = 0.2) + facet_wrap(~ crude_cell_class) +theme_void()
```


```{r}
pic = ggplot(meta, aes(x= x_um, y = y_um, color = crude_cell_class)) + geom_point(alpha = 0.2) + facet_wrap(~ crude_cell_class) +theme_void() + 
  theme(
      strip.text = element_text(size = 20),
     plot.background = element_rect(fill = "white", color = NA)) + ylab(NULL)
```


#custom_labels <- c(astrocyte = "Astrocyte \n 17766 cells, 11.9% ", endothelial = "Endothelial \n 5178 cells, 3.4%", ependymal = "Ependymal \n 2530 cells, 1.7%", microglia = "Microglia \n 10895 cells, 7.4%", neuron = "Neuron \n 38569 cells, 25.9%", oligo = "Oligo \n 68223 cells, 45.8%", opc ="OPC \n 5756 cells, 3.8%")
```{r}
custom_labels <- c(astrocyte = "Astrocyte \n 11.9% ", endothelial = "Endothelial \n 3.4%", ependymal = "Ependymal \n 1.7%", microglia = "Microglia \n 7.4%", neuron = "Neuron \n 25.9%", oligo = "Oligo \n 45.8%", opc ="OPC \n 3.8%")

# Plot with light gray points for all data in the background
pic = ggplot(meta, aes(x= x_um, y = y_um, color = crude_cell_class)) + geom_point(alpha = 0.3, size = 0.5) + ggtitle(" SCF-18-006: XDP Male", subtitle = " Age at Death: 51 \n Disease Duration: 5 years \n Total Cells: 149,817 \n") + 
  facet_wrap(~ crude_cell_class,  labeller = labeller(crude_cell_class = custom_labels)) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 24),
    strip.text = element_text(size = 22),
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 12, height = 12)
```

```{r}
custom_labels <- c(astrocyte = "Astrocyte", endothelial = "Endothelial", ependymal = "Ependymal", microglia = "Microglia", neuron = "Neuron", oligo = "Oligo", opc ="OPC")

pic = ggplot(meta, aes(x= x_um, y = y_um, color = crude_cell_class)) + geom_point(alpha = 0.3, size = 0.2) + theme_void() + theme(plot.background = element_rect(fill = "white", color = NA), legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)) + scale_color_discrete(labels = custom_labels) + labs(color = "Cell Classes")
```


```{r}
library(ggplot2)

# Create the plot with larger legend key sizes
pic <- ggplot(meta, aes(x = x_um, y = y_um, color = crude_cell_class)) +
  geom_point(alpha = 0.4, size = 0.2) +
  scale_color_discrete(labels = custom_labels) +  # If you want to rename labels
  labs(color = "Cell Classes") +
  guides(color = guide_legend(override.aes = list(size = 4))) +  # Increase size of dots in the legend
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)
  )


ggsave(pic, filename = "pic.png", width = 8, height = 6)
```


```{r}
ggplot(meta, aes(x= x_um, y = y_um, color = logumi)) + geom_point(alpha = 0.2) + facet_wrap(~ crude_cell_class) +theme_void()
```
```{r}
qsave(Recon_sobj, "RECON/Recon_sobj.qs")
```


```{r}
Recon_astro = subset(Recon_sobj, subset = crude_cell_class == "astrocyte")
Recon_endo = subset(Recon_sobj, subset = crude_cell_class == "endothelial")
Recon_ependymal = subset(Recon_sobj, subset = crude_cell_class == "ependymal")
Recon_micro = subset(Recon_sobj, subset = crude_cell_class == "microglia")
Recon_neuron = subset(Recon_sobj, subset = crude_cell_class == "neuron")
Recon_oligo = subset(Recon_sobj, subset = crude_cell_class == "oligo")
Recon_opc = subset(Recon_sobj, subset = crude_cell_class == "opc")
Recon_maybe_junk = subset(Recon_sobj, subset = crude_cell_class == "1")

Recon_astro
Recon_endo 
Recon_ependymal 
Recon_micro 
Recon_neuron 
Recon_oligo 
Recon_opc 
Recon_maybe_junk
```


```{r}
qsave(Recon_astro, "RECON/astro.qs")
qsave(Recon_endo, "RECON/endo.qs") 
qsave(Recon_ependymal, "RECON/ependymal.qs") 
qsave(Recon_micro, "RECON/micro.qs") 
qsave(Recon_neuron, "RECON/neuron.qs") 
qsave(Recon_oligo, "RECON/oligo.qs") 
qsave(Recon_opc, "RECON/opc.qs") 
qsave(Recon_maybe_junk, "RECON/maybe_junk.qs") 
```

```{r}
Recon_neuron = qread("RECON/neuron.qs")
```

```{r}
n_dims_use=20

Recon_neuron = (Recon_neuron
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.01) 
   %>% FindClusters(resolution = 0.05)
   %>% FindClusters(resolution = 0.1)
   %>% FindClusters(resolution = 0.15) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6) 
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
Recon_neuron
```

```{r}
Recon_neuron@meta.data
```

```{r}
DimPlot(Recon_neuron, group.by = "crude_cell_class", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.01", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.05", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.1", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.15", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.2", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.3", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.4", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.5", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.6", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.7", label = T, raster = FALSE)
DimPlot(Recon_neuron, group.by = "RNA_snn_res.0.8", label = T, raster = FALSE)
FeaturePlot(Recon_neuron, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(Recon_neuron, features = c("OLIG1", "OLIG2", "MOG" ,"BCAS1"),raster=FALSE) 
```

```{r}
FeaturePlot(Recon_neuron, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(Recon_neuron, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(Recon_neuron, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(Recon_neuron, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(Recon_neuron, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(Recon_neuron, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron, features = c("P2RY12", "CX3CR1", "C1QB"),raster=FALSE) 
```

```{r}
FeaturePlot(Recon_neuron, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
```
```{r}
hist(Recon_neuron$logumi)
```


```{r}
FeaturePlot(Recon_neuron, features = c("logumi", "percent.mt"),raster=FALSE) 
```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7")


Dotplot = DotPlot(object = Recon_neuron, features = marker_genes, group.by = "subclass")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
table(Recon_neuron$RNA_snn_res.0.7)
```
```{r}
Idents(Recon_neuron) = Recon_neuron$RNA_snn_res.0.4

classes = c("0", "1", "2", "tempremove", "4", "5", "tempremove", "7", "8", "9", "10", "11", "12", "13", "tempremove", "15", "16", "17", "doublet", "19", "doublet", "tempremove", "22", "doublet", "24", "25")


#classes = c("SPN_matrix", "SPN_matrix", "SPN_matrix", "non-SPN", "eSPN", "SPN_matrix", "non-SPN", "SPN_patch", "SPN_matrix", "non-SPN", "SPN_exotic", "SPN_patch", "non-SPN", "non-SPN", "doublet", "SPN_exotic", "non-SPN", "SPN_patch", "doublet", "non-SPN", "doublet", "non-SPN", "non-SPN", "doublet", "non-SPN", "non-SPN")

Recon_neuron= assignCellClasses(Recon_neuron, classes=classes, cluster_col="RNA_snn_res.0.4", class_col = "subclass")

DimPlot(Recon_neuron, group.by = "subclass" ,label = T, raster = FALSE)
```
```{r}
#more than 5000 numi
Recon_neuron
Recon_neuron_clean = subset(Recon_neuron, subset = logumi >3.69)
Recon_neuron_clean
```
```{r}
Recon_neuron_clean = subset(Recon_neuron_clean, subclass != "doublet")
Recon_neuron_clean = subset(Recon_neuron_clean, subclass != "tempremove")
Recon_neuron_clean
```

```{r}
DimPlot(Recon_neuron_clean)
```

```{r}
n_dims_use=20

Recon_neuron_clean = (Recon_neuron_clean
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.01) 
   %>% FindClusters(resolution = 0.05)
   %>% FindClusters(resolution = 0.1)
   %>% FindClusters(resolution = 0.15) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6) 
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
Recon_neuron
```

```{r}
Recon_neuron_clean@meta.data
```

```{r}
DimPlot(Recon_neuron_clean, group.by = "crude_cell_class", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.01", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.05", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.1", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.15", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.2", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.3", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.4", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.5", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.6", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.7", label = T, raster = FALSE)
DimPlot(Recon_neuron_clean, group.by = "RNA_snn_res.0.8", label = T, raster = FALSE)
FeaturePlot(Recon_neuron_clean, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(Recon_neuron_clean, features = c("OLIG1", "OLIG2", "MOG" ,"BCAS1"),raster=FALSE) 
```

```{r}
FeaturePlot(Recon_neuron_clean, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(Recon_neuron_clean, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(Recon_neuron_clean, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(Recon_neuron_clean, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(Recon_neuron_clean, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron_clean, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(Recon_neuron_clean, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron_clean, features = c("P2RY12", "CX3CR1", "C1QB"),raster=FALSE) 
```

```{r}
FeaturePlot(Recon_neuron_clean, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 

FeaturePlot(Recon_neuron_clean, features = c("logumi", "percent.mt"),raster=FALSE) 
```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7")


Dotplot = DotPlot(object = Recon_neuron_clean, features = marker_genes, group.by = "subclass")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```


```{r}
table(Recon_neuron_clean$RNA_snn_res.0.6)
```

```{r}
Idents(Recon_neuron_clean) = Recon_neuron_clean$RNA_snn_res.0.6

classes = c("D2_matrix", "D1_matrix", "D1_matrix", "D2_matrix", "eSPN", "D1_matrix", "eSPN", "doublet", "D1_exotic", "D1_patch", "non-SPN", "D1_patch", "D2_exotic", "non-SPN", "D1_D2_SPN", "non-SPN", "non-SPN", "doublet", "D2_exotic", "D2_patch", "non-SPN", "D2_patch", "non-SPN", "non-SPN", "doublet", "non-SPN")


Recon_neuron_clean= assignCellClasses(Recon_neuron_clean, classes=classes, cluster_col="RNA_snn_res.0.6", class_col = "subclass")

DimPlot(Recon_neuron_clean, group.by = "subclass" ,label = T, raster = FALSE)
```

```{r}
Recon_neuron_clean
Recon_neuron_clean = subset(Recon_neuron_clean, subset = subclass != "doublet")
Recon_neuron_clean = subset(Recon_neuron_clean, subset = subclass != "D1_D2_SPN")
Recon_neuron_clean
```
```{r}
table(Recon_neuron_clean$subclass)
```

```{r}
Recon_neuron_clean@meta.data$reclustered_patch_matrix_exotic =Recon_neuron_clean$subclass
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "D1_exotic"] = "SPN_exotic"
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "D1_matrix"] = "SPN_matrix"
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "D1_patch"] = "SPN_patch"
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "D2_exotic"] = "SPN_exotic"
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "D2_matrix"] = "SPN_matrix"
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "D2_patch"] = "SPN_patch"
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$reclustered_patch_matrix_exotic == "eSPN"] = "non-SPN"
table(Recon_neuron_clean$reclustered_patch_matrix_exotic)
```

```{r}
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$subclass == "eSPN"] = "eSPN"

```


```{r}
Idents(Recon_neuron_clean) = "reclustered_patch_matrix_exotic"
DimPlot(Recon_neuron_clean, label = T)
```
```{r}
qsave(Recon_neuron_clean, "Recon_neuron_clean.qs")
```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7")


Dotplot = DotPlot(object = Recon_neuron_clean, features = marker_genes, group.by = "reclustered_patch_matrix_exotic")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
neuron_meta = Recon_neuron_clean@meta.data
table(neuron_meta$reclustered_patch_matrix_exotic)
```


```{r}
neuron_meta$reclustered_patch_matrix_exotic[neuron_meta$reclustered_patch_matrix_exotic == "non-SPN"] = "non_SPN"
```

```{r}
table(neuron_meta$reclustered_patch_matrix_exotic)
```


```{r}
neuron_meta$reclustered_patch_matrix_exotic <- factor(neuron_meta$reclustered_patch_matrix_exotic, 
                                                      levels = c("SPN_matrix", "SPN_patch", "SPN_exotic","non_SPN", "eSPN"))

custom_labels <- c(non_SPN = "non-SPN \n 16.5%", SPN_exotic = "SPN Patch 2 \n 10.6%", SPN_matrix = "SPN Matrix \n 48.8%", SPN_patch = "SPN Patch 1 \n 10.5%", eSPN = "eSPN \n 13.5%")

# Plot with light gray points for all data in the background
pic = ggplot(neuron_meta, aes(x= x_um, y = y_um, color = reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.5, size = 0.7) + ggtitle(" SCF-18-006 Neurons \n") + 
  facet_wrap(~ reclustered_patch_matrix_exotic,  labeller = labeller(reclustered_patch_matrix_exotic = custom_labels)) +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 24),
    strip.text = element_text(size = 22),
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 16, height = 10)
```

```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")
# Create the plot with larger legend key sizes
pic <- ggplot(neuron_meta, aes(x = x_um, y = y_um, color = reclustered_patch_matrix_exotic)) +
  geom_point(alpha = 0.5, size = 0.5) +
  scale_color_discrete(labels = custom_labels) +  # If you want to rename labels
  labs(color = "Neuronal Subclasses") +
  guides(color = guide_legend(override.aes = list(size = 4))) +  # Increase size of dots in the legend
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)
  )


ggsave(pic, filename = "pic.png", width = 9, height = 6)
```

```{r}
library(sctransform)
Recon_neuron_clean = SCTransform(Recon_neuron_clean, vars.to.regress = "percent.mt", verbose = FALSE)
DefaultAssay(Recon_neuron_clean) = "SCT"
Recon_neuron_clean
```

#ucell scores
```{r}
library(UCell)
Recon_neuron_clean <- AddModuleScore_UCell(Recon_neuron_clean,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'UCELL'
)

Recon_neuron_clean <- AddModuleScore_UCell(Recon_neuron_clean,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'UCELL'
)


Recon_neuron_clean <- AddModuleScore_UCell(Recon_neuron_clean,
 features = list(matrix_markers = new_BICAN_V17_matrix),
  name = 'UCELL'
)
```

```{r}
Recon_neuron_clean <- AddModuleScore_UCell(Recon_neuron_clean,
 features = list(D_genes = new_d_genes_BICAN),
  name = 'UCELL'
)
```

```{r}
Recon_neuron_clean$reclustered_patch_matrix_exotic[Recon_neuron_clean$subclass == "eSPN"] = "eSPN"
```


```{r}
recon_df = Recon_neuron_clean@meta.data
recon_df$Condition = "XDP"
recon_df
```

```{r}
final_df = qread("XDP_BICAN_ucell_scores.qs")
final_df
recon_df
```
```{r}
ggplot(Recon_neuron_clean@meta.data, aes(x= x_um, y = y_um)) + geom_point()
```


```{r}
recon_df_cah_put = subset(recon_df, subset = y_um < 12500)
recon_df_cah_put$Region = "Other"
recon_df_cah_put$Region[recon_df_cah_put$x_um < 10000] = "Putamen" 
recon_df_cah_put$Region[recon_df_cah_put$x_um > 10000] = "Caudate" 

ggplot(recon_df_cah_put, aes(x= x_um, y = y_um, color = Region)) + geom_point()
```


```{r}
new_df = final_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "matrix_markersUCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL")]  

new_df$C_minusUCELL = new_df$C_minusSPN_Matrix_scores_UCELL
new_df$C_minusSPN_Matrix_scores_UCELL = NULL

new_df$C_plusUCELL = new_df$C_plusSPN_Matrix_scores_UCELL
new_df$C_plusSPN_Matrix_scores_UCELL = NULL

new_df$D_genesUCELL = new_df$D_genesSPN_Matrix_scores_UCELL
new_df$D_genesSPN_Matrix_scores_UCELL = NULL

xdp_df = recon_df_cah_put[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "matrix_markersUCELL", "C_minusUCELL", "C_plusUCELL", "D_genesUCELL", "Region")]  

xdp_df$Condition = "XDP_18_006"

new_df$Region = "Other"
new_df$Region[new_df$BICAN_V8] = "Caudate"

xdp_df
```

```{r}
table(recon_df_combined$Condition)
```


```{r}
recon_df_combined = rbind(xdp_df, new_df)
recon_df_combined
```


```{r}
histograms_by_celltype(final_df= recon_df_combined, score_col = "matrix_markersUCELL", xlab = "SPN Matrix Score")
histograms_by_celltype(final_df= recon_df_combined, score_col = "C_minusUCELL", xlab = "C Minus Score")
histograms_by_celltype(final_df= recon_df_combined, score_col = "C_plusUCELL", xlab = "C Plus Score")
histograms_by_celltype(final_df= recon_df_combined, score_col = "D_genesUCELL", xlab = "D Score")
```

```{r}
neuron_meta
```


```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")
# Create the plot with larger legend key sizes
pic <- ggplot(neuron_meta, aes(x = x_um, y = y_um, color = C_minusUCELL)) +
  geom_point(alpha = 0.5, size = 0.2) +
    scale_color_gradient(low = "blue", high = "red") +  # If you want to rename labels
  labs(color = "Neuronal Subclasses") +
  guides(color = guide_legend(override.aes = list(size = 4))) +  # Increase size of dots in the legend
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)
  ) + facet_wrap(~ reclustered_patch_matrix_exotic)


ggsave(pic, filename = "pic.png", width = 8, height = 6)
```


```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")

# Plot with light gray points for all data in the background
matrix_recon = subset(neuron_meta, subset = reclustered_patch_matrix_exotic == "SPN_matrix")

a = ggplot(matrix_recon, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")
) +   labs(color = "C Minus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)

b = ggplot(matrix_recon, aes(x= x_um, y = y_um, color = C_plusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Plus Scores \n") + scale_color_gradientn(colors = c("#0000FF", "#4682B4", "#87CEEB", "#FFD700", "#FF7F50", "#FF4500", "#FF0000")
) +  labs(color = "C Plus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)

pic = a+b
ggsave(pic, filename = "pic.png", width = 20, height = 10)
```

```{r}
ggplot(neuron_meta, aes(x=C_minusUCELL, y=C_plusUCELL, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle("C minus vs C plus UCell Scores") + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ reclustered_patch_matrix_exotic) 

```
```{r}
matrix_recon_cah_put = subset(matrix_recon, subset = y_um < 12000)
matrix_recon_cah_put
```

```{r}
ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF7F50", "#FFFF00", "#87CEEB", "#0000FF")
) +   labs(color = "C Minus Scores") + ylim(0,12000)
```


```{r}
 a = ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")

) +   labs(color = "C Minus Scores") + ylim(0,12000) + xlim(10000, 16000)+
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)


b = ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_plusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Plus Scores \n") + scale_color_gradientn(colors = c("#0000FF", "#4682B4", "#87CEEB", "#FFD700", "#FF7F50", "#FF4500", "#FF0000")

) +  labs(color = "C Plus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + ylim(0,12000) +xlim(10000, 16000)+
  ylab(NULL)

pic = a+b
ggsave(pic, filename = "pic.png", width = 20, height = 10)
```


```{r}
Recon_neuron_clean
```
```{r}
DimPlot(Recon_neuron_clean, label = T)
```
```{r}
Recon_neuron_clean@meta.data
```


```{r}
Idents(Recon_neuron_clean) = "reclustered_patch_matrix_exotic"
markers = FindAllMarkers(Recon_neuron_clean, logfc.threshold=0.5, min.pct = 0.1, only.pos = T) 
markers 
```

```{r}
markers_p = subset(markers, p_val_adj < 0.05) 
markers_p
```

```{r}
markers_pp = subset(markers_p, cluster != "non-SPN" & cluster != "eSPN") 
markers_pp
```


```{r}
markers_pct = subset(markers_pp, pct.1 > 0.8) 
markers_pct
```
```{r}
EPHX4
```


```{r}
markers_p[markers_p$gene == "SEMA3E",]
```

```{r}
write.csv(markers_pp, "findmarkers.csv")
```

