---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(tidyr)
library(qs)
library(tibble)
library(gridExtra)
```

#functions: plot_histogram, SPN scoring 
```{r}
plot_overlapping_density_histogram = function(
    df, 
    hist_col,
    fill_col,
    colors = c("blue", "red"),
    alpha=0.5,
    breaks=seq(0, 16, 1),
    title= NULL,
    xlab = NULL,
    fig_filename = NULL

){
    # hist_col is the column you're making a histogram of (e.g. nUMI)
    # fill_col is the column you're coloring by (e.g. cell_class)
    # if fig_filename is not null, the plot will be saved to that file
     
    if (is.null(xlab)){
        xlab = hist_col
    }

    if (is.null(title)){
        title = paste0("Density Histogram of ", xlab, " by ", fill_col)
    }


    p = (
        ggplot(df, aes_string(x=hist_col, fill=fill_col)) 
        + geom_histogram(aes(y=..density..), alpha=alpha, position="identity", breaks=breaks)
        + labs(title=title, x=xlab, y="Density")    
        + theme(
                plot.title = element_text(size=16),
                axis.line = element_line(color = "black"),  # Add axis lines
                axis.ticks = element_line(color = "black"),  # Add axis ticks
                axis.text = element_text(size = 14),  # Increase tick label font size
                axis.title = element_text(size = 15)  # Increase axis label font size
            ) 
        + scale_fill_manual(values=colors)   
    )

    if (!is.null(fig_filename)){
        ggsave(fig_filename, p, width=8, height=6)
    }

    return(p)
}

SPN_score_normalized = function(gene_df, SCtransform_counts, logfc_val, method = "multiply"){

significant_genes = unique(gene_df$gene)

exp = FetchData(SCtransform_counts, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df
counts_df <- exp

print(logfc_df)
print(counts_df)

# Check if all column names in counts_df are in the row names of logfc_df
if (!all(colnames(counts_df) %in% rownames(logfc_df))) {
  stop("Not all genes in counts_df are present in logfc_df")
}

# Reorder logfc_df to match the columns in counts_df
logfc_ordered <- logfc_df[colnames(counts_df), , drop = FALSE]
logfc_ordered

logfc = logfc_ordered[[logfc_val]]

# Check for NA values in logfc_ordered
if (any(is.na(logfc))) {
  stop("There are NA values in the logFC values for the genes")
}


# Ensure logfc_ordered$logfc is a numeric vector
logfc_vector <- as.numeric(logfc)
logfc_vector

 gene_averages <- colMeans(counts_df)
 print("Printing gene averages")
 print(gene_averages)
if (method == "multiply") {
  
#THE ACTUAL
result_df <- sweep(counts_df, 2, logfc_vector, FUN = "*")
} else if(method == "log"){
  custom_log_transform <- function(x, logFC_value) {
     x * 2^logFC_value
  }
  result_df <- sweep(counts_df, 2, logfc_vector, FUN = custom_log_transform)
} else{
  stop("Calculation is not working")
}
print(result_df)
# Divide each gene's expression by its average expression
 result_df <- sweep(result_df, 2, gene_averages, FUN = "/")

# Print the result
print("Printing normalized")
print(result_df)


metadata <- SCtransform_counts@meta.data
# Assume that metadata has a column 'donor' that contains donor information
# If not, modify this part according to your metadata structure
if(!"donor_id" %in% colnames(metadata)) {
  stop("Metadata does not contain 'donor' information. Please check your metadata structure.")
}

# Create unique identifiers for cell column to avoid conflicts
expr_data <- result_df %>%
  rownames_to_column(var = "cell_id")

metadata <- metadata %>%
  rownames_to_column(var = "cell_id")

# Combine expression data with donor information
expr_data_long <- expr_data %>%
  pivot_longer(cols = -cell_id, names_to = "gene", values_to = "expression") %>%
  left_join(metadata %>% select(cell_id, donor_id, Condition, cell_class, reclustered_cell_class, reclustered_neuron_type, reclustered_patch_matrix, reclustered_subcluster, reclustered_patch_matrix_exotic, reclustered_neuron_type_joint_cluster, pct_mito, nUmi, region), by = "cell_id")
# Assuming your data frame is named expr_data_long
print(expr_data_long)
# Count the number of occurrences for each gene per donor

summarized_expr_data <- expr_data_long %>%
  group_by(cell_id, donor_id, Condition, cell_class, reclustered_cell_class, reclustered_neuron_type, reclustered_patch_matrix, reclustered_subcluster, reclustered_patch_matrix_exotic, reclustered_neuron_type_joint_cluster, pct_mito, nUmi,region) %>%
  summarize(total_expression = sum(expression), .groups = 'drop')
print(summarized_expr_data)

for (donor in donor_order) {
    test <- summarized_expr_data[summarized_expr_data$donor_id == donor, ]
    test$scaled_score <- NA  # Initialize the new column
    cell_classes = unique(test$reclustered_patch_matrix_exotic)  
    for (class in cell_classes) {
        df = test[test$reclustered_patch_matrix_exotic == class, ]
        test$scaled_score[test$reclustered_patch_matrix_exotic == class] <- scale(df$total_expression)
    }
    summarized_expr_data[summarized_expr_data$donor_id == donor, "scaled_score"] <- test$scaled_score
}

# spn_scores = summarized_expr_data$total_expression
# mean_spn <- mean(spn_scores, na.rm = TRUE)
# sd_spn <- sd(spn_scores, na.rm = TRUE)
# # Compute the z-score for each SPN score
# summarized_expr_data$z_score  <- (spn_scores - mean_spn) / sd_spn

return(summarized_expr_data)

}

# # Add z-scores to Seurat object metadata
# caudate_neurons_transformed <- AddMetaData(caudate_neurons_transformed, metadata = spn_zscores, col.name = "SPN_zscore")
# 
# # Visualize SPN z-scores on UMAP
# plot <- FeaturePlot(caudate_neurons_transformed, features = "SPN_zscore") +
#   ggtitle("SPN Z-Score on UMAP")
# 
# # Save the UMAP plot with SPN z-scores as a PNG file
# ggsave("SPN_zscore_umap.png", plot = plot, width = 10, height = 8, dpi = 300)


SPN_score_graphs <- function(SPN_score_output, 
                             donor_order = donors, 
                             total_expression = "total_expression", 
                             fillcol = "reclustered_subcluster", 
                             color = color1, 
                             donor_graph_title = "CaH SPNs vs non-SPNs", 
                             SCtransformcounts, 
                             SPN_score_col_name) {
  
  # Ensure total_expression is a string
  total_expression <- as.character(total_expression)
  
  # Calculate min, max, and median
  min_SPN_score <- min(SPN_score_output[[total_expression]], na.rm = TRUE)
  max_SPN_score <- max(SPN_score_output[[total_expression]], na.rm = TRUE)
  median_SPN_score <- median(SPN_score_output[[total_expression]], na.rm = TRUE)
  
  print("min, max, median scores")
  print(min_SPN_score)
  print(max_SPN_score)
  print(median_SPN_score)
  
  options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  
  for (donor in donor_order) {
    test <- SPN_score_output[SPN_score_output$donor_id == donor, ]
    plots[[donor]] <- plot_overlapping_density_histogram(df = test,
                                                         hist_col = total_expression,
                                                         fill_col = fillcol,
                                                         colors = color,
                                                         breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score / 50)),
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "SPN Matrix Score",
                                                         fig_filename = NULL)
  }
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  print("donor plot done")
  
  XDP <- SPN_score_output[SPN_score_output$Condition == "XDP", ]
  a <- plot_overlapping_density_histogram(df = XDP, 
                                          hist_col = total_expression,
                                          fill_col = fillcol,
                                          colors = color,
                                          breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score / 50)),
                                          title = paste(donor_graph_title, ": ", "XDP"),
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  Control <- SPN_score_output[SPN_score_output$Condition == "Control", ]
  b <- plot_overlapping_density_histogram(df = Control, 
                                          hist_col = total_expression,
                                          fill_col = fillcol,
                                          colors = color,
                                          breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score / 50)),
                                          title = paste(donor_graph_title, ": ", "Control"),
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  print("Condition plot done")
  
    
  SPN <- SPN_score_output[SPN_score_output$reclustered_subcluster == "SPN", ]
  c <- plot_overlapping_density_histogram(df = SPN, 
                                          hist_col = total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score / 50)),
                                          title = "XDP vs Control: SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  notSPN <- SPN_score_output[SPN_score_output$reclustered_subcluster == "non-SPN", ]
  d <- plot_overlapping_density_histogram(df = notSPN, 
                                          hist_col = total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score / 50)),
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  print(a)
  print(b)
  print(c)
  print(d)
  
  print("graphs done")
  
  # Calculate the threshold
  threshold <- quantile(SPN_score_output[[total_expression]][SPN_score_output[["reclustered_subcluster"]] == "SPN" & SPN_score_output[["Condition"]] == "XDP"], 0.1, na.rm = TRUE)
  print(threshold)
  
  # Subset the data
  SPN_score_output_identity_loss_SPN <- SPN_score_output[SPN_score_output[[total_expression]] < threshold & SPN_score_output[["reclustered_subcluster"]] == "SPN", ]
  
  print(SPN_score_output_identity_loss_SPN)
  print(table(SPN_score_output_identity_loss_SPN$donor_id))
  
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Losing_Identity"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  pic <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", split.by = "Condition", cols = c("red", "grey"))
  print(pic)
  ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
  
  spn_scores <- setNames(SPN_score_output[[total_expression]], SPN_score_output$cell_id)
  
  SCtransformcounts <- AddMetaData(SCtransformcounts, metadata = spn_scores, col.name = SPN_score_col_name)
  
  pic2 <- FeaturePlot(SCtransformcounts, features = SPN_score_col_name, split.by = "Condition")
  print(pic2)
  ggsave("~/SPN_SCORE_Output/SPN_UMAP_TEST.png", plot = pic2, width = 20, height = 8, units = "in", dpi = 300)
  
  return(SCtransformcounts)
}


BICAN_SPN_score_normalized = function(gene_df, SCtransform_counts, logfc_val, method = "multiply"){

significant_genes = unique(gene_df$gene)

exp = FetchData(SCtransform_counts, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df
counts_df <- exp

print(logfc_df)
print(counts_df)

# Check if all column names in counts_df are in the row names of logfc_df
if (!all(colnames(counts_df) %in% rownames(logfc_df))) {
  stop("Not all genes in counts_df are present in logfc_df")
}

# Reorder logfc_df to match the columns in counts_df
logfc_ordered <- logfc_df[colnames(counts_df), , drop = FALSE]
logfc_ordered

logfc = logfc_ordered[[logfc_val]]

# Check for NA values in logfc_ordered
if (any(is.na(logfc))) {
  stop("There are NA values in the logFC values for the genes")
}


# Ensure logfc_ordered$logfc is a numeric vector
logfc_vector <- as.numeric(logfc)
logfc_vector

gene_averages <- colMeans(counts_df)
print("Printing gene averages")
print(gene_averages)
if (method == "multiply") {
  
#THE ACTUAL
result_df <- sweep(counts_df, 2, logfc_vector, FUN = "*")
} else if(method == "log"){
  custom_log_transform <- function(x, logFC_value) {
     x * 2^logFC_value
  }
  result_df <- sweep(counts_df, 2, logfc_vector, FUN = custom_log_transform)
} else{
  stop("Calculation is not working")
}
print(result_df)
# Divide each gene's expression by its average expression
result_df <- sweep(result_df, 2, gene_averages, FUN = "/")

# Print the result
print("Printing normalized")
print(result_df)


metadata <- SCtransform_counts@meta.data
# Assume that metadata has a column 'donor' that contains donor information
# If not, modify this part according to your metadata structure
if(!"DONOR" %in% colnames(metadata)) {
  stop("Metadata does not contain 'donor' information. Please check your metadata structure.")
}

# Check if 'cell_id' column already exists and remove it
if ("cell_id" %in% colnames(metadata)) {
  metadata <- metadata %>% select(-cell_id)
}

# Ensure unique row names in result_df
if (any(duplicated(rownames(result_df)))) {
  stop("Row names in result_df are not unique. Please ensure unique row names.")
}


# Create unique identifiers for cell column to avoid conflicts
expr_data <- result_df %>%
  rownames_to_column(var = "cell_id")

metadata <- metadata %>%
  rownames_to_column(var = "cell_id")

# Combine expression data with donor information
expr_data_long <- expr_data %>%
  pivot_longer(cols = -cell_id, names_to = "gene", values_to = "expression") %>%
  left_join(metadata %>% select(cell_id, DONOR, subcluster, pct_mt, NUM_TRANSCRIPTS, reclustered_cell_class, reclustered_subcluster,reclustered_neuron_type,reclustered_patch_matrix,reclustered_neuron_joint_type), by = "cell_id")

# Assuming your data frame is named expr_data_long
print(expr_data_long)
# Count the number of occurrences for each gene per donor

summarized_expr_data <- expr_data_long %>%
  group_by(cell_id, DONOR, subcluster, pct_mt, NUM_TRANSCRIPTS, reclustered_cell_class, reclustered_subcluster,reclustered_neuron_type,reclustered_patch_matrix,reclustered_neuron_joint_type) %>%
  summarize(total_expression = sum(expression), .groups = 'drop')
print(summarized_expr_data)


for (donor in donor_order) {
    test <- summarized_expr_data[summarized_expr_data$DONOR == donor, ]
    test$scaled_score <- NA  # Initialize the new column
    cell_classes = unique(test$reclustered_neuron_joint_type)  
    for (class in cell_classes) {
        df = test[test$reclustered_neuron_joint_type == class, ]
        test$scaled_score[test$reclustered_neuron_joint_type == class] <- scale(df$total_expression)
    }
    summarized_expr_data[summarized_expr_data$DONOR == donor, "scaled_score"] <- test$scaled_score
}

# spn_scores = summarized_expr_data$total_expression
# mean_spn <- mean(spn_scores, na.rm = TRUE)
# sd_spn <- sd(spn_scores, na.rm = TRUE)
# # Compute the z-score for each SPN score
# summarized_expr_data$z_score  <- (spn_scores - mean_spn) / sd_spn

return(summarized_expr_data)
}


BICAN_SPN_score_graphs <- function(SPN_score_output, 
                             donor_order = BICANdonors, 
                             total_expression = "total_expression", 
                             fillcol = "subcluster", 
                             color = color1, 
                             donor_graph_title = "BICAN SPN Matrix vs non-SPNs", 
                             SCtransformcounts, 
                             SPN_score_col_name) {
  
  # Ensure total_expression is a string
  total_expression <- as.character(total_expression)
  
  # Calculate min, max, and median
  min_SPN_score <- min(SPN_score_output[[total_expression]], na.rm = TRUE)
  max_SPN_score <- max(SPN_score_output[[total_expression]], na.rm = TRUE)
  median_SPN_score <- median(SPN_score_output[[total_expression]], na.rm = TRUE)
  
  print("min, max, median scores")
  print(min_SPN_score)
  print(max_SPN_score)
  print(median_SPN_score)
  
  options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  
  for (donor in donor_order) {
    test <- SPN_score_output[SPN_score_output$DONOR == donor, ]
    plots[[donor]] <- plot_overlapping_density_histogram(df = test,
                                                         hist_col = total_expression,
                                                         fill_col = fillcol,
                                                         colors = color,
                                                         breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score/50)),
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "Matrix SPN Score",
                                                         fig_filename = NULL)
  }
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, 14, 15),
    c(16, 17, 18, 19, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  print("donor plot done")
  
  b <- plot_overlapping_density_histogram(df = SPN_score_output, 
                                          hist_col = total_expression,
                                          fill_col = fillcol,
                                          colors = color,
                                          breaks = seq(min_SPN_score, max_SPN_score, round(max_SPN_score/50)),
                                          title = paste(donor_graph_title, ": ", "Control"),
                                          xlab = "SPN score",
                                          fig_filename = NULL)
  
  print("Condition plot done")
  

  
  # Calculate the threshold
  threshold <- quantile(SPN_score_output[[total_expression]][SPN_score_output[["reclustered_neuron_type"]] == "SPN"], 0.1, na.rm = TRUE)
  print(threshold)
  
  # Subset the data
  SPN_score_output_identity_loss_SPN <- SPN_score_output[SPN_score_output[[total_expression]] < threshold & SPN_score_output[["reclustered_neuron_type"]] == "SPN", ]
  
  print(SPN_score_output_identity_loss_SPN)
  print(table(SPN_score_output_identity_loss_SPN$DONOR))
  
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10%"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  pic <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) 
  print(pic)
  ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
  
  spn_scores <- setNames(SPN_score_output[[total_expression]], SPN_score_output$cell_id)
  
  SCtransformcounts <- AddMetaData(SCtransformcounts, metadata = spn_scores, col.name = SPN_score_col_name)
  
  pic2 <- FeaturePlot(SCtransformcounts, features = SPN_score_col_name)
  print(pic2)
  ggsave("~/SPN_SCORE_Output/SPN_UMAP_TEST.png", plot = pic2, width = 20, height = 8, units = "in", dpi = 300)
  
  return(SCtransformcounts)
}

```

#files to load
```{r}
final_V8_BICAN_neurons = qread("~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_V8_BICAN_neurons.qs")
#final_V8_BICAN_neurons = subset(final_V8_BICAN_neurons, subset = DONOR != "MD6701")
final_V8_BICAN_neurons
#qsave(final_V8_BICAN_neurons, "~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_V8_BICAN_neurons.qs") 

final_merged_xdp_transformed = qread("~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_merged_xdp_transformed_081224.qs")
final_merged_xdp_transformed

final_V17_BICAN_neurons = qread("~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_V17_BICAN_neurons.qs")
final_V17_BICAN_neurons

Idents(final_V8_BICAN_neurons) = "reclustered_patch_matrix"

Intersected_BICAN_matrix_markers_final_filtered = qread("~/rstudio/workdir/Old Work/SPN_Matrix_BICAN_findmarkers.qs")
Intersected_BICAN_matrix_markers_final_filtered

donor_order = c("PCMC-16-011","PCMC-16-012", "SCF-18-003", "SCF-18-004", "SCF-18-006", "SCF-19-009", "SCF-19-014",  "SCF-19-018", "SCF-20-023", "SCF_20-024", "SCF-20-025", "SCF-21-030", "SCF_22-043","SCF_21-037CM2","SCF-22-054CM", "SCF-22-058CF","SCF-23-068CM") 

BICANdonors = unique(final_V8_BICAN_neurons$DONOR)
BICANdonors
```

```{r}
Intersected_BICAN_matrix_markers_final_filtered$new_weight = Intersected_BICAN_matrix_markers_final_filtered$avg_log2FC * (Intersected_BICAN_matrix_markers_final_filtered$pct.1/(Intersected_BICAN_matrix_markers_final_filtered$pct.1 + Intersected_BICAN_matrix_markers_final_filtered$pct.2))


Intersected_BICAN_matrix_markers_final_filtered$relative_pct =Intersected_BICAN_matrix_markers_final_filtered$pct.1/(Intersected_BICAN_matrix_markers_final_filtered$pct.1 + Intersected_BICAN_matrix_markers_final_filtered$pct.2)
```

```{r}
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = pct.1, y = pct.2)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = pct.1, y = pct_subtract)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = pct.2, y = pct_subtract)) + geom_point(alpha = 0.4, color = "red")
```



```{r}
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = avg_log2FC, y = pct.1)) + geom_point(alpha = 0.4, color = "red") 
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = avg_log2FC, y = pct.2)) + geom_point(alpha = 0.4, color = "red") 
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = avg_log2FC, y = new_weight)) + geom_point(alpha = 0.4, color = "red") 
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = avg_log2FC, y = weighted_logFC)) + geom_point(alpha = 0.4, color = "red") 
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = weighted_logFC, y = new_weight)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x = pct_subtract, y = relative_pct)) + geom_point(alpha = 0.4, color = "red")
```
```{r}
cor.test(Intersected_BICAN_matrix_markers_final_filtered$avg_log2FC, Intersected_BICAN_matrix_markers_final_filtered$weighted_logFC, method = "spearman", exact = FALSE )

cor.test(Intersected_BICAN_matrix_markers_final_filtered$avg_log2FC, Intersected_BICAN_matrix_markers_final_filtered$new_weight, method = "spearman", exact = FALSE )

cor.test(Intersected_BICAN_matrix_markers_final_filtered$weighted_logFC, Intersected_BICAN_matrix_markers_final_filtered$new_weight, method = "spearman", exact = FALSE )
```



```{r}
cortest1 <- cor.test(Intersected_BICAN_matrix_markers_final_filtered$avg_log2FC, Intersected_BICAN_matrix_markers_final_filtered$weighted_logFC, method = "spearman", exact = FALSE )
cortest1

cor1 <- cortest1$estimate
pvalue1 <- cortest1$p.value
subtitl1 <- paste("Spearman correlation: ", sprintf("%0.3f", cor1), " R^2: ", sprintf("%0.3f", cor1^2), " p-value:", sprintf("%0.3f", pvalue1^2))

b <- ggplot(data = Intersected_BICAN_matrix_markers_final_filtered, aes(x =Intersected_BICAN_matrix_markers_final_filtered$avg_log2FC, y = Intersected_BICAN_matrix_markers_final_filtered$weighted_logFC, color = Intersected_BICAN_matrix_markers_final_filtered$donor_id)) + 
  geom_point() + labs(fill = "Condition") + xlab("SPN Score") + ylab("MMR Score") + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("CB: GP RQS vs GP DV200", subtitle = subtitl1) + scale_color_discrete(name = "Sample ID")

b
```

```{r}
final_V8_BICAN_neurons_final@meta.data

table(final_V8_BICAN_neurons_final$reclustered_patch_matrix)
```

```{r}
final_V8_BICAN_neurons_final
```







```{r}
#BICAN_filtered_test = subset(Intersected_BICAN_matrix_markers_final_filtered, subset = avg_log2FC > 1)
BICAN_filtered_test = subset(Intersected_BICAN_matrix_markers_final_filtered, subset = relative_pct > 0.6)
BICAN_filtered_test
```





```{r}
gene_df = Intersected_BICAN_matrix_markers_final_filtered

significant_genes = unique(gene_df$gene)

exp = FetchData(final_merged_xdp_transformed, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df
counts_df <- exp

print(logfc_df)
print(counts_df)
```

```{r}
matrix_cells = subset(final_merged_xdp_transformed, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
matrix_cells
matrix_cells_names = rownames(matrix_cells@meta.data)
matrix_cells_names
```


```{r}
counts_df
```

```{r}
matrix_counts_df <- subset(counts_df, rownames(counts_df) %in% matrix_cells_names)
matrix_counts_df
```

```{r}
gene_averages <- colMeans(matrix_counts_df)
gene_averages
```




#another test

```{r}
new_df = data.frame()
gene_df = Intersected_BICAN_matrix_markers_final_filtered

significant_genes = unique(gene_df$gene)
exp = FetchData(final_merged_xdp_transformed_cases, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df
counts_df <- exp

print(logfc_df)
print(counts_df)

gene_averages <- colMeans(counts_df)
df = as.data.frame(gene_averages)
df

df$gene <- rownames(df)

Combo_compare = merge(Combo_compare, df, by = "gene")
Combo_compare

Combo_compare$XDP_Cases = Combo_compare$gene_averages
Combo_compare$gene_averages = NULL
Combo_compare

Combo_compare= read.csv("~/rstudio/workdir/Files/avg_gene_expression_compare.csv")

Combo_compare$X = NULL
Combo_compare
```

```{r}
final_merged_xdp_controls = subset(final_merged_xdp_transformed, subset = Condition == "Control")
final_merged_xdp_cases = subset(final_merged_xdp_transformed, subset = Condition == "XDP")
```


#instead of mean try median
```{r}
new_df = data.frame()
gene_df = Intersected_BICAN_matrix_markers_final_filtered

significant_genes = unique(gene_df$gene)
exp = FetchData(final_merged_xdp_cases, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df
counts_df <- exp

print(logfc_df)
print(counts_df)

gene_medians <- apply(counts_df, 2, median)
df = as.data.frame(gene_medians)
df
```
```{r}
Combo_compare = df
Combo_compare$XDP_all = Combo_compare$gene_medians
Combo_compare$gene_medians= NULL
Combo_compare
```


```{r}
df$gene <- rownames(df)
#Combo_compare$gene <- rownames(Combo_compare)

Combo_compare = merge(Combo_compare, df, by = "gene")
Combo_compare

Combo_compare$XDP_Cases = Combo_compare$gene_medians
Combo_compare$gene_medians = NULL
Combo_compare

```



```{r}
write.csv(Combo_compare, "~/rstudio/workdir/Files/avg_gene_expression_compare_MEDIAN.csv")

```

```{r}
# Creating the histogram using ggplot2
ggplot(new, aes(x = XDP_all)) +
  geom_histogram(bins = 100, fill = "grey", color = "black") +
  ggtitle("XDP all ") +
  xlab("Gene Median Expression") +
  ylab("Count")

ggplot(new, aes(x = BICAN_V8)) +
  geom_histogram(bins = 100, fill = "grey", color = "black") +
  ggtitle("BICAN V8 ") +
  xlab("Gene Median Expression") +
  ylab("Count")

ggplot(new, aes(x = BICAN_V17)) +
  geom_histogram(bins = 100, fill = "grey", color = "black") +
  ggtitle("BICAN V17") +
  xlab("Gene Median Expression") +
  ylab("Count")

ggplot(new, aes(x = XDP_Controls)) +
  geom_histogram(bins = 100, fill = "grey", color = "black") +
  ggtitle("XDP Controls") +
  xlab("Gene Median Expression") +
  ylab("Count")

ggplot(new, aes(x = XDP_Cases)) +
  geom_histogram(bins = 100, fill = "grey", color = "black") +
  ggtitle("XDP Cases") +
  xlab("Gene Median Expression") +
  ylab("Count")
```



```{r}
ggplot(data = Combo_compare, aes(x = XDP_all, y = V8_BICAN)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Combo_compare, aes(x = XDP_all, y = V17_BICAN)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Combo_compare, aes(x = V8_BICAN, y = V17_BICAN)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Combo_compare, aes(x = XDP_Controls, y = XDP_Cases)) + geom_point(alpha = 0.4, color = "red")
```
```{r}
new
```


```{r}
ggplot(data = new, aes(x = XDP_Controls, y = BICAN_V8)) + geom_point(alpha = 0.4, color = "red")#+ geom_text(aes(label = gene), hjust = 0.5, vjust = -0.5, size = 3) 
ggplot(data = new, aes(x = XDP_Controls, y = BICAN_V17)) + geom_point(alpha = 0.4, color = "red")#+ geom_text(aes(label = gene), hjust = 0.5, vjust = -0.5, size = 3) 
ggplot(data = new, aes(x = BICAN_V8, y = BICAN_V17)) + geom_point(alpha = 0.4, color = "red")#+ geom_text(aes(label = gene), hjust = 0.5, vjust = -0.5, size = 3) 
```
```{r}
ggplot(data = Combo_compare, aes(x = XDP_Cases, y = V8_BICAN)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Combo_compare, aes(x = XDP_Cases, y = V17_BICAN)) + geom_point(alpha = 0.4, color = "red")
ggplot(data = Combo_compare, aes(x = V8_BICAN, y = V17_BICAN)) + geom_point(alpha = 0.4, color = "red")
```

```{r}
new = subset(Combo_compare, subset = BICAN_V8 > 0)
new

new = subset(new, subset = BICAN_V17 > 0)
new

new = subset(new, subset = XDP_Controls > 0)
new
```
```{r}
ggplot(data = New_filtered_expression, aes(x = XDP_Controls, y = V8_BICAN)) + geom_point(alpha = 0.4, color = "red")+ geom_text(aes(label = gene), hjust = 0.5, vjust = -0.5, size = 3) 
ggplot(data = New_filtered_expression, aes(x = XDP_Controls, y = V17_BICAN)) + geom_point(alpha = 0.4, color = "red")+ geom_text(aes(label = gene), hjust = 0.5, vjust = -0.5, size = 3) 
ggplot(data = New_filtered_expression, aes(x = V8_BICAN, y = V17_BICAN)) + geom_point(alpha = 0.4, color = "red")+ geom_text(aes(label = gene), hjust = 0.5, vjust = -0.5, size = 3) 
```




```{r}
NEW_Intersected_BICAN_matrix_markers_final_filtered
```

```{r}
New_NEW_Intersected_BICAN_matrix_markers_final_filtered = subset(NEW_Intersected_BICAN_matrix_markers_final_filtered, subset = avg_log2FC > 1)
New_NEW_Intersected_BICAN_matrix_markers_final_filtered
```



#test
```{r}
BICAN_TEST_Score= function(gene_df, SCtransform_counts, logfc_val, method = "multiply"){

significant_genes = unique(gene_df$gene)

counts_df = FetchData(SCtransform_counts, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df

print(logfc_df)
print(counts_df)

# Check if all column names in counts_df are in the row names of logfc_df
if (!all(colnames(counts_df) %in% rownames(logfc_df))) {
  stop("Not all genes in counts_df are present in logfc_df")
}

# Reorder logfc_df to match the columns in counts_df
logfc_ordered <- logfc_df[colnames(counts_df), , drop = FALSE]
logfc_ordered

logfc = logfc_ordered[[logfc_val]]

# Check for NA values in logfc_ordered
if (any(is.na(logfc))) {
  stop("There are NA values in the logFC values for the genes")
}


# Ensure logfc_ordered$logfc is a numeric vector
logfc_vector <- as.numeric(logfc)
logfc_vector


matrix_cells = subset(SCtransform_counts, subset = reclustered_neuron_joint_type == "SPN_matrix")
matrix_cells_names = rownames(matrix_cells@meta.data)
matrix_cells_names

matrix_counts_df <- subset(counts_df, rownames(counts_df) %in% matrix_cells_names)
matrix_counts_df

gene_averages <- colMeans(matrix_counts_df)
print("Printing gene averages")
print(gene_averages)

gene_medians <- apply(counts_df, 2, median)

if (method == "multiply") {
  
#THE ACTUAL
result_df <- sweep(counts_df, 2, logfc_vector, FUN = "*")
} else if(method == "log"){
  custom_log_transform <- function(x, logFC_value) {
     x * 2^logFC_value
  }
  result_df <- sweep(counts_df, 2, logfc_vector, FUN = custom_log_transform)
} else{
  stop("Calculation is not working")
}
print(result_df)
# Divide each gene's expression by its average expression
#result_df <- sweep(result_df, 2, gene_averages, FUN = "/")

# Print the result
print("Printing normalized")
print(result_df)


metadata <- SCtransform_counts@meta.data
# Assume that metadata has a column 'donor' that contains donor information
# If not, modify this part according to your metadata structure
if(!"DONOR" %in% colnames(metadata)) {
  stop("Metadata does not contain 'donor' information. Please check your metadata structure.")
}

# Check if 'cell_id' column already exists and remove it
if ("cell_id" %in% colnames(metadata)) {
  metadata <- metadata %>% select(-cell_id)
}

# Ensure unique row names in result_df
if (any(duplicated(rownames(result_df)))) {
  stop("Row names in result_df are not unique. Please ensure unique row names.")
}


# Create unique identifiers for cell column to avoid conflicts
expr_data <- result_df %>%
  rownames_to_column(var = "cell_id")

metadata <- metadata %>%
  rownames_to_column(var = "cell_id")

# Combine expression data with donor information
expr_data_long <- expr_data %>%
  pivot_longer(cols = -cell_id, names_to = "gene", values_to = "expression") %>%
  left_join(metadata %>% select(cell_id, DONOR, subcluster, pct_mt, NUM_TRANSCRIPTS, reclustered_cell_class, reclustered_subcluster,reclustered_neuron_type,reclustered_patch_matrix,reclustered_neuron_joint_type), by = "cell_id")

# Assuming your data frame is named expr_data_long
print(expr_data_long)
# Count the number of occurrences for each gene per donor

summarized_expr_data <- expr_data_long %>%
  group_by(cell_id, DONOR, subcluster, pct_mt, NUM_TRANSCRIPTS, reclustered_cell_class, reclustered_subcluster,reclustered_neuron_type,reclustered_patch_matrix,reclustered_neuron_joint_type) %>%
  summarize(total_expression = sum(expression), .groups = 'drop')
print(summarized_expr_data)

for (donor in donor_order) {
    test <- summarized_expr_data[summarized_expr_data$DONOR == donor, ]
    test$scaled_score <- NA  # Initialize the new column
    cell_classes = unique(test$reclustered_neuron_joint_type)  
    for (class in cell_classes) {
        df = test[test$reclustered_neuron_joint_type == class, ]
        test$scaled_score[test$reclustered_neuron_joint_type == class] <- scale(df$total_expression)
    }
    summarized_expr_data[summarized_expr_data$DONOR == donor, "scaled_score"] <- test$scaled_score
}

return(summarized_expr_data)
}

SPN_TEST_SCORE = function(gene_df, SCtransform_counts, logfc_val, method = "multiply"){

significant_genes = unique(gene_df$gene)

exp = FetchData(SCtransform_counts, vars = significant_genes)

rownames(gene_df) = gene_df$gene
gene_df$gene = NULL

# Assuming gene_df and exp are your dataframes
logfc_df <- gene_df
counts_df <- exp

print(logfc_df)
print(counts_df)

# Check if all column names in counts_df are in the row names of logfc_df
if (!all(colnames(counts_df) %in% rownames(logfc_df))) {
  stop("Not all genes in counts_df are present in logfc_df")
}

# Reorder logfc_df to match the columns in counts_df
logfc_ordered <- logfc_df[colnames(counts_df), , drop = FALSE]
logfc_ordered

logfc = logfc_ordered[[logfc_val]]

# Check for NA values in logfc_ordered
if (any(is.na(logfc))) {
  stop("There are NA values in the logFC values for the genes")
}


# Ensure logfc_ordered$logfc is a numeric vector
logfc_vector <- as.numeric(logfc)
logfc_vector

matrix_cells = subset(SCtransform_counts, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
matrix_cells_names = rownames(matrix_cells@meta.data)
matrix_cells_names

matrix_counts_df <- subset(counts_df, rownames(counts_df) %in% matrix_cells_names)
matrix_counts_df

gene_averages <- colMeans(matrix_counts_df)
print(gene_averages)
print("Printing gene averages")

if (method == "multiply") {
  
#THE ACTUAL
result_df <- sweep(counts_df, 2, logfc_vector, FUN = "*")
} else if(method == "log"){
  custom_log_transform <- function(x, logFC_value) {
     x * 2^logFC_value
  }
  result_df <- sweep(counts_df, 2, logfc_vector, FUN = custom_log_transform)
} else{
  stop("Calculation is not working")
}
print(result_df)
# Divide each gene's expression by its average expression
result_df <- sweep(result_df, 2, gene_averages, FUN = "/")

# Print the result
print("Printing normalized")
print(result_df)


metadata <- SCtransform_counts@meta.data
# Assume that metadata has a column 'donor' that contains donor information
# If not, modify this part according to your metadata structure
if(!"donor_id" %in% colnames(metadata)) {
  stop("Metadata does not contain 'donor' information. Please check your metadata structure.")
}

# Create unique identifiers for cell column to avoid conflicts
expr_data <- result_df %>%
  rownames_to_column(var = "cell_id")

metadata <- metadata %>%
  rownames_to_column(var = "cell_id")

# Combine expression data with donor information
expr_data_long <- expr_data %>%
  pivot_longer(cols = -cell_id, names_to = "gene", values_to = "expression") %>%
  left_join(metadata %>% select(cell_id, donor_id, Condition, cell_class, reclustered_cell_class, reclustered_neuron_type, reclustered_patch_matrix, reclustered_subcluster, reclustered_patch_matrix_exotic, reclustered_neuron_type_joint_cluster, pct_mito, nUmi, region), by = "cell_id")
# Assuming your data frame is named expr_data_long
print(expr_data_long)
# Count the number of occurrences for each gene per donor

summarized_expr_data <- expr_data_long %>%
  group_by(cell_id, donor_id, Condition, cell_class, reclustered_cell_class, reclustered_neuron_type, reclustered_patch_matrix, reclustered_subcluster, reclustered_patch_matrix_exotic, reclustered_neuron_type_joint_cluster, pct_mito, nUmi,region) %>%
  summarize(total_expression = sum(expression), .groups = 'drop')
print(summarized_expr_data)

for (donor in donor_order) {
    test <- summarized_expr_data[summarized_expr_data$donor_id == donor, ]
    test$scaled_score <- NA  # Initialize the new column
    cell_classes = unique(test$reclustered_patch_matrix_exotic)  
    for (class in cell_classes) {
        df = test[test$reclustered_patch_matrix_exotic == class, ]
        test$scaled_score[test$reclustered_patch_matrix_exotic == class] <- scale(df$total_expression)
    }
    summarized_expr_data[summarized_expr_data$donor_id == donor, "scaled_score"] <- test$scaled_score
}
return(summarized_expr_data)
}

```



```{r}
XDP_matrix_scores = SPN_TEST_SCORE(Intersected_BICAN_matrix_markers_final_filtered, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply")
XDP_matrix_scores$Village = "XDP"

XDP_matrix_scores
V8_BICAN_scores = BICAN_TEST_Score(Intersected_BICAN_matrix_markers_final_filtered, final_V8_BICAN_neurons, logfc_val = "weighted_logFC", method = "multiply")
V8_BICAN_scores$Village = "BICAN_V8"
V8_BICAN_scores

V17_BICAN_scores = BICAN_TEST_Score(Intersected_BICAN_matrix_markers_final_filtered, final_V17_BICAN_neurons, logfc_val = "weighted_logFC", method = "multiply")
V17_BICAN_scores$Village = "BICAN_V17"
V17_BICAN_scores
```

```{r}
 V17_BICAN_scores$reclustered_patch_matrix_exotic = V17_BICAN_scores$reclustered_neuron_joint_type
 V17_BICAN_scores$reclustered_patch_matrix_exotic[V17_BICAN_scores$reclustered_cell_class == "D1_patch_exotic" | V17_BICAN_scores$reclustered_cell_class == "D2_patch_exotic"] = "SPN_exotic"
table(V17_BICAN_scores$reclustered_patch_matrix_exotic)

library(dplyr)
XDP_matrix_scores_df = XDP_matrix_scores %>% select(cell_id, donor_id, Condition, reclustered_patch_matrix_exotic, reclustered_patch_matrix, reclustered_neuron_type_joint_cluster,  pct_mito, nUmi, total_expression, scaled_score, Village)

BICAN_matrix_scores_df_V8 = V8_BICAN_scores %>% select(cell_id, DONOR, reclustered_patch_matrix, reclustered_neuron_joint_type,  pct_mt, NUM_TRANSCRIPTS, total_expression , scaled_score, Village) 

BICAN_matrix_scores_df_V17 = V17_BICAN_scores %>% select(cell_id, DONOR, reclustered_patch_matrix, reclustered_neuron_joint_type,reclustered_patch_matrix_exotic,  pct_mt, NUM_TRANSCRIPTS, total_expression , scaled_score, Village) 

BICAN_matrix_scores_df_V8$Condition = "BICAN Control V8"
BICAN_matrix_scores_df_V8$reclustered_patch_matrix_exotic = BICAN_matrix_scores_df_V8$reclustered_neuron_joint_type
BICAN_matrix_scores_df_V8$reclustered_neuron_type_joint_cluster = BICAN_matrix_scores_df_V8$reclustered_neuron_joint_type
BICAN_matrix_scores_df_V8$reclustered_neuron_joint_type = NULL
BICAN_matrix_scores_df_V8$pct_mito = BICAN_matrix_scores_df_V8$pct_mt 
BICAN_matrix_scores_df_V8$pct_mt  = NULL
BICAN_matrix_scores_df_V8$nUmi = BICAN_matrix_scores_df_V8$NUM_TRANSCRIPTS 
BICAN_matrix_scores_df_V8$NUM_TRANSCRIPTS  = NULL
BICAN_matrix_scores_df_V8$donor_id = BICAN_matrix_scores_df_V8$DONOR 
BICAN_matrix_scores_df_V8$DONOR  = NULL

BICAN_matrix_scores_df_V17$Condition = "BICAN Control V17"
BICAN_matrix_scores_df_V17$reclustered_neuron_type_joint_cluster = BICAN_matrix_scores_df_V17$reclustered_neuron_joint_type
BICAN_matrix_scores_df_V17$reclustered_neuron_joint_type = NULL
BICAN_matrix_scores_df_V17$pct_mito = BICAN_matrix_scores_df_V17$pct_mt 
BICAN_matrix_scores_df_V17$pct_mt  = NULL
BICAN_matrix_scores_df_V17$nUmi = BICAN_matrix_scores_df_V17$NUM_TRANSCRIPTS 
BICAN_matrix_scores_df_V17$NUM_TRANSCRIPTS  = NULL
BICAN_matrix_scores_df_V17$donor_id = BICAN_matrix_scores_df_V17$DONOR 
BICAN_matrix_scores_df_V17$DONOR  = NULL

XDP_matrix_scores_df
BICAN_matrix_scores_df_V8
BICAN_matrix_scores_df_V17

Combined_scores_df = rbind(XDP_matrix_scores_df, BICAN_matrix_scores_df_V8, BICAN_matrix_scores_df_V17)
Combined_scores_df

table(Combined_scores_df$Condition, Combined_scores_df$reclustered_patch_matrix_exotic)
table(Combined_scores_df$Condition, Combined_scores_df$reclustered_neuron_type_joint_cluster)

min(Combined_scores_df$total_expression)
max(Combined_scores_df$total_expression)
```

```{r}

limits = seq(0, 120, 2)

matrix <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  patch <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    exotic <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: Exotic SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    eSPN <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```





























#reals

```{r}
outlier_genes = c("FOXP1", "KCNH1", "SGK3", "CALM2", "TSPAN7", "PPP3R1", "SPATA13", "CSNK1G1", "PRB2", "RAP1GAP", "PCDH11X", "DPYD", "KCNAB1", "HS3ST4")
```


```{r}
NEW_Intersected_BICAN_matrix_markers_final_filtered = subset(Intersected_BICAN_matrix_markers_final_filtered, subset = !(gene %in% outlier_genes))
NEW_Intersected_BICAN_matrix_markers_final_filtered
```


```{r}
New_filtered_expression = subset(Intersected_BICAN_matrix_markers_final_filtered, subset = !(gene %in% outlier_genes))
New_filtered_expression

below_1 = new$gene
head(below_1)

New_filtered_expression = subset(New_filtered_expression, subset = gene %in% below_1)
New_filtered_expression
```


```{r}
XDP_matrix_scores = SPN_score_normalized(New_filtered_expression, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply")

XDP_matrix_scores$Village = "XDP"

V8_BICAN_scores = BICAN_SPN_score_normalized(New_filtered_expression, final_V8_BICAN_neurons, logfc_val = "weighted_logFC", method = "multiply")
V8_BICAN_scores$Village = "BICAN_V8"
V8_BICAN_scores

V17_BICAN_scores = BICAN_SPN_score_normalized(New_filtered_expression, final_V17_BICAN_neurons, logfc_val = "weighted_logFC", method = "multiply")
V17_BICAN_scores$Village = "BICAN_V17"
V17_BICAN_scores
```

```{r}
 V17_BICAN_scores$reclustered_patch_matrix_exotic = V17_BICAN_scores$reclustered_neuron_joint_type
 V17_BICAN_scores$reclustered_patch_matrix_exotic[V17_BICAN_scores$reclustered_cell_class == "D1_patch_exotic" | V17_BICAN_scores$reclustered_cell_class == "D2_patch_exotic"] = "SPN_exotic"
table(V17_BICAN_scores$reclustered_patch_matrix_exotic)

library(dplyr)
XDP_matrix_scores_df = XDP_matrix_scores %>% select(cell_id, donor_id, Condition, reclustered_patch_matrix_exotic, reclustered_patch_matrix, reclustered_neuron_type_joint_cluster,  pct_mito, nUmi, total_expression, scaled_score, Village)

BICAN_matrix_scores_df_V8 = V8_BICAN_scores %>% select(cell_id, DONOR, reclustered_patch_matrix, reclustered_neuron_joint_type,  pct_mt, NUM_TRANSCRIPTS, total_expression , scaled_score, Village) 

BICAN_matrix_scores_df_V17 = V17_BICAN_scores %>% select(cell_id, DONOR, reclustered_patch_matrix, reclustered_neuron_joint_type,reclustered_patch_matrix_exotic,  pct_mt, NUM_TRANSCRIPTS, total_expression , scaled_score, Village) 

BICAN_matrix_scores_df_V8$Condition = "BICAN Control V8"
BICAN_matrix_scores_df_V8$reclustered_patch_matrix_exotic = BICAN_matrix_scores_df_V8$reclustered_neuron_joint_type
BICAN_matrix_scores_df_V8$reclustered_neuron_type_joint_cluster = BICAN_matrix_scores_df_V8$reclustered_neuron_joint_type
BICAN_matrix_scores_df_V8$reclustered_neuron_joint_type = NULL
BICAN_matrix_scores_df_V8$pct_mito = BICAN_matrix_scores_df_V8$pct_mt 
BICAN_matrix_scores_df_V8$pct_mt  = NULL
BICAN_matrix_scores_df_V8$nUmi = BICAN_matrix_scores_df_V8$NUM_TRANSCRIPTS 
BICAN_matrix_scores_df_V8$NUM_TRANSCRIPTS  = NULL
BICAN_matrix_scores_df_V8$donor_id = BICAN_matrix_scores_df_V8$DONOR 
BICAN_matrix_scores_df_V8$DONOR  = NULL

BICAN_matrix_scores_df_V17$Condition = "BICAN Control V17"
BICAN_matrix_scores_df_V17$reclustered_neuron_type_joint_cluster = BICAN_matrix_scores_df_V17$reclustered_neuron_joint_type
BICAN_matrix_scores_df_V17$reclustered_neuron_joint_type = NULL
BICAN_matrix_scores_df_V17$pct_mito = BICAN_matrix_scores_df_V17$pct_mt 
BICAN_matrix_scores_df_V17$pct_mt  = NULL
BICAN_matrix_scores_df_V17$nUmi = BICAN_matrix_scores_df_V17$NUM_TRANSCRIPTS 
BICAN_matrix_scores_df_V17$NUM_TRANSCRIPTS  = NULL
BICAN_matrix_scores_df_V17$donor_id = BICAN_matrix_scores_df_V17$DONOR 
BICAN_matrix_scores_df_V17$DONOR  = NULL

XDP_matrix_scores_df
BICAN_matrix_scores_df_V8
BICAN_matrix_scores_df_V17

Combined_scores_df = rbind(XDP_matrix_scores_df, BICAN_matrix_scores_df_V8, BICAN_matrix_scores_df_V17)
Combined_scores_df

table(Combined_scores_df$Condition, Combined_scores_df$reclustered_patch_matrix_exotic)
table(Combined_scores_df$Condition, Combined_scores_df$reclustered_neuron_type_joint_cluster)

min(Combined_scores_df$total_expression)
max(Combined_scores_df$total_expression)
```

```{r}

limits = seq(0, 105, 2)

matrix <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  patch <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    exotic <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: Exotic SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    eSPN <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control V8" = "green", "BICAN Control V17" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```

```{r}
table(Combined_scores_df$reclustered_patch_matrix_exotic,Combined_scores_df$Condition)
```




```{r}
spn_genes = c("PPPR1B1")
spn_genes
```


#Add module score
```{r}
# Add SPN score
temp <- AddModuleScore(
  object = final_XDP_merged_transformed,
  features = list(SPN = spn_genes),
  name = 'SPN_score'
)

# Inspect the new SPN score column
head(seurat_obj@meta.data)

# Define a threshold to identify low SPN score cells
threshold <- quantile(seurat_obj@meta.data$SPN_score1, 0.1)  # Example threshold at the 10th percentile

# Find cells with low SPN scores
low_spn_cells <- seurat_obj@meta.data[seurat_obj@meta.data$SPN_score1 < threshold, ]

# Visualize
DimPlot(seurat_obj, group.by = "SPN_score1")

```



