---
title: "R Notebook"
output: html_notebook
---

```{r}
xdp_neurons = qread("~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_merged_xdp_neurons.qs")
xdp_neurons

BICAN_V8 = qread("~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_V8_BICAN_neurons.qs")
BICAN_V8
```

```{r}
histograms_by_celltype = function(final_df, score_col, xlab){

  
min = min(final_df[[score_col]])
max = max(final_df[[score_col]])
step = (max-min)/100

limits = seq(min, max, step)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  a = plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix[[score_col]],
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green", "pd" = "red", "ctr" = "blue", "XDP_18_006" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = xlab,
                                          fig_filename = NULL)
  
patch <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  b= plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch[[score_col]],
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green", "pd" = "red", "ctr" = "blue","XDP_18_006" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = xlab,
                                          fig_filename = NULL)
  
  nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
 c=  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN[[score_col]],
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green", "pd" = "red", "ctr" = "blue","XDP_18_006" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = xlab,
                                          fig_filename = NULL)
  

    eSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "eSPN", ]
  d= plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN[[score_col]],
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green", "pd" = "red", "ctr" = "blue","XDP_18_006" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = xlab,
                                          fig_filename = NULL)
  
      exotic <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  e= plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic[[score_col]],
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green", "pd" = "red", "ctr" = "blue","XDP_18_006" = "orange"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = xlab,
                                          fig_filename = NULL)
 
  
print(a) 
print(b) 
print(c) 
print(d) 
print(e) 
}
```

```{r}
spn_bican = qread("SPN_Matrix_BICAN_findmarkers.qs")
spn_bican = rownames(spn_bican)
```

```{r}
test_xdp = xdp_neurons
```

#Comparing RNA and SCT scores
```{r}
length(rownames(test_xdp))
DefaultAssay(test_xdp) = "RNA"
length(rownames(test_xdp))
```

```{r}
test_xdp <- AddModuleScore_UCell(test_xdp,
  features = list(SPN_matrix = spn_bican),
  name = 'SCT_SPN'
)

DefaultAssay(test_xdp) = "RNA"
test_xdp <- AddModuleScore_UCell(test_xdp,
  features = list(SPN_matrix = spn_bican),
  name = 'RNA_SPN'
)
```

```{r}
meta_RNA_SCT = test_xdp@meta.data
meta_RNA_SCT
```

```{r}
histograms_by_celltype(final_df= meta_RNA_SCT, score_col = "SPN_matrixSCT_SPN", xlab = "SPN Scores - SCT")
```


```{r}
histograms_by_celltype(final_df= meta_RNA_SCT, score_col = "SPN_matrixRNA_SPN", xlab = "SPN Scores - RNA")
```
```{r}
cortest <- cor.test(meta_RNA_SCT$SPN_matrixRNA_SPN, meta_RNA_SCT$SPN_matrixSCT_SPN, method = "spearman", exact = FALSE )
cortest
cor <- cortest$estimate
pvalue <- cortest$p.value
subtitle <- paste("Spearman correlation: ", sprintf("%0.3f", cor), " R^2: ", sprintf("%0.3f", cor^2), " p-value: ", sprintf("%0.3f", pvalue))


ggplot(meta_RNA_SCT, aes(x=SPN_matrixRNA_SPN, y=SPN_matrixSCT_SPN, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("SPN matrix score", subtitle = subtitle) + xlab("RNA") + ylab("SCT")

ggplot(meta_RNA_SCT, aes(x=SPN_matrixRNA_SPN, y=SPN_matrixSCT_SPN, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("SPN matrix score") + xlab("RNA") + ylab("SCT") +facet_wrap(~ Condition)

ggplot(meta_RNA_SCT, aes(x=SPN_matrixRNA_SPN, y=SPN_matrixSCT_SPN, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("SPN matrix score") + xlab("RNA") + ylab("SCT") +facet_wrap(~ reclustered_patch_matrix_exotic)
```

#now comparing between datasets for just SCT

```{r}
test_bican = BICAN_V8
DefaultAssay(test_bican) = "SCT"
DefaultAssay(test_xdp) = "SCT"
test_xdp
test_bican
```
#17417 shared genes
```{r}
xdp_genes = rownames(test_xdp)
length(xdp_genes)
bican_genes = rownames(test_bican)
length(bican_genes)
intersected_genes = intersect(xdp_genes, bican_genes)
length(intersected_genes)
```

```{r}
test_xdp = subset(test_xdp, features = intersected_genes)
test_xdp

test_bican = subset(test_bican, features = intersected_genes)
test_bican
```

```{r}
xdp_neurons
BICAN_V8
```

```{r}
c_minus_genes = readRDS("~/ferris_handsaker_genes_phase_c_minus.rds")
c_plus_genes = readRDS("~/ferris_handsaker_genes_phase_c_plus.rds")
d_genes = readRDS("~/ferris_handsaker_genes_phase_d.rds")
c_minus_genes
c_plus_genes
d_genes
```

#186/203 c minus genes, 340/369 c plus genes, 32/107 d genes
```{r}
length(c_minus_genes)
new_c_minus_genes = intersect(rownames(xdp_neurons), c_minus_genes) 
length(new_c_minus_genes)

length(c_plus_genes)
new_c_plus_genes = intersect(rownames(xdp_neurons), c_plus_genes) 
length(new_c_plus_genes)

length(d_genes)
new_d_genes = intersect(rownames(xdp_neurons), d_genes) 
length(new_d_genes)
```

#186/203 c minus genes, 339/369 c plus genes, 30/107 d genes 
```{r}
length(new_c_minus_genes)
new_c_minus_genes_BICAN = intersect(rownames(BICAN_V8), new_c_minus_genes) 
length(new_c_minus_genes_BICAN)

length(new_c_plus_genes)
new_c_plus_genes_BICAN = intersect(rownames(BICAN_V8), new_c_plus_genes) 
length(new_c_plus_genes_BICAN)

length(new_d_genes)
new_d_genes_BICAN = intersect(rownames(BICAN_V8), new_d_genes) 
length(new_d_genes_BICAN)
```
```{r}
test_xdp <- AddModuleScore_UCell(test_xdp,
  features = list(Score = spn_bican),
  name = 'SPN_Matrix'
)

test_bican <- AddModuleScore_UCell(test_bican,
  features = list(Score = spn_bican),
  name = 'SPN_Matrix'
)

test_xdp <- AddModuleScore_UCell(test_xdp,
  features = list(Score = new_c_minus_genes_BICAN),
  name = 'C_MINUS'
)

test_bican <- AddModuleScore_UCell(test_bican,
  features = list(Score = new_c_minus_genes_BICAN),
  name = 'C_MINUS'
)

test_xdp <- AddModuleScore_UCell(test_xdp,
  features = list(Score = new_c_plus_genes_BICAN),
  name = 'C_PLUS'
)

test_bican <- AddModuleScore_UCell(test_bican,
  features = list(Score = new_c_plus_genes_BICAN),
  name = 'C_PLUS'
)

test_xdp <- AddModuleScore_UCell(test_xdp,
  features = list(Score = new_d_genes_BICAN),
  name = 'D'
)

test_bican <- AddModuleScore_UCell(test_bican,
  features = list(Score = new_d_genes_BICAN),
  name = 'D'
)
```

```{r}
xdp_test = test_xdp@meta.data
bican_test = test_bican@meta.data

xdp_test
bican_test
```


```{r}
bican_test$Condition = "BICAN_V8"

xdp_test <- xdp_test[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "ScoreSPN_Matrix", "ScoreC_MINUS", "ScoreC_PLUS", "ScoreD")]  
bican_test <- bican_test[, c("DONOR", "Condition", "reclustered_neuron_joint_type", "ScoreSPN_Matrix", "ScoreC_MINUS", "ScoreC_PLUS", "ScoreD")]

bican_test$donor_id = bican_test$DONOR
bican_test$DONOR = NULL

bican_test$reclustered_patch_matrix_exotic = bican_test$reclustered_neuron_joint_type
bican_test$reclustered_neuron_joint_type = NULL
bican_test$reclustered_patch_matrix_exotic[bican_test$reclustered_patch_matrix_exotic == "SPN_patch"] = "SPN_exotic"

final_df = rbind(xdp_test, bican_test)
final_df
```

```{r}
histograms_by_celltype(final_df= final_df, score_col = "ScoreSPN_Matrix", xlab = "SPN Score - 17417 features")
histograms_by_celltype(final_df= final_df, score_col = "ScoreC_MINUS", xlab = "C Minus Score - 17417 features")
histograms_by_celltype(final_df= final_df, score_col = "ScoreC_PLUS", xlab = "C Plus Score - 17417 features")
histograms_by_celltype(final_df= final_df, score_col = "ScoreD", xlab = "D Score - 17417 features")
```

```{r}
test_bican
test_xdp
```


```{r}
original_df = qread("XDP_BICAN_ucell_scores.qs")
original_df
```
```{r}
final_df$cell = rownames(final_df)
original_df$cell = rownames(original_df)

combo = merge(final_df, original_df, by = "cell")
combo
```

```{r}
SPNSPN_Matrix_scores_UCELL - ScoreSPN_Matrix
C_minusSPN_Matrix_scores_UCELL - ScoreC_MINUS
C_plusSPN_Matrix_scores_UCELL - ScoreC_PLUS
D_genesSPN_Matrix_scores_UCELL - ScoreD
```


```{r}
cortest <- cor.test(combo$C_plusSPN_Matrix_scores_UCELL, combo$ScoreC_PLUS, method = "pearson", exact = FALSE )
cortest
cor <- cortest$estimate
pvalue <- cortest$p.value
subtitle <- paste("Pearson correlation: ", sprintf("%0.3f", cor), " R^2: ", sprintf("%0.3f", cor^2), " p-value: ", sprintf("%0.3f", pvalue))


ggplot(combo, aes(x=C_plusSPN_Matrix_scores_UCELL, y=ScoreC_PLUS, color=reclustered_patch_matrix_exotic.x)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("C Plus score", subtitle = subtitle) + xlab("Original") + ylab("17417 features")

ggplot(combo, aes(x=C_plusSPN_Matrix_scores_UCELL, y=ScoreC_PLUS, color=reclustered_patch_matrix_exotic.x)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("C Plus score") + xlab("Original") + ylab("17417 features") +facet_wrap(~ Condition.x)

ggplot(combo, aes(x=C_plusSPN_Matrix_scores_UCELL, y=ScoreC_PLUS, color=reclustered_patch_matrix_exotic.x)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("C Plus score") + xlab("Original") + ylab("17417 features") +facet_wrap(~ reclustered_patch_matrix_exotic.x)

```

```{r}
xdp_neurons
BICAN_V8
```

```{r}
sum(rowSums(xdp_neurons@assays$RNA@counts) > 0)

sum(rowSums(BICAN_V8@assays$RNA@counts) > 0)
```

```{r}
xdp_sct = as.data.frame(rowSums(test_xdp@assays$SCT@counts))
xdp_sct

bican_sct = as.data.frame(rowSums(test_bican@assays$SCT@counts))
bican_sct
```
```{r}
xdp_sct$genes = rownames(xdp_sct)
bican_sct$genes = rownames(bican_sct)
merge_sct = merge(xdp_sct, bican_sct, by = "genes")
merge_sct
```
```{r}
ggplot(merge_sct, aes(x=rowSums(test_xdp@assays$SCT@counts), y=rowSums(test_bican@assays$SCT@counts))) + geom_point(alpha = 0.4, color = "red") + xlab("XDP SCT counts") +ylab("BICAN SCT counts") 
#+ xlim(0,1000000) +ylim(0,1000000)

#+ ggtitle("C Plus score", subtitle = subtitle) + xlab("Original") + ylab("17417 features")
```

