---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(Matrix)
library(dplyr)
library(qs)
library(ggplot2)
```

```{r}
normalizeScalePcaClusterUmap = function(
   sobj,
   subset_col="donor_id",
   n_hvgs_orig=2500,
   n_dims_use=20,
   resolutions=c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)){
   # this function takes a Seurat object, normalizes the data, scales the data, runs PCA, finds neighbors,
   # clusters at a variety of resolutions, and runs UMAP
   # it then returns the Seurat object
  
   hvgs = getSeuratVarFeatureIntersectByCol(sobj, subset_col=subset_col, original_nfeatures=n_hvgs_orig)
   sobj = (sobj
       %>% NormalizeData()
       %>% ScaleData(features=hvgs, split.by=subset_col) #get rid of spilt by and add var.by.regress***
       %>% RunPCA(features=hvgs, npcs=n_dims_use)
       %>% FindNeighbors(dims = 1:n_dims_use)
   )
   for(res in resolutions){
       sobj = sobj %>% FindClusters(resolution = res)
   }
    sobj = sobj %>% RunUMAP(dims = 1:n_dims_use)
   return(sobj)
}

assignCellClasses = function(
   obj,
   classes,
   cluster_col="seurat_clusters",
   class_col="cell_class") {
   obj@meta.data[[class_col]] = NA  # Assign NA to the entire column in meta.data


   for (i in 1:length(classes)) {
       # Find cells that match the current cluster number
       cells = which(as.numeric(obj@meta.data[[cluster_col]]) == i)
     
       # Assign the class label to the cells in the cluster
       obj@meta.data[cells, class_col] = classes[[i]]
   }
  
   # Return the modified object
   return(obj)
}

getSeuratVarFeatureIntersectByCol = function(
   seurat_obj,
   subset_col,
   original_nfeatures,
   n_subsets_to_cover=NULL
){
  
   hvgs = list()


   unique_ids = unique(seurat_obj@meta.data[[subset_col]])


   if (is.null(n_subsets_to_cover)){
       n_subsets_to_cover = floor(length(unique_ids)/2)
   }


   i=1
   for (id in unique_ids) {
       print(paste("Subset", id, "--", i, "of", length(unique_ids)))
       i = i + 1
      
       seurat_subset = seurat_obj[, seurat_obj[[subset_col]] == id]
      
       if (ncol(seurat_subset) < 2){next}
      
       suppressWarnings({
           seurat_subset = FindVariableFeatures(
               seurat_subset, nfeatures=original_nfeatures, verbose = FALSE)
       })
      
       hvgs[[id]] = getSeuratVarFeatures(seurat_subset)
      
   }


   common_hvgs = getCommonStrings(hvgs, n_subsets_to_cover)
   print(paste("Number of HVGs in common across", n_subsets_to_cover, "--", length(common_hvgs)))


   return(common_hvgs)
}


getSeuratVarFeatures = function(sobj){
    # the magical incantation that returns the slot of the attribute of the slot that actually holds the list of variable feature -_-
    return(sobj@assays$RNA@var.features)
}

getCommonStrings <- function(list_of_lists, n) {
  # Create an empty list to store string occurrences
  string_occurrences <- list()

  # Iterate over each sublist
  for (sublist in list_of_lists) {
    # For each string in the sublist, increment its count in string_occurrences
    for (string in unique(sublist)) {
      if (!is.null(string_occurrences[[string]])) {
        string_occurrences[[string]] <- string_occurrences[[string]] + 1
      } else {
        string_occurrences[[string]] <- 1
      }
    }
  }

  # Filter the strings that occur at least n times
  common_strings <- names(string_occurrences)[string_occurrences >= n]

  return(common_strings)
}

mergeSeuratListWithMetadata = function(seurat_obj_list, cell_ids=NULL, project=NULL){

    # Harmonize metadata columns
    all_colnames = unique(unlist(lapply(seurat_obj_list, function(x) colnames(x@meta.data))))
    seurat_obj_list = lapply(seurat_obj_list, function(x) {
        missing_cols = setdiff(all_colnames, colnames(x@meta.data))
        if(length(missing_cols) > 0){
            x@meta.data[missing_cols] = NA
        }
        return(x)
    })

    if (is.null(project)){
        project = "merged"
    }
    
    if (is.null(cell_ids)){
        seurat_merged = Reduce(function(x, y) merge(x, y, project=project), 
            seurat_obj_list)
    } else {
        seurat_merged = Reduce(function(x, y) merge(x, y, project=project, add.cell.ids=cell_ids), 
            seurat_obj_list)
    }
    
    md = lapply(seurat_obj_list, function(x){
        x@meta.data$orig.row.names = rownames(x@meta.data)
        x@meta.data
    })
    
    md = do.call(rbind, md)
    rownames(md) = md$orig.row.names
    md$orig.row.names = NULL
    seurat_merged@meta.data = md
    return(seurat_merged)
}
```


```{r}
calico_putamen = qread("~/calico_putamen.qs")
calico_putamen
calico_putamen@meta.data
DimPlot(calico_putamen, label = T, raster=FALSE)

table(calico_putamen$case_control)
```

```{r}
DimPlot(calico_putamen, label = T, raster=FALSE)
DimPlot(calico_putamen, raster=FALSE, group.by = "RNA_snn_res.0.2")
DimPlot(calico_putamen, raster=FALSE, group.by = "RNA_snn_res.0.3")
DimPlot(calico_putamen, raster=FALSE, group.by = "RNA_snn_res.0.4")
```

```{r}
hist(calico_putamen$nUMI)
hist(calico_putamen$QC_MT.pct)
hist(calico_putamen$pct_intronic)
```

```{r}
calico_putamen
calico_putamen = subset(calico_putamen, subset= nUMI > 1000)
calico_putamen
```


```{r}
calico_putamen = subset(calico_putamen, subset= pct_intronic > 20)
calico_putamen
```

```{r}
calico_putamen = subset(calico_putamen, subset= QC_MT.pct < 10)
calico_putamen
```
#1668 cells filtered
```{r}
hist(calico_putamen$nUMI)
hist(calico_putamen$QC_MT.pct)
hist(calico_putamen$pct_intronic)
```

```{r}
FeaturePlot(calico_putamen, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE,)
FeaturePlot(calico_putamen, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE,) 
FeaturePlot(calico_putamen, features = c("PPP1R1B", "CASZ1", "DRD1", "DRD2"),raster=FALSE,)
FeaturePlot(calico_putamen, features = c("QC_MT.pct", "nUMI"),raster=FALSE,)
```
```{r}
calico_putamen@meta.data
```


```{r}
Idents(calico_putamen) = calico_putamen$crude_cell_class
putamen_markers = FindAllMarkers(calico_putamen, only.pos = TRUE, min.pct = 0.5, logfc.threshold = 3)
putamen_markers
```
```{r}
putamen_markers_sub = subset(putamen_markers, subset = cluster == "unsure")
putamen_markers_sub
```

```{r}
rownames(putamen_markers_sub)
```

```{r}
DimPlot(calico_putamen, group.by = "crude_cell_class" ,label = T, raster = FALSE)
```


```{r}
FeaturePlot(calico_putamen, features = c("NELL1", "GAD1"),raster=FALSE)
```


```{r}
Idents(calico_putamen) = calico_putamen$RNA_snn_res.0.2

classes = c("oligo", "neuron", "neuron", "neuron", "endo", "neuron", "neuron", "neuron", "neuron", "neuron", "astrocyte", "neuron", "astrocyte", "opc","oligo", "microglia", "neuron", "neuron","neuron")

calico_putamen= assignCellClasses(calico_putamen, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "crude_cell_class")

DimPlot(calico_putamen, group.by = "crude_cell_class" ,label = T, raster = FALSE)
```

```{r}
qsave(calico_putamen, "~/calico_putamen.qs")
```

```{r}
calico_putamen = qread("~/calico_putamen.qs")
table(calico_putamen$crude_cell_class)
```

```{r}
calico_subset = subset(calico_putamen, subset = crude_cell_class == "opc")

calico_subset= normalizeScalePcaClusterUmap(calico_subset,
   subset_col="participant_id",
   n_hvgs_orig=2500,
   n_dims_use=20,
   resolutions=c(0.2, 0.3))
   #resolutions=c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1))

calico_subset
DimPlot(calico_subset, group.by = "crude_cell_class", label = T, raster = FALSE)
DimPlot(calico_subset, group.by = "case_control", label = T, raster = FALSE)
DimPlot(calico_subset, group.by = "RNA_snn_res.0.2", label = T, raster = FALSE)
#DimPlot(calico_subset, group.by = "RNA_snn_res.0.3", label = T, raster = FALSE)
#DimPlot(calico_subset, group.by = "RNA_snn_res.0.4", label = T, raster = FALSE)
#DimPlot(calico_subset, group.by = "RNA_snn_res.0.5", label = T, raster = FALSE)
#DimPlot(calico_subset, group.by = "RNA_snn_res.0.6", label = T, raster = FALSE)
FeaturePlot(calico_subset, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(calico_subset, features = c("OLIG1", "OLIG2", "MOG" ,"BCAS1"),raster=FALSE) 
```

```{r}
FeaturePlot(calico_subset, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(calico_subset, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(calico_subset, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(calico_subset, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(calico_subset, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(calico_subset, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(calico_subset, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(calico_subset, features = c("P2RY12", "CX3CR1", "C1QB"),raster=FALSE) 
```

```{r}
FeaturePlot(calico_subset, features = c("P2RY12", "CX3CR1", "C1QB"),raster=FALSE) 
```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7")


Dotplot = DotPlot(object = calico_subset, features = marker_genes, group.by = "RNA_snn_res.0.3")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```


```{r}
A = FindAllMarkers(calico_subset, min.pct = 0.7, logfc.threshold = 4, only.pos = TRUE)
A
```
```{r}
table(calico_subset$RNA_snn_res.0.2)
```


```{r}
Idents(calico_subset) = calico_subset$RNA_snn_res.0.3

classes = c("0", "1","2", "3", "doublet", "5", "6", "7", "doublet", "doublet")

calico_subset= assignCellClasses(calico_subset, classes=classes, cluster_col="RNA_snn_res.0.3", class_col = "sub_class")

DimPlot(calico_subset, group.by = "sub_class" ,label = T, raster = FALSE)
```


```{r}
calico_subset
calico_clean <- subset(calico_subset, subset = sub_class != "doublet")
calico_clean
table(calico_clean$sub_class)
DimPlot(calico_clean, group.by = "crude_cell_class", label = T, raster = FALSE)
DimPlot(calico_clean, group.by = "RNA_snn_res.0.2", label = T, raster = FALSE)
DimPlot(calico_clean, group.by = "RNA_snn_res.0.3", label = T, raster = FALSE)
FeaturePlot(calico_clean, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(calico_clean, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(calico_clean, features = c("CACNG4", "SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE)
```

```{r}
# Assuming 'seurat_obj' is your Seurat object and you're plotting MBP

# Extract gene expression for MBP
mbp_expression <- FetchData(calico_subset, vars = "CX3CR1")

# Convert to a dataframe
mbp_df <- as.data.frame(mbp_expression)

# Load ggplot2 for visualization
library(ggplot2)

# Create a histogram of MBP expression
ggplot(mbp_df, aes(x = CX3CR1)) +
  geom_histogram(binwidth = 0.01, fill = "blue", color = "black") +
  theme_minimal() +
  labs(title = "Histogram of MBP Expression", x = "MBP Expression", y = "Frequency") +xlim(0,1)

```



```{r}
calico_subset
calico_clean <- subset(calico_subset, subset = RBFOX3 < 0.01 | CX3CR1 <0.01 | AQP4 < 0.01 | C1QB < 0.01)
calico_clean
```


```{r}
FeaturePlot(calico_clean, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(calico_clean, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(calico_clean, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(calico_clean, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(calico_clean, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(calico_clean, features = c("DRD1", "DRD2", "CASZ1" ,"PPP1R1B"),raster=FALSE) 
FeaturePlot(calico_clean, features = c("EPHA4", "SEMA3E", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(calico_clean, features = c("P2RY12", "CX3CR1", "C1QB"),raster=FALSE)
```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7")


Dotplot = DotPlot(object = calico_clean, features = marker_genes, group.by = "sub_class")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```



```{r}
qsave(calico_clean, "pd_clean_opc_NEW_093024.qs")
```




```{r}
pd_oligo = qread("pd_clean_oligo_NEW.qs")
pd_opc = qread("pd_clean_opc_NEW_093024.qs")
pd_mg = qread("pd_clean_microglia_NEW.qs")
pd_neuron = qread("pd_clean_neuron_NEW.qs")
pd_endo = qread("pd_clean_endo_NEW.qs")
pd_astro = qread("pd_clean_astrocyte_NEW.qs")

pd_list = list(pd_oligo, pd_opc, pd_mg,pd_neuron,pd_endo, pd_astro)
pd_list

pd_putamen_sobj = mergeSeuratListWithMetadata(pd_list, cell_ids=NULL, project=NULL)
pd_putamen_sobj
head(pd_putamen_sobj)
```
```{r}
pd_putamen_sobj
```

```{r}
qsave(pd_putamen_sobj, "~/pd_putamen_sobj_notscaled_093024.qs")
```


```{r}
# Counts of super lowly expressed genes are essentially random
# Also, we don't really care about housekeeping genes that have almost the same expression in every cell
# Before clustering, we want to find "highly variable genes" (hvgs) that tend to be both highly expressed and vary a lot from cell to cell.
# we do this by finding hvgs in each participant individually, and collating the genes
# that are highly variable in at least half of donors.


# this code should take 3-10 minutes
hvgs = getSeuratVarFeatureIntersectByCol(pd_putamen_sobj, subset_col="donor_id", original_nfeatures=2500)


n_dims_use=20

# now cluster
# the "%>%" lines are a little piece of syntax from the dyplr library,
# short for "apply the following transformation to the object"
# doing this line-by-line allows us to apply a sequence of transformations
pd_putamen_sobj = (pd_putamen_sobj
   %>% NormalizeData() # log normalizes raw counts
   %>% ScaleData(features=hvgs, split.by="donor_id") # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
   %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
   %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
   %>% FindClusters(resolution = 0.01) # finds clusters at a variety of resolutions
  # %>% FindClusters(resolution = 0.05) # after clustering, the cluster labels are accessible via filtered_merged_caudate$RNA_snn_res.{resolution}
  # %>% FindClusters(resolution = 0.1) # e.g.: filtered_merged_caudate$RNA_snn_res.0.4 here
   #%>% FindClusters(resolution = 0.15)
   %>% FindClusters(resolution = 0.2)
    #  %>% FindClusters(resolution = 0.3)
   %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
)


# Now we can plot the data and just see what it looks like


setwh = function(w, h){
   # set the width of the ensuing figures to w, height to h
   options(repr.plot.width = w, repr.plot.height = h)
}

head(pd_putamen_sobj)
```

```{r}
pd_putamen_sobj
```
```{r}
table(pd_putamen_sobj$sub_class)
```


```{r}
DimPlot(pd_putamen_sobj, group.by = "library",raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "donor_id",raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "case_control",raster=FALSE) 
DimPlot(pd_putamen_sobj, group.by = "RNA_snn_res.0.01", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "RNA_snn_res.0.05", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "RNA_snn_res.0.1", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "RNA_snn_res.0.15", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "RNA_snn_res.0.2", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "RNA_snn_res.0.3", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "crude_cell_class", label=T,raster=FALSE)
DimPlot(pd_putamen_sobj, group.by = "sub_class", label=T,raster=FALSE)
```

```{r}
Idents(pd_putamen_sobj_zoom) = pd_putamen_sobj_zoom$RNA_snn_res.0.01

classes = c("neuron", "oligo", "astrocyte", "oligo", "neuron", "opc", "microglia", "endo", "oligo", "oligo")

pd_putamen_sobj_zoom= assignCellClasses(pd_putamen_sobj_zoom, classes=classes, cluster_col="RNA_snn_res.0.01", class_col = "updated_cell_class")

DimPlot(pd_putamen_sobj_zoom, group.by = "updated_cell_class" ,label = T, raster = FALSE)
```


```{r}
FeaturePlot(pd_putamen_sobj, features = c("GAPDH", "QC_MT.pct", "DRD1", "DRD2"),raster=FALSE)
FeaturePlot(pd_putamen_sobj, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(pd_putamen_sobj, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(pd_putamen_sobj, features = c("CACNG4", "SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE)
```

```{r}
Idents(pd_putamen_sobj) = pd_putamen_sobj$RNA_snn_res.0.2

classes = c("neuron", "oligo", "neuron", "oligo", "astrocyte", "oligo", "opc", "microglia", "oligo", "oligo", "neuron", "neuron", "astrocyte", "neuron", "oligo", "astrocyte", "neuron", "neuron", "oligo", "oligo", "neuron", "endo", "astrocyte", "oligo", "neuron", "opc", "oligo", "astrocyte", "neuron", "oligo")

pd_putamen_sobj= assignCellClasses(pd_putamen_sobj, classes=classes, cluster_col="RNA_snn_res.0.2", class_col = "updated_cell_class")

DimPlot(pd_putamen_sobj, group.by = "updated_cell_class" ,label = T, raster = FALSE)
```
```{r}
pd_putamen_sobj_zoom@meta.data
Idents(pd_putamen_sobj_zoom) = pd_putamen_sobj_zoom$updated_cell_class
DimPlot(pd_putamen_sobj_zoom, raster = F)
```
```{r}
qsave(pd_putamen_sobj_zoom, "pd_clean_putamen.qs")
```


#retry spn scores
```{r}
calico_putamen = subset(pd_putamen_sobj_zoom, subset = updated_cell_class == "neuron")
calico_putamen
calico_putamen@meta.data
DimPlot(calico_putamen, group.by = "updated_cell_class", label = T, raster = FALSE)
DimPlot(calico_putamen, group.by = "case_control", label = T, raster = FALSE)
```

```{r}
FeaturePlot(calico_putamen, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE,)
FeaturePlot(calico_putamen, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE,) 
FeaturePlot(calico_putamen, features = c("CACNG4", "SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE,)
FeaturePlot(calico_putamen, features = c("QC_MT.pct", "nUMI"),raster=FALSE,)
```

```{r}
head(calico_putamen)
```

```{r}
table(calico_putamen$donor_id)
table(calico_putamen$participant_id)
```


```{r}
calico_putamen = normalizeScalePcaClusterUmap(calico_putamen, subset_col = "donor_id", resolutions = c(0.01, 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1))
DimPlot(calico_putamen)
DimPlot(calico_putamen, group.by = "participant_id", raster = F)
DimPlot(calico_putamen, group.by = "updated_cell_class", raster = F)
DimPlot(calico_putamen, group.by = "library", raster = F)
DimPlot(calico_putamen, group.by = "case_control", raster = F)
```
```{r}
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.01", raster = F)
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.05", raster = F)
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.1", raster = F)
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.15", raster = F)
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.2", raster = F)
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.3", raster = F)
DimPlot(calico_putamen, group.by = "RNA_snn_res.0.4", raster = F)

FeaturePlot(calico_putamen, features = c("DRD1", "DRD2"),raster=FALSE,)

FeaturePlot(calico_putamen, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE,)
FeaturePlot(calico_putamen, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE,) 
FeaturePlot(calico_putamen, features = c("CACNG4", "SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE,)
FeaturePlot(calico_putamen, features = c("QC_MT.pct", "nUMI"),raster=FALSE,)
```

```{r}
#qsave(calico_putamen, "~/scaled_calico_put_temp.qs")
```

```{r}
pd_neuron
```


```{r}
library(harmony)

calico_putamen_integrated = (pd_neuron
    %>% RunHarmony(
        group.by = "donor_id")
    %>% FindNeighbors(reduction='harmony', dims=1:20)
    %>% FindClusters(res=0.2)
    %>% FindClusters(res=0.3)
    %>% FindClusters(res=0.4)
    %>% FindClusters(res=0.5)
    %>% RunUMAP(reduction="harmony", dims=1:20)
)
calico_putamen_integrated

# DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.01", raster = F)
# DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.05", raster = F)
# DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.1", raster = F)
# DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.15", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.2", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.3", raster = F)
DimPlot(calico_putamen_integrated, group.by = "RNA_snn_res.0.4", raster = F)
DimPlot(calico_putamen_integrated, group.by = "participant_id", raster = F)
DimPlot(calico_putamen_integrated, group.by = "sub_class", raster = F)
DimPlot(calico_putamen_integrated, group.by = "case_control", raster = F)
```

```{r}
FeaturePlot(calico_putamen_integrated, features = c("SYT1","SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE)
FeaturePlot(calico_putamen_integrated, features = c("DRD1", "DRD2", "EPHA4", "SEMA3E"),raster=FALSE)
FeaturePlot(calico_putamen_integrated, features = c("QC_MT.pct", "nUMI"),raster=FALSE)

FeaturePlot(calico_putamen_integrated, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE,)
FeaturePlot(calico_putamen_integrated, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE,) 
FeaturePlot(calico_putamen_integrated, features = c("CACNG4", "SLC6A3", "PPP1R1B", "CASZ1"),raster=FALSE,)
FeaturePlot(calico_putamen_integrated, features = c("QC_MT.pct", "nUMI"),raster=FALSE,)
FeaturePlot(calico_putamen_integrated, features = c("LAMP5","VIP", "SST", "PVALB"),raster=FALSE)
```

```{r}
FeaturePlot(calico_putamen_integrated, features = c("LAMP5","VIP", "SST", "PVALB"),raster=FALSE)
```

```{r}
DimPlot(calico_putamen_integrated, group.by = "sub_class", raster = F, label = T)
```


```{r}
Idents(calico_putamen_integrated) = calico_putamen_integrated$RNA_snn_res.0.8

classes = c("D1_matrix", "D2_matrix", "D2_matrix", "D2_patch_exotic", "D1_patch_exotic", "D1_matrix", "D1_matrix", "D2_matrix", "eSPN", "SPN_junk", "D1_patch", "interneuron", "D2_patch", "eSPN_2", "D2_matrix", "interneuron", "interneuron", "interneuron", "interneuron", "unsure", "interneuron", "interneuron", "interneuron", "interneuron", "eSPN", "D1_matrix", "D1_patch", "D2_matrix", "SPN_junk", "interneuron")
  
  #c("D2_matrix", "D1_matrix", "maybe_junk", "D1_patch", "D2_patch", "eSPN", "D2_split", "not_neuron", "interneuron_1", "interneuron_2", "eSPN_2", "interneuron_3", "interneuron_4", "interneuron_5", "interneuron_6", "interneuron_7", "interneuron_8", "D1_matrix", "eSPN")

calico_putamen_integrated= assignCellClasses(calico_putamen_integrated, classes=classes, cluster_col="RNA_snn_res.0.8", class_col = "neuron_cell_class")

DimPlot(calico_putamen_integrated, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
FeaturePlot(calico_putamen_integrated, features = c("LAMP5", "PVALB", "VIP"), raster = FALSE)
FeaturePlot(calico_putamen_integrated, features = c("GAD1", "GAD2","SST", "CALB2"), raster = FALSE)
FeaturePlot(calico_putamen_integrated, features = c("CUX2", "SATB2","SLC17A7", "SLC17A6"), raster = FALSE)
```


```{r}
calico_putamen_integrated
calico_putamen_integrated = subset(calico_putamen_integrated, subset = neuron_cell_class != "SPN_junk")
calico_putamen_integrated = subset(calico_putamen_integrated, subset = neuron_cell_class != "unsure")
calico_putamen_integrated
DimPlot(calico_putamen_integrated, group.by = "neuron_cell_class" ,label = T, raster = FALSE)
```

```{r}
table(calico_putamen_integrated$neuron_cell_class)
```

```{r}
calico_putamen_integrated@meta.data$subclass = calico_putamen_integrated$neuron_cell_class
calico_putamen_integrated$subclass[calico_putamen_integrated$subclass == "eSPN_2"] = "eSPN"

table(calico_putamen_integrated$subclass)
```

```{r}
DimPlot(calico_putamen_integrated, group.by = "subclass" ,label = T, raster = FALSE)
```


```{r}
calico_putamen_integrated@meta.data$final = calico_putamen_integrated$subclass
calico_putamen_integrated$final[calico_putamen_integrated$final == "D1_matrix"] = "SPN_matrix"
calico_putamen_integrated$final[calico_putamen_integrated$final == "D2_matrix"] = "SPN_matrix"
calico_putamen_integrated$final[calico_putamen_integrated$final == "D1_patch"] = "SPN_patch"
calico_putamen_integrated$final[calico_putamen_integrated$final == "D2_patch"] = "SPN_patch"
calico_putamen_integrated$final[calico_putamen_integrated$final == "D1_patch_exotic"] = "SPN_exotic"
calico_putamen_integrated$final[calico_putamen_integrated$final == "D2_patch_exotic"] = "SPN_exotic"
table(calico_putamen_integrated$final)
```

```{r}
Intersected_BICAN_matrix_markers_final_filtered = qread("~/rstudio/workdir/Old Work/SPN_Matrix_BICAN_findmarkers.qs")
Intersected_BICAN_matrix_markers_final_filtered
spn_bican = rownames(Intersected_BICAN_matrix_markers_final_filtered)
```

```{r}
Idents(calico_putamen_integrated) = "final"
calico_putamen_integrated <- AddModuleScore(
  object = calico_putamen_integrated,
  features = list(SPN = spn_bican),
  name = 'SPN_Matrix_scores'
)

new_df = calico_putamen_integrated@meta.data 
new_df
```

```{r}
table(new_df$subclass)
table(new_df$final)
```


```{r}
min(new_df$SPN_Matrix_scores1)
max(new_df$SPN_Matrix_scores1)
```


```{r}
limits = seq(-0.15, 0.4, 0.01)

matrix <- new_df[new_df$final == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: SPN matrix (zoom)",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  patch <- new_df[new_df$final == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: SPN patch(zoom)",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- new_df[new_df$final == "interneuron", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  

    eSPN <- new_df[new_df$final == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: eSPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
      exotic <- new_df[new_df$final == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$SPN_Matrix_scores1,
                                          fill_col = "case_control",
                                          colors = c("pd" = "red", "ctr" = "blue"),
                                          breaks = limits,
                                          title = "PD vs Control: SPN exotic patch(zoom)",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```

```{r}
qsave(calico_putamen_integrated, "~/calico_putamen_integrated_neurons.qs")
```

```{r}
DimPlot(calico_putamen_integrated, raster = FALSE)
```


```{r}
FeaturePlot(calico_putamen_integrated, features = c("SPN_Matrix_scores1", "QC_MT.pct","nUMI"), raster = FALSE)
```

```{r}
FeaturePlot(calico_putamen_integrated, features = c("SPN_Matrix_scores1"), raster = FALSE, split.by = "final")
```

```{r}
  # Subset the data
  SPN_score_output_identity_loss_SPN <- subset(new_df, subset = SPN_Matrix_scores1 < 0.45 & final == "SPN_matrix")
  
  print(SPN_score_output_identity_loss_SPN)
  print(table(SPN_score_output_identity_loss_SPN$participant_id))
  print(table(SPN_score_output_identity_loss_SPN$case_control))
```


```{r}
identity_loss_cells <- unique(rownames(SPN_score_output_identity_loss_SPN))
  
  calico_putamen_integrated@meta.data$SPN_identity <- "Other"
  calico_putamen_integrated$SPN_identity[identity_loss_cells] <- "Losing_Identity"
  calico_putamen_integrated@meta.data
```


```{r}
# Visualize on UMAP
  pic <- DimPlot(calico_putamen_integrated, reduction = "umap", group.by = "SPN_identity", split.by = "case_control", cols = c("red", "grey"))
  print(pic)
  ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
```

```{r}
pic = FeaturePlot(calico_putamen_integrated, features = c("QC_MT.pct","nUMI"), raster = FALSE)
print(pic)
 ggsave("~/SPN_SCORE_Output/SPN_score_10pct_TEST.png", plot = pic, width = 20, height = 8, units = "in", dpi = 300)
```


```{r}
# Visualize on UMAP
  
what = subset(calico_putamen_integrated, subset = participant_id == "PD0800")
DimPlot(what, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) + ggtitle("PD0800 SPN Matrix")

```



















```{r}
qsave(DFC_sobj, "~/new_092024/DFC_sobj_all.qs")

```










```{r}
head(calico_putamen)
```

```{r}
table(calico_putamen$donor_id)
table(calico_putamen$participant_id)
```


```{r}
calico_putamen = normalizeScalePcaClusterUmap(calico_putamen, subset_col = "donor_id", resolutions = c(0.01, 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1))
DimPlot(calico_putamen)
DimPlot(calico_putamen, group.by = "participant_id", raster = F)
DimPlot(calico_putamen, group.by = "cell_class", raster = F)
DimPlot(calico_putamen, group.by = "library", raster = F)
c
```





