---
title: "R Notebook"
output: html_notebook
---

#replace with V17

```{r}
normalizeScalePcaClusterUmap = function(
    sobj,
    subset_col="donor_id",
    n_hvgs_orig=2500,
    n_dims_use=20,
    resolutions=c(0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1)){
    # this function takes a Seurat object, normalizes the data, scales the data, runs PCA, finds neighbors, clusters, and runs UMAP
    # it then returns the Seurat object
    hvgs = getSeuratVarFeatureIntersectByCol(sobj, subset_col=subset_col, original_nfeatures=n_hvgs_orig)
    sobj = (sobj
        %>% NormalizeData() # log normalizes raw counts
        %>% ScaleData(features=hvgs, split.by=subset_col) # within each cell, for each gene scale the data (i.e. subtract the donor's mean and divide by the donor's standard deviation of that gene)
        %>% RunPCA(features=hvgs, npcs=n_dims_use) # Reduce the dimensions to the n_dims_use dimensions that best explain the data https://en.wikipedia.org/wiki/Principal_component_analysis
        %>% FindNeighbors(dims = 1:n_dims_use) # Finds every cells closest neighbors in the PCA space
    )
    for(res in resolutions){
        sobj = sobj %>% FindClusters(resolution = res) # finds clusters at a variety of resolutions
    }
    sobj = sobj %>% RunUMAP(dims = 1:n_dims_use) # projects the PCA onto 2 dimensions, such that both "global structure" and "local structure" are optimally preserved
    return(sobj)
}

getSeuratVarFeatureIntersectByCol = function(
   seurat_obj,
   subset_col,
   original_nfeatures,
   n_subsets_to_cover=NULL
){
  
   hvgs = list()


   unique_ids = unique(seurat_obj@meta.data[[subset_col]])


   if (is.null(n_subsets_to_cover)){
       n_subsets_to_cover = floor(length(unique_ids)/2)
   }


   i=1
   for (id in unique_ids) {
       print(paste("Subset", id, "--", i, "of", length(unique_ids)))
       i = i + 1
      
       seurat_subset = seurat_obj[, seurat_obj[[subset_col]] == id]
      
       if (ncol(seurat_subset) < 2){next}
      
       suppressWarnings({
           seurat_subset = FindVariableFeatures(
               seurat_subset, nfeatures=original_nfeatures, verbose = FALSE)
       })
      
       hvgs[[id]] = getSeuratVarFeatures(seurat_subset)
      
   }


   common_hvgs = getCommonStrings(hvgs, n_subsets_to_cover)
   print(paste("Number of HVGs in common across", n_subsets_to_cover, "--", length(common_hvgs)))


   return(common_hvgs)
}

getSeuratVarFeatures = function(sobj){
    # the magical incantation that returns the slot of the attribute of the slot that actually holds the list of variable feature -_-
    return(sobj@assays$RNA@var.features)
}

getCommonStrings <- function(list_of_lists, n) {
  # Create an empty list to store string occurrences
  string_occurrences <- list()

  # Iterate over each sublist
  for (sublist in list_of_lists) {
    # For each string in the sublist, increment its count in string_occurrences
    for (string in unique(sublist)) {
      if (!is.null(string_occurrences[[string]])) {
        string_occurrences[[string]] <- string_occurrences[[string]] + 1
      } else {
        string_occurrences[[string]] <- 1
      }
    }
  }

  # Filter the strings that occur at least n times
  common_strings <- names(string_occurrences)[string_occurrences >= n]

  return(common_strings)
}

assignCellClasses = function(
   obj,
   classes,
   cluster_col="seurat_clusters",
   class_col="cell_class") {
   obj@meta.data[[class_col]] = NA  # Assign NA to the entire column in meta.data


   for (i in 1:length(classes)) {
       # Find cells that match the current cluster number
       cells = which(as.numeric(obj@meta.data[[cluster_col]]) == i)
     
       # Assign the class label to the cells in the cluster
       obj@meta.data[cells, class_col] = classes[[i]]
   }
  
   # Return the modified object
   return(obj)
}
```

```{r}
library(qs)
library(Seurat)
library(ggplot2)
library(dplyr)
library(tidyr)
```


```{r}
BICAN_3P_V8_CaH = qread("BICAN_3P_V8_CaH.qs")
BICAN_5P_V8_CaH = qread("BICAN_5P_V8_CaH.qs")

BICAN_3P_V8_CaH
BICAN_5P_V8_CaH
```

```{r}
DimPlot(BICAN_3P_V8_CaH, label = TRUE)
```

#Findallmarkers on BICAN: SPN vs non-SPNs 
```{r}
BICAN_3P_V8_CaH_neurons = subset(BICAN_3P_V8_CaH, subset = predClass == "SPN" | predClass == "interneuron")
BICAN_3P_V8_CaH_neurons
```
```{r}
DimPlot(BICAN_3P_V8_CaH_neurons, label =TRUE)
BICAN_3P_V8_CaH_neurons = normalizeScalePcaClusterUmap(BICAN_3P_V8_CaH_neurons, subset_col = "DONOR", resolutions = c(0.01, 0.05, 0.1, 0.15, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1))

Idents(BICAN_3P_V8_CaH_neurons) = BICAN_3P_V8_CaH_neurons@meta.data$predClass
DimPlot(BICAN_3P_V8_CaH_neurons, label =TRUE)
```

```{r}
table(BICAN_3P_V8_CaH_neurons$predClass)
```

```{r}
head(BICAN_3P_V8_CaH_neurons)
```

```{r}
Idents(BICAN_3P_V8_CaH_neurons) = BICAN_3P_V8_CaH_neurons@meta.data$predClass
DimPlot(BICAN_3P_V8_CaH_neurons, group.by = "RNA_snn_res.0.2")
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("CASZ1", "CHAT"))
```
```{r}
DimPlot(BICAN_3P_V8_CaH_neurons, group.by = "RNA_snn_res.0.01")
DimPlot(BICAN_3P_V8_CaH_neurons, group.by = "RNA_snn_res.0.05")
DimPlot(BICAN_3P_V8_CaH_neurons, group.by = "RNA_snn_res.0.1")
DimPlot(BICAN_3P_V8_CaH_neurons, group.by = "RNA_snn_res.0.15")
DimPlot(BICAN_3P_V8_CaH_neurons, group.by = "RNA_snn_res.0.2")

```
```{r}
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("DRD1", "DRD2"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("EPHA4", "SEMA3E"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features =c("CASZ1","CHAT"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features =c("C1QA"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("PPP1R1B", "pct_mt"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("GAD1", "GAD2"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("VIP", "CALB2"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("SLC17A7", "SLC17A6"))
```


```{r}
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("DRD1", "DRD2"))
#Patch
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("SEMA5B", "MFGE8")) 
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("KREMEN1", "PDE1C")) 
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("LYPD1")) 
#matrix
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("ID4", "SGK1")) 
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("EPHA4", "SV2B")) 
 #Coexpression is exopatch
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("ID4", "OPRM1"))
#first 2 is D1 patch,
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("NECAB1", "COL11A1")) 
#next is D2 patch
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("ASIC4")) 

FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("TSHZ1", "TAC1", "NNAT")) #patch
 
```
```{r}
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("pct_mt"))
FeaturePlot(BICAN_3P_V8_CaH_neurons, features = c("PPP1R1B", "CASZ1")) 
```

```{r}
subcluster = c("D1_SPN_matrix","D2_SPN_matrix", "D1_SPN_patch", "D2_SPN_patch", "interneuron_1", "eSPN", "SPN-junk", "interneuron_2", "interneuron_3","D2_SPN_patch","cholinergic", "D1_SPN_matrix")

BICAN_3P_V8_CaH_neurons= assignCellClasses(BICAN_3P_V8_CaH_neurons, classes=subcluster, cluster_col="RNA_snn_res.0.2", class_col = "subcluster")

Idents(BICAN_3P_V8_CaH_neurons) <- "subcluster"
DimPlot(BICAN_3P_V8_CaH_neurons, label = TRUE)
```


#Get rid of the SPN junk cluster
```{r}
BICAN_3P_V8_CaH_neurons
DimPlot(BICAN_3P_V8_CaH_neurons, label = TRUE)
BICAN_3P_V8_CaH_neurons_filtered = subset(BICAN_3P_V8_CaH_neurons, subset = subcluster != "SPN-junk")
BICAN_3P_V8_CaH_neurons_filtered
DimPlot(BICAN_3P_V8_CaH_neurons_filtered, label = TRUE)
```

```{r}
BICAN_3P_V8_CaH_neurons_filtered@meta.data$sub_class = BICAN_3P_V8_CaH_neurons_filtered@meta.data$subcluster
BICAN_3P_V8_CaH_neurons_filtered@meta.data$SPN_class = BICAN_3P_V8_CaH_neurons_filtered@meta.data$subcluster
BICAN_3P_V8_CaH_neurons_filtered@meta.data
unique(BICAN_3P_V8_CaH_neurons_filtered@meta.data$sub_class)
```


```{r}
BICAN_3P_V8_CaH_neurons_filtered$sub_class[BICAN_3P_V8_CaH_neurons_filtered$sub_class == "interneuron_1"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$sub_class[BICAN_3P_V8_CaH_neurons_filtered$sub_class == "eSPN"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$sub_class[BICAN_3P_V8_CaH_neurons_filtered$sub_class == "interneuron_2"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$sub_class[BICAN_3P_V8_CaH_neurons_filtered$sub_class == "interneuron_3"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$sub_class[BICAN_3P_V8_CaH_neurons_filtered$sub_class == "cholinergic"] = "non-SPN"
```

```{r}
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "D1_SPN_matrix"] = "SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "D2_SPN_matrix"] = "SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "D1_SPN_patch"] = "SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "D2_SPN_patch"] = "SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "interneuron_1"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "eSPN"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "interneuron_2"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "interneuron_3"] = "non-SPN"
BICAN_3P_V8_CaH_neurons_filtered$SPN_class[BICAN_3P_V8_CaH_neurons_filtered$SPN_class == "cholinergic"] = "non-SPN"
```


```{r}
BICAN_3P_V8_CaH_neurons_filtered@meta.data$D1_D2 = BICAN_3P_V8_CaH_neurons_filtered@meta.data$sub_class
BICAN_3P_V8_CaH_neurons_filtered$D1_D2[BICAN_3P_V8_CaH_neurons_filtered$D1_D2 == "D1_SPN_matrix"] = "D1_SPN"
BICAN_3P_V8_CaH_neurons_filtered$D1_D2[BICAN_3P_V8_CaH_neurons_filtered$D1_D2 == "D2_SPN_matrix"] = "D2_SPN"
BICAN_3P_V8_CaH_neurons_filtered$D1_D2[BICAN_3P_V8_CaH_neurons_filtered$D1_D2 == "D1_SPN_patch"] = "D1_SPN"
BICAN_3P_V8_CaH_neurons_filtered$D1_D2[BICAN_3P_V8_CaH_neurons_filtered$D1_D2 == "D2_SPN_patch"] = "D2_SPN"

BICAN_3P_V8_CaH_neurons_filtered@meta.data$patch_matrix = BICAN_3P_V8_CaH_neurons_filtered@meta.data$sub_class
BICAN_3P_V8_CaH_neurons_filtered$patch_matrix[BICAN_3P_V8_CaH_neurons_filtered$patch_matrix == "D1_SPN_matrix"] = "matrix"
BICAN_3P_V8_CaH_neurons_filtered$patch_matrix[BICAN_3P_V8_CaH_neurons_filtered$patch_matrix == "D2_SPN_matrix"] = "matrix"
BICAN_3P_V8_CaH_neurons_filtered$patch_matrix[BICAN_3P_V8_CaH_neurons_filtered$patch_matrix == "D1_SPN_patch"] = "patch"
BICAN_3P_V8_CaH_neurons_filtered$patch_matrix[BICAN_3P_V8_CaH_neurons_filtered$patch_matrix == "D2_SPN_patch"] = "patch"

BICAN_3P_V8_CaH_neurons_filtered@meta.data
```


```{r}
Idents(BICAN_3P_V8_CaH_neurons_filtered) <- "subcluster"
DimPlot(BICAN_3P_V8_CaH_neurons_filtered, label = TRUE)

Idents(BICAN_3P_V8_CaH_neurons_filtered) <- "sub_class"
DimPlot(BICAN_3P_V8_CaH_neurons_filtered, label = TRUE)

Idents(BICAN_3P_V8_CaH_neurons_filtered) <- "SPN_class"
DimPlot(BICAN_3P_V8_CaH_neurons_filtered, label = TRUE)

Idents(BICAN_3P_V8_CaH_neurons_filtered) <- "D1_D2"
DimPlot(BICAN_3P_V8_CaH_neurons_filtered, label = TRUE)

Idents(BICAN_3P_V8_CaH_neurons_filtered) <- "patch_matrix"
DimPlot(BICAN_3P_V8_CaH_neurons_filtered, label = TRUE)

```

