---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(UCell)
library(ggplot2)
library(qs)
```

```{r}
bican_recon = qread("/broad/macosko/bican/A22J235LT4_3cm_seurat.qs")
bican_recon
```
```{r}
bican_recon_meta = bican_recon@meta.data
bican_recon_meta
```
```{r}
unique(bican_recon_meta$cell_class_annot)
```


```{r}
bican_recon_meta = subset(bican_recon_meta, cell_class_annot != "doublet")
bican_recon_meta$reclustered_patch_matrix_exotic = bican_recon_meta$cell_type_group_annot
bican_recon_meta$reclustered_patch_matrix_exotic[bican_recon_meta$cell_class_annot == "oligo"] = "oligo"
bican_recon_meta$reclustered_patch_matrix_exotic[bican_recon_meta$cell_class_annot == "astro"] = "astrocyte"
bican_recon_meta$reclustered_patch_matrix_exotic[bican_recon_meta$cell_class_annot == "mg"] = "microglia"
bican_recon_meta$reclustered_patch_matrix_exotic[bican_recon_meta$cell_class_annot == "endo"] = "endothelial"
bican_recon_meta$reclustered_patch_matrix_exotic[bican_recon_meta$cell_class_annot == "opc"] = "opc"
bican_recon_meta
```




```{r}
cell_classes = unique(bican_recon_meta$reclustered_patch_matrix_exotic)

for(cell_type in cell_classes){
opc = subset(bican_recon_meta, subset = reclustered_patch_matrix_exotic == cell_type)

a = ggplot(opc, aes(x = x_um, y = y_um)) +
    geom_hex(bins = 50, aes(fill = ..count..)) +
    #facet_wrap(~ reclustered_patch_matrix_exotic) +
    scale_fill_viridis_c() + ggtitle(paste0(cell_type))+
    theme_minimal()

print(a)
}
```

```{r}
theta <- 135
radians <- theta * pi / 180  # Convert degrees to radians
cos_theta <- cos(radians)
sin_theta <- sin(radians)

bican_recon_meta$x_um_rotated = bican_recon_meta$x_um * cos_theta + bican_recon_meta$y_um * sin_theta
bican_recon_meta$y_um_rotated = -bican_recon_meta$x_um * sin_theta + bican_recon_meta$y_um * cos_theta
bican_recon_meta
```

```{r}
df = bican_recon_meta[na.omit(bican_recon_meta$x_um),] 
df
```

```{r}
opx
```

```{r}
recon_xdp = qread("/broad/macosko/kimkathl/recon_meta.qs")
recon_xdp
```

```{r}
cell_classes = unique(recon_xdp$reclustered_patch_matrix_exotic)

for(cell_type in cell_classes){
opc = subset(recon_xdp, subset = reclustered_patch_matrix_exotic == cell_type)
a = ggplot(opc, aes(x = x_um, y = y_um)) +
    geom_hex(bins = 50, aes(fill = ..count..)) +
    geom_point(size = 0.0001)+
    #facet_wrap(~ reclustered_patch_matrix_exotic) +
    scale_fill_viridis_c() + ggtitle(paste0(cell_type))+
    theme_minimal()

a <- ggMarginal(a, type = "density", size = 10)
print(a)
}
```



```{r}
cell_classes = unique(df$reclustered_patch_matrix_exotic)

for(cell_type in cell_classes){
opc = subset(df, subset = reclustered_patch_matrix_exotic == cell_type)

a = ggplot(opc, aes(x = x_um_rotated, y = y_um_rotated)) +
    geom_hex(bins = 50, aes(fill = ..count..)) +
    geom_point(size = 0.0001)+
    #facet_wrap(~ reclustered_patch_matrix_exotic) +
    scale_fill_viridis_c() + ggtitle(paste0(cell_type))+
    theme_minimal()

a <- ggMarginal(a, type = "histogram", size = 10)
print(a)
}
```




```{r}
bican_recon
bican_recon@meta.data
```

```{r}
table(bican_recon$cell_class_annot)
```

```{r}
bican_recon = subset(bican_recon, subset = cell_class_annot != "doublet")
```



```{r}
xdp_recon_full = qread("/broad/macosko/kimkathl/temp_disco/more_temp_1205/clean_recon_sobj_with_neuron_subclusters_sct_new.qs")
xdp_recon_full
```


```{r}
recon_xdp_full = xdp_recon_full@meta.data
recon_xdp_full
```


```{r}
cell_classes = unique(recon_xdp_full$reclustered_patch_matrix_exotic)

for(cell_type in cell_classes){
opc = subset(recon_xdp_full, subset = reclustered_patch_matrix_exotic == cell_type)
a = ggplot(opc, aes(x = x_um, y = y_um)) +
    geom_hex(bins = 50, aes(fill = ..count..)) +
    geom_point(size = 0.0001)+
    #facet_wrap(~ reclustered_patch_matrix_exotic) +
    scale_fill_viridis_c() + ggtitle(paste0(cell_type))+
    theme_minimal()

a <- ggMarginal(a, type = "density", size = 10)
print(a)
}
```

```{r}
cell_classes = unique(recon_xdp_full$reclustered_patch_matrix_exotic)

for(cell_type in cell_classes){
opc = subset(recon_xdp_full, subset = reclustered_patch_matrix_exotic == cell_type)
a = ggplot(opc, aes(x = x_um, y = y_um)) +
    geom_hex(bins = 10, aes(fill = ..count..)) +
    geom_point(size = 0.0001)+
    #facet_wrap(~ reclustered_patch_matrix_exotic) +
    scale_fill_viridis_c() + ggtitle(paste0(cell_type))+
    theme_minimal()

a <- ggMarginal(a, type = "density", size = 10)
print(a)
}
```



```{r}
a =ggplot(recon_xdp_full, aes(x = x_um, y = y_um)) +
    geom_hex(bins = 40, aes(fill = ..count..)) +
    scale_fill_viridis_c()+
    theme_minimal()+xlab("Spatial_1") +ylab("Spatial_2")

ggsave(a, filename = "a.png", width = 8, height = 7)
```

```{r}

opc = subset(recon_xdp_full, subset = reclustered_patch_matrix_exotic == "opc")
a = ggplot(opc, aes(x = x_um, y = y_um)) +
    geom_hex(bins = 40, aes(fill = ..count..)) +
      geom_point(size = 0.0001)+
    #facet_wrap(~ reclustered_patch_matrix_exotic) +
    scale_fill_viridis_c() + 
    theme_minimal() +xlab("Spatial_1") +ylab("Spatial_2") +xlim(0,20000) +ylim(0, 20000)
a <- ggMarginal(a, type = "density", size = 10)

ggsave(a, filename = "a.png", width = 8, height = 7)
```


ˆ
```{r}
xdp = qread("/broad/macosko/kimkathl/temp_disco/more_temp_1205/xdp_cah_put_sct_new.qs")
xdp
```
```{r}
DimPlot(xdp, label = T)
```


```{r}
FeaturePlot(xdp_recon_full, features = c("TAF1"), label = T)
```


```{r}
xdp_recon_full@meta.data
```


```{r}
taf1_data <- FetchData(
  xdp_recon_full,
  vars = c("TAF1", "reclustered_patch_matrix_exotic", "logumi", "x_um", "y_um" ), 
  slot = "counts" 
)
taf1_data
```

```{r}
ggplot(taf1_data, aes(x = x_um, y = y_um)) +
  geom_hex(aes(fill = TAF1), bins = 30) +  # Adjust 'bins' for spatial resolution
  scale_fill_viridis_c(option = "plasma") +           # Choose color scale
  labs(
    title = "Hexbin Plot of TAF1 Counts",
    x = "X Coordinate",
    y = "Y Coordinate",
    fill = "TAF1 Counts"
  ) +
  theme_minimal() +
  theme(aspect.ratio = 1)  # Ensure proper spatial proportions

```

