---
title: "R Notebook"
output: html_notebook
---

```{r}
Recon_opc = qread("RECON/Recon_opc.qs")
Recon_oligo = qread("RECON/Recon_oligo.qs")
Recon_micro = qread("RECON/Recon_microglia.qs")
Recon_ependymal = qread("RECON/Recon_ependymal.qs")
Recon_endo = qread("RECON/Recon_endo.qs")
Recon_astrocyte = qread("RECON/Recon_astrocyte.qs")
```

```{r}
Recon_endo@meta.data
DimPlot(Recon_endo, label = T)
DimPlot(Recon_endo, label = T, group.by = "RNA_snn_res.0.3")
```
```{r}
Recon_endo = subset(Recon_endo, subset = RNA_snn_res.0.3 !="3")
DimPlot(Recon_endo, label = T)
DimPlot(Recon_endo, label = T, group.by = "RNA_snn_res.0.3")
```

```{r}
sobj_list = list(Recon_neuron_clean, Recon_opc, Recon_oligo, Recon_micro, Recon_ependymal, Recon_astrocyte, Recon_endo)
sobj_list
```

#create sobj
```{r}
counts_list <- lapply(sobj_list, function(sobj) GetAssayData(sobj, slot = "counts"))
counts_list
```

```{r}
merged_counts <- do.call(cbind, counts_list)
merged_counts
```

```{r}
metadata_list <- lapply(sobj_list, function(sobj) sobj@meta.data)
metadata_list
```

```{r}
merged_metadata <- do.call(rbind, metadata_list)
merged_metadata
```

```{r}
stopifnot(all(rownames(merged_metadata) == colnames(merged_counts)))
```

```{r}
# Create Seurat object
clean_recon_sobj <- CreateSeuratObject(counts = merged_counts, meta.data = merged_metadata)
clean_recon_sobj
```

```{r}
n_dims_use=20

clean_recon_sobj = (clean_recon_sobj
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.1) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6)
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% FindClusters(resolution = 0.9)
   %>% FindClusters(resolution = 1)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
clean_recon_sobj

clean_recon_sobj@meta.data
```

```{r}
DimPlot(clean_recon_sobj, group.by = "subclass", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.2", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.3", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.4", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.5", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.6", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.7", raster = F, label = T)
DimPlot(clean_recon_sobj, group.by = "RNA_snn_res.0.8", raster = F, label = T)
```

```{r}
FeaturePlot(clean_recon_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("OLIG1", "MOG", "MOBP"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(clean_recon_sobj, features = c("logumi", "percent.mt"),raster=FALSE)
```
```{r}
a = clean_recon_sobj@meta.data
```


```{r}
ggplot(a, aes(x= x_um, y = y_um, color = subclass)) + geom_point(alpha = 0.2, size = 0.2) + facet_wrap(~ subclass) +theme_void()
```

```{r}
clean_recon_sobj@meta.data$RNA_snn_res.0.01 = NULL
clean_recon_sobj@meta.data$RNA_snn_res.0.05 = NULL
clean_recon_sobj@meta.data$RNA_snn_res.0.1 = NULL
clean_recon_sobj@meta.data$RNA_snn_res.0.15 = NULL
clean_recon_sobj@meta.data$final_cell_classes = clean_recon_sobj$subclass
clean_recon_sobj@meta.data$cell_class_try2_combine = NULL
clean_recon_sobj@meta.data
```

```{r}
clean_recon_sobj$final_cell_classes[clean_recon_sobj$final_cell_classes == "immune"] = "microglia"
```


```{r}
Idents(clean_recon_sobj) = "final_cell_classes"
DimPlot(clean_recon_sobj, label = T, raster = F)
```

```{r}
qsave(clean_recon_sobj, "RECON/clean_recon_sobj.qs")
```



```{r}
clean_recon_sobj@meta.data
```

```{r}
Recon_endo@meta.data
DimPlot(Recon_endo, label = T)
DimPlot(Recon_endo, label = T, group.by = "RNA_snn_res.0.2")
DimPlot(Recon_endo, label = T, group.by = "RNA_snn_res.0.3")
```

```{r}
FeaturePlot(Recon_endo, features = c("GFAP", "AQP4", "FLT1"))
```
```{r}
confused = subset(Recon_endo, subset = RNA_snn_res.0.3 == "3")
confused
```

```{r}
what = rownames(confused@meta.data)
what
```



```{r}
DimPlot(clean_recon_sobj, label = T, raster = F)
```

```{r}
clean_recon_sobj@meta.data
```


```{r}
clean_recon_sobj@meta.data$contamin = "Other"
clean_recon_sobj$contamin[rownames(clean_recon_sobj@meta.data) %in% what] = "Contamin"
clean_recon_sobj@meta.data
table(clean_recon_sobj$contamin)
```

```{r}
DimPlot(clean_recon_sobj, label = T, raster = F, group.by = "contamin")
```
```{r}
clean_recon_sobj
new_clean_recon_sobj = subset(clean_recon_sobj, subset = contamin != "Contamin")
new_clean_recon_sobj
```
```{r}
clean_recon_sobj@meta.data
```

```{r}
DimPlot(clean_recon_sobj, group.by = "subclass", label = T)
```
```{r}
FeaturePlot(clean_recon_sobj, features = c("SYT1", "RBFOX3", "GAD2", "SLC17A6"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("AQP4", "GINS3", "GFAP"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("C1QA", "C1QB", "CX3CR1", "P2RY12"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("FLT1", "DCN", "RGS5"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("OLIG1", "MOG", "MOBP"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("OLIG2", "VCAN", "GAPDH"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("ZBBX", "CFAP157", "CFAP299", "BSG"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("CD96", "NKG7", "SKAP1"), raster = F)
FeaturePlot(clean_recon_sobj, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(clean_recon_sobj, features = c("logumi", "percent.mt"),raster=FALSE)
```
```{r}
qsave(clean_recon_sobj, "cleaned_recon_sobj_102424.qs")
```

