---
title: "R Notebook"
output: html_notebook
---

```{r}
clean_recon_sobj
clean_recon_sobj@meta.data
```
```{r}
Recon_neuron_new = subset(clean_recon_sobj, subset = final_cell_class == "neuron")
Recon_neuron_new
```

```{r}
hist(Recon_neuron_new$logumi, breaks = 100)
min(Recon_neuron_new$logumi)
max(Recon_neuron_new$logumi)
median(Recon_neuron_new$logumi)
FeaturePlot(Recon_neuron_new, features = c("percent.mt", "logumi"))
```

```{r}
n_dims_use=20

Recon_neuron_new = (Recon_neuron_new
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.01) 
   %>% FindClusters(resolution = 0.05)
   %>% FindClusters(resolution = 0.1)
   %>% FindClusters(resolution = 0.15) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6) 
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
Recon_neuron_new
Recon_neuron_new@meta.data
```

```{r}
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.01", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.05", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.1", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.15", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.2", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.3", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.4", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.5", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.6", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.7", label = T, raster = FALSE)
DimPlot(Recon_neuron_new, group.by = "RNA_snn_res.0.8", label = T, raster = FALSE)
```

```{r}
FeaturePlot(Recon_neuron_new, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(Recon_neuron_new, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(Recon_neuron_new, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("DRD1", "DRD2", "EPHA4", "SEMA3E"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("CASZ1" ,"PPP1R1B" ,"SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("P2RY12", "CX3CR1", "C1QB", "CHAT"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(Recon_neuron_new, features = c("logumi", "percent.mt"),raster=FALSE) 

```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "CHAT")


Dotplot = DotPlot(object = Recon_neuron_new, features = marker_genes, group.by = "RNA_snn_res.0.8")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
Recon_neuron_new_clean = subset(Recon_neuron_new, logumi > 3.7)
hist(Recon_neuron_new_clean$logumi, breaks = 100)
FeaturePlot(Recon_neuron_new_clean, features = c("percent.mt", "logumi"))
```
```{r}
DimPlot(Recon_neuron_new_clean,group.by = "RNA_snn_res.0.2", label = T)
```


```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "CHAT")


Dotplot = DotPlot(object = Recon_neuron_new_clean, features = marker_genes, group.by = "RNA_snn_res.0.2")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
table(Recon_neuron_new_clean$RNA_snn_res.0.2)
```

```{r}
Recon_neuron_new_clean = subset(Recon_neuron_new_clean, subset = RNA_snn_res.0.2 != "4" & RNA_snn_res.0.2 != "5")
Recon_neuron_new_clean
table(Recon_neuron_new_clean$RNA_snn_res.0.2)
```

```{r}
n_dims_use=20

Recon_neuron_new_clean = (Recon_neuron_new_clean
%>% NormalizeData()
%>% ScaleData()
%>% FindVariableFeatures(nfeatures = 2500)
%>% RunPCA()
   %>% FindNeighbors(dims = 1:n_dims_use) 
   %>% FindClusters(resolution = 0.01) 
   %>% FindClusters(resolution = 0.05)
   %>% FindClusters(resolution = 0.1)
   %>% FindClusters(resolution = 0.15) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.2) 
   %>% FindClusters(resolution = 0.3) 
   %>% FindClusters(resolution = 0.4) 
   %>% FindClusters(resolution = 0.5)
   %>% FindClusters(resolution = 0.6) 
   %>% FindClusters(resolution = 0.7)
   %>% FindClusters(resolution = 0.8)
   %>% RunUMAP(dims = 1:n_dims_use) 
)
Recon_neuron_new_clean
Recon_neuron_new_clean@meta.data
```

```{r}
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.01", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.05", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.1", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.15", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.2", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.3", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.4", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.5", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.6", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.7", label = T, raster = FALSE)
DimPlot(Recon_neuron_new_clean, group.by = "RNA_snn_res.0.8", label = T, raster = FALSE)
```

```{r}
FeaturePlot(Recon_neuron_new_clean, features = c("SYT1", "AQP4", "C1QA","FLT1"),raster=FALSE)
FeaturePlot(Recon_neuron_new_clean, features = c("OLIG1", "OLIG2", "MOG" ,"CD96"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("MBP", "MOBP", "TF", "ST18"),raster=FALSE)
FeaturePlot(Recon_neuron_new_clean, features = c("RBFOX3", "CX3CR1", "GFAP" ,"AQP4"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("GAD1", "GAD2", "SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("DRD1", "DRD2", "EPHA4", "SEMA3E"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("CASZ1" ,"PPP1R1B" ,"SLC17A7" ,"SLC17A6"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("P2RY12", "CX3CR1", "C1QB", "CHAT"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("UBB", "GAPDH", "TUBB2A"),raster=FALSE) 
FeaturePlot(Recon_neuron_new_clean, features = c("logumi", "percent.mt"),raster=FALSE) 

```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "CHAT", "SST", "PENK", "LAMP5", "CALB", "PVALB")


Dotplot = DotPlot(object = Recon_neuron_new_clean, features = marker_genes, group.by = "subclass")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```

```{r}
Idents(Recon_neuron_new_clean) = Recon_neuron_new_clean$RNA_snn_res.0.7

classes = c("D1_matrix", "D2_matrix", "D2_matrix", "D1_matrix", "eSPN_D1", "D1_matrix", "eSPN", "D1_exotic", "D1_patch", "D1_patch", "interneuron_1", "interneuron_2", "D2_exotic", "D2_matrix", "D1_D2", "interneuron_3", "interneuron_4", "D2_patch_2", "D1_patch", "interneuron_SST", "D2_patch", "interneuron_5", "cholinergic_1", "glutamatergic", "doublet", "cholinergic_2", "doublet")

  
  #c("D1_matrix", "D2_matrix", "D2_matrix", "eSPN", "D1_matrix", "D1_matrix", "D1_patch_2", "eSPN_D1", "D1_exotic", "D1_patch_1", "D2_exotic", "interneuron_1", "interneuron_2", "D2_matrix", "D1_D2", "interneuron_3", "interneuron_4", "D2_eSPN", "D2_patch", "interneuron_SST", "interneuron_5", "cholinergic_1", "glutamatergic", "doublet_1", "cholinergic_2", "doublet_2")

Recon_neuron_new_clean= assignCellClasses(Recon_neuron_new_clean, classes=classes, cluster_col="RNA_snn_res.0.7", class_col = "subclass")

DimPlot(Recon_neuron_new_clean, group.by = "subclass" ,label = T, raster = FALSE)
```

```{r}
marker_genes <- c("CD96", "CX3CR1", "P2RY12", "C1QB", "C1QA", "CASZ1", "FLT1", "TF", "MOBP", "MOG", "MBP", "OLIG2", "OLIG1", "ST18", "GFAP", "AQP4", "SEMA3E", "EPHA4", "PPP1R1B", "DRD2", "DRD1", "GAD2", "GAD1", "SYT1", "RBFOX3", "SLC17A6", "SLC17A7", "CHAT","SST", "PENK", "LAMP5", "CALB", "PVALB")


Dotplot = DotPlot(object = Recon_neuron_new_clean, features = marker_genes, group.by = "subclass")
Dotplot  <- Dotplot  + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ coord_flip() 
print(Dotplot)
```
```{r}
FeaturePlot(Recon_neuron_new_clean, features = c("SST", "PENK", "LAMP5", "CALB1"))
FeaturePlot(Recon_neuron_new_clean, features = c("TH", "SOX6", "PTHLH", "CCK"))
```
```{r}
table(Recon_neuron_new_clean$subclass)
```

```{r}
Idents(Recon_neuron_new_clean) = "subclass"
gene = FindAllMarkers(Recon_neuron_new_clean, only.pos = T, min.pct = 0.2, logfc.threshold = 2)
gene
```

```{r}
b = subset(gene, subset = p_val_adj <0.05 & pct.1 > 0.9)
b
```

```{r}
Recon_neuron_new_clean_final = subset(Recon_neuron_new_clean, subset = subclass != "doublet")

DimPlot(Recon_neuron_new_clean_final, group.by = "subclass" ,label = T, raster = FALSE)
```

```{r}
table(Recon_neuron_new_clean_final$subclass)
```
```{r}
Recon_neuron_new_clean_final@meta.data$reclustered_patch_matrix_exotic = Recon_neuron_new_clean_final$subclass
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "cholinergic_1"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "cholinergic_2"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D1_exotic"] = "SPN_exotic"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D2_exotic"] = "SPN_exotic"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D1_matrix"] = "SPN_matrix"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D2_matrix"] = "SPN_matrix"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D1_patch"] = "SPN_patch"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D2_patch"] = "SPN_patch"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "D2_patch_2"] = "SPN_patch"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "eSPN_D1"] = "eSPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "glutamatergic"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "interneuron_1"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "interneuron_2"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "interneuron_3"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "interneuron_4"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "interneuron_5"] = "non_SPN"
Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic[Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic == "interneuron_SST"] = "non_SPN"

table(Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic)
```

```{r}
DimPlot(Recon_neuron_new_clean_final, group.by = "reclustered_patch_matrix_exotic", label = T)
```
```{r}
Idents(Recon_neuron_new_clean_final) ="reclustered_patch_matrix_exotic"
```

```{r}
qsave(Recon_neuron_new_clean_final, "RECON_neuron_subclustered_102824.qs")
```


```{r}
ggplot(Recon_neuron_new_clean_final@meta.data, aes(x= x_um, y = y_um, color = reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.5, size = 0.7) +  theme_void() +  facet_wrap(~ reclustered_patch_matrix_exotic)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 24),
    strip.text = element_text(size = 22),
    plot.background = element_rect(fill = "white", color = NA)
  ) +
  ylab(NULL)

```
```{r}
Recon_neuron_new_clean_final
```

```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")
# Create the plot with larger legend key sizes
ggplot(Recon_neuron_new_clean_final@meta.data, aes(x = x_um, y = y_um, color = reclustered_patch_matrix_exotic)) +
  geom_point(alpha = 0.5, size = 0.5) +
  scale_color_discrete(labels = custom_labels) +  # If you want to rename labels
  labs(color = "Neuronal Subclasses") +
  guides(color = guide_legend(override.aes = list(size = 4))) +  # Increase size of dots in the legend
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)
  )

```

```{r}
library(sctransform)
Recon_neuron_new_clean_final = SCTransform(Recon_neuron_new_clean_final, vars.to.regress = "percent.mt", verbose = FALSE)
DefaultAssay(Recon_neuron_new_clean_final) = "SCT"
Recon_neuron_new_clean_final
```
```{r}
table(Recon_neuron_new_clean_final$reclustered_patch_matrix_exotic)
```

```{r}
MMR_genes =c("MSH2", "MSH3", "PMS2", "POLD3", "LIG1","RFC3", "RFC4", "POLD2",  "MLH3", "MSH6", "FAN1", "POLE", "POLD4", "POLD1", "MLH1", "RFC2", "PMS1", "PCNA")
#Warning: The following genes were not found and will be imputed to exp=0: * RCF5,RCF1

BER_genes = c("PARP1", "TDG", "LIG3", "OGG1", "TDP1", "UNG", "APEX1", "XRCC1", "NEIL1", "TOP1", "POLB", "HMGB1")

```


#ucell scores
```{r}
library(UCell)
Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'UCELL'
)

Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'UCELL'
)


Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
 features = list(matrix_markers = new_BICAN_V17_matrix),
  name = 'UCELL'
)

Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
 features = list(D_genes = new_d_genes_BICAN),
  name = 'UCELL'
)

Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
 features = list(MMR = MMR_genes),
  name = 'UCELL'
)

Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
 features = list(BER = BER_genes),
  name = 'UCELL'
)

Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
 features = list(MSH2 = c("MSH2")),
  name = 'UCELL'
)

Recon_neuron_new_clean_final <- AddModuleScore_UCell(Recon_neuron_new_clean_final,
 features = list(MSH3 = c("MSH3")),
  name = 'UCELL'
)
```



```{r}
my_df = Recon_neuron_new_clean_final@meta.data
my_df$Condition = "XDP"
my_df
```

```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")

# Plot with light gray points for all data in the background
matrix_recon = subset(my_df, subset = reclustered_patch_matrix_exotic == "SPN_matrix")

a = ggplot(matrix_recon, aes(x= x_um, y = y_um, color = MSH2UCELL)) + geom_point() + ggtitle(" SPN Matrix: MSH2 Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")
) +   labs(color = "MSH2 Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)

b = ggplot(matrix_recon, aes(x= x_um, y = y_um, color = MSH3UCELL)) + geom_point() + ggtitle(" SPN Matrix: MSH3 Scores \n") + scale_color_gradientn(colors =  c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")
) +  labs(color = "MSH3 Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)

pic = a+b
ggsave(pic, filename = "pic.png", width = 20, height = 10)
```


```{r}
matrix_recon = subset(my_df, subset = reclustered_patch_matrix_exotic == "non_SPN")
ggplot(matrix_recon, aes(x= x_um, y = y_um, color = D_genesUCELL)) + geom_point() + ggtitle(" non-SPN: D Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")
) +   labs(color = "D Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)
```


```{r}
ggplot(my_df, aes(x=MMRUCELL, y=BERUCELL, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle("MMR vs BER UCell Scores") + xlab("MMR score") + ylab("BER score") + facet_wrap(~ reclustered_patch_matrix_exotic) 

```


















```{r}
matrix_recon_cah_put = subset(matrix_recon, subset = y_um < 12000)
matrix_recon_cah_put
```

```{r}
ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF7F50", "#FFFF00", "#87CEEB", "#0000FF")
) +   labs(color = "C Minus Scores") + ylim(0,12000)
```


```{r}
 a = ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")

) +   labs(color = "C Minus Scores") + ylim(0,12000) + xlim(10000, 16000)+
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)


b = ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_plusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Plus Scores \n") + scale_color_gradientn(colors = c("#0000FF", "#4682B4", "#87CEEB", "#FFD700", "#FF7F50", "#FF4500", "#FF0000")

) +  labs(color = "C Plus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + ylim(0,12000) +xlim(10000, 16000)+
  ylab(NULL)

pic = a+b
ggsave(pic, filename = "pic.png", width = 20, height = 10)
```









```{r}
Recon_neuron_new_clean@meta.data
```


```{r}
ggplot(Recon_neuron_new_clean@meta.data, aes(x= x_um, y = y_um, color = logumi)) + geom_point() + theme_void() +  ylab(NULL) + facet_wrap(~ final_cell_class) 
```








```{r}
xdp_df
```





```{r}
# new_df = final_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "matrix_markersUCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL")]  
# 
# new_df$C_minusUCELL = new_df$C_minusSPN_Matrix_scores_UCELL
# new_df$C_minusSPN_Matrix_scores_UCELL = NULL
# 
# new_df$C_plusUCELL = new_df$C_plusSPN_Matrix_scores_UCELL
# new_df$C_plusSPN_Matrix_scores_UCELL = NULL
# 
# new_df$D_genesUCELL = new_df$D_genesSPN_Matrix_scores_UCELL
# new_df$D_genesSPN_Matrix_scores_UCELL = NULL
```


```{r}
new_df$Region = NULL
```


```{r}
new_xdp_df = my_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "matrix_markersUCELL", "C_minusUCELL", "C_plusUCELL", "D_genesUCELL")]  

new_xdp_df$Condition = "XDP_18_006"
new_xdp_df

```

```{r}
recon_df_combined = rbind(new_xdp_df, new_df)
recon_df_combined

table(recon_df_combined$Condition)
```

```{r}
recon_df_combined$reclustered_patch_matrix_exotic[recon_df_combined$reclustered_patch_matrix_exotic == "non_SPN"] = "non-SPN"
```


```{r}
histograms_by_celltype(final_df= recon_df_combined, score_col = "matrix_markersUCELL", xlab = "SPN Matrix Score")
histograms_by_celltype(final_df= recon_df_combined, score_col = "C_minusUCELL", xlab = "C Minus Score")
histograms_by_celltype(final_df= recon_df_combined, score_col = "C_plusUCELL", xlab = "C Plus Score")
histograms_by_celltype(final_df= recon_df_combined, score_col = "D_genesUCELL", xlab = "D Score")
```

```{r}
DimPlot(Recon_neuron_new_clean_final, label = T)
```
```{r}
all(new_c_minus_genes_BICAN %in% rownames(Recon_neuron_new_clean_final))
all(new_c_plus_genes_BICAN %in% rownames(Recon_neuron_new_clean_final))
```


```{r}
# Extract normalized expression data for these genes across all cells
expr_data <- FetchData(Recon_neuron_new_clean_final, vars = new_c_minus_genes_BICAN)

# Define a reference for log fold change calculation, e.g., mean expression across all cells
# You could also calculate this within a specific subset of cells (like a control group)
reference_expression <- colMeans(expr_data)

# Calculate log fold change per gene for each cell
logFC_per_cell <- log2(expr_data + 1) - log2(matrix(reference_expression + 1, nrow = nrow(expr_data), ncol = length(reference_expression), byrow = TRUE))

# Convert to a data frame for easier manipulation
logFC_per_cell_df <- as.data.frame(logFC_per_cell)

# Calculate the median logFC for the genes of interest for each cell
median_logFC_per_cell <- apply(logFC_per_cell_df, 1, median, na.rm = TRUE)

# Add this as metadata in your Seurat object if needed
test_sobj <- AddMetaData(Recon_neuron_new_clean_final, median_logFC_per_cell, col.name = "Median_logFC_genes_of_interest")

# Check the result
head(median_logFC_per_cell)

```
```{r}
test_sobj@meta.data$Median_C_Minus_logFC = test_sobj$Median_logFC_genes_of_interest 
test_sobj$Median_logFC_genes_of_interest  = NULL
```

```{r}
expr_data <- FetchData(test_sobj, vars = new_c_plus_genes_BICAN)

# Define a reference for log fold change calculation, e.g., mean expression across all cells
# You could also calculate this within a specific subset of cells (like a control group)
reference_expression <- colMeans(expr_data)

# Calculate log fold change per gene for each cell
logFC_per_cell <- log2(expr_data + 1) - log2(matrix(reference_expression + 1, nrow = nrow(expr_data), ncol = length(reference_expression), byrow = TRUE))

# Convert to a data frame for easier manipulation
logFC_per_cell_df <- as.data.frame(logFC_per_cell)

# Calculate the median logFC for the genes of interest for each cell
median_logFC_per_cell <- apply(logFC_per_cell_df, 1, median, na.rm = TRUE)

# Add this as metadata in your Seurat object if needed
test_sobj <- AddMetaData(test_sobj, median_logFC_per_cell, col.name = "Median_C_Plus_logFC")

# Check the result
test_sobj@meta.data
```




```{r}
ggplot(test_sobj@meta.data, aes(x = C_plusUCELL, y = Median_C_Plus_logFC, color = reclustered_patch_matrix_exotic)) +geom_point() + facet_wrap(~ reclustered_patch_matrix_exotic)
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)

# Assume 'seurat_object' has two metadata columns for each gene list's median logFC
df <- data.frame(
  cell_id = Cells(test_sobj),  # Extract cell IDs
  Median_C_Minus_logFC = FetchData(test_sobj, "Median_C_Minus_logFC"),
  Median_C_Plus_logFC = FetchData(test_sobj, "Median_C_Plus_logFC"), reclustered_patch_matrix_exotic = test_sobj@meta.data$reclustered_patch_matrix_exotic
)
df
```



```{r}
# Calculate absolute difference between the two median logFC values for each cell
df <- df %>%
  mutate(Abs_Diff = abs(Median_C_Minus_logFC - Median_C_Plus_logFC))

# Sort cells by absolute difference
df <- df %>%
  arrange(Abs_Diff)

# Convert cell_id to a factor based on this order for ggplot
df$cell_id <- factor(df$cell_id, levels = df$cell_id)


df_long <- df %>%
  tidyr::pivot_longer(cols = starts_with("Median"),
                      names_to = "GeneList",
                      values_to = "Median")

df_long
```

```{r}
df_long_matrix = subset(df_long, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
```


```{r}
# Plot with ggplot2, ordering cells by absolute difference on y-axis
pic = ggplot(df_long_matrix, aes(x = cell_id, y = Median, color = GeneList)) +
  geom_point(position = position_dodge(width = 0.5)) +
  labs(x = "Cell ID (ordered by absolute difference)", y = "Median logFC", color = "Gene List") +
  theme(axis.text.x = element_blank(),  # Hide cell IDs if too many cells
        axis.ticks.x = element_blank()) 

ggsave(pic, filename = "pic.png", width = 25, height = 5)
```




```{r}
df <- data.frame(
  cell_id = Cells(test_sobj),  # Extract cell IDs
  Median_C_Minus_logFC = FetchData(test_sobj, "Median_C_Minus_logFC"),
  Median_C_Plus_logFC = FetchData(test_sobj, "Median_C_Plus_logFC"), reclustered_patch_matrix_exotic = test_sobj@meta.data$reclustered_patch_matrix_exotic
)
df
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(Seurat)


# Ensure these genes are present in the Seurat object
valid_genes_list1 <- new_c_minus_genes_BICAN[new_c_minus_genes_BICAN %in% rownames(test_sobj)]
valid_genes_list2 <- new_c_plus_genes_BICAN[new_c_plus_genes_BICAN %in% rownames(test_sobj)]

# Calculate the median expression per cell for each gene list and store in metadata
test_sobj <- test_sobj %>%
  AddMetaData(
    data = apply(FetchData(test_sobj, vars = valid_genes_list1), 1, median),
    col.name = "Median_Expression_list1"
  ) %>%
  AddMetaData(
    data = apply(FetchData(test_sobj, vars = valid_genes_list2), 1, median),
    col.name = "Median_Expression_list2"
  )

# Create a dataframe to plot the median expression values for each cell
df <- data.frame(
  cell_id = Cells(test_sobj),
  Median_Expression_list1 = FetchData(seurat_object, "Median_Expression_list1"),
  Median_Expression_list2 = FetchData(seurat_object, "Median_Expression_list2")
)

# Optionally, calculate the absolute difference between the two lists' medians
df$Abs_Diff_Median_Expression = abs(df$Median_Expression_list1 - df$Median_Expression_list2)

```


```{r}
test_sobj <- test_sobj %>%
  AddMetaData(
    data = apply(FetchData(test_sobj, vars = valid_genes_list1), 1, median),
    col.name = "Median_Expression_list1"
  ) %>%
  AddMetaData(
    data = apply(FetchData(test_sobj, vars = valid_genes_list2), 1, median),
    col.name = "Median_Expression_list2"
  )

# Retrieve the calculated median values for each list
df <- data.frame(
  cell_id = Cells(test_sobj),
  Median_logFC_list1 = FetchData(test_sobj, "Median_logFC_genes_list1"),
  Median_logFC_list2 = FetchData(test_sobj, "Median_logFC_genes_list2")
)
```


```{r}
# Calculate midpoint and centered logFC values
df <- df %>%
  mutate(Midpoint = (Median_logFC_list1 + Median_logFC_list2) / 2) %>%
  mutate(
    Centered_logFC_list1 = Median_logFC_list1 - Midpoint,
    Centered_logFC_list2 = Median_logFC_list2 - Midpoint,
    Abs_Diff = abs(Centered_logFC_list1 - Centered_logFC_list2)
  ) %>%
  arrange(Abs_Diff)

# Convert cell_id to a factor based on this order for ggplot
df$cell_id <- factor(df$cell_id, levels = df$cell_id)

# Reshape dataframe to long format for plotting
df_long <- df %>%
  pivot_longer(cols = starts_with("Centered_logFC"),
               names_to = "GeneList",
               values_to = "Centered_logFC") %>%
  mutate(GeneList = ifelse(GeneList == "Centered_logFC_list1", "List1", "List2"))

# Plot with ggplot2, centered around zero and ordered by absolute difference
ggplot(df_long, aes(x = cell_id, y = Centered_logFC, color = GeneList)) +
  geom_point(position = position_dodge(width = 0.5)) +
  labs(x = "Cell ID (ordered by absolute difference)", y = "Centered Median logFC", color = "Gene List") +
  theme(axis.text.x = element_blank(),  # Hide cell IDs if too many cells
        axis.ticks.x = element_blank()) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "black")





ggsave(pic, filename = "pic.png", width = 25, height = 5)

```


```{r}
Recon_neuron_new_clean_final
```
```{r}
DefaultAssay(Recon_neuron_new_clean_final) = "RNA"
```

```{r}
test
```


```{r}
#SRRM4
gene_of_interest <- "TNFAIP6"  

taf1_df = Recon_neuron_new_clean_final@meta.data
taf1_df$cell_ids = rownames(taf1_df)

test = as.data.frame(FetchData(Recon_neuron_new_clean_final, vars = gene_of_interest))
test

test$cell_ids = rownames(test)

taf1_df_final = merge(taf1_df, test, by = "cell_ids" )
#taf1_df_final$HLA_A = taf1_df_final[["HLA-A"]]

pic = ggplot(taf1_df_final, aes(x= x_um, y = y_um, color = TNFAIP6)) + geom_point() +  scale_color_gradient(low = "lightgrey", high = "blue") +  labs(color = "TAF1 Expression") +
  theme_void() +  facet_wrap(~ reclustered_patch_matrix_exotic)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 30, height = 20)
```

```{r}
  pic = ggplot(taf1_df_final, aes(x= x_um, y = y_um, color = TAF1)) + geom_point() +  scale_color_gradient(low = "lightgrey", high = "blue") +  labs(color = "TAF1 Expression") +
  theme_void() +  facet_wrap(~ subclass)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 30, height = 20)

```




```{r}
gene_of_interest <- "Gene" #change gene
```


```{r}
gene_of_interest = "TAF1" 

#replace seurat_obj here
metadata_df = seurat_obj@meta.data
metadata_df$cell_ids = rownames(metadata_df)

#replace seurat_obj here
gene_df = as.data.frame(FetchData(seurat_obj, vars = gene_of_interest))
gene_df$cell_ids = rownames(gene_df)

df_final = merge(metadata_df, gene_df, by = "cell_ids" )
df_final

#Replace GENE with gene name
ggplot(df_final, aes(x= x_um, y = y_um, color = TAF1)) + geom_point() +  scale_color_gradient(low = "lightgrey", high = "blue") +  labs(color = "Expression") +
  theme_void() +  facet_wrap(~ subclass)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)
```
```{r}

```






```{r}
ImageFeaturePlot(Recon_neuron_new_clean_final, features = Spatial)

```









```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")
# Create the plot with larger legend key sizes
pic <- ggplot(neuron_meta, aes(x = x_um, y = y_um, color = C_minusUCELL)) +
  geom_point(alpha = 0.5, size = 0.2) +
    scale_color_gradient(low = "blue", high = "red") +  # If you want to rename labels
  labs(color = "Neuronal Subclasses") +
  guides(color = guide_legend(override.aes = list(size = 4))) +  # Increase size of dots in the legend
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = NA),
    legend.text = element_text(size = 16),  # Increase legend text size
    legend.title = element_text(size = 18)
  ) + facet_wrap(~ reclustered_patch_matrix_exotic)


ggsave(pic, filename = "pic.png", width = 8, height = 6)
```


```{r}
custom_labels <- c(non_SPN = "non-SPN", SPN_exotic = "SPN Patch 2", SPN_matrix = "SPN Matrix", SPN_patch = "SPN Patch 1", eSPN = "eSPN")

# Plot with light gray points for all data in the background
matrix_recon = subset(neuron_meta, subset = reclustered_patch_matrix_exotic == "SPN_matrix")

a = ggplot(matrix_recon, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")
) +   labs(color = "C Minus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)

b = ggplot(matrix_recon, aes(x= x_um, y = y_um, color = C_plusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Plus Scores \n") + scale_color_gradientn(colors = c("#0000FF", "#4682B4", "#87CEEB", "#FFD700", "#FF7F50", "#FF4500", "#FF0000")
) +  labs(color = "C Plus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)

pic = a+b
ggsave(pic, filename = "pic.png", width = 20, height = 10)
```

```{r}
ggplot(neuron_meta, aes(x=C_minusUCELL, y=C_plusUCELL, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle("C minus vs C plus UCell Scores") + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ reclustered_patch_matrix_exotic) 

```
```{r}
matrix_recon_cah_put = subset(matrix_recon, subset = y_um < 12000)
matrix_recon_cah_put
```

```{r}
ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF7F50", "#FFFF00", "#87CEEB", "#0000FF")
) +   labs(color = "C Minus Scores") + ylim(0,12000)
```


```{r}
 a = ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_minusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Minus Scores \n") + scale_color_gradientn(colors = c("#FF0000", "#FF4500", "#FF7F50", "#FFD700", "#87CEEB", "#4682B4", "#0000FF")

) +   labs(color = "C Minus Scores") + ylim(0,12000) + xlim(10000, 16000)+
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +
  ylab(NULL)


b = ggplot(matrix_recon_cah_put, aes(x= x_um, y = y_um, color = C_plusUCELL)) + geom_point() + ggtitle(" SPN Matrix: C Plus Scores \n") + scale_color_gradientn(colors = c("#0000FF", "#4682B4", "#87CEEB", "#FFD700", "#FF7F50", "#FF4500", "#FF0000")

) +  labs(color = "C Plus Scores") +
  theme_void() +
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) + ylim(0,12000) +xlim(10000, 16000)+
  ylab(NULL)

pic = a+b
ggsave(pic, filename = "pic.png", width = 20, height = 10)
```




```{r}
clean_recon_sobj

gene_of_interest <- "TAF1"  
taf1_df = clean_recon_sobj@meta.data
taf1_df$cell_ids = rownames(taf1_df)
taf1_df

test = as.data.frame(FetchData(clean_recon_sobj, vars = gene_of_interest))
test$cell_ids = rownames(test)
test

taf1_df_final = merge(taf1_df, test, by = "cell_ids" )
taf1_df_final
```


```{r}
  pic = ggplot(taf1_df_final, aes(x= x_um, y = y_um, color = TAF1)) + geom_point(size = 1) +  scale_color_gradient(low = "lightgrey", high = "blue") +  labs(color = "TAF1 Expression") +
  theme_void() +  facet_wrap(~ final_cell_class)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 20, height = 15)

```


```{r}
FeaturePlot(clean_recon_sobj, features = c("TAF1"), label = T, raster = F)
Idents(Recon_neuron_new_clean_final) = "subclass"
FeaturePlot(Recon_neuron_new_clean_final, features = c("TAF1"), label = T)
Idents(Recon_neuron_new_clean_final) = "reclustered_patch_matrix_exotic"
```

```{r}
  pic = ggplot(taf1_df_final, aes(x= x_um, y = y_um, color = percent.mt)) + geom_point(size = 1) +  scale_color_gradient(low = "lightgrey", high = "blue") +  labs(color = "percent mito") +
  theme_void() +  facet_wrap(~ final_cell_class)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 20, height = 15)
```

```{r}
taf1_df_final
```
```{r}
taf1_df_final$log_Cminus_Cplus = log(taf1_df_final$C_minusUCELL/taf1_df_final$C_plusUCELL)
taf1_df_final
```


```{r}
 pic = ggplot(taf1_df_final, aes(x= x_um, y = y_um, color = log_Cminus_Cplus)) + geom_point(size = 1) + scale_color_gradientn(colors = c("#0000FF",  "#87CEEB", "#FFD700", "#FF7F50", "#FF0000")) +  labs(color = "log(C minus/C plus)") +
  theme_void() +  facet_wrap(~ reclustered_patch_matrix_exotic)+
  theme(
    plot.title = element_text(size = 30),
    plot.subtitle = element_text(size = 30),
    strip.text = element_text(size = 30),
    plot.background = element_rect(fill = "white", color = NA),
     legend.text = element_text(size = 24),  # Increase legend text size
    legend.title = element_text(size = 26)
  ) +  ylab(NULL)

ggsave(pic, filename = "pic.png", width = 30, height = 15)
```




```{r}
new_df
```

```{r}
what = qread("temphome/XDP_BICAN_ucell_scores.qs")
what
```

```{r}
new_df
```



