---
title: "R Notebook"
output: html_notebook
---

```{r}
matrix_markers = read.csv("matrix_markers083024.csv")
patch_markers = read.csv("patch_markers083024.csv")
eSPN_markers = read.csv("eSPN_markers083024.csv")
nonSPN_markers = read.csv("non_SPN_markers083024.csv")

matrix_markers = matrix_markers$gene
patch_markers = patch_markers$gene
eSPN_markers= eSPN_markers$gene
nonSPN_markers = nonSPN_markers$gene
```

```{r}
BICAN_V17_matrix = read.csv("BICAN_V17_matrix.csv")

BICAN_V17_patch= read.csv("BICAN_V17_patch.csv")

BICAN_V17_exotic= read.csv("BICAN_V17_exotic.csv")

BICAN_V17_eSPN= read.csv("BICAN_V17_eSPN.csv")

BICAN_V17_nonSPN= read.csv("BICAN_V17_nonSPN.csv")

BICAN_V17_matrix = BICAN_V17_matrix$gene
BICAN_V17_patch = BICAN_V17_patch$gene
BICAN_V17_exotic = BICAN_V17_exotic$gene
BICAN_V17_eSPN = BICAN_V17_eSPN$gene
BICAN_V17_nonSPN = BICAN_V17_nonSPN$gene
```



```{r}
c_minus_genes = readRDS("~/ferris_handsaker_genes_phase_c_minus.rds")
c_plus_genes = readRDS("~/ferris_handsaker_genes_phase_c_plus.rds")
d_genes = readRDS("~/ferris_handsaker_genes_phase_d.rds")
c_minus_genes
c_plus_genes
d_genes
```

```{r}
xdp_neurons = qread("~/rstudio/workdir/SOBJ/kkim_SOBJ_USE_THESE_final_merged_xdp_neurons.qs")
xdp_neurons
```
#186/203 c minus genes, 340/369 c plus genes, 32/107 d genes
```{r}
length(c_minus_genes)
new_c_minus_genes = intersect(rownames(xdp_neurons), c_minus_genes) 
length(new_c_minus_genes)

length(c_plus_genes)
new_c_plus_genes = intersect(rownames(xdp_neurons), c_plus_genes) 
length(new_c_plus_genes)

length(d_genes)
new_d_genes = intersect(rownames(xdp_neurons), d_genes) 
length(new_d_genes)
```


```{r}
DimPlot(xdp_neurons, label = T)
```

```{r}
spn_bican = qread("~/Downloads/SPN_Matrix_BICAN_findmarkers.qs")
spn_bican = rownames(spn_bican)
```

```{r}
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(SPN = spn_bican),
  name = 'SPN_Matrix_scores_UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(D_genes = new_d_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)
```


```{r}
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(matrix_markers = matrix_markers),
  name = 'SPN_Matrix_scores_UCELL'
)
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(patch_markers = patch_markers),
  name = 'SPN_Matrix_scores_UCELL'
)
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(eSPN_markers = eSPN_markers),
  name = 'SPN_Matrix_scores_UCELL'
)
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(nonSPN_markers = nonSPN_markers),
  name = 'SPN_Matrix_scores_UCELL'
)
```



#intersection of V17 markers, xdp, V8
```{r}
BICAN_V8 = qread("BICAN_neurons_ucell.qs") 
BICAN_V8@meta.data
```


```{r}
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(patch_markers = BICAN_V17_patch),
  name = 'UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(eSPN_markers = BICAN_V17_eSPN),
  name = 'UCELL'
)

xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(nonSPN_markers = BICAN_V17_nonSPN),
  name = 'UCELL'
)
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(exotic_markers = BICAN_V17_exotic),
  name = 'UCELL'
)
```


```{r}
qsave(xdp_neurons, "xdp_neurons_ucell.qs") 
xdp_neurons = qread("xdp_neurons_ucell.qs") 
xdp_df = xdp_neurons@meta.data 
xdp_df
```

```{r}
min(xdp_df$exotic_markersUCELL)
max(xdp_df$exotic_markersUCELL)
```


```{r}
limits = seq(0.15, 0.70, 0.005)

matrix <- xdp_df[xdp_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$exotic_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "V17 Exotic Patch score UCell",
                                          fig_filename = NULL)
  
  patch <- xdp_df[xdp_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$exotic_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "V17 Exotic Patch score UCell",
                                          fig_filename = NULL)
  nonSPN <- xdp_df[xdp_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$exotic_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "V17 Exotic Patch score UCell",
                                          fig_filename = NULL)
  

    eSPN <- xdp_df[xdp_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$exotic_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "V17 Exotic Patch score UCell",
                                          fig_filename = NULL)
  
      exotic <- xdp_df[xdp_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$exotic_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = "V17 Exotic Patch score UCell",
                                          fig_filename = NULL)
```

```{r}
qsave(xdp_df, "XDP_ucell_scores.qs")
```



```{r}
cell_types = unique(xdp_df$reclustered_patch_matrix_exotic)

for (celltype in cell_types) {
 df = subset(xdp_df, subset = reclustered_patch_matrix_exotic == celltype)
 x_order = c("SCF_21-037CM2","SCF-23-068CM","SCF-22-054CM", "SCF-22-058CF", "SCF-20-025", "SCF-18-003",  "SCF_22-043", "SCF_20-024", "SCF-18-004", "SCF-18-006", "SCF-20-023", "SCF-21-030", "PCMC-16-012", "SCF-19-009", "SCF-19-014", "PCMC-16-011", "SCF-19-018")

df$donor_id = factor(df$donor_id, levels = x_order)
  
a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ donor_id) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4")) 

print(a)
 ggsave(filename = paste0("plot_", celltype, ".png"), plot = a, width = 12, height = 8)
}

```


#now BICAN
```{r}
BICAN_V8 = qread("~/Downloads/kkim_SOBJ_USE_THESE_090424_sobjs_final_V8_BICAN_neurons.qs")
BICAN_V8
DimPlot(BICAN_V8, label = T)
BICAN_V8@meta.data$reclustered_patch_matrix_exotic = BICAN_V8$reclustered_neuron_joint_type
BICAN_V8$reclustered_patch_matrix_exotic[BICAN_V8$reclustered_patch_matrix_exotic == "SPN_patch"] = "SPN_exotic"
Idents(BICAN_V8) = "reclustered_patch_matrix_exotic"
DimPlot(BICAN_V8, label = T)
```

#186/203 c minus genes, 339/369 c plus genes, 30/107 d genes 

```{r}
length(new_c_minus_genes)
new_c_minus_genes_BICAN = intersect(rownames(BICAN_V8), new_c_minus_genes) 
length(new_c_minus_genes_BICAN)

length(new_c_plus_genes)
new_c_plus_genes_BICAN = intersect(rownames(BICAN_V8), new_c_plus_genes) 
length(new_c_plus_genes_BICAN)

length(new_d_genes)
new_d_genes_BICAN = intersect(rownames(BICAN_V8), new_d_genes) 
length(new_d_genes_BICAN)
```

```{r}
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(SPN = spn_bican),
  name = 'SPN_Matrix_scores_UCELL'
)
```

```{r}
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(C_minus = new_c_minus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(C_plus = new_c_plus_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(D_genes = new_d_genes_BICAN),
  name = 'SPN_Matrix_scores_UCELL'
)
```

```{r}
qsave(BICAN_V8, "BICAN_neurons_ucell.qs") 
#BICAN_V8 = qread("BICAN_neurons_ucell.qs") 
new_df = BICAN_V8@meta.data 
new_df
```

```{r}
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(patch_markers = BICAN_V17_patch),
  name = 'UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(eSPN_markers = BICAN_V17_eSPN),
  name = 'UCELL'
)

BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(nonSPN_markers = BICAN_V17_nonSPN),
  name = 'UCELL'
)
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(exotic_markers = BICAN_V17_exotic),
  name = 'UCELL'
)
```

```{r}
new_df = BICAN_V8@meta.data 
new_df
```

```{r}
xdp_df = qread("XDP_ucell_scores.qs")
xdp_df
new_df
```

```{r}
colnames(new_df)
```


```{r}
new_df$Condition = "BICAN_V8"
# Select specific columns from each data frame
xdp_df <- xdp_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "SPNSPN_Matrix_scores_UCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL", "matrix_markersUCELL", "patch_markersUCELL", "eSPN_markersUCELL", "nonSPN_markersUCELL", "exotic_markersUCELL"  )]  

new_df <- new_df[, c("DONOR", "Condition", "reclustered_patch_matrix_exotic", "SPNSPN_Matrix_scores_UCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL","matrix_markersUCELL", "patch_markersUCELL", "eSPN_markersUCELL", "nonSPN_markersUCELL", "exotic_markersUCELL")]

new_df$donor_id = new_df$DONOR
new_df$DONOR = NULL

new_df
xdp_df
```

```{r}
final_df = rbind(xdp_df, new_df)
final_df
```

```{r}
min(final_df$eSPN_markersUCELL)
max(final_df$eSPN_markersUCELL)
```

```{r}
limits = seq(0.3, 0.7, 0.005)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$eSPN_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  
  patch <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$eSPN_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$eSPN_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  
    eSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$eSPN_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  
      exotic <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$eSPN_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
```

```{r}
qsave(final_df, "XDP_BICAN_ucell_scores.qs")
```



```{r}
cell_types = unique(new_df$reclustered_patch_matrix_exotic)

for (celltype in cell_types) {
 df = subset(new_df, subset = reclustered_patch_matrix_exotic == celltype)
  
a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ donor_id) + scale_color_manual(values = c("BICAN_V8" = "#00BA38")) 

print(a)
 ggsave(filename = paste0("plot_", celltype, ".png"), plot = a, width = 12, height = 8)
}

```


```{r}
for (celltype in cell_types) {
  
df = subset(final_df, subset = reclustered_patch_matrix_exotic == celltype)

a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ Condition) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4", "BICAN_V8" = "#00BA38")) 
print(a)
}

df = subset(final_df, subset = reclustered_patch_matrix_exotic == "SPN_patch")

a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle("SPN_patch: C minus vs C plus UCell Scores") + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ Condition) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4")) 
print(a)
```


```{r}
MMR_genes =c("MSH2", "MSH3", "PMS2", "POLD3", "LIG1","RFC3", "RFC4", "POLD2",  "MLH3", "MSH6", "FAN1", "POLE", "POLD4", "POLD1", "MLH1", "RFC2", "PMS1", "PCNA")
#Warning: The following genes were not found and will be imputed to exp=0: * RCF5,RCF1

BER_genes = c("PARP1", "TDG", "LIG3", "OGG1", "TDP1", "UNG", "APEX1", "XRCC1", "NEIL1", "TOP1", "POLB", "HMGB1")

```




```{r}
BICAN_V8 <- AddModuleScore(BICAN_V8,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'Seurat_'
)
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(MMR = MMR_genes),
  name = 'UCELL'
)
BICAN_V8 <- AddModuleScore_UCell(BICAN_V8,
  features = list(BER = BER_genes),
  name = 'UCELL'
)
new_df = BICAN_V8@meta.data 
new_df
```

```{r}
xdp_neurons = qread("xdp_neurons_ucell.qs") 

xdp_neurons <- AddModuleScore(xdp_neurons,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'Seurat_'
)
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(MMR = MMR_genes),
  name = 'UCELL'
)
xdp_neurons <- AddModuleScore_UCell(xdp_neurons,
  features = list(BER = BER_genes),
  name = 'UCELL'
)
xdp_df = xdp_neurons@meta.data 
new_df
xdp_df
```


```{r}
new_df$Condition = "BICAN_V8"
# Select specific columns from each data frame
xdp_df <- xdp_df[, c("donor_id", "Condition", "reclustered_patch_matrix_exotic", "SPNSPN_Matrix_scores_UCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL", "matrix_markersUCELL", "patch_markersUCELL", "eSPN_markersUCELL", "nonSPN_markersUCELL", "exotic_markersUCELL", "Seurat_1", "MMRUCELL", "BERUCELL")]  

new_df <- new_df[, c("DONOR", "Condition", "reclustered_patch_matrix_exotic", "SPNSPN_Matrix_scores_UCELL", "C_minusSPN_Matrix_scores_UCELL", "C_plusSPN_Matrix_scores_UCELL", "D_genesSPN_Matrix_scores_UCELL","matrix_markersUCELL", "patch_markersUCELL", "eSPN_markersUCELL", "nonSPN_markersUCELL", "exotic_markersUCELL","Seurat_1", "MMRUCELL", "BERUCELL")]

new_df$donor_id = new_df$DONOR
new_df$DONOR = NULL

final_df = rbind(xdp_df, new_df)
final_df
qsave(final_df, "XDP_BICAN_ucell_scores.qs")
```


```{r}
cortest <- cor.test(new_df$Seurat_1, new_df$matrix_markersUCELL, method = "spearman", exact = FALSE )
cortest
cor <- cortest$estimate
pvalue <- cortest$p.value
subtitle <- paste("Spearman correlation: ", sprintf("%0.3f", cor), " R^2: ", sprintf("%0.3f", cor^2), " p-value: ", sprintf("%0.3f", pvalue))

ggplot(new_df, aes(x=Seurat_1, y=matrix_markersUCELL, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("AddModuleScore: Seurat vs UCell (BICAN V8)", subtitle = subtitle) + xlab("SPN Matrix Scores (Seurat)") + ylab("SPN Matrix Scores (UCell)")
```


```{r}
cortest <- cor.test(xdp_df$Seurat_1, xdp_df$matrix_markersUCELL, method = "spearman", exact = FALSE )
cortest
cor <- cortest$estimate
pvalue <- cortest$p.value
subtitle <- paste("Spearman correlation: ", sprintf("%0.3f", cor), " R^2: ", sprintf("%0.3f", cor^2), " p-value: ", sprintf("%0.3f", pvalue))

ggplot(xdp_df, aes(x=Seurat_1, y=matrix_markersUCELL, color=reclustered_patch_matrix_exotic)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("AddModuleScore: Seurat vs UCell", subtitle = subtitle) + xlab("SPN Matrix Scores (Seurat)") + ylab("SPN Matrix Scores (UCell)")
```

```{r}
cortest <- cor.test(xdp_df$Seurat_1, xdp_df$matrix_markersUCELL, method = "spearman", exact = FALSE )
cortest
cor <- cortest$estimate
pvalue <- cortest$p.value
subtitle <- paste("Spearman correlation: ", sprintf("%0.3f", cor), " R^2: ", sprintf("%0.3f", cor^2), " p-value: ", sprintf("%0.3f", pvalue))
```


```{r}
ggplot(xdp_df, aes(x=Seurat_1, y=matrix_markersUCELL, color=Condition)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("AddModuleScore: Seurat vs UCell") + xlab("SPN Matrix Scores (Seurat)") + ylab("SPN Matrix Scores (UCell)") +facet_wrap(~ reclustered_patch_matrix_exotic)
```

```{r}
final_df
```


```{r}
min(final_df$BERUCELL)
max(final_df$BERUCELL)
```

```{r}
limits = seq(0.001, 0.2, 0.001)

matrix <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$BERUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "BER Score (zoom)",
                                          fig_filename = NULL)
  
  patch <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$BERUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "BER Score (zoom)",
                                          fig_filename = NULL)
  nonSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$BERUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "BER Score (zoom)",
                                          fig_filename = NULL)
  
    eSPN <- final_df[final_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$BERUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "BER Score (zoom)",
                                          fig_filename = NULL)
  
      exotic <- final_df[final_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$BERUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = "BER Score (zoom)",
                                          fig_filename = NULL)
```
```{r}
final_df
```
```{r}
table(BICAN_V8$reclustered_patch_matrix_exotic)
```

```{r}
BICAN_V8_matrix = qread("BICAN_V8_matrix.qs")
BICAN_V8_exotic = qread("BICAN_V8_exotic")
BICAN_V8_eSPN = qread("BICAN_V8_eSPN")
```


```{r}
BICAN_V8_matrix = subset(BICAN_V8, subset = reclustered_patch_matrix_exotic == "SPN_matrix")
BICAN_V8_exotic= subset(BICAN_V8, subset = reclustered_patch_matrix_exotic == "SPN_exotic")
BICAN_V8_eSPN= subset(BICAN_V8, subset = reclustered_patch_matrix_exotic == "eSPN")
BICAN_V8_nonSPN= subset(BICAN_V8, subset = reclustered_patch_matrix_exotic == "non-SPN")

BICAN_V8_matrix
BICAN_V8_exotic
BICAN_V8_eSPN
BICAN_V8_nonSPN
```

```{r}
BICAN_V8_exotic
BICAN_V8_eSPN
BICAN_V8_nonSPN
```


```{r}
BICAN_V8_matrix <- AddModuleScore_UCell(BICAN_V8_matrix,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'UCELL'
)
BICAN_V8_matrix <- AddModuleScore_UCell(BICAN_V8_matrix,
  features = list(patch_markers = BICAN_V17_patch),
  name = 'UCELL'
)
BICAN_V8_matrix <- AddModuleScore_UCell(BICAN_V8_matrix,
  features = list(eSPN_markers = BICAN_V17_eSPN),
  name = 'UCELL'
)

BICAN_V8_matrix <- AddModuleScore_UCell(BICAN_V8_matrix,
  features = list(nonSPN_markers = BICAN_V17_nonSPN),
  name = 'UCELL'
)
BICAN_V8_matrix <- AddModuleScore_UCell(BICAN_V8_matrix,
  features = list(exotic_markers = BICAN_V17_exotic),
  name = 'UCELL'
)
```


```{r}

BICAN_V8_exotic <- AddModuleScore_UCell(BICAN_V8_exotic,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'UCELL'
)
BICAN_V8_exotic <- AddModuleScore_UCell(BICAN_V8_exotic,
  features = list(patch_markers = BICAN_V17_patch),
  name = 'UCELL'
)
BICAN_V8_exotic <- AddModuleScore_UCell(BICAN_V8_exotic,
  features = list(eSPN_markers = BICAN_V17_eSPN),
  name = 'UCELL'
)

BICAN_V8_exotic <- AddModuleScore_UCell(BICAN_V8_exotic,
  features = list(nonSPN_markers = BICAN_V17_nonSPN),
  name = 'UCELL'
)
BICAN_V8_exotic <- AddModuleScore_UCell(BICAN_V8_exotic,
  features = list(exotic_markers = BICAN_V17_exotic),
  name = 'UCELL'
)


BICAN_V8_eSPN <- AddModuleScore_UCell(BICAN_V8_eSPN,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'UCELL'
)
BICAN_V8_eSPN <- AddModuleScore_UCell(BICAN_V8_eSPN,
  features = list(patch_markers = BICAN_V17_patch),
  name = 'UCELL'
)
BICAN_V8_eSPN <- AddModuleScore_UCell(BICAN_V8_eSPN,
  features = list(eSPN_markers = BICAN_V17_eSPN),
  name = 'UCELL'
)

BICAN_V8_eSPN <- AddModuleScore_UCell(BICAN_V8_eSPN,
  features = list(nonSPN_markers = BICAN_V17_nonSPN),
  name = 'UCELL'
)
BICAN_V8_eSPN <- AddModuleScore_UCell(BICAN_V8_eSPN,
  features = list(exotic_markers = BICAN_V17_exotic),
  name = 'UCELL'
)




BICAN_V8_nonSPN <- AddModuleScore_UCell(BICAN_V8_nonSPN,
  features = list(matrix_markers = BICAN_V17_matrix),
  name = 'UCELL'
)
BICAN_V8_nonSPN <- AddModuleScore_UCell(BICAN_V8_nonSPN,
  features = list(patch_markers = BICAN_V17_patch),
  name = 'UCELL'
)
BICAN_V8_nonSPN <- AddModuleScore_UCell(BICAN_V8_nonSPN,
  features = list(eSPN_markers = BICAN_V17_eSPN),
  name = 'UCELL'
)

BICAN_V8_nonSPN <- AddModuleScore_UCell(BICAN_V8_nonSPN,
  features = list(nonSPN_markers = BICAN_V17_nonSPN),
  name = 'UCELL'
)
BICAN_V8_nonSPN <- AddModuleScore_UCell(BICAN_V8_nonSPN,
  features = list(exotic_markers = BICAN_V17_exotic),
  name = 'UCELL'
)
```

```{r}
BICAN_V8_matrix = BICAN_V8_matrix@meta.data
BICAN_V8_exotic= BICAN_V8_exotic@meta.data
BICAN_V8_eSPN = BICAN_V8_eSPN@meta.data
BICAN_V8_nonSPN= BICAN_V8_nonSPN@meta.data

BICAN_V8_rbinded = rbind(BICAN_V8_matrix, BICAN_V8_exotic, BICAN_V8_eSPN, BICAN_V8_nonSPN)
BICAN_V8_rbinded
```

```{r}
new_df
BICAN_V8_rbinded
```


```{r}
min(BICAN_V8_rbinded$matrix_markersUCELL)
max(BICAN_V8_rbinded$matrix_markersUCELL)
```




```{r}
limits = seq(0.2, 0.7, 0.005)

  plot_overlapping_density_histogram(df = BICAN_V8_rbinded, 
                                          hist_col = BICAN_V8_rbinded$matrix_markersUCELL,
                                          fill_col = "reclustered_patch_matrix_exotic",
                                          colors = c("red", "yellow", "green", "blue", "purple"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
```


```{r}
patch <- BICAN_V8_rbinded[BICAN_V8_rbinded$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  nonSPN <- BICAN_V8_rbinded[BICAN_V8_rbinded$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  
    eSPN <- BICAN_V8_rbinded[BICAN_V8_rbinded$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: eSPN",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
  
      exotic <- BICAN_V8_rbinded[BICAN_V8_rbinded$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$matrix_markersUCELL,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN_V8" = "green"),
                                          breaks = limits,
                                          title = "XDP vs Control: SPN exotic patch",
                                          xlab = "V17 eSPN score UCell",
                                          fig_filename = NULL)
```

```{r}
final_df
```

```{r}
cortest <- cor.test(xdp_df$matrix_markersUCELL, xdp_df$C_minusSPN_Matrix_scores_UCELL, method = "spearman", exact = FALSE )
cortest
cor <- cortest$estimate
pvalue <- cortest$p.value
subtitle <- paste("Spearman correlation: ", sprintf("%0.3f", cor), " R^2: ", sprintf("%0.3f", cor^2), " p-value: ", sprintf("%0.3f", pvalue))
```


```{r}
xdp_df_matrix = subset(xdp_df, subset = reclustered_patch_matrix_exotic == "SPN_matrix")

ggplot(xdp_df_matrix, aes(x=matrix_markersUCELL, y=C_minusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4)  + geom_smooth(method = "lm", se = FALSE, color = "black") + ggtitle("SPN Matrix scores vs C minus scores") + xlab("SPN Matrix Scores") + ylab("C Minus Scores") + facet_wrap(~ donor_id)
```



```{r}
cell_types = unique(xdp_df$reclustered_patch_matrix_exotic)

for (celltype in cell_types) {
 df = subset(xdp_df, subset = reclustered_patch_matrix_exotic == celltype)
  
a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ donor_id) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4", "BICAN_V8" = "#00BA38")) 

print(a)
 ggsave(filename = paste0("plot_", celltype, ".png"), plot = a, width = 12, height = 8)
}

```


```{r}
for (celltype in cell_types) {
  
df = subset(final_df, subset = reclustered_patch_matrix_exotic == celltype)

a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle(paste(celltype, ": C minus vs C plus UCell Scores")) + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ Condition) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4", "BICAN_V8" = "#00BA38")) 
print(a)
}

df = subset(final_df, subset = reclustered_patch_matrix_exotic == "SPN_patch")

a = ggplot(df, aes(x=C_minusSPN_Matrix_scores_UCELL, y=C_plusSPN_Matrix_scores_UCELL, color=Condition)) + geom_point(alpha = 0.4) + geom_smooth(method="loess", se=FALSE, color="black") + ggtitle("SPN_patch: C minus vs C plus UCell Scores") + xlab("C minus score") + ylab("C plus score") + facet_wrap(~ Condition) + scale_color_manual(values = c("XDP" = "#F8766D", "Control" = "#00BFC4")) 
print(a)
```

