---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
library(tidyr)
library(qs)
library(tibble)
library(gridExtra)
```

```{r}
final_V8_BICAN_neurons = qread("~/SOBJ_USE_THESE/final_V8_BICAN_neurons.qs")
final_V8_BICAN_neurons
final_merged_xdp_transformed = qread("~/SOBJ_USE_THESE/final_merged_xdp_transformed_081224.qs")
final_merged_xdp_transformed

Idents(final_V8_BICAN_neurons) = "reclustered_patch_matrix"

Intersected_BICAN_matrix_markers_final_filtered = qread("~/SPN_Matrix_BICAN_findmarkers.qs")
Intersected_BICAN_matrix_markers_final_filtered
```

```{r}
final_V8_BICAN_neurons
final_V8_BICAN_neurons_final = subset(final_V8_BICAN_neurons, subset = DONOR != "MD6701")
final_V8_BICAN_neurons_final
```


```{r}
BICAN_matrix_scores = BICAN_SPN_score_normalized(Intersected_BICAN_matrix_markers_final_filtered, final_V8_BICAN_neurons_final, logfc_val = "weighted_logFC", method = "multiply")
BICAN_matrix_scores
```


```{r}
color4 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange")

color1 = c("SPN" = "red", "non-SPN"= "blue") #for subcluster: SPN vs non-SPNS
color2 = c("red", "blue")
color3 = c("SPN"="red", "eSPN"="yellow", "other"="green", "IN" = "blue") #for subclass

color5 = c("SPN_matrix"="red", "SPN_patch" = "orange","eSPN"="green", "non-SPN" = "blue") 
```


#now I want to take score distribution for each person, subtract the mean of the distribution, divide by st dev
```{r}
BICAN_matrix_scores$Village = "BICAN"
BICAN_matrix_scores
```
```{r}
unique(BICAN_matrix_scores$reclustered_neuron_joint_type)
```


```{r}
color4 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange")
color3 = c("SPN_matrix" = "red", "non-SPN" = "blue")
BICAN_matrix_scores
donor_order = BICANdonors
fillcol = "reclustered_neuron_joint_type" #"reclustered_patch_matrix" 
color = color5 #color4 or 5
donor_graph_title = "BICAN SPN Matrix vs non-SPNs"
SCtransformcounts =final_V8_BICAN_neurons_final
SPN_score_col_name = "BICANtest"

 
  options(repr.plot.width = 24, repr.plot.height = 16)
  BICAN_matrix_scores$new_distribution <- NA
  plots <- list()

for (donor in donor_order) {
    test <- BICAN_matrix_scores[BICAN_matrix_scores$DONOR == donor, ]
    test$new_distribution <- NA  # Initialize the new column
    cell_classes = unique(test$reclustered_neuron_joint_type)  
    for (class in cell_classes) {
        df = test[test$reclustered_neuron_joint_type == class, ]
        test$new_distribution[test$reclustered_neuron_joint_type == class] <- scale(df$total_expression)
    }
    BICAN_matrix_scores[BICAN_matrix_scores$DONOR == donor, "new_distribution"] <- test$new_distribution

    plots[[donor]] <- plot_overlapping_density_histogram(df = test,
                                                         hist_col = "new_distribution",
                                                         fill_col = fillcol,
                                                         colors = color,
                                                         breaks = seq(-8,6,0.5),
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "Matrix SPN Score",
                                                         fig_filename = NULL)
    

  }
  BICAN_matrix_scores_final <- do.call(rbind, combined_df_list)
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, 14, 15),
    c(16, 17, 18, NA, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  BICAN_matrix_scores
```



```{r}
matrix <- BICAN_matrix_scores[BICAN_matrix_scores$reclustered_neuron_joint_type == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$total_expression,
                                          fill_col = "reclustered_neuron_joint_type",
                                          colors = c("SPN_matrix" = "red"),
                                          breaks = seq(0,120,2),
                                          title = "BICAN Controls: SPN matrix",
                                          xlab = "Matrix SPN score",
                                          fig_filename = NULL)
  patch <- BICAN_matrix_scores[BICAN_matrix_scores$reclustered_neuron_joint_type == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$total_expression,
                                          fill_col = "reclustered_neuron_joint_type",
                                          colors = c("SPN_patch" = "orange"),
                                          breaks = seq(0,120,2),
                                          title = "BICAN Controls: SPN patch",
                                          xlab = "Matrix SPN score",
                                          fig_filename = NULL)
  nonSPN <- BICAN_matrix_scores[BICAN_matrix_scores$reclustered_neuron_joint_type == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$total_expression,
                                          fill_col = "reclustered_neuron_joint_type",
                                          colors = c("non-SPN" = "blue"),
                                          breaks = seq(0,120,2),
                                          title = "BICAN Controls: non-SPN",
                                          xlab = "Matrix SPN score",
                                          fig_filename = NULL)
    eSPN <- BICAN_matrix_scores[BICAN_matrix_scores$reclustered_neuron_joint_type == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$total_expression,
                                          fill_col = "reclustered_neuron_joint_type",
                                          colors = c("eSPN" = "green"),
                                          breaks = seq(0,120,2),
                                          title = "BICAN Controls: eSPN",
                                          xlab = "Matrix SPN score",
                                          fig_filename = NULL)
  
```


```{r}
 options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  for (donor in BICANdonors) {
   test <- BICAN_matrix_scores[BICAN_matrix_scores$DONOR == donor, ]
   threshold <- quantile(test[["new_distribution"]][test[["reclustered_patch_matrix"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- test[test[["new_distribution"]] < threshold & test[["reclustered_patch_matrix"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = subset(final_V8_BICAN_neurons, subset = DONOR == donor)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  plots[[donor]] <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) +ggtitle(paste(donor, ", 10% threshold:", sprintf("%.2f", threshold)))
}
  
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, 14, 15),
    c(16, 17, 18, 19, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/tenten.png", plot = grid_plots, width = 36, height = 16)

```

```{r}
   threshold <- quantile(BICAN_matrix_scores[["new_distribution"]][BICAN_matrix_scores[["reclustered_patch_matrix"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- BICAN_matrix_scores[BICAN_matrix_scores[["new_distribution"]] < threshold & BICAN_matrix_scores[["reclustered_patch_matrix"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = final_V8_BICAN_neurons
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey"))

```
```{r}
qsave(BICAN_matrix_scores, "~/BICAN_matrix_scores.qs")

BICAN_matrix_scores = qread("~/BICAN_matrix_scores.qs")
BICAN_matrix_scores
```




#xdp integrated Matrix score
```{r}
XDP_matrix_scores = SPN_score_normalized(Intersected_BICAN_matrix_markers_final_filtered, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply")

XDP_matrix_scores$Village = "XDP"
XDP_matrix_scores
```


```{r}
color4 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange", "SPN_exotic" = "yellow", "eSPN" = "green")
color5 = c("SPN_matrix" = "red", "non-SPN" = "blue")
XDP_matrix_scores
donor_order = donors
fillcol = "reclustered_patch_matrix_exotic"
color = color4 #color4 or 5
donor_graph_title = "XDP SPN Matrix vs non-SPNs"
SCtransformcounts =final_merged_xdp_transformed
SPN_score_col_name = "XDP"

 
  options(repr.plot.width = 24, repr.plot.height = 16)
  XDP_matrix_scores$new_distribution <- NA
  plots <- list()

  # for (donor in donor_order) {
  #   test <- XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, ]
  #   test$new_distribution = scale(test$total_expression)
  #   XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, "new_distribution"] <- test$new_distribution
  #   plots[[donor]] <- plot_overlapping_density_histogram(df = test,
  #                                                        hist_col = "new_distribution",
  #                                                        fill_col = fillcol,
  #                                                        colors = color,
  #                                                        breaks = seq(-2,1,0.1),
  #                                                        title = paste(donor_graph_title, ": ", donor),
  #                                                        xlab = "Matrix SPN Score",
  #                                                        fig_filename = NULL)
  # }
  
  for (donor in donor_order) {
    test <- XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, ]
    test$new_distribution <- NA  # Initialize the new column
    cell_classes = unique(test$reclustered_patch_matrix_exotic)  
    for (class in cell_classes) {
        df = test[test$reclustered_patch_matrix_exotic == class, ]
        test$new_distribution[test$reclustered_patch_matrix_exotic == class] <- scale(df$total_expression)
    }
    XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, "new_distribution"] <- test$new_distribution

    plots[[donor]] <- plot_overlapping_density_histogram(df = test,
                                                         hist_col = "new_distribution",
                                                         fill_col = fillcol,
                                                         colors = color,
                                                         breaks = seq(-6,6,0.1),
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "Matrix SPN Score",
                                                         fig_filename = NULL)
  }
  
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16,17 , NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  XDP_matrix_scores
```


```{r}
 options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  combined_df_list <- list()
  for (donor in donors) {
   test <- XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, ]
   threshold <- quantile(test[["new_distribution"]][test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- test[test[["new_distribution"]] < threshold & test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = subset(final_merged_xdp_transformed, subset = donor_id == donor)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data

  filtered_df <- SCtransformcounts@meta.data[SCtransformcounts@meta.data$SPN_identity == "Bottom 10% of Matrix SPNs", ]

combined_df_list[[donor]] <- filtered_df

  # Visualize on UMAP
  plots[[donor]] <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) +ggtitle(paste(donor, ", 10% threshold:", sprintf("%.2f", threshold)))
}
  
combined_df <- do.call(rbind, combined_df_list)

  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/tenten.png", plot = grid_plots, width = 36, height = 16)
combined_df
```

```{r}
   threshold <- quantile(XDP_matrix_scores[["new_distribution"]][XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- XDP_matrix_scores[XDP_matrix_scores[["new_distribution"]] < threshold & XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = final_merged_xdp_transformed
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey"))

```




#8/18

```{r}
 options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  combined_df_list <- list()
  top_df_list = list()
  for (donor in donors) {
   test <- XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, ]
   threshold <- quantile(test[["total_expression"]][test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
   top_threshold <- quantile(test[["total_expression"]][test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.5, na.rm = TRUE)
  print(threshold)
  
  SPN_score_output_identity_loss_SPN <- test[test[["total_expression"]] < threshold & test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
  
    SPN_score_top <- test[test[["total_expression"]] > top_threshold & test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  top_cells = unique(SPN_score_top$cell_id)
  
  SCtransformcounts = subset(final_merged_xdp_transformed, subset = donor_id == donor)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts$SPN_identity[top_cells] <- "Top 50% of Matrix SPNs"
  SCtransformcounts@meta.data

  filtered_df <- SCtransformcounts@meta.data[SCtransformcounts@meta.data$SPN_identity == "Bottom 10% of Matrix SPNs", ]
  top_df = SCtransformcounts@meta.data[SCtransformcounts@meta.data$SPN_identity == "Top 50% of Matrix SPNs", ]
combined_df_list[[donor]] <- filtered_df

top_df_list[[donor]] <- top_df

  # Visualize on UMAP
  plots[[donor]] <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("Bottom 10% of Matrix SPNs"="red","Top 50% of Matrix SPNs" ="blue","Other" ="grey")) +ggtitle(paste(donor, ", 10% threshold:", sprintf("%.2f", threshold)))
}
  
old_combined_df <- do.call(rbind, combined_df_list)
top_df <- do.call(rbind, top_df_list)
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/tenten.png", plot = grid_plots, width = 36, height = 16)
old_combined_df
```

```{r}
combined_df
top_df
```

```{r}
sctransform_all = final_merged_xdp_transformed
sctransform_all@meta.data$SPN_identity = "Other"
sctransform_all$SPN_identity[sctransform_all$cell %in% combined_df$cell] = "Bottom 10% of Matrix SPNs"
sctransform_all$SPN_identity[sctransform_all$cell %in% top_df$cell] = "Top 50% of Matrix SPNs"
sctransform_all@meta.data
```


```{r}
DimPlot(sctransform_all, reduction = "umap", group.by = "SPN_identity", cols = c("Bottom 10% of Matrix SPNs"="red","Top 50% of Matrix SPNs" ="blue","Other" ="grey"), split.by = "Condition")
```


```{r}
   threshold <- quantile(XDP_matrix_scores[["total_expression"]][XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
   top_threshold <- quantile(XDP_matrix_scores[["total_expression"]][XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.5, na.rm = TRUE)

  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- XDP_matrix_scores[XDP_matrix_scores[["total_expression"]] < threshold & XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
  top_cells = XDP_matrix_scores[XDP_matrix_scores[["total_expression"]] > top_threshold & XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
  
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  top_cells <- unique(top_cells$cell_id)
  
  SCtransformcounts = final_merged_xdp_transformed
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
    SCtransformcounts$SPN_identity[top_cells] <- "Top 50% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey", "blue"), split.by = "Condition")

```

```{r}
SCtransformcounts@meta.data
```

```{r}
SCtransformcounts@meta.data$top_bottom = SCtransformcounts$SPN_identity
SCtransformcounts$top_bottom[SCtransformcounts$top_bottom == "Bottom 10% of Matrix SPNs"] = "Bottom_10"
SCtransformcounts$top_bottom[SCtransformcounts$top_bottom == "Top 50% of Matrix SPNs"] = "Top_50"

SCtransformcounts@meta.data$donor_10_percentile = paste(SCtransformcounts$donor_id, "_", SCtransformcounts$top_bottom) 
SCtransformcounts@meta.data
```




```{r}
donor_markers_list = list()

for (donor in donors) {
  donor_sobj = subset(SCtransformcounts, subset = donor_id == donor)
  Idents(donor_sobj) = "top_bottom"
  df = FindMarkers(donor_sobj, ident.1 = "Bottom_10", ident.2 = "Top_50")
  df$donor_id = donor
  df$gene = rownames(df)
  print(df)
  write.csv(df, paste0("~/Matrix_SPN_GSEA_top50/donor_markers_", donor, ".csv"), row.names = FALSE)
  donor_markers_list[[donor]] = df
}
donor_marker_df <- do.call(rbind, donor_markers_list)
```

```{r}
donor_marker_df_xdp = subset(donor_marker_df, subset = Condition == "XDP")
donor_marker_df_xdp

donor_marker_df_control= subset(donor_marker_df, subset = Condition == "Control")
donor_marker_df_control

write.csv(donor_marker_df_xdp, paste0("~/Matrix_SPN_GSEA/compiled/XDP.csv"), row.names = FALSE)
write.csv(donor_marker_df_control, paste0("~/Matrix_SPN_GSEA/compiled/Control.csv"), row.names = FALSE)
```
#what if i didnt do it by donor...
```{r}
donor_sobj = subset(SCtransformcounts, subset = Condition == "Control")
  Idents(donor_sobj) = "top_bottom"
  DimPlot(donor_sobj, label = T)
```


```{r}
df = FindMarkers(donor_sobj, ident.1 = "Bottom_10", ident.2 = "Top_50")
  df$gene = rownames(df)
  print(df)
write.csv(df, paste0("~/Matrix_SPN_GSEA_top50/compiled_control.csv"), row.names = FALSE)


```












#GSEA

#change around the logfc and stuff
```{r}
library(Seurat)
library(dplyr)
library(qs)

library(Matrix)
library(fgsea)


# when concatenated together, these should be the paths to your DE csv files
BASE_PATH="~/"
DE_SUBDIR= "Matrix_SPN_GSEA_top50/"


.extraHumanGeneAnnoAdderFn=function(inputGeneNames=NULL){
  #require(EnsDb.Hsapiens.v75)
  require(EnsDb.Hsapiens.v86)
  
  if(!dir.exists("~/serverFiles")){
    dir.create("~/serverFiles",recursive = T)
  }
  
  gns <- as.data.frame(genes(EnsDb.Hsapiens.v86))
  gns$gene_short_name=gns$gene_name
  gns$symbol=toupper(gns$symbol)
  gns$ensembl_gene_id=row.names(gns)
  
  if(!is.null(inputGeneNames)){
    rwNames=toupper(inputGeneNames)
    psCols=c("gene_short_name","ensembl_gene_id")
    slCounts=0
    slCol=""
    if(sum(grepl("\\.",rwNames)&grepl("^ENS",rwNames))>0){
      rwNames=strsplit(rwNames,"\\.")
      rwNames=unlist(lapply(rwNames,function(x)x[1]))
    }
    system(paste0("gsutil -m cp gs://fc-71ac3b81-2441-4171-8038-baf653634620/serverFiles/human_map_to_ensembl.rda ."))
    load("human_map_to_ensembl.rda")
    
    
    map_to_ensmbl$source=toupper(map_to_ensmbl$source)
    
    system(paste0("gsutil -m cp gs://fc-71ac3b81-2441-4171-8038-baf653634620/serverFiles/human_mapping_hg19.rda ."))
      
    
    load("human_mapping_hg19.rda")
    human_hg19$source=toupper(human_hg19$source)
    
    if(sum(toupper(rwNames) %in% human_hg19$source) > sum(toupper(rwNames) %in% map_to_ensmbl$source)){
      map_to_ensmbl=merge(human_hg19,data.frame(source=toupper(rwNames),stringsAsFactors = F),by="source",all.y=T)
    } else {
      map_to_ensmbl=merge(map_to_ensmbl,data.frame(source=toupper(rwNames),stringsAsFactors = F),by="source",all.y=T)
    }
    
    gns=merge(gns,map_to_ensmbl,by.x="ensembl_gene_id",by.y="target",all.y=T)
    gns=gns[match(rwNames,gns$source),]
    row.names(gns)=inputGeneNames
    gns$gene_id=inputGeneNames
    gns=gns[,-which(colnames(gns) %in% c("source","target"))]
  }
  
  return(gns)
}

.sconline.GSEA.readGMT=function (file,bkg_genes=NULL,min.gs.size=NULL,max.gs.size=NULL) {
  if (!grepl("\\.gmt$", file)[1]&F) {
    stop("Pathway information must be in a .gmt file format")
  }
  geneSetDB = readLines(file)
  geneSetDB = strsplit(geneSetDB, "\t")
  names(geneSetDB) = sapply(geneSetDB, "[", 1)
  geneSetDB = lapply(geneSetDB, "[", -1:-2)
  geneSetDB = lapply(geneSetDB, function(x) {
    x[which(x != "")]
  })
  
  if(!is.null(bkg_genes)){
    for(i in 1:length(geneSetDB)){
      tmp=geneSetDB[[i]]
      tmp=bkg_genes[which(toupper(bkg_genes) %in% toupper(tmp))]
      geneSetDB[[i]]=tmp
    }
  }
  
  if(!is.null(min.gs.size)){
    size.dist=unlist(lapply(geneSetDB,length))
    geneSetDB=geneSetDB[size.dist>=min.gs.size]
  }
  
  if(!is.null(max.gs.size)){
    size.dist=unlist(lapply(geneSetDB,length))
    geneSetDB=geneSetDB[size.dist<=max.gs.size]
  }
  
  return(geneSetDB)
}

.myfGSEAfn=function(rankedVec,gs,minSize  = 15,maxSize  = 250, scoreType='std'){
  require(fgsea)
  fgseaRes <- fgsea(pathways = gs, 
                    stats    = rankedVec,
                    minSize  = minSize,
                    maxSize  = maxSize,
                    scoreType= scoreType)
  fgseaRes=fgseaRes[order(fgseaRes$pval,decreasing = F),]
  fgseaRes=as.data.frame(fgseaRes)
  fgseaRes$leadingEdge=unlist(lapply(fgseaRes$leadingEdge,function(x) paste(x,collapse = ",")))
  
  return(fgseaRes)
}

runGSEA = function(
    de_df,
    gs_list_of_char,
    rank_col='avg_log2FC',
    gene_id_col='gene_short_name',
    desc=FALSE,
    abs=TRUE,
    scoreType='std'){

    de_df=de_df[!duplicated(de_df[[gene_id_col]]),]
    
    order_vector = de_df[[rank_col]]
    if(abs){
        order_vector = abs(order_vector)
    }
    
    ranked_vec=de_df[,rank_col]
    names(ranked_vec)=de_df[[gene_id_col]]
    ranked_vec=ranked_vec[order(order_vector,decreasing = desc)]
    
    print(head(ranked_vec))

    res_fGSEA=.myfGSEAfn(rankedVec=ranked_vec,gs=gs_list_of_char, scoreType=scoreType)
    res_fGSEA=res_fGSEA[order(res_fGSEA$padj,decreasing=F),]
    return(res_fGSEA)
}
```



#IDK why but gsea is not workign
```{r}
outpath = file.path(BASE_PATH, DE_SUBDIR, "gsea")
# if you're running into permission errors may need to delete directory and remake with mkdir on command line
dir.create(outpath, recursive=TRUE, showWarnings=FALSE)
de_files = list.files(file.path(BASE_PATH, DE_SUBDIR))
de_files = de_files[grep(".csv$", de_files)]

gene_sets = list(
    # add the paths to the gene sets you want to use here
    kegg_2021_human = "GSEA/genesets/KEGG_2021_Human.txt",
    go_process = "GSEA/genesets/GO_Biological_Process_2021.txt",
    go_function = "GSEA/genesets/GO_Molecular_Function_2021.txt",
    disgenet = "GSEA/genesets/DisGeNET.txt",
    msigdb_hallmark = "GSEA/genesets/MSigDB_Hallmark_2020.txt",
    neural_activity = "GSEA/genesets/neural_activity_arranged.txt",
    wikipathways = "GSEA/genesets/WikiPathways_2019_Human.txt",
    #tf_perturbations = "GSEA/genesets/TF_Perturbations_Followed_by_Expression.txt",
    jensen_diseases = "GSEA/genesets/Jensen_DISEASES.txt",
    X_chromsome_positional= "GSEA/genesets/allchrome.txt",  
    Xlinked_recessive = "GSEA/genesets/Xlinked_RESS.txt",
    Xlinked_dominant = "GSEA/genesets/Xlinked_DOM.txt",
    similar_diseases = "GSEA/genesets/similardiseases.txt"
)

for (de_file in de_files) {
    de_slogan = sub(".txt$", "", de_file)

    dataDE = read.csv(file.path(BASE_PATH, DE_SUBDIR, de_file))
    anno = .extraHumanGeneAnnoAdderFn(inputGeneNames = dataDE$gene)
    anno = anno[match(dataDE$gene, anno$gene_id), ]
    dataDE = cbind(dataDE, anno)
    dataDE = dataDE[which(dataDE$gene_biotype == "protein_coding"), ]

    gsea_list = list()

    for (gene_set in names(gene_sets)) {
        path = gene_sets[[gene_set]]

        gs = .sconline.GSEA.readGMT(file = path, bkg_genes = dataDE$gene_short_name, min.gs.size = 15, max.gs.size = 500)
        gsea = runGSEA(dataDE, gs, rank_col = "avg_log2FC", abs = FALSE, desc = TRUE)
        gsea = gsea[which(gsea$padj < 0.05), ]

        if (nrow(gsea) > 0) {  # Check if gsea is not empty
            gsea$gene_set = gene_set
            gsea_list[[gene_set]] = gsea
        }
    }

    if (length(gsea_list) > 0) {  # Ensure gsea_list is not empty before combining and saving
        gsea_df = do.call(rbind, gsea_list)
        write.table(gsea_df, file.path(outpath, paste0(de_slogan, "__gsea.tsv")), sep = "\t", quote = FALSE, row.names = FALSE)
    } else {
        message(paste("No significant GSEA results for:", de_slogan))
    }
}

```

```{r}
Matrix_SPN_gsea_list = list()

# Loop through each cell type and read the corresponding file into a dataframe
for (donor in donors) {
  # Construct the file name
  gsea_file_name <- paste("~/Matrix_SPN_GSEA_top50/gsea/donor_markers_", donor, ".csv__gsea.tsv", sep = "")
  
  # Print the file name to verify the path
  print(paste("Trying to read file:", gsea_file_name))
  
  # Check if the file exists
  if (file.exists(gsea_file_name)) {
    # Read the file into a dataframe
    gsea_file <- read.delim(gsea_file_name, header = TRUE)
    
    gsea_file$donor_id = donor
    # Store the dataframe in the list with the cell type as the name
    Matrix_SPN_gsea_list[[donor]] <- gsea_file
  } else {
    print(paste("File does not exist:", gsea_file_name))
  }
}
Matrix_SPN_gsea_list
gsea_donor_marker_df <- do.call(rbind, Matrix_SPN_gsea_list)
gsea_donor_marker_df
```

#gsea with leading edge annotations
```{r}
plot_gsea_result_hdot = function(
    df,
    title=NULL,
    xlim=c(-4, 4),
    fig_filename = NULL,
    leading_edge_n=10,
    leading_edge_linebreak_n=5,
    top_n=10) {
    #takes in a df with the following columns: NES, pathway, size, leading_edge
    # along with a title, xlim, fig_filename (nullable)
    # leading_edge_n is the max number of leading_edge genes to be annotated
    # leading_edge_linebreak_n is the number of leading_edge genes to be displayed before a line break
    # top_n is the number of pathways to be displayed on the plot for each direction
    # (i.e. max rows is 2*top_n for up- and down-regulated genesets)
    # the df is filtered to the top_n pathways by NES above 0 and below 0
    # Y axis: pathway. every 30 characters, replace the next space with a \n and then start over
    # X axis: NES, appearing as an open circle. If NES > 0, this circle is blue, < 0 red. The size of the circle relates to the Gene Set Size.
    # The plot is annotated on the right with the leading_edge_top_n.
    # first, turn the leading edge into something we can read by taking the first `leading_edge_n` elemnets
    # separating them with `, ` and finally adding line breaks
    df_pos = df[df$NES > 0,]
    df_neg = df[df$NES < 0,]
    df_pos = df_pos[order(df_pos$NES, decreasing = TRUE),]
    df_neg = df_neg[order(df_neg$NES, decreasing = FALSE),]
    df = rbind(df_pos[1:top_n,], df_neg[1:top_n,])
    df = df[order(df$NES),]
    df = df[!is.na(df$NES),]
    # Function to insert line breaks every `n` entries
    insert_line_breaks = function(text, n = leading_edge_linebreak_n) {
        parts = strsplit(text, ",\\s*")[[1]]
        if (length(parts) <= n) {
            return(text)
        }
        new_text = ""
        for (i in seq_along(parts)) {
            new_text = paste0(new_text, parts[i])
            if (i < length(parts)) {
                new_text = paste0(new_text, ",")
            }
            if (i %% n == 0 && i != length(parts)) {
                new_text = paste0(new_text, "\n")
            } else if (i != length(parts)) {
                new_text = paste0(new_text, " ")
            }
        }
        return(new_text)
    }
    df$leading_edge_top_n = sapply(df$leadingEdge, function(x){
        edge_list = strsplit(x, ",")[[1]]
        len = length(edge_list)
        if (len > leading_edge_n){
            len=leading_edge_n
        }
        return(insert_line_breaks(paste(edge_list[1:len], collapse=", ")))
    })
    if (is.null(title)){
        title = "GSEA NES by Pathway"
    }
    # Format the pathway names to include newline every 30 characters
    df$pathway = gsub("(.{30}\\s)", "\\1\n", df$pathway, perl = TRUE)
    df$NES_direction = ifelse(df$NES > 0, "NES > 0", "NES < 0")
    # Create the plot
    p = ggplot(df, aes(x = NES, y = reorder(pathway, NES))) +
        geom_point(aes(size = size, color = NES_direction), shape = 1) +
        scale_color_manual(name = "NES Direction", values = c("NES > 0" = "blue", "NES < 0" = "red")) +
        scale_size_continuous(name = "Size") +
        geom_vline(xintercept = 0, linetype = "dotted", color = "black") +
        labs(title = title, x = "NES", y = "Pathway") +
        xlim(xlim) +
        theme(
            panel.grid.major = element_line(color = "gray", linetype = "dotted"),
            panel.grid.minor = element_blank(),
            legend.position = "left",
            plot.title = element_text(size = 14),
            plot.caption = element_text(hjust = 0.1),
            plot.title.position = "plot",
            axis.line = element_line(color = "black"),
            axis.ticks = element_line(color = "black"),
            axis.text = element_text(size = 13),
            axis.title = element_text(size = 13),
            axis.text.y.right = element_text(hjust = 1)
        )
        # Create a secondary y-axis with leading_edge_top_n labels
    p = p + geom_text(aes(y = reorder(pathway, NES), x = Inf, label = leading_edge_top_n),
                      hjust = -0.1, size = 4) +
        coord_cartesian(clip = 'off') +
        theme(
            plot.margin = margin(5.5, 340, 5.5, 5.5),  # Increase right margin to make space for secondary labels
            axis.text.y.right = element_text(hjust = 1)
        )
    # Save the plot to file if a filename is provided
    if (!is.null(fig_filename)) {
        ggsave(fig_filename, plot = p, width = 5, height = 2*nrow(df)/3)
    }
    # Print the plot to the R console
    print(p)
}
```

```{r}
Matrix_SPN_gsea_list
```

```{r}
for (donor_df in names(Matrix_SPN_gsea_list)) {
  df = Matrix_SPN_gsea_list[[donor_df]]
  a= plot_gsea_result_hdot(df, title = paste("Bottom 10% vs Top 50% SPN Matrix Scores:", donor_df), leading_edge_n=5)
  print(a)
  ggsave(filename = paste("~/Matrix_SPN_GSEA_top50/gsea/graphs/sig", donor_df, ".png"), plot = a, width = 15, height = 10)
}

```




#figuring out which genes are consistent????
```{r}
donor_marker_df
donor_marker_df$Condition = ifelse(grepl("SCF_21-037CM2|SCF-23-068CM|SCF-22-058CF|SCF-22-054CM", donor_marker_df$donor_id), "Control", "XDP")
donor_marker_df
```


```{r}
controls_df <- donor_marker_df %>%
  filter(Condition == "Control") %>%
  separate_rows(gene, sep = ",")
controls_df
xdp_df <- donor_marker_df %>%
  filter(Condition == "XDP") %>%
  separate_rows(gene, sep = ",")
xdp_df
```

```{r}
xdp_gene_counts <- xdp_df %>%
  group_by(gene) %>%
  summarize(count = n()) %>%
  ungroup()
xdp_gene_counts
control_gene_counts <- controls_df %>%
  group_by(gene) %>%
  summarize(count = n()) %>%
  ungroup()
control_gene_counts

```

```{r}
# Total number of diseased donors
total_xdp <- length(unique(xdp_df$donor_id))
threshold <- 10  # Define "almost all" for diseased cases (e.g., 12 out of 13)

# Genes found in almost all diseased cases
genes_in_xdp <- xdp_gene_counts %>%
  filter(count >= threshold)
genes_in_xdp
```

```{r}
xdp_genes = genes_in_xdp$gene 
xdp_genes
control_genes = control_gene_counts$gene
```

```{r}
intersect(xdp_genes, control_genes)
```

#COCH




```{r}
# Genes not found in controls
genes_not_in_controls <- control_gene_counts %>%
  filter(count == 1)
genes_not_in_controls
```


```{r}
# Final list of genes present in diseased but absent in controls
genes_specific_to_xdp <- genes_in_xdp %>%
  filter(gene %in% genes_not_in_controls$gene)
genes_specific_to_xdp
```





```{r}
a= as.data.frame(table(donor_marker_df$gene))
b = subset(a, subset = Freq > 8)
b
```

```{r}
genes = unique(b$Var1)

for(gene in genes){
 test = donor_marker_df[donor_marker_df$gene == gene,]
 if (all(test$Condition == "XDP")) {
    print(test) 
 }
}
```


```{r}
donor_marker_df_filtered = subset(donor_marker_df, subset = p_val_adj < 0.05)
donor_marker_df_filtered
```

```{r}
donor_marker_df_filtered[donor_marker_df_filtered$gene == "ZNF385B",]
```


```{r}
a= as.data.frame(table(donor_marker_df_filtered$gene))
a

b = subset(a, subset = Freq >5)
b
```



































```{r}
min(XDP_matrix_scores$new_distribution)
max(XDP_matrix_scores$new_distribution)
```


```{r}
matrix <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(-6, 6, 0.2),
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  patch <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(-6, 6, 0.2),
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(-6, 6, 0.2),
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    exotic <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(-6, 6, 0.2),
                                          title = "XDP vs Control: Exotic SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    eSPN <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(-6, 6, 0.2),
                                          title = "XDP vs Control: eSPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```

```{r}
colnames(XDP_matrix_scores)
colnames(BICAN_matrix_scores)
```


```{r}
library(dplyr)
XDP_matrix_scores_df = XDP_matrix_scores %>% select(cell_id, donor_id, Condition, reclustered_patch_matrix_exotic, reclustered_patch_matrix, reclustered_neuron_type_joint_cluster,  pct_mito, nUmi, total_expression , z_score, Village,new_distribution)

BICAN_matrix_scores_df = BICAN_matrix_scores %>% select(cell_id, DONOR, reclustered_patch_matrix, reclustered_neuron_joint_type,  pct_mt, NUM_TRANSCRIPTS, total_expression , z_score, Village,new_distribution) 

BICAN_matrix_scores_df$Condition = "BICAN Control"
BICAN_matrix_scores_df$reclustered_patch_matrix_exotic = BICAN_matrix_scores_df$reclustered_neuron_joint_type
BICAN_matrix_scores_df$reclustered_neuron_type_joint_cluster = BICAN_matrix_scores_df$reclustered_neuron_joint_type
BICAN_matrix_scores_df$reclustered_neuron_joint_type = NULL
BICAN_matrix_scores_df$pct_mito = BICAN_matrix_scores_df$pct_mt 
BICAN_matrix_scores_df$pct_mt  = NULL
BICAN_matrix_scores_df$nUmi = BICAN_matrix_scores_df$NUM_TRANSCRIPTS 
BICAN_matrix_scores_df$NUM_TRANSCRIPTS  = NULL
BICAN_matrix_scores_df$donor_id = BICAN_matrix_scores_df$DONOR 
BICAN_matrix_scores_df$DONOR  = NULL

XDP_matrix_scores_df
BICAN_matrix_scores_df

Combined_scores_df = rbind(XDP_matrix_scores_df, BICAN_matrix_scores_df)
Combined_scores_df
```

```{r}
table(Combined_scores_df$Condition, Combined_scores_df$reclustered_patch_matrix_exotic)
table(Combined_scores_df$Condition, Combined_scores_df$reclustered_neuron_type_joint_cluster)
```

```{r}
XDP_matrix_scores_df
```

```{r}
matrix <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control" = "green"),
                                          breaks = seq(-8, 6, 0.1),
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  patch <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control" = "green"),
                                          breaks = seq(-8, 6, 0.1),
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control" = "green"),
                                          breaks = seq(-8, 6, 0.1),
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    exotic <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_exotic", ]
  plot_overlapping_density_histogram(df = exotic, 
                                          hist_col = exotic$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control" = "green"),
                                          breaks = seq(-8, 6, 0.1),
                                          title = "XDP vs Control: Exotic SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
    eSPN <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "eSPN", ]
  plot_overlapping_density_histogram(df = eSPN, 
                                          hist_col = eSPN$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue","BICAN Control" = "green"),
                                          breaks = seq(-8, 6, 0.1),
                                          title = "XDP vs Control: eSPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```

```{r}
matrix <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control" = "green"),
                                          breaks = seq(-6, -2, 0.1),
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  
  matrix <- Combined_scores_df[Combined_scores_df$reclustered_patch_matrix_exotic == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$new_distribution,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue", "BICAN Control" = "green"),
                                          breaks = seq(0, 4, 0.1),
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```




```{r}
color4 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange", "SPN_exotic" = "yellow", "eSPN" = "green")
fillcol = "reclustered_patch_matrix_exotic"
color = color4 #color4 or 5
donor_graph_title = "eSPN"

 
  options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()

  for (donor in donor_order) {
    xdp_donor <- Combined_scores_df[Combined_scores_df$donor_id == donor, ]
    control = subset(Combined_scores_df, subset = Condition == "Control" | Condition == "BICAN Control")
    test = rbind(xdp_donor, control)
      df = test[test$reclustered_patch_matrix_exotic == "eSPN",]
       plots[[donor]] <- plot_overlapping_density_histogram(df = df,
                                                         hist_col = "new_distribution",
                                                         fill_col = "Condition",
                                                         colors = c("XDP" = "red", "Control" = "blue", "BICAN Control" = "green"),
                                                         breaks = seq(-6,6,0.2),
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "Matrix SPN Score",
                                                         fig_filename = NULL)
  }
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16,17 , NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  Combined_scores_df
```

#just plot xdp

```{r}
color4 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange", "SPN_exotic" = "yellow", "eSPN" = "green")
fillcol = "reclustered_patch_matrix_exotic"
color = color4 #color4 or 5
donor_graph_title = "eSPN"

 
  options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()

  for (donor in donor_order) {
    xdp_donor <- XDP_matrix_scores_df[XDP_matrix_scores_df$donor_id == donor, ]
    control = subset(XDP_matrix_scores_df, subset = Condition == "Control")
    test = rbind(xdp_donor, control)
      df = test[test$reclustered_patch_matrix_exotic == "eSPN",]
       plots[[donor]] <- plot_overlapping_density_histogram(df = df,
                                                         hist_col = "new_distribution",
                                                         fill_col = "Condition",
                                                         colors = c("XDP" = "red", "Control" = "blue", "BICAN Control" = "green"),
                                                         breaks = seq(-6,6,0.2),
                                                         title = paste(donor_graph_title, ": ", donor),
                                                         xlab = "Matrix SPN Score",
                                                         fig_filename = NULL)
  }
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16,17 , NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/USETEST.png", plot = grid_plots, width = 30, height = 16)
  
  Combined_scores_df
```



















```{r}
a = unique(Combined_scores_df$reclustered_patch_matrix_exotic)

for (class in a) {
df = subset(Combined_scores_df, subset = reclustered_patch_matrix_exotic == class )
b = ggplot(data = df, aes(x = new_distribution, y = total_expression, color = Condition)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "Condition") +ggtitle(class)    
print(b)
}

```




```{r}
table(XDP_matrix_scores$donor_id, XDP_matrix_scores$reclustered_patch_matrix_exotic)
```


```{r}
 options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
  combined_df_list <- list()
  for (donor in donors) {
   test <- XDP_matrix_scores[XDP_matrix_scores$donor_id == donor, ]
   threshold <- quantile(test[["new_distribution"]][test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- test[test[["new_distribution"]] < threshold & test[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = subset(final_merged_xdp_transformed, subset = donor_id == donor)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data

  filtered_df <- SCtransformcounts@meta.data[SCtransformcounts@meta.data$SPN_identity == "Bottom 10% of Matrix SPNs", ]

combined_df_list[[donor]] <- filtered_df

  # Visualize on UMAP
  plots[[donor]] <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) +ggtitle(paste(donor, ", 10% threshold:", sprintf("%.2f", threshold)))
}
  
combined_df <- do.call(rbind, combined_df_list)

  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/tenten.png", plot = grid_plots, width = 36, height = 16)
combined_df
```

```{r}
   threshold <- quantile(XDP_matrix_scores[["new_distribution"]][XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- XDP_matrix_scores[XDP_matrix_scores[["new_distribution"]] < threshold & XDP_matrix_scores[["reclustered_patch_matrix_exotic"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = final_merged_xdp_transformed
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey"))

```

```{r}
combined_df
rownames(combined_df) <- sub("^[^.]+\\.", "", rownames(combined_df))
combined_df
```

```{r}
bottom10 =rownames(combined_df)
bottom10
```

```{r}
table(combined_df$donor_id)
table(combined_df$Condition)
table(combined_df$region)
table(combined_df$donor_id)
```


```{r}
XDP_matrix_scores_bottom10 = subset(XDP_matrix_scores, subset = XDP_matrix_scores$cell_id %in% bottom10)
XDP_matrix_scores_bottom10
```

```{r}
x_order = c("SCF_21-037CM2","SCF-22-054CM", "SCF-22-058CF","SCF-23-068CM","PCMC-16-011","PCMC-16-012", "SCF-18-003", "SCF-18-004", "SCF-18-006", "SCF-19-009", "SCF-19-014",  "SCF-19-018", "SCF-20-023", "SCF_20-024", "SCF-20-025", "SCF-21-030", "SCF_22-043")

XDP_matrix_scores_bottom10$donor_id = factor(XDP_matrix_scores_bottom10$donor_id, levels = x_order)

ggplot(data = XDP_matrix_scores_bottom10, aes(x = donor_id, y = total_expression, color = Condition)) +geom_point()+  xlab("Donors") + ylab("SPN score") + theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "Donor") + geom_vline(xintercept =  4.5, linetype = "solid", color = "black")

```

```{r}
ggplot(data = XDP_matrix_scores_bottom10, aes(x = donor_id, y = new_distribution, color = Condition)) +
  geom_point() +
  stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 0.5, color = "black") +
  xlab("Donors") +
  ylab("SPN score") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(fill = "Donor") +
  geom_vline(xintercept =  4.5, linetype = "solid", color = "black")

```


```{r}
ggplot(data = XDP_matrix_scores_bottom10, aes(x = total_expression, y = new_distribution, color = Condition)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "Condition") 
```

```{r}
metadata= read.csv("~/Important_csv/Donor_metadata_updated.csv")
repeats = read.csv("~/Important_csv/repeat_lengths.csv")
metadata
repeats
```

```{r}
merged_metadata = merge(metadata, repeats, by.x = "Donor.ID", by.y = "donor_id")
merged_metadata
```
```{r}
XDP_matrix_scores_bottom10_meta = merge(XDP_matrix_scores_bottom10, merged_metadata, by.x = "donor_id", by.y = "Donor.ID")
XDP_matrix_scores_bottom10_meta
```
```{r}
XDP_matrix_scores_bottom10_meta$Repeat_Length[is.na(XDP_matrix_scores_bottom10_meta$Repeat_Length)] <- 0
XDP_matrix_scores_bottom10_meta$Age.of.Onset[is.na(XDP_matrix_scores_bottom10_meta$Age.of.Onset)] <- 0
XDP_matrix_scores_bottom10_meta$Disease_duration[is.na(XDP_matrix_scores_bottom10_meta$Disease_duration)] <- 0
```

```{r}
XDP_matrix_scores_bottom10_meta$CAP = XDP_matrix_scores_bottom10_meta$Age.of.Death * XDP_matrix_scores_bottom10_meta$Repeat_Length
XDP_matrix_scores_bottom10_meta
```


```{r}
ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = Repeat_Length, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id") +
  stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 1, color = "black") + xlab("Repeat Length") + ylab("SPN Matrix Scores (normalized)") + ggtitle(label = "Repeat Length") + labs(color = "Donor")

ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = Age.of.Onset, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id")+
  stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 1, color = "black") + xlab("Age of Onset") + ylab("SPN Matrix Scores (normalized)")+ ggtitle(label = "Age of Onset") + labs(color = "Donor")
  

ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = Age.of.Death, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id")+
  stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 1, color = "black") + xlab("Age of Death") + ylab("SPN Matrix Scores (normalized)")+ ggtitle(label = "Age of Death") + labs(color = "Donor")
  

ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = Disease_duration, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id")+
  stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 0.5, color = "black")  + xlab("Disease Duration") + ylab("SPN Matrix Scores (normalized)")+ ggtitle(label = "Disease Duration") + labs(color = "Donor")
 
ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = CAP, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id") + stat_summary(fun = mean, geom = "errorbar", aes(ymin = ..y.., ymax = ..y..), width = 40, color = "black")  + xlab("CAP Score") + ylab("SPN Matrix Scores (normalized)")+ ggtitle(label = "CAP Score") + labs(color = "Donor")

```


```{r}
ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = nUmi, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id") 

ggplot(data = XDP_matrix_scores_bottom10_meta, aes(x = pct_mito, y = new_distribution, color = donor_id)) +geom_point()+ theme(axis.text.x = element_text(angle = 45, hjust = 1))+ labs(fill = "donor_id") 
```

```{r}
XDP_matrix_scores_bottom10_meta
```








```{r}
XDP_matrix_scores
```


```{r}
donors = c("PCMC-16-011","PCMC-16-012", "SCF-18-003", "SCF-18-004", "SCF-18-006", "SCF-19-009", "SCF-19-014",  "SCF-19-018", "SCF-20-023", "SCF_20-024", "SCF-20-025", "SCF-21-030", "SCF_22-043","SCF_21-037CM2","SCF-22-054CM", "SCF-22-058CF","SCF-23-068CM") 
color6 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange", "SPN_exotic" = "yellow", "eSPN" = "green")

SPN_score_graphs(XDP_matrix_scores, donor_order = donors, total_expression = "total_expression",  fillcol = "reclustered_neuron_type_joint_cluster", 
                             color = color6, 
                             donor_graph_title = "SPN Matrix vs non-SPNs", 
                             final_merged_xdp_transformed, 
                             SPN_score_col_name = "test") 
```

```{r}
color1 = c("SPN" = "red", "non-SPN"= "blue") #for subcluster: SPN vs non-SPNS
color2 = c("red", "blue")
color3 = c("SPN"="red", "eSPN"="yellow", "other"="green", "IN" = "blue") #for subclass

SPN_score_graphs(XDP_matrix_scores, donor_order = donors, total_expression = "total_expression",  fillcol = "reclustered_subcluster", 
                             color = color1, 
                             donor_graph_title = "Matrix SPNs vs non-SPNs", 
                             final_merged_xdp_transformed, 
                             SPN_score_col_name = "test")
```

```{r}
color3 = c("SPN_matrix"="red", "SPN_patch" = "orange", "SPN_exotic" = "yellow" ,"eSPN"="green", "non-SPN" = "blue") 

SPN_score_graphs(XDP_matrix_scores, donor_order = donors, total_expression = "total_expression",  fillcol = "reclustered_patch_matrix_exotic", 
                             color = color3, 
                             donor_graph_title = "Matrix SPNs vs non-SPNs", 
                             final_merged_xdp_transformed, 
                             SPN_score_col_name = "test")
```



```{r}
SPN_score_output
```


```{r}
 options(repr.plot.width = 24, repr.plot.height = 16)
  plots <- list()
   SPN_score_output=  XDP_matrix_scores 
  for (donor in donors) {
   test <- SPN_score_output[SPN_score_output$donor_id == donor, ]
   threshold <- quantile(test[["total_expression"]][test[["reclustered_patch_matrix"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- test[test[["total_expression"]] < threshold & test[["reclustered_patch_matrix"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = subset(final_merged_xdp_transformed, subset = donor_id == donor)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  plots[[donor]] <- DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey")) +ggtitle(paste(donor, ", 10% threshold:", sprintf("%.2f", threshold)))
}
  
  
  layout_matrix <- rbind(
    c(1, 2, 3, 4, 5),
    c(6, 7, 8, 9, 10),
    c(11, 12, 13, NA, NA),
    c(14, 15, 16, 17, NA)
  )
  
  # Arrange the plots according to the custom layout
  grid_plots <- grid.arrange(grobs = plots, layout_matrix = layout_matrix)
  
  # Save the arranged plots to a PNG file
  ggsave(filename = "~/SPN_SCORE_Output/tenten.png", plot = grid_plots, width = 36, height = 16)

```

```{r}
SPN_score_output=  XDP_matrix_scores 
   threshold <- quantile(SPN_score_output[["total_expression"]][SPN_score_output[["reclustered_patch_matrix"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
    
  SPN_score_output_identity_loss_SPN <- SPN_score_output[SPN_score_output[["total_expression"]] < threshold & SPN_score_output[["reclustered_patch_matrix"]] == "SPN_matrix", ]
   
  print(SPN_score_output_identity_loss_SPN)
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts = final_merged_xdp_transformed
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Bottom 10% of Matrix SPNs"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
DimPlot(SCtransformcounts, reduction = "umap", group.by = "SPN_identity", cols = c("red", "grey"), split.by = "Condition")

```





























#xdp integrated Matrix score
```{r}
XDP_matrix_scores = SPN_score_normalized(xdp_matrix_markers_final, final_merged_xdp_transformed, logfc_val = "weighted_logFC", method = "multiply")
```


```{r}
color6 = c("SPN_matrix" = "red", "non-SPN" = "blue", "SPN_patch" = "orange")

SPN_score_graphs(XDP_matrix_scores, donor_order = donors, total_expression = "total_expression",  fillcol = "reclustered_patch_matrix", 
                             color = color6, 
                             donor_graph_title = "SPN Matrix vs non-SPNs", 
                             final_merged_xdp_transformed, 
                             SPN_score_col_name = "test") 
```

```{r}
color1 = c("SPN" = "red", "non-SPN"= "blue") #for subcluster: SPN vs non-SPNS
color2 = c("red", "blue")
color3 = c("SPN"="red", "eSPN"="yellow", "other"="green", "IN" = "blue") #for subclass

SPN_score_graphs(XDP_matrix_scores, donor_order = donors, total_expression = "total_expression",  fillcol = "reclustered_subcluster", 
                             color = color1, 
                             donor_graph_title = "Matrix SPNs vs non-SPNs", 
                             final_merged_xdp_transformed, 
                             SPN_score_col_name = "test")
```


```{r}
matrix <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix == "SPN_matrix", ]
  plot_overlapping_density_histogram(df = matrix, 
                                          hist_col = matrix$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(0, 150, 2),
                                          title = "XDP vs Control: SPN matrix",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  patch <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix == "SPN_patch", ]
  plot_overlapping_density_histogram(df = patch, 
                                          hist_col = patch$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(0, 150, 2),
                                          title = "XDP vs Control: SPN patch",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
  nonSPN <- XDP_matrix_scores[XDP_matrix_scores$reclustered_patch_matrix == "non-SPN", ]
  plot_overlapping_density_histogram(df = nonSPN, 
                                          hist_col = nonSPN$total_expression,
                                          fill_col = "Condition",
                                          colors = c("XDP" = "red", "Control" = "blue"),
                                          breaks = seq(0, 150, 2),
                                          title = "XDP vs Control: non-SPN",
                                          xlab = "SPN Matrix score",
                                          fig_filename = NULL)
```
```{r}
SPN_score_output
```

```{r}
SPN_score_output = XDP_matrix_scores
SCtransformcounts = final_merged_xdp_transformed

  threshold <- quantile(SPN_score_output[["total_expression"]][SPN_score_output[["reclustered_patch_matrix"]] == "SPN_matrix"], 0.1, na.rm = TRUE)
  print(threshold)
  
  # Subset the data
  SPN_score_output_identity_loss_SPN <- SPN_score_output[SPN_score_output[["total_expression"]] < threshold & SPN_score_output[["reclustered_patch_matrix"]] == "SPN_matrix", ]
  
  print(SPN_score_output_identity_loss_SPN)
  print(table(SPN_score_output_identity_loss_SPN$donor_id))
  
  identity_loss_cells <- unique(SPN_score_output_identity_loss_SPN$cell_id)
  
  SCtransformcounts@meta.data$SPN_identity <- "Other"
  SCtransformcounts$SPN_identity[identity_loss_cells] <- "Losing_Identity"
  SCtransformcounts@meta.data
  
  # Visualize on UMAP
  pic <- DimPlot(SCtransformcounts, group.by = "SPN_identity", split.by = "Condition", cols = c("red", "grey"))
  print(pic)
  
```

```{r}
ggplot(data = SPN_score_output_identity_loss_SPN, aes(x = total_expression, y = nUmi, color = reclustered_patch_matrix)) + geom_point(alpha = 0.3) + xlab("SPN Matrix Score")
ggplot(data = SPN_score_output_identity_loss_SPN, aes(x = total_expression, y = pct_mito, color = reclustered_patch_matrix)) + geom_point(alpha = 0.3)+ xlab("SPN Matrix Score") 
ggplot(data = SPN_score_output_identity_loss_SPN, aes(x = nUmi, y = pct_mito, color = reclustered_patch_matrix)) + geom_point(alpha = 0.3)
```
```{r}
ggplot(data = SPN_score_output_identity_loss_SPN, aes(x = nUmi, y = pct_mito, color = total_expression, shape = Condition)) + geom_point(alpha = 0.6, size = 2) + labs(color = "SPN Matrix Score", shape = "Condition")+ scale_shape_manual(values = c(4, 16)) 
```
```{r}
SPN_score_output_identity_loss_SPN_XDP = subset(SPN_score_output_identity_loss_SPN, subset = SPN_score_output_identity_loss_SPN$Condition == "XDP")

ggplot(data = SPN_score_output_identity_loss_SPN_XDP, aes(x = nUmi, y = pct_mito, color = total_expression)) + geom_point(alpha = 0.6, size = 2) + labs(color = "SPN Matrix Score") +ggtitle("XDP") 

SPN_score_output_identity_loss_SPN_Control = subset(SPN_score_output_identity_loss_SPN, subset = SPN_score_output_identity_loss_SPN$Condition == "Control")

ggplot(data = SPN_score_output_identity_loss_SPN_Control, aes(x = nUmi, y = pct_mito, color = total_expression)) + geom_point(alpha = 0.6, size = 2) + labs(color = "SPN Matrix Score") + ggtitle("Control")
```



```{r}
XDP_matrix_scores$identity <- ifelse(XDP_matrix_scores$cell_id %in% identity_loss_cells, "Bottom 10% SPN Matrix", "Other")
XDP_matrix_scores

ggplot(data = XDP_matrix_scores, aes(x = total_expression, y = nUmi, color = identity)) + geom_point(alpha = 0.2) + xlab("SPN Matrix Score")
ggplot(data = XDP_matrix_scores, aes(x = total_expression, y = pct_mito, color = identity)) + geom_point(alpha = 0.2)+ xlab("SPN Matrix Score") 
ggplot(data = XDP_matrix_scores, aes(x = nUmi, y = pct_mito, color = identity)) + geom_point(alpha = 0.2) 
  
```
```{r}
ggplot(data = XDP_matrix_scores, aes(x = total_expression, y = nUmi, color = reclustered_patch_matrix)) + geom_point(alpha = 0.2) + xlab("SPN Matrix Score")
ggplot(data = XDP_matrix_scores, aes(x = total_expression, y = pct_mito, color = reclustered_patch_matrix)) + geom_point(alpha = 0.2) + xlab("SPN Matrix Score")
ggplot(data = XDP_matrix_scores, aes(x = nUmi, y = pct_mito, color = reclustered_patch_matrix)) + geom_point(alpha = 0.2) 
  
```